### ISSUE TITLE
Sign outs due to inactivity 

### ISSUE THREAD

**Issue by eclectir** [Microsoft/AzureNotebooks#1]
A customer reported that users are being signed out of notebooks every few minutes while they are typing. Fix is being tested internally for roll out. 

Workaround summary for now: log back in & it will reconnect to Jupyter.

Step:
1.	Open a new tab in the same browser, go to notebooks.azure.com
2.	Click “Sign In” & sign in
3.	You can close this sign-in tab now and your notebook will reconnect to the kernel
4.	Press Ctrl-S to save edits or wait 120 seconds for automatic checkpoint to kick in

**Comment by crwilcox** [comment]
This fix has been deployed to production.
