### ISSUE TITLE
Pull notebooks from GitHub/Bitbucket

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#10]
It would be great if libraries could be linked to GitHub or Bitbucket repos from where the notebooks are pulled in.

At present I copy notebooks manually from https://github.com/CambridgeEngineering/PartIA-Computing-Michaelmas to https://notebooks.azure.com/library/CUED-IA-Computing-Michaelmas.

**Comment by smortaz** [comment]
Thanks. Currently you can load a notebook via URL.  unfortunately it's only one notebook.  

The ability to pull a whole github repo, including data, images, etc. in that repo is being worked on right now.  Stay tuned.

**Comment by DinoV** [comment]
#5 needs to come first so we can load more than just the notebooks themselves

**Comment by brianray** [comment]
bump. It would be for sure nice to load a github repository into azure. For instance, I am publishing a video series on learning Python "Python from Scratch LiveLessons" where I keep the sources here:  https://github.com/brianray/bakepie  Even when I wget and unzip the files, I am unable to to open/show the notebooks in azure. That is a blocker that prevents me from allowing the multitude of users from using the platform. A work around would be appreciated.

**Comment by smortaz** [comment]
brian - do you need to just the notebooks uploaded or notebooks, other .py files, .csv's, other data files, ... or both?  ie, is just bringing notebooks over good enough for now? 

note that proper notebook + data support is coming.

**Comment by brianray** [comment]
For the course to work it would require everything in the repository, including the sub-module. I can get everything over with the wget command and unzip; however, the platform does not seem to recognize the notebook once it is there. This is actually unusual behavior for jupyter. Normally, jupyter detects new files when they are added to the directory where the notebooks sit.

**Comment by DinoV** [comment]
We're actively working on the data support now and we have a hidden preview of it - although we're working on completely re-writing it.  There's a hidden .library folder where you'll find your libraries and can also store data.  If you were to unzip there then your notebooks would be picked up by Jupyter (and you can also store data there today).

Unfortunately it's not very fast and isn't necessarily stable - hence the forthcoming re-write.  We're hoping that'll land in the next month or so.  Once that's available the folder will be more obvious and will be configured to be the directory where Jupyter is running from.  You'll also be able to (safely) do a git init in there and turn your library into a Git repo, push/pull from GitHub, etc...
