### ISSUE TITLE
Issues with plotting map data

### ISSUE THREAD

**Issue by wilt00** [Microsoft/AzureNotebooks#100]
I'm trying to use Azure Notebooks to plot addresses on a map. I've encountered a few issues with this:

* Zip code boundary data is provided by Census.gov, which is not whitelisted (403)
* The python library Cartopy (http://scitools.org.uk/cartopy/index.html) cannot be installed, as it relies on the GEOS library (https://trac.osgeo.org/geos/). This also prevents matplotlib.basemap from being used. Optional dependency GDAL (http://www.gdal.org/) also could not be installed (No idea if that's needed, though)
* The R package ggmap (https://github.com/dkahle/ggmap) can be installed, but cannot be used as it pulls map data from Stamen Maps (http://maps.stamen.com and http://tile.stamen.com/), OpenStreetMap (https://www.openstreetmap.org and http://tile.openstreetmap.org/) and/or Google Maps (https://maps.googleapis.com), which don't seem to be whitelisted. The geocoding functionality of ggmap relies on http://www.datasciencetoolkit.org/, which also doesn't seem to be whitelisted.

Could these be made available?

**Comment by smortaz** [comment]
Thanks Will.  Scenarios like these (especially white listing), is basically
poke-driven base on user demand to avoid abuse.  We'll take a look & report
back!

Cheers.

**Comment by crwilcox** [comment]
@wilt00 , I have whitelisted the following sites.
.census.gov
trac.osgeo.org
maps.stamen.com
tile.stamen.com
.openstreetmap.org
maps.googleapis.com
.datasciencetoolkit.org

I am closing this as this should resolve all of your issues.

Thanks!
Chris
