### ISSUE TITLE
curl, wget and other web downloading command got 403 from squid proxy.

### ISSUE THREAD

**Issue by cswords** [Microsoft/AzureNotebooks#101]
Please consider the template below to file your issue. 

### Description

curl, wget and other web downloading command got 403 from squid proxy. 

### Repro Steps

!curl http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data

### Usage Scenario (e.g. teaching a computing course at university foo)

Testing code with uci datasets.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable): test20170525
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by cswords** [comment]
!exports shows:
export http_proxy='http://webproxy:3128'
export https_proxy='http://webproxy:3128'

And according to the HTML returned with 403, I know there is a squid. 

Downloading data from UCI is quite common operation for ML tasks. If it is forbidden to download too large data file or too frequently, please specify the rule. Seeing 403 is a surprise.

**Comment by brettcannon** [comment]
There is a whitelist of domains we allow people to hit to prevent abuse of the service. Someone will need to check if  archive.ics.uci.edu is on the whitelist, and if not then consider adding it.

**Comment by DinoV** [comment]
It wasn't on the whitelist, I've gone ahead and added it, it should be available immediately.
