### ISSUE TITLE
Cannot access dropbox api from endpoint dropboxapi.com

### ISSUE THREAD

**Issue by joshstaiger** [Microsoft/AzureNotebooks#102]
### Description

Using the current python dropbox package (v7.3.1), the default api endpoint domain is "dropboxapi.com".  

It appears that this not currently whitelisted by Azure notebooks.

See also the [dropbox api documentation](https://www.dropbox.com/developers/documentation/http/documentation) to verify.

### Repro Steps

In a Python 3.6 notebook, first place an appropriate dropbox api token in the access_token variable then enter the following code into a cell and run it:

```
!pip install dropbox
import dropbox
dbx = dropbox.Dropbox(access_token)
dbx.files_list_folder("")

```

This results in the following exception:

`ProxyError: HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/list_folder (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))`

Please note that a current workaround is to set the DROPBOX_DOMAIN environmental variable before importing the dropbox package.

This works okay:

```
!pip install dropbox

import os
os.environ["DROPBOX_DOMAIN"] = ".dropbox.com"

import dropbox
dbx = dropbox.Dropbox(access_token)
dbx.files_list_folder("")
```

### Recommended Metadata
The Jupyter Kernel: Python 3.6

**Comment by joshstaiger** [comment]
Also note that it appears that even with the workaround I mentioned, the 

content.dropboxapi.com endpoint also needs to be whitelisted:

`dbx.files_download_to_file("local.xlsx", "/remote/data.xlsx")`

`ProxyError: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/download (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))`

**Comment by crwilcox** [comment]
@joshstaiger , it should be whitelisted now.
