### ISSUE TITLE
Lost installed Python packages

### ISSUE THREAD

**Issue by romainsacchi** [Microsoft/AzureNotebooks#104]
### Description

The packages manually installed by the user in a library (e.g. Basemap, utm, etc.) will be found non-existing at the next login.
Are they deleted every time one logs out?
Or am I installing them the wrong way?

### Repro Steps
In the notebook, for example for Basemap:
!conda install -c conda-forge basemap -y
The next day, the module would not be found.

### Recommended Metadata
The Jupyter Kernel: Python3
Occurrence Time:
Web Browser: Chrome
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Each session starts clean. You should have a setup notebook that uses
"!pip install" etc  to set up your environment,  retrieves require data
etc.

**Comment by crwilcox** [comment]
To elaborate on what @smortaz said, This is the expected behavior. Every session starts the same as every other. If you have packages that are necessary for your notebook, they will need to be re-installed on each run.

One method to do this is to include a setup.ipynb notebook that just has a series of bang commands in a python notebook

    !pip install basemap
    !pip install utm

You can also, if it is just a few things, put those cells at the top of your notebook.

Also, if these packages are ones that you believe are of common use in the community we can consider adding them to our 'base image' so they are present each time.

-Chris

**Comment by romainsacchi** [comment]
Got it. Thank you very much for the explanation.
Br, Romain

**Comment by maajdl** [comment]
Hello!
When would the setup.ipynb notebook be executed?
Or would I need to execute it before starting other notebooks?
Would it be enough to execute the setup once before working on several different workbooks?
Thanks,
Michel

**Comment by kynan** [comment]
@crwilcox can you elaborate what you mean by "session" in this context? How long does a "session" last? Is this deterministic in any way or is it a question of when azure decides to shut down the container running the notebook server?

Also is there a way to encore a new "session"? I want to start with a clean environment (only default packages) to debug a package dependency issue.

**Comment by kynan** [comment]
Sorry, I think I found my answer in the FAQ:

> * When you are in a notebook server, your session is active as long as you are interacting with it - the timeout is set to 60 minutes.
> * If you are inactive for more than 60 minutes, your notebook server will be reclaimed and recycled.  However, your notebooks themselves are safe - you just have to log back in to see them.

My reading of this is that there's no way to enforce a clean session other than waiting for the 60min timeout.

**Comment by crwilcox** [comment]
Closing this issue. I will add
1) library instances now have a 'shutdown' button in the UI you can use to force a clean environment. 
2) https://notebooks.azure.com/help/libraries/library-settings/environment will show how to script configuring your environment at startup.
