### ISSUE TITLE
library link broken

### ISSUE THREAD

**Issue by ayo155111** [Microsoft/AzureNotebooks#105]
Please consider the template below to file your issue. 

### I recently signed up for the azure notebook to take an online course.After setting up a new account and immediately changing my id, the link to the library is broken (still is anon-).

The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by DinoV** [comment]
Where is the link that is broken?  After changing your profile you should be able to go to /your-user-id/libraries and see any libraries that you created or cloned.

**Comment by crwilcox** [comment]
Closing due to lack of response and insufficient details to move forward.
