### ISSUE TITLE
ImportError:torchvision

### ISSUE THREAD

**Issue by tom2002965** [microsoft/AzureNotebooks#106]
Please consider the template below to file your issue. 

### Description
Hi
I successfully install pytorch and torchvision by !conda install pytorch torchvision -c soumith -y
and then check in !pip list 

but when I import torchvision , it always show me import error issue 
"ImportError: No module named torchvision"
what could I fix it?

thank you!

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):Python2
Occurrence Time:
Web Browser:safari

**Comment by smortaz** [comment]
i'd suggest trying to those steps locally in a python environment (with
anaconda).  if it's successful, then try it with the same python version on
azure notebooks.  thx

**Comment by tom2002965** [comment]
@smortaz 
I successfully installed in local environment.
So I guess that Azure notebook doesn't support torchvision?

thanks!

**Comment by smortaz** [comment]
thanks - was that locally in a jupyter environment with the same version of
R as is on azure notebooks?

**Comment by antkmsft** [comment]
We now have pytorch 1.1.0 and torchvision 0.3.0 pre-installed for Python 3.6 kernel. Thank you for using Azure Notebooks!
