### ISSUE TITLE
Whiltelist several interesting data sources

### ISSUE THREAD

**Issue by nirajd** [Microsoft/AzureNotebooks#109]
HuffingtonPost Elections: http://elections.huffingtonpost.com/pollster/api/v2
Seah Lahman Baseball data: http://seanlahman.com/baseball-archive/statistics
City data: https://data.boston.gov/ and others
UCI ML archive: https://archive.ics.uci.edu/ml/datasets.html

Tons of interesting sources listed here by author of Data is Plural Newsletter: https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit#gid=0

**Comment by pde** [comment]
Whitelisting https://arxiv.org would be very helpful for letting us mirror EFF's [AI Progress Measurement](https://eff.org/ai/metrics) Notebook in a way that's very friendly and easy for contributors.

**Comment by pde** [comment]
Also probably the Google Docs domains will turn out to be very useful...

**Comment by nirajd** [comment]
Another one California HHS data: https://data.chhs.ca.gov/dataset
