### ISSUE TITLE
Add environment variable to detect when running on Azure service

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#11]
It would be helpful to have an environment variable for detecting when a notebook is being run on the Azure notebook service.

**Comment by DinoV** [comment]
This is now implemented with todays deployment.  The env var is "AZURE_NOTEBOOKS_HOST".  It actually points back to the hostname of the service as well (in case we ever have multiple public deployments and there was some scenario where it'd be interesting to get back to this).
