### ISSUE TITLE
Feature request: Add an API for pushing the latest copy of a (mirrored) notebook

### ISSUE THREAD

**Issue by pde** [microsoft/AzureNotebooks#110]
Perhaps this is already included in planned Github integration functionality, but we'd like to be able to mirror Notebooks that are hosted on Github (or elsewhere) to Azure Notebooks. At the moment, this seems to require a manual re-upload every time the master copy has changed.

**Comment by smortaz** [comment]
Thanks Peter.  It's on the to do list as well!  thanks for confirming the
need.

**Comment by mikecroucher** [comment]
Not sure if it's useful or not to say 'Me too' but we would really like this functionality too please.
