### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by atalef** [Microsoft/AzureNotebooks#111]
After changing some notebooks' names I haven't access to them, it returns "Bad request". The previous name also doesn't work. What to do with it? I suppose it occured because some problematic symbols in the notebooks' name (like '&'). Is it possible to fix this problem and give me access to my notebooks again?

Here are the links:
1) The new name: MOD02_1-3.1_Intro_Python_Functions Arguments & Parameters.ipynb
The previous name was: MOD02_1-3.1_Intro_Python.ipynb
Link: https://notebooks.azure.com/run/atalef/DEV236x?dest=/notebooks/MOD02_1-3.1_Intro_Python_Functions%20Arguments%20%26%20Parameters.ipynb
2) The new name: Practice_MOD02_1-3_IntroPy_Functions Arguments & Parameters.ipynb
The previous name was: Practice_MOD02_1-3_IntroPy.ipynb
Link: https://notebooks.azure.com/run/atalef/DEV236x?dest=/notebooks/Practice_MOD02_1-3_IntroPy_Functions%20Arguments%20%26%20Parameters.ipynb

Library:
https://notebooks.azure.com/atalef/libraries/DEV236x

**Comment by smortaz** [comment]
natasha - here's a workaround -

1. go to your library
2. click download (it downloads the whole library to your local machine)
3. unzip it
4. rename the bad notebook names (eg remove "&")
5. upload the renamed notebooks

LMK if that works.

**Comment by atalef** [comment]
Thanks a lot, I got it right!
I just can't delete the old copies with the bad names, but it doesn't matter

**Comment by smortaz** [comment]
great!  that's a bug on our side.  we'll fix. thx.

**Comment by atalef** [comment]
I'm happy to help you in finding and fixing a bug :)

**Comment by crwilcox** [comment]
@atalef , it seems this is resolved?
Thanks!
Chris
