### ISSUE TITLE
superuser (sudo root) permissions

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/AzureNotebooks#112]
How do I get sudo root permissions from the notebook interface? I'm trying to install some dependencies such as clang.

**Comment by denfromufa** [comment]
maybe this, but still not clear:

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/use-root-privileges

**Comment by denfromufa** [comment]
![image](https://user-images.githubusercontent.com/7870949/27653278-3a949f7a-5c04-11e7-8156-ed0e7c8e1ef8.png)

**Comment by denfromufa** [comment]
So sudo access is not available according to @dinov

**Comment by hadoopbypradeep** [comment]
Refer to my post in MSDN : [superuser (sudo root) permissions ](https://social.msdn.microsoft.com/Forums/en-US/c0a0dc23-e98a-4935-bc4f-d0ac0bd3d3ed/superuser-sudo-root-permissions?forum=hdinsight).

**Comment by denfromufa** [comment]
@hadoopbypradeep see this comment from @smortaz:

https://github.com/Microsoft/AzureNotebooks/issues/114#issuecomment-315281079
