### ISSUE TITLE
FAQ could use clarification about getting data out

### ISSUE THREAD

**Issue by szaydel** [Microsoft/AzureNotebooks#113]
As I was looking through the FAQ at [Azure Notebooks FAQ](https://notebooks.azure.com/faq), I noticed mention of using transfer.sh with cURL to fetch data out.

I am referring to [How can I get my data out? ](https://notebooks.azure.com/faq#download_data) Question specifically.
The example provided will work with an _IPython kernel_, but I am pretty sure it won't work if it is a R notebook. Perhaps some clarity is warranted here.
```
!curl --upload-file ./MyPlot.pdf https://transfer.sh/MyPlot.pdf
```
Thanks!

**Comment by smortaz** [comment]
That's a good point!   I will update the FAQ.

 Note that you can do a New/Terminal  and use  bash to do a curl still.

**Comment by szaydel** [comment]
Yeah, shell works fine, but I figured someone could be confused by lack of this clarification. Perhaps it is worth noting that shell is effectively kernel agnostic.

**Comment by gilbertw** [comment]
Documentation updated
