### ISSUE TITLE
Mono 5.0.0 update NEEDED

### ISSUE THREAD

**Issue by QuantApp** [Microsoft/AzureNotebooks#115]
I am running software that doesn't work under Mono 4.X due to a bug in this version. I am not able to update myself due to permissioning.

BUG: https://bugzilla.xamarin.com/show_bug.cgi?id=42169

Thanks!

**Comment by denfromufa** [comment]
@quantapp I talked to @dinov and he mentioned that Mono upgrade may be blocked by ifsharp kernel. So someone has to test ifsharp with Mono 4.8+.

**Comment by cgravill** [comment]
With MacOS I have Mono 5.0.1 Stable (5.0.1.1) working with the F# Jupyter kernel so it's likely to work with Ubuntu but does need checking.

**Comment by npmurphy** [comment]
With Ubuntu 16.04 and 17.04, Mono 5.0 to 5.2 (beta) are working fine with the F# Jupyter kernel.

**Comment by DinoV** [comment]
Okay, the deployment got a little bit delayed last week, but the new VMs are up w/ Mono 5.0.  Let us know if anything else needs to be updated!
