### ISSUE TITLE
update to notebook 5.0 - can't use embedded cell attachments

### ISSUE THREAD

**Issue by denfromufa** [microsoft/AzureNotebooks#116]
http://jupyter-notebook.readthedocs.io/en/latest/changelog.html#other-additions

Markdown cells now support attachments. Simply drag and drop an image from your desktop to a markdown cell to add it. Unlike relative links that you enter manually, attachments are embedded in the notebook itself. An unreferenced attachment will be automatically scrubbed from the notebook on save.

https://github.com/jupyter/notebook/pull/621/

**Comment by gilbertw** [comment]
Thank you for taking time to file this issue.  We are looking into Jupyter 5.0 and hope to have it in one of future releases.  Thanks again for using the service
