### ISSUE TITLE
Failing to install skimr package with devtools::install_github

### ISSUE THREAD

**Issue by szaydel** [microsoft/AzureNotebooks#118]
### Description
Failing to install packages with devtools::install_github function.

This may be me doing something silly, or failing to notice something, but seems like this should be working. I tested via shell, as well as from a Notebook directly and results are identical.

```
Downloading GitHub repo hadley/colformat@master
from URL https://api.github.com/repos/hadley/colformat/zipball/master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...): error in running command
Traceback:

1. devtools::install_github("hadley/colformat")
2. install_remotes(remotes, quiet = quiet, ...)
3. vapply(remotes, install_remote, ..., FUN.VALUE = logical(1))
4. FUN(X[[i]], ...)
5. source_pkg(bundle, subdir = remote$subdir)
6. source_pkg_info(path = path, subdir = subdir)
7. decompress(path, outdir)
8. my_unzip(src, target)
9. system_check(unzip, args, quiet = TRUE)
10. suppressWarnings(withr::with_dir(path, withr::with_envvar(env_vars, 
  .     system(full, intern = quiet, ignore.stderr = quiet, ...))))
11. withCallingHandlers(expr, warning = function(w) invokeRestart("muffleWarning"))
12. withr::with_dir(path, withr::with_envvar(env_vars, system(full, 
  .     intern = quiet, ignore.stderr = quiet, ...)))
13. force(code)
14. withr::with_envvar(env_vars, system(full, intern = quiet, ignore.stderr = quiet, 
  .     ...))
15. force(code)
16. system(full, intern = quiet, ignore.stderr = quiet, ...)
```

### Repro Steps
devtools::install_github("hadley/colformat")
devtools::install_github("ropenscilabs/skimr")

### Usage Scenario (e.g. teaching a computing course at university foo)
Trying to add skimr package for use in R Notebook.

**Comment by szaydel** [comment]
I wanted to bump this issue and note that the problem is not just this specific package. There is not really anything special about it frankly. I obviously have not tested with enough packages to be in any confident that this is a problem with all packages from github, but perhaps a confirmation would be good.

```
> devtools::install_github("hadley/colformat")

Downloading GitHub repo hadley/colformat@master
from URL https://api.github.com/repos/hadley/colformat/zipball/master
Error in system(full, intern = quiet, ignore.stderr = quiet, ...) :
  error in running command
```

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update that could potentially resolve this problem. `devtools::install_github("hadley/colformat")` runs successfully.
Please reactivate this issue if you still see the problem. Thanks for using Azure Notebooks!
