### ISSUE TITLE
Allow data download from https://www.ncbi.nlm.nih.gov

### ISSUE THREAD

**Issue by mikecroucher** [Microsoft/AzureNotebooks#119]
Please consider the template below to file your issue. 

### Description

Download of data not possible.

### Repro Steps

```
url <- "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE63310&format=file"

utils::download.file(url, destfile="GSE63310_RAW.tar", mode="wb")
utils::untar("GSE63310_RAW.tar", exdir = ".")

files <- c("GSM1545535_10_6_5_11.txt", "GSM1545536_9_6_5_11.txt", "GSM1545538_purep53.txt",
  "GSM1545539_JMS8-2.txt", "GSM1545540_JMS8-3.txt", "GSM1545541_JMS8-4.txt",
  "GSM1545542_JMS8-5.txt", "GSM1545544_JMS9-P7c.txt", "GSM1545545_JMS9-P8c.txt")

for(i in paste(files, ".gz", sep=""))
  R.utils::gunzip(i, overwrite=TRUE)
```

### Usage Scenario (e.g. teaching a computing course at university foo)

Teaching 'Bioinformatics awareness day' at University of Sheffield: http://bitsandchips.me/BAD_days/RNA-sequencing.html 

We currently have to mirror that data on GitHub to get it into Azure notebook.

### Recommended Metadata

R kernel

**Comment by gilbertw** [comment]
Thanks for taking the time to report this issue.  We have gone ahead and opened up access to the ncbi site.  

Thanks for using the service.
