### ISSUE TITLE
HTML preview is broken when using XPlot

### ISSUE THREAD

**Issue by gsomix** [microsoft/AzureNotebooks#121]
### Description

It seems HTML preview is broken when using XPlot and produces a lot of JS internals. 

Here sample:
https://notebooks.azure.com/evelina/libraries/stackoverflow/html/population-distribution.ipynb

![2017-07-14_16-48-56](https://user-images.githubusercontent.com/832449/28212861-82f14d06-68b4-11e7-9c0d-15198e96d3fa.png)

### Repro Steps

Add following code for XPlot initialization and open notebook in preview.

```fsharp
#load "Paket.fsx"
Paket.Package [ "FSharp.Data" ]
#load "Paket.Generated.Refs.fsx"

#load "XPlot.Plotly.Paket.fsx"
#load "XPlot.Plotly.fsx"
```

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): F#
Web Browser: Opera 46.0

**Comment by gsomix** [comment]
It seems it's closely related to https://github.com/fsprojects/IfSharp/issues/142

**Comment by gsomix** [comment]
Cannot reproduce at local machine with latest IfSharp master and Anaconda 4.4.0.

**Comment by xperiandri** [comment]
@cartermp, could you force a process of fixing?
I wanted to force studying F# through Azure Workbooks in a university and this issue blocks the process!
