### ISSUE TITLE
Stopped getting outputs when running code

### ISSUE THREAD

**Issue by itcouldbeworse** [microsoft/AzureNotebooks#122]
Everything was working perfectly for about an hour, and all day yesterday.  Now after running code I get no output nor any errors (when I intentionally mess up code). I also get an * in the brackets in front of the code box (In [*]) instead of a number (In [1])

I have restarted my computer and switched from internet explorer (initially the only browser that would let me log in), to google chrome (which worked for one line of code), and finally to  Microsoft Edge ( which also worked for one line of code)

I am using this for an online intro to python class.

### Recommended Metadata
The Jupyter Kernel Python 3
Occurrence Time: 6:20 pm
Web Browser: Google Chrome, Internet Explorer, and Microsoft Edge
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/itcouldbeworse/libraries/DEV236x

**Comment by DinoV** [comment]
Which notebook were you having issues in particular?  Did you try restarting the kernel in the notebook at all?
