### ISSUE TITLE
I can't upload my database .db file?

### ISSUE THREAD

**Issue by YSZAIIT** [microsoft/AzureNotebooks#124]
### Description
Hi,
I try to upload my database file .db 
from upload then I choose my local file 
but that not working in azure notebook because the file should be .ipynb
Can any one help me to do that

**Comment by DinoV** [comment]
Upload to library only supports ipynb, in the notebook you can upload anything.  We'll be supporting upload of arbitrary files to the library soon.

**Comment by smortaz** [comment]
Upload in the library only supports uploading notebooks. When in Jupyter
though you can upload anything.

**Comment by smortaz** [comment]
Thx. Replied w that.

**Comment by binaryfunt** [comment]
To add a bit of clarity: open any notebook in the library, then `File > Open...` to open the Jupyter browser, then click the `Upload` button on the right

**Comment by DinoV** [comment]
This should actually be working now, can you let us know if you're still having troubles?  We used to use a Jupyter contents manager for persisting files and we've recently moved away from that.  We now store the files on disk and support any file types.  You can also copy them into and out of the "library" folder in your home directory

**Comment by binaryfunt** [comment]
In the "library browser", it only says I can upload `.ipynb` notebooks if I click the `New` button. In the "Jupyter browser" I can upload anything

**Comment by DinoV** [comment]
Yep, we're working on adding support for uploading and creating other file types via the library UI now, it will probably be available in the next few weeks.  Unfortunately until then non-ipynb files will need to be uploaded via the Jupyter UI.

**Comment by smortaz** [comment]
specifically, to upload you now, you can:

1. start your notebook, and use the Data tab

![image](https://user-images.githubusercontent.com/742484/30128569-fa11ab52-92f7-11e7-8dec-120c7891ea89.png)

2. or click the Terminal button and transfer a file manually
