### ISSUE TITLE
NbExtensions support

### ISSUE THREAD

**Issue by tuhintarafder6** [Microsoft/AzureNotebooks#125]
### Description
How can I install [NbExtensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions)?

**Comment by DinoV** [comment]
Here's an example notebook on how to do that: https://notebooks.azure.com/dino/libraries/nbextensions/html/InstallExtension.ipynb

**Comment by smortaz** [comment]
@dinov - let's add this to the faq.  it's useful.
