### ISSUE TITLE
Kernal connection problems

### ISSUE THREAD

**Issue by arafrahmanDel** [microsoft/AzureNotebooks#126]
Please consider the template below to file your issue. 

### Description

My kernal never seems to connect. Whenever I sign in to use jupyter, the Kernal attempts to connect for  seconds before a message pops up saying "A connection to the notebook server could not be established. This notebook will continue trying to reconnect. Check your network connection or notebook server configuration" But regardless on time of day, where I am, whether I'm connected or not. It never connects

### Repro Steps

I just login, try to run Jupyter and get that message

### Usage Scenario (e.g. teaching a computing course at university foo)

Studying python

### Recommended Metadata
The Jupyter Kernel: Python3
Occurrence Time:
Web Browser: Google chrome, IE 
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/anon-gk4gfg/libraries/DEV236x
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by gilbertw** [comment]
Are you still experiencing any connection issues?  If you are can you attach the output from the .nb.log file.  If you'd prefer not to attach you can email it to me.
