### ISSUE TITLE
Broken link on AzureNotebooks github page

### ISSUE THREAD

**Issue by kaiminglee** [Microsoft/AzureNotebooks#127]
### Description
The AzureNotebooks github page https://github.com/Microsoft/AzureNotebooks contains a "release notes" link in section Current Release with a link to the non-existing page https://notebooks.azure.com/releasenotes

### Repro Steps
- Open https://github.com/Microsoft/AzureNotebooks
- Scroll to "Current Release"
- Click on "release notes"

**Comment by gilbertw** [comment]
The release notes in github is not updated on a regular cadence.  You can however see up to date notes on thte site, https://notebooks.azure.com/new

**Comment by crwilcox** [comment]
Thanks for the feedback @kaiminglee. The link to our release notes was moved from /releasenotes to the link @gilbertw mentions. I will update the release notes to match.
