### ISSUE TITLE
Giphy Whitelist

### ISSUE THREAD

**Issue by heatherbshapiro** [Microsoft/AzureNotebooks#128]
### Description
Is it possible to whitelist "api.giphy.com"? I am trying to reach the giphy API but keep getting a 403 Forbidden error.

Thanks!

**Comment by smortaz** [comment]
Hi can you describe the scenario where access to giphy is needed?  Thx.

**Comment by heatherbshapiro** [comment]
I am looking to pull all of the [SignWithRobert ](https://giphy.com/signwithrobert) Gifs to create a Speech to Text to Sign Language ML Model.

**Comment by smortaz** [comment]
Nice. Until it's opened you can download them outside azure notebooks, zip.
The. In azure notebooks start a Jupyter session and use the Upload menu to
upload it. Can also pull from Dropbox. Persisted data coming soon.

**Comment by DinoV** [comment]
It should be available now...  Let us know if you have any other issues accessing it.
