### ISSUE TITLE
Are you going to support Julia soon ?

### ISSUE THREAD

**Issue by analytics86** [Microsoft/AzureNotebooks#129]
Please consider the template below to file your issue. 

### Description
Are you going to support Julia soon ?

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
Closing as dupe of #4
