### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by lmcpatterson** [Microsoft/AzureNotebooks#130]
Please consider the template below to file your issue. 

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
Closing as this bug has no information
