### ISSUE TITLE
Problem with creating notebook server

### ISSUE THREAD

**Issue by siddgood** [Microsoft/AzureNotebooks#131]
Please consider the template below to file your issue. 

### Description

Whenever I open a notebook (.ipynb) file, I can never go past "Creating notebook server." I keep waiting, but nothing happens. This only happened as of recent. I really need this fixed. I don't want to lose my entire library. 

### Usage Scenario (e.g. teaching a computing course at university foo)

Using for an edX course.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python3
Occurrence Time: 11:49 PM CST
Web Browser: Chrome, Firefox, Safari, Edge
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/siddgood/libraries/DEV236x
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Hi this was a temporary glitch and has been fixed.  sorry about that!  your
notebooks are safe and backed up regularly.

On Wed, Jul 19, 2017 at 9:51 PM, Siddharth Kumaran <notifications@github.com

**Comment by siddgood** [comment]
Thank you! It's working again.
