### ISSUE TITLE
Cannot install tidyverse package in R notebook due to CRAN being blocked

### ISSUE THREAD

**Issue by detlefnauck** [Microsoft/AzureNotebooks#132]
Please consider the template below to file your issue. 

### Description
When trying to install the tidyverse package in an R notebook I receive an error as the package not being available for R 3.3. 
This is because access to cran.r-project.org is blocked and changing the repository via the repos= option or setting the global option CRAN= via options does not circumvent the block. 
Libraries are installed from an outdated copy at 
'https://mran.microsoft.com/snapshot/2016-06-01'

### Repro Steps
install.packages("tidyverse")
install.packages("tidyverse", repos="http://cran.r-project.org")
getOptions("repos")

### Usage Scenario (e.g. teaching a computing course at university foo)
Setting up R notebook for teaching a university course using Hadley Wickham's tidyverse package based on his book "R for Data Science" at http://r4ds.had.co.nz/

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): R
Occurrence Time: July 21, 2017 at 15.50 BST
Web Browser: Chrome
LibraryID and Notebook Name (if applicable): DetlefNauck | essex | tidyverse.ipynb
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
@detlefnauck, it seems we didn't whitelist that particular mirror. I have whitelisted it now though so you should have access to cran.r-project.org.

**Comment by smortaz** [comment]
per @chris, we have a bunch white-listed, but not that one.  will add:


​

**Comment by detlefnauck** [comment]
Excellent, thank you very much. 
install.packages("tidyverse", repos="http://cran.r-project.org") now works. 
Since the CRAN entry in the global options still points to the outdated MS copy other users may have similar issues. I suggest to update the FAQs and point to the fact that the repos option can be used.
