### ISSUE TITLE
No created date is showing and arranging according to it.

### ISSUE THREAD

**Issue by aayush-the-great** [Microsoft/AzureNotebooks#135]
# **ISSUE AT CREATED**
  When i was trying to arranging the notebooks according to created. But unfortunately 
               it arranged the first one is order and rest was not in  proper order.
 It was also not showing the created date.

i did the following steps........
       - first i opened and singe in
       - then i clicked at profile and went to the library the i tried to arrange it, it was not arranging.
     
occurrence  time- 
                          Nepali Time----   1:52 pm

i hope you will understand my problems and try to solve my problem.
I am kindly with my heart requesting to bring the solution for this problem.
i did a lots of hard work for completing so much because of these notebooks,
but now in one second it can be destroyed and it can make a lots of difficulties while
going through the notebooks. So please..........
                                                   
                                         
Microsoft azure notebook id..
                                     anon-c28dhw 
 email id-   aayushkumarkarna@gmail,com
   contact no-  +9779842641628

**Comment by crwilcox** [comment]
We no longer support created date on your files. The modified date is still available. Also the created date still exist on each library. The choice to not track this anymore was deliberate. You found a bug however where we failed to remove the column from that view showing you an empty column.  

It seems you may be in an interesting scenario where these dates are critical to you. If they are and you want to know what they were I can retrieve them for you as we still have them for old files in our back-end data. I will need the following from you in order to retrieve this data:

1) your User ID (anon-c28dhw)
2) the library that you want the created times for

**Comment by aayush-the-great** [comment]
My user ID is   
> anon-c28dhw 
the library that I want the created times for 
>

  | NAME | STATUS | CLONES | CREATED | MODIFIED

  | python.1.begginer | Stopped | 2 | Jun 11, 2017 | Jul 31, 2017



just name then
- python.1.begginer

**Comment by crwilcox** [comment]
@aayush-the-great , I have retrieved the data for you. Please note we are intend to purge our system of created date data. If you rely on this I suggest changing your file names to reflect some form of ordering to assist yourself. You also still have modified date which will indicate when the file was last written.

Thanks!
Chris

| File Name                                     | CreatedDate              | ModifiedDate             | 
|-----------------------------------------------|--------------------------|--------------------------| 
| ASCII.ipynb                                   | 2017-07-14T12:16:47.645Z | 2017-07-14T12:25:01.644Z | 
| CREATION OF simple function.ipynb             | 2017-07-28T03:16:56.972Z | 2017-07-29T03:39:59.577Z | 
| Python try.ipynb                              | 2017-06-11T11:34:15.798Z | 2017-07-09T07:14:04.148Z | 
| String.ipynb                                  | 2017-07-09T07:51:31.695Z | 2017-07-09T09:42:51.378Z | 
| TAsk from edx.ipynb                           | 2017-07-09T07:24:54.736Z | 2017-07-09T07:28:27.323Z | 
| True or false.ipynb                           | 2017-07-14T14:00:14.063Z | 2017-07-14T14:12:36.569Z | 
| addition of number and string.ipynb           | 2017-07-13T12:08:00.755Z | 2017-07-13T13:06:43.884Z | 
| argument.ipynb                                | 2017-07-23T14:10:46.311Z | 2017-07-28T03:07:09.048Z | 
| call function with return.ipynb               | 2017-07-29T01:09:33.995Z | 2017-07-29T03:39:45.766Z | 
| concept of error.ipynb                        | 2017-07-14T00:32:14.168Z | 2017-07-14T00:45:29.529Z | 
| data types in variable.ipynb                  | 2017-07-09T14:40:23.290Z | 2017-07-09T15:13:48.745Z | 
| displaying quots inside the quots.ipynb       | 2017-07-14T13:42:56.513Z | 2017-07-14T13:55:19.505Z | 
| function parameters.ipynb                     | 2017-07-28T06:50:21.404Z | 2017-07-29T03:39:46.869Z | 
| functions with multipal parameters.ipynb      | 2017-07-29T04:03:37.230Z | 2017-07-29T05:14:35.752Z | 
| integer.ipynb                                 | 2017-07-09T10:06:54.174Z | 2017-07-09T15:02:19.476Z | 
| more concept of error.ipynb                   | 2017-07-14T00:47:38.696Z | 2017-07-14T01:13:48.902Z | 
| string formate method 2.ipynb                 | 2017-07-15T13:35:43.737Z | 2017-07-18T15:08:17.939Z | 
| string formate method.ipynb                   | 2017-07-15T13:25:37.993Z | 2017-07-15T13:35:06.064Z | 
| use of comma.ipynb                            | 2017-07-14T13:12:24.788Z | 2017-07-14T13:32:19.151Z | 
| use of has tag.ipynb                          | 2017-07-09T06:53:00.530Z | 2017-07-09T07:03:21.322Z | 
| user input.ipynb                              | 2017-07-14T12:54:09.222Z | 2017-07-14T13:12:10.577Z | 
| using type .ipynb                             | 2017-07-09T15:14:29.327Z | 2017-07-13T12:06:45.782Z | 
| variable addition.ipynb                       | 2017-07-13T15:15:21.119Z | 2017-07-14T00:29:38.221Z | 
| variable and storing in string variable.ipynb | 2017-07-09T11:58:18.500Z | 2017-07-09T14:39:24.803Z |

**Comment by aayush-the-great** [comment]
THanks a lot
I liked your service
