### ISSUE TITLE
getting data from OneDrive

### ISSUE THREAD

**Issue by maajdl** [microsoft/AzureNotebooks#136]
Hello,

I desperately tried to download some files from OneDrive for use in a Python or an R Azure Notebook.
Here is one of the many attempts I made that failed:
_____________________________________________________________________________________________________
import urllib
onedriveURL = "https://onedrive.live.com/download?cid=9194394ABFA6631C&resid=9194394ABFA6631C%2127355&authkey=AO6VrIdT_CZ_HU0"
copy_onedrive = "copy_onedrive_Python.csv"
urllib.request.urlretrieve(onedriveURL , copy_onedrive)
_____________________________________________________________________________________________________

This code works perfectly on my laptop, but not on Azure Notebook where it returns the following error:

`URLError: <urlopen error Tunnel connection failed: 403 Forbidden>`

This code works anytimes when using github instead of OneDrive.

I am evaluating the possibility to use Azure Notebook to share calculations with colleagues.
However they will most often use their own data with the notebooks that I would offer.
Therefore the possibility to access OneDrive would be essential to me.

**My first question**: is there a way to download from OneDrive?

I also noted that a OneDrive download URL is not very readable. Therefore:

**My second question**: is there a way to use readable URLs when storing and retrieve files for use in Azure Notebooks. Or in other words: is there a user-friendly repository?

Thanks,

Michel

**Comment by smortaz** [comment]
Hi Michel - Azure Notebooks does not have direct onedrive integration.
 there's a bug in onedrive that they're unwilling to address immediately so
we removed it.  however if you notice dropbox is integrated and you can use
it from the menu in Jupyter.

more importantly, proper data storage will roll out in the next 3 weeks or
so.  you can then store your data directly in the library and not upload it
each time.

i would highly recommend filing an issue/request with the onedrive team to
provide nice publicly accessible urls that anyone can use:

https://onedrive.uservoice.com/forums/262982-onedrive/category/89675-bugs

**Comment by crwilcox** [comment]
I just attempted to do this with my OneDrive and I was able to download without issue:

```
url = "https://onedrive.live.com/download?cid=72F86FF847D500A9&resid=72F86FF847D500A9%21366502&authkey=AIlJ5gPxIQtPilE"
urllib.request.urlretrieve(url, "file.pdf")
```
I tried your file and received a tunnel forbidden though. Though the file you provided doesn't seem to exist when I try to access it via a browser?

**Comment by maajdl** [comment]
Thanks crwilcox!
Thanks smortaz!

I just made some more tests with the ondrive URL above:
- download in a browser: OK
- urlretrieve on my laptop: OK
- urlretrieve on Azure Notebook my account: URLError: <urlopen error Tunnel connection failed: 403 Forbidden>
- urlretrieve on Azure Notebook another account: URLError: <urlopen error Tunnel connection failed: 403 Forbidden>

I also tried urlretrieve  on Azure with GoogleDrive, iCloudDrive  without success, but thes same worked on my laptop.
Finally, I tried also urlretrieve with dropbox on my laptop without success: HTTP Error 403: Forbidden.

As such, I can hardly go further to share stuff with my colleagues.
Fortunately, smortaz gave me good hopes for a solution soon.
I am eager to see what will be possible then!
I hope that it will be possible to store some data and some packages on Notebooks Azure.
Nevertheless, it would be useful if urlretrieve could be used sometimes!

Thanks,

Michel

**Comment by crwilcox** [comment]
I have added a sample to our getting to your data notebook. Here is the text below.

## Using OneDrive 
You can download files from OneDrive by viewing the file in the web UI. You can get the download id and authkey from viewing the 'embed' code. Change the link slightly to go to 'download' instead of 'embed' and use the requests library.

The HTML provided by embed contains a source link that just needs to be changed to use /download instead of /embed.

<iframe src="https://onedrive.live.com/embed?cid=72087E967DE94E66&amp;resid=72087E967DE94E66%21107&amp;authkey=AB1cjNae6IB1Bm4" width="98" height="120" frameborder="0" scrolling="no"></iframe>

https://onedrive.live.com/download?cid=72087E967DE94E66&resid=72087E967DE94E66%21107&authkey=AB1cjNae6IB1Bm4

```
import requests
onedrive_file = "https://onedrive.live.com/download?cid=72087E967DE94E66&resid=72087E967DE94E66%21107&authkey=AB1cjNae6IB1Bm4"
disk_location = "aTextFile.txt"

r = requests.get(onedrive_file, stream=True)
if r.status_code == 200:
    with open(disk_location, 'wb') as f:
        for chunk in r.iter_content(1024):
            f.write(chunk)
```

**Comment by smbanaie** [comment]
https://blogs.msdn.microsoft.com/uk_faculty_connection/2017/08/25/getting-data-into-azure-notebooks-jupyter-in-the-classroom/
