### ISSUE TITLE
Restarting notebook fails with empty error message

### ISSUE THREAD

**Issue by kynan** [microsoft/AzureNotebooks#137]
### Description

When a session has expired and one is presented with the modal to try to restart the notebook server, this fails when a re-login is required. The error message in the modal popping up is rather unhelpfully empty:

> # Error creating notebook...
> We were unable to successfully create your notebook server. Please try again or report the issue if it persists.
>
> *Error:*

In addition, there's no way to dismiss this modal!

### Repro Steps

This is going to be difficult to reproduce:
1. Start a notebook server and leave it idle (do not close the tab)
2. Wait for the notebook session to expire and also the azure notebooks login session to expire such that a re-login is required
3. Try to restart the notebook server from the modal

**Comment by kynan** [comment]
Turns out this is happening regardless of whether or not a re-login is required.

**Comment by szaydel** [comment]
I can confirm, I have same experience, including this being login agnostic.

**Comment by crwilcox** [comment]
Sorry you are experiencing an issue. Could you answer the following?
1) Are you accessing this via notebooks.azure.com or Azure ML Studio?
2) Do you have third party cookies disabled?

**Comment by kynan** [comment]
@crwilcox
1. via notebooks.azure.com
2. not in general, however I'm using Privacy Badger (no cookies seem to be blocked on notebooks.azure.com though)
