### ISSUE TITLE
notebooks can be uploaded, but images do not upload, get stuck, refresh does not show

### ISSUE THREAD

**Issue by denfromufa** [microsoft/AzureNotebooks#139]
notebooks can be uploaded, but images do not upload, get stuck, refresh does not show:

![image](https://user-images.githubusercontent.com/7870949/28811770-de96e332-7656-11e7-99ff-89319d2f83e9.png)

**Comment by gilbertw** [comment]
Thank you for filing this issue.  We don't currently support storing files other than ipynb in our system. 
 The upload is failing with a 400 bad request.  Unfortunately Jupyter does a poor job of reporting back to the user that the underlying request failed.

We are working to expand our system to allow storing more than ipynb files.  We are not sure when that change will arrive but when it does you will be able to upload these files

**Comment by denfromufa** [comment]
@smortaz yes, i tested it. but these files disappers the next sessions, which is not feasible for persistent simulations/presentations.

**Comment by smortaz** [comment]
ah ok.  yes, data persistence is coming.
