### ISSUE TITLE
Kernel died after multiple Restart and Run All

### ISSUE THREAD

**Issue by quang-ha** [Microsoft/AzureNotebooks#14]
Hi, 

I am working for @garth-wells on notebooks used at Cambridge University Engineering Department. There is a following bug causing kernel dead described as below. 
### Description

Sending two Restart and Run All consecutively caused Kernel dead.
### Repro Steps

Try running the quoted notebooks in the library quoted below and send two consecutive Restart and Run all without waiting for the previous Run All to finish. That should create a kernel dead.
### Usage Scenario

Teaching at CUED.
### Recommended Metadata

The Jupyter Kernel: Python 3
Web Browser: Producible on Chrome Version 54.0.2840.59 (64-bit) and Safari 10.0.1 and Firefox 49.0.2
LibraryID and Notebook Name: https://notebooks.azure.com/library/CUED-IA-Computing-Michaelmas notebooks 05, 07, 08, 10 and 11 in particular.

**Comment by smortaz** [comment]
Thanks Quan-ha for the report.  Will take a look & update soon.

Does this repro for you on a local Jupyter installation?   

Interestingly, for me it got stuck on this line & didnt proceed:

![rem 22](https://cloud.githubusercontent.com/assets/742484/19821944/dc1045c4-9d15-11e6-9a40-755e92b51e10.jpg)

**Comment by quang-ha** [comment]
On local installation Jupyter it is the same - so I guess it could be more or less a problem of Jupyter? Else if I wait enough time for the previous Run All to finish it should be fine.

**Comment by smortaz** [comment]
From what i've seen, Kernel Restarts are somewhat unpredictable and should be used carefully - essentially only when things are wedged totally.  I usually try Kernel Interrupt, then if that doesnt work, Kernel restart, then shutdown & restart the whole container.   

I've pinged some folks to see what they say.

**Comment by garth-wells** [comment]
I think this can be closed now.
