### ISSUE TITLE
this notebook.azure page is loading since 2 hr..i cannot open my jupyter so i m waiting since then so that i can programme in python

### ISSUE THREAD

**Issue by aditya14581** [microsoft/AzureNotebooks#141]
Please consider the template below to file your issue. 

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by rossjones23** [comment]
I am experiencing the same thing.  It started about 6 hours ago.  Everything was working fine and suddenly I lost access to my Notebook.  I am seeing a perpetual "loading" as it tries to display my files

**Comment by rossjones23** [comment]
It appears to be back now.  I can open my notebook files and run Python

**Comment by vickizz** [comment]
me to it doesn't display my notebooks on my chrome browser, hence i'm stuck can't do anywork

**Comment by aditya14581** [comment]
yeah. its back now

**Comment by rossjones23** [comment]
And now it's gone again.  I hope that they are working on it!!

**Comment by smortaz** [comment]
Folks - just to be sure - are you using notebooks via Azure ML Studio:

https://studio.azureml.net/

or directly via

http://notebooks.azure.com

?

thanks

**Comment by DinoV** [comment]
An additional data point that would be useful is the notebook server ID.  That's the part that will show up in the url after the /n/ when you're in the notebook server.
