### ISSUE TITLE
Broken link on notebooks.azure.com

### ISSUE THREAD

**Issue by dougferg** [Microsoft/AzureNotebooks#143]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Broken link on https://notebooks.azure.com/faq#preview

### Description
Get page not found error when clicking on the link mentioned below:

### Repro Steps
Click on the link in the following text:
You can share your notebooks with other users of Azure Notebooks by using an **Azure Notebooks Library**

**Comment by crwilcox** [comment]
I am not seeing a broken link. Both https://notebooks.azure.com/faq#preview and https://notebooks.azure.com/faq#libraries work great.

**Comment by crwilcox** [comment]
Closing as I can't reproduce. Feel free to reopen this if you have more details.

**Comment by dougferg** [comment]
I see what happened:  
It works when I click on the link to follow it, but fails when I right click and tell it to open in a new tab.

 - How can I share a notebook with students and colleagues? 
You can share your notebooks with other users of Azure Notebooks by using an *Azure Notebooks Library*

**Comment by crwilcox** [comment]
Thanks @dougferg. I can see the issue now. I will make a new issue that describes this and track it. Thanks for point this out!
