### ISSUE TITLE
Feature Request: Upload from dl.dropboxusercontent.com shared links

### ISSUE THREAD

**Issue by noel-smith** [Microsoft/AzureNotebooks#144]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
Currently Azure notebooks allow uploading from Dropbox via the file selector. This works great for individual files, but is time-consuming when dealing with larger numbers of them.

Would it be possible to allow direct uploads from shared Dropbox files via *dl.dropboxusercontent.com* links? (Currently these return a 403 - Forbidden code).

### Repro Steps

    !curl -v https://dl.dropboxusercontent.com/content_link/...<some shared file>.../file -o data.csv
    < ...
    < HTTP/1.1 403 Forbidden

### Usage Scenario

Any situation where multiple Dropbox-hosted data files are required for a notebook.

### Recommended Metadata
n/a

**Comment by crwilcox** [comment]
Hi @noel-smith,

we already whitelist dropboxusercontent.com so this probably isn't blocking on our end. I don't know if that link you have requires some browser token or something though you wouldn't have? Using `curl` with -L worked for me.


`!curl https://www.dropbox.com/s/lvn3qoz8o03a5a1/Python-3-vs-Python-2-Converging.png?dl=0 -L -o file.png`

**Comment by noel-smith** [comment]
Hi @crwilcox,

You're absolutely right - the 403 was from Dropbox, it looks like the ```dl.dropboxusercontent.com``` links I was generating only have a limited use.

Using ```curl -L``` with the original link worked perfectly - Thanks!
