### ISSUE TITLE
"package 'AzureSMR' is not available (for R version 3.3.0)"

### ISSUE THREAD

**Issue by richardg23** [microsoft/AzureNotebooks#146]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com) 

### Description
Trying to do load a AzureSMR package in R (install.packages("AzureSMR")). I wanted to access my Azure Storage blob. But it R requires to instal AzureSMR package.

### Usage Scenario (e.g. teaching a computing course at university foo)
Presenting on how to use Azure Notebook using R while accessing Azure Storage.

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A): R
Occurrence Time: Everytime
Web Browser: Chrome
LibraryID and Notebook Name (if applicable): 
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

install.packages("AzureSMR")
library(AzureSMR)

Installing package into '/home/nbcommon/R'
(as 'lib' is unspecified)
Warning message:
"package 'AzureSMR' is not available (for R version 3.3.0)"
Error in library(AzureSMR): there is no package called 'AzureSMR'
Traceback:

1. library(AzureSMR)
2. stop(txt, domain = NA)

**Comment by crwilcox** [comment]
So, to clarify, you need a newer version of R to support a new package?

**Comment by richardg23** [comment]
Yes, that would be great. Thank you!
