### ISSUE TITLE
How to import notebooks.

### ISSUE THREAD

**Issue by Ravirajadrangi** [microsoft/AzureNotebooks#147]
How to import notebooks from github like IBM data science work bench ? Is there any github azure integration plugin button, AWS, Azure, IBM, cloud services integration plugin button and submit to cluster plugin button ? If there is no option to import notebook from github in azure. Can you add some project templates and tutorials ?

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Hi Ravi,

Loading a single notebook from github is available in the New dialog when
in a library.

Loading an entire github repo, including all the data files, etc. is coming
next week.

there is no automatic submit to cluster option.  what would you like to see
here?  can you share details on your scenario?

thanks!

**Comment by Ravirajadrangi** [comment]
Hi there,

I have uploaded some notebooks in azure but they are not saved. I am just evaluating data science platforms.IBM data science platform, Cloudera data science. Rapidminer and azure notebooks. IBM DS has some good features like cloud, github, import notebook, submit to cluster and its completely free.MS azure can be better if it has more features than IBM DS, more tutorials and project templates. Rapidminer is very easy to use but no jupyter notebooks. Cloudera DS can only be installed on VMs and has many more features.

Regards
Ravi Raj

**Comment by Ravirajadrangi** [comment]
Hi there,

Azure notebooks needs two more main features Tableau BI server plugin and Shiny app. plugin.Then I am good to go.

Regards
Raviraj

**Comment by jhconning** [comment]
I just used new **Create New Library From Github* feature and it worked great.   I was also able to then pull in updates to the library (from the \library folder) via a `git pull origin master`.   This is really going to make keeping classroom notebook materials organized and up to date much easier. Thanks!

Is there anyway to automate the process (via a github webhook?) such that any new content pushed to the github repository gets automatically pulled into the Azure library?  That would of course be a killer feature..

**Comment by smortaz** [comment]
Hi Jonathan - thanks!

it's definitely on the TODO list!

**Comment by yoavram** [comment]
Hi, I wanted to check if there's anything new with the webhook?
Or maybe just a button that does "cd library & git pull"?
