### ISSUE TITLE
Cell in Jupyter is not responding

### ISSUE THREAD

**Issue by jasonrstein** [microsoft/AzureNotebooks#148]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)
Azure Notebooks
### Description
I am taking the Python course through Edx and I the cells keep freezing on me not allowing me to run my code. 

I can clear the asterisk ( In [*]) but the it still will not run and the asterisk returns. 

I have included and image. 

![29579706-958027fc-8741-11e7-9718-cbd2b5489424 1](https://user-images.githubusercontent.com/31254222/29579733-ac28478c-8741-11e7-9c48-1395e4f29a27.png)

**Comment by foreverzzx** [comment]
I have met a similar problem.My problem is that the task of this cell as shown below has finished,but the line number won't be shown 
![image](https://user-images.githubusercontent.com/13760297/29656374-ddaaa7b8-88e6-11e7-926d-6e977af064bf.png)

**Comment by foreverzzx** [comment]
And this problem may get me stuck since I don't know whether the running of this cell has finished

**Comment by maajdl** [comment]
I too had problem.
I caused me headaches at restarting the kernel many times.
Now I observed that  "reconnecting" is enough, but it is still not comfortable.
My feeling is that this happens mainly on long calculations, maybe a simple probability effect.

**Comment by crwilcox** [comment]
There are a few ways this may happen:

The first comment, @jasonrstein, seems like an unusual mode for notebooks. You are using input() and completion is blocking on stdin, but you never received the input popup. I just ran the code you provided from chrome and it worked. There is a chance that your browser is causing an issue? Jupyter supports webkit browsers, but not IE/Edge. Is this perhaps the issue?

@foreverzzx , while I am unsure of yours it seems likely you are executing some long running code. Is the kernel crashed (dialog in upper right)? Some of these data heavy libs will run out of memory that they can use which can cause problems, some of them communicate in odd ways with the kernel, etc.

You can look at /home/nbuser/.nb.log if you want and you will see some of the logs jupyter itself provides. It is possible from there you can figure out why your execution is hanging.

**Comment by acosen** [comment]
I'm having the same problem, can anyone help? I run the code and it just sits there and doesn't do anything at all. I'm in chrome.

**Comment by smortaz** [comment]
@jasonrstein - this is a known issue with Jupyter - it's independent of Azure Notebooks which hosts it.  We've asked course authors not to use input() in its current state but its use continues...  one of the Jupyter main devs said this about it:

> 
> More than willing to help you get connected with the right person and figure this out. I am including Grant Nestor, the lead maintainer of the classic notebook. But I think I know what the problem is ahead of time ;-)
> 
> When a user runs a cell with a call to input(), the kernel actually goes into a state where it will block any further requests until the users types into the input box and presses return.
> 
> **However, if the user doesn't press return when the first input box appears,** the kernel will remain in the waiting state and be unable to do anything else. If the user happens to re-run the cell containing the original input() call, the output is cleared, and a new input won't appear because the kernel is still waiting on the original one.
> 
> The real issue here is that input() should be a completely modal dialog and not allow the user to continue to do other things with the kernel (as they will fail). Because of this, in JupyterLab, we are removing input() support from the actual notebook and design a better UX around how/where it goes and works.
> 
> But that does leave the classic notebook. We could prevent the user from running more code? Or at least prevent the output from clearing that cell?
>
