### ISSUE TITLE
how to import local (user-defined) module?

### ISSUE THREAD

**Issue by jhconning** [Microsoft/AzureNotebooks#149]
### Azure Notebooks environment 
notebooks.azure.com

### Description

I receive a **ModuleNotFoundError** when I try to import my own user-written module:
     `import mymodule` 

I had previously uploaded `mymodule.py` to the \library folder that contains the notebook (and I confirmed the file is there via !dir).  

When I try the same on my own PC on the same notebook and module in the same relative file position. everything works fine/

The full error I receive is:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-f4384ce18582> in <module>()
----> 1 import mymodule.py

ModuleNotFoundError: No module named 'mymodule.py'; 'mymodule' is not a package
```

### Usage Scenario  
I will be teaching a course and there are several function methods that I would like to place in a a module that is imported at the start of each notebook so as to not have to define the same functions every time. 

### Recommended Metadata
The Jupyter Kernel: Python 3
Occurrence Time:
Web Browser: Chrome

--------------

Any help/workarounds appreciated. Thanks!

**Comment by gilbertw** [comment]
Thanks for using Azure Notebooks.  We will look into fixing this.  

For now you can workaround this issue by setting the system path to include the library folder.      
     sys.path.append('/home/nbuser/library/')

**Comment by jhconning** [comment]
Thank you, that works!  

(I had tried  'sys.path.append('/home/nbuser/library')'  but it doesn't work without that final `/` !)

**Comment by eculiat** [comment]
Is this bug fixed?  The suggestion solution still does not for (for me at least).

import sys
from torchvision import datasets, transforms
sys.path.append('/home/eculiat/library/')
import helper

ImportError                               Traceback (most recent call last)
<ipython-input-23-57c980e17a6e> in <module>()
      3 from torchvision import datasets, transforms
      4 sys.path.append('/home/eculiat/library/import.py')
----> 5 import helper
      6 
      7 # Define a transform to normalize the data

**Comment by matvelloso** [comment]
Note the above doesn't seem to work when you point the Azure Notebook to a DSVM. Searching the file system, it seems that somehow these modules don't carry over to a separate environment?

**Comment by andneilmsft** [comment]
The path for your project file content is /project/ rather than /library/

For DSVM. We are working with the AML team to restore file system feature. it was regressed last week.  We'll provide updates when we have a ETA from them on getting file systems working again.

**Comment by MohammadAliAfsahi** [comment]
> Thanks for using Azure Notebooks. We will look into fixing this.
> 
> For now you can workaround this issue by setting the system path to include the library folder.
> 
> ```python
> import sys
> sys.path.append('/home/nbuser/library/')
> ```

Thanks... 
This worked for me...
Don't forget to add last '/' otherwise it won't work!
