### ISSUE TITLE
Whitelist EC2 and RDS instances for remote database communication

### ISSUE THREAD

**Issue by tmthyjames** [microsoft/AzureNotebooks#150]
### Azure Notebooks environment 
I have a [notebook](https://notebooks.azure.com/n/iskFx6jQQ5o/notebooks/SQLCell%20Set%20Up.ipynb) on Azure Notebooks.

### Description
I have databases on RDS and EC2 that I'm trying to query from the notebook using SQLAlchemy but can't get through to the servers because the hosts aren't whitelisted.

### Repro Steps
To reproduce, run this code:

from sqlalchemy import create_engine
```
engine = create_engine('postgresql://<username>:<password>@ec2-<ip_address>.compute-1.amazonaws.com:5432/<database>')
engine.execute('select true')
```

This should return the following error code:

```
OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused
	Is the server running on host "ec2-34-203-252-161.compute-1.amazonaws.com" (34.203.252.161) and accepting
	TCP/IP connections on port 5432?
```

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser: **Chrome**
LibraryID and Notebook Name (if applicable): 
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
Hi @tmthyjames, 

I have whitelisted amazonaws.com. That ought to allow you to do what you desire.

Thanks!
Chris

**Comment by tmthyjames** [comment]
Hmm. It's still not allowing me to connect.

**Comment by crwilcox** [comment]
It is on the whitelist and ought to work. Is there perhaps a setting on PostgreSQL on AWS about what IPs can connect? I know for Azure SQL, you can't access it from outside of Azure by default and you have to open it up a bit to allow external access.

**Comment by DinoV** [comment]
Note the white list applies for HTTP/HTTPS traffic, connecting to the database is going to go over a different port and we can't whitelist arbitrary traffic via a proxy to that

**Comment by tmthyjames** [comment]
So there's no way to connect to a remote database from an Azure notebook? Is it possible to set up a local database on Azure?

**Comment by DinoV** [comment]
The firewall actually doesn't block traffic within Azure so you should actually be able to setup a database within Azure and connect to it directly.  The only other option would be setting up a SQLite database within your library, but that'd be limited to the library storage limit of 1gb (and I'm not sure anyone has tested that yet).

**Comment by tmthyjames** [comment]
Awesome! Will try that out. Thanks.

**Comment by tmthyjames** [comment]
Thanks for pointing me in the right direction. I set up a database on an Azure VM and all is working now.
