### ISSUE TITLE
preview showing a huge bunch of javascript instead

### ISSUE THREAD

**Issue by maajdl** [Microsoft/AzureNotebooks#151]
You can see the problem on this page, as an example:

[https://notebooks.azure.com/maajdl/libraries/Eulerbuckling/html/Euler+buckling+1+PP.ipynb](url)

Would that be because of using **holoviews**   or   **bokeh**   ?
Would there be some workaround?

Thanks,

Michel

**Comment by crwilcox** [comment]
Hi Michel.

Due to security risks, we don't render javascript in previews. In this case you are correct that it is the javascript for a bokeh plot.

Thanks!
Chris
