### ISSUE TITLE
How to set up dark theme in azure notebook

### ISSUE THREAD

**Issue by melancholymirth** [Microsoft/AzureNotebooks#152]

**Comment by gilbertw** [comment]
I'm assuming you are referring to themes like portal.azure.com?  Can you elaborate on which part of our site you would like to theme.

As of now we do not have themes in our UI.

**Comment by crwilcox** [comment]
Closing due to non-response. If you are referring to Jupyter themes, you would need to install the extension yourself at this time. You could also file a new request for adding the Jupyter Theme Extension
