### ISSUE TITLE
git global user.name and user.email info not stored

### ISSUE THREAD

**Issue by jhconning** [microsoft/AzureNotebooks#156]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
 I have been successfully using git to pull and push files from a github repository but  I keep getting periodically re-prompted to enter a user.name and user.email.  Here is the dialog on my latest attempt to commit:

```
nbuser@nbserver:~/library$ git commit -m "added explanations of surfaces"

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <nbuser@nbserver.(none)>) not allowed
```
After I enter the info things work and I don't seem to get asked on subsequent commits in the same session but if I let several hours elapse I get re-prompted again.  The rest of the git state seems to be stored without problem but the user.name and user.email seem to get lost.  

Is this expected behavior? Is there a way to save this information more permanently to avoid being re-prompted so often?

Thanks

### Usage Scenario (e.g. teaching a computing course at university foo)
Teaching an economics course at Hunter College, CUNY

### Recommended Metadata
Occurrence Time: 8/29/17 1:45pm

**Comment by DinoV** [comment]
~/.gitconfig isn't preserved with your library right now...  You could try using --local instead of --global but I'm not sure if that'd have undesirable consequences when other users try and clone it.  We probably will need to add some options that allow you to configure your global git config and populate that when we launch your notebook server.

**Comment by jhconning** [comment]
Thank you for the explanation.  It is not too bad to have to re-enter this information each session but I'm glad to hear it might have a future fix.

**Comment by DinoV** [comment]
I'll leave this open until we do have it fixed, it'll be good to track the functionality
