### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by starlord-daniel** [Microsoft/AzureNotebooks#158]
I want to connect to the [OpenWeatherMap APIs](https://openweathermap.org/api) via Azure Notebooks. 

Please whitelist the URL of OpenWeatherMap:
- http://api.openweathermap.org/data/2.5/weather
- http://api.openweathermap.org/data

**Comment by gilbertw** [comment]
Thanks for using the service.  We've enabled access to this site
