### ISSUE TITLE
Add option to replace a notebook

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#16]
At present, if attempting to upload a notebook to a library with the same name as a notebook that is already in the library nothing happens. It would be useful to have a dialogue asking if the file should be replaced.

**Comment by crwilcox** [comment]
Thanks for the feedback Garth. A 'would you like to overwrite' flow would be very nice. I will label this as an enhancement to the product and hopefully we can find time to implement it in the future.

**Comment by DinoV** [comment]
Thanks for the feedback, this got deployed with today's update!
