### ISSUE TITLE
Cannot acess Materials Project database

### ISSUE THREAD

**Issue by MuriloHMoreira** [Microsoft/AzureNotebooks#161]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Arrive at a notebook from Azure Notebooks (notebooks.azure.com) 

### Description
Cannot connect to Materials Project database via pymatgen package

### Repro Steps
!conda install -c matsci pymatgen -y

from pymatgen import MPRester
m = MPRester()
for s in m.get_structures("LiBeH3"):
    print(s.lattice.abc)
    print(s.lattice.angles)

### Usage Scenario (e.g. teaching a computing course at university foo)
Use the powerful materials project api
### Recommended Metadata
The Jupyter Kernel: Python3
Occurrence Time: 01/09/2017
Web Browser: Chrome

**Comment by crwilcox** [comment]
Since the creation of this issue, we have opened up access a bit. I expect this works now. Closing.
