### ISSUE TITLE
Cannot login using Office 365 account

### ISSUE THREAD

**Issue by johnagillespie** [Microsoft/AzureNotebooks#162]
### Azure Notebooks environment 
Logging in via Azure Notebooks (notebooks.azure.com) 

### Description
When attempting to log into Notebooks using an Office 365 identity after authenticating I get the following error 

"You can't access this application Azure Notebooks needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it."

Our admin cannot grant permission. The Notebook service does not appear to correctly implemented the Azure AD OAuth2 – and there is no admin consent model allowing us to authorise this application.

The way this should work is the new v2.0 Oauth2 endpoint for Microsoft Apps (Windows Live ID and Azure AD) should have permission scope (e.g. email address, sign in etc.. etc..) and this should be published in the application manifest – this then allows administrative users to authorise this application. Jupyter Notebook does not currently do this. There would appear to be no way of providing this application with these permission (short of assigning an administrative license to all users) without relaxing the Azure AD configuration

Therefore our users cannot access using corporate Office 365 identities

### Repro Steps
1: Sign into Office 365
2: Go to https://notebooks.azure.com/
3: Attempt to sign-in

### Usage Scenario (e.g. teaching a computing course at university foo)
We wish to offer Notebooks to staff on our Office 365 tenancy. By virtue of having an Office 365 account they have an AAD account.  

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A): N/A
Occurrence Time: 15:00
Web Browser:  Chrome
LibraryID and Notebook Name (if applicable): N/A
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable: N/A

**Comment by eduvik** [comment]
We've got the same issue; we were planning on using this for students at our school, but this bug is preventing that from happening.

**Comment by smortaz** [comment]
thanks folks for bringing this to our attention.  we'll be looking at this shortly and respond here.  apologies for the inconvenience.

**Comment by DinoV** [comment]
We've now got the required permissions specified in our application.  Your admin can go to:

https://login.microsoftonline.com/<tenant ID>/adminconsent?client_id=0d973830-135d-4ffa-92cd-4c57650dc220&redirect_uri=https%3a%2f%2fnotebooks.azure.com


To consent for the entire organization (replacing <tenant ID> with their actual tenant ID).  We'll add a link to this in our Help page - we should be able to have it go to the correct location if the admin signs in so they don't have to modify the URL.

**Comment by turnma** [comment]
Have the application permissions been updated?  We're running into consent issues again, having been using the app fine a few months ago.  Looks at AAD it only required 3 permissions previously, whereas now it seems to require a 4th, but going through the admin consent again doesn't fix the issue.

**Comment by DinoV** [comment]
Yes, sorry, we needed to add a new permission to enable supporting GDPR's forget me feature (We need to be able to receive a user's Azure active directory tenant and object ID so that when MS's internal systems request a delete we can fulfill it).

It looks like while we were asking for it at sign-in time our application was declaring the permission.  I've updated our application to declare that ahead of time, can you try the admin consent again and let us know if that fixes it?

**Comment by turnma** [comment]
That was quick, thanks!  Tested admin consent and it's now added the extra permission in AAD and users can log in again.  Thanks for the rapid response!

**Comment by DinoV** [comment]
Great, glad that fixed it, and thanks for letting us know about the issue!
