### ISSUE TITLE
hyperlinks not working in preview mode, but works in edit mode and in nbviewer

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/AzureNotebooks#166]
Here is the notebook that i'm working with:

https://notebooks.azure.com/denfromufa/libraries/pmlc/html/A%20Whirlwind%20Tour%20of%20Python.ipynb

**Comment by denfromufa** [comment]
BTW, github has the same issue. Here is working version on nbviewer:

http://nbviewer.jupyter.org/github/denfromufa/WhirlwindTourOfPython/blob/master/A%20Whirlwind%20Tour%20of%20Python.ipynb#Index

https://github.com/denfromufa/WhirlwindTourOfPython/blob/master/A%20Whirlwind%20Tour%20of%20Python.ipynb

**Comment by KieranBrantnerMagee** [comment]
Hey denfromufa,
Thanks for the breadcrumb.  We've become aware of this and are tracking the bug.  Will update as progress is made.

**Comment by KieranBrantnerMagee** [comment]
Sorry for the slow followup, closing out a bunch of resolved bugs; I believe this problem has been addressed for some time now.  (Validated against the whirlwind tour of python notebook in your library) Thank you for your patience!
