### ISSUE TITLE
Share does not reflect recent changes

### ISSUE THREAD

**Issue by aolney** [microsoft/AzureNotebooks#168]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com) 

### Description
Shared notebooks appear to be "frozen" to the checkpoint at time of share. Further changes do not appear via shared link.

### Repro Steps

1. public notebook created
2. various R blocks created and executed
3. public notebook shared by link 
4. notebook opened in another browser, no sign in
5. notebook successfully viewed
6. changes made to original notebook (additional blocks) saved/checkpointed
7. changes do not appear in another browser using public link, no sign in

- re-sharing does not propagate changes
- original notebook, preview, also doesn't show changes, but they appear in editing.

### Usage Scenario (e.g. teaching a computing course at university foo)

Classroom instruction, follow along

### Recommended Metadata
Server Information:

You are using Jupyter notebook.

The version of the notebook server is 5.0.0 and is running on:

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]

Current Kernel Information:

R version 3.3.0 (2016-05-03)

Occurrence Time: 3:25pm CST 9/5/17
Web Browser: Chrome and Firefox
LibraryID and Notebook Name (if applicable): 
https://notebooks.azure.com/hideo-ishiguro/libraries/regression-millington
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable
```nbuser@nbserver:~$ cat .nb.log
[I 15:56:48.414 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[W 15:56:48.415 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[I 15:56:48.420 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/sha
re/jupyter/runtime/notebook_cookie_secret
[W 15:56:48.448 NotebookApp] WARNING: The notebook server is listening on all IP addresses an
d not using encryption. This is not recommended.
[W 15:56:48.448 NotebookApp] WARNING: The notebook server is listening on all IP addresses an
d not using authentication. This is highly insecure and not recommended.
[I 15:56:48.480 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.2.5
[I 15:56:48.505 NotebookApp] JupyterLab alpha preview extension loaded from /usr/local/lib/py
thon2.7/dist-packages/jupyterlab
JupyterLab v0.26.4
Known labextensions:
[I 15:56:48.507 NotebookApp] Running the core application with no additional extensions or se
ttings
[E 15:56:48.508 NotebookApp] shemas_dir: /usr/local/lib/python2.7/dist-packages/jupyterlab/sc
hemas
[I 15:56:48.512 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 15:56:48.512 NotebookApp] 0 active kernels
[I 15:56:48.512 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on
your system]:19002/n/6b1o3DLcec8/
[I 15:56:48.512 NotebookApp] Use Control-C to stop this server and shut down all kernels (twi
ce to skip confirmation).
[E 20:34:26.544 NotebookApp] Could not open static file ''
[W 20:34:26.545 NotebookApp] 404 GET / (172.17.0.1) 24.42ms referer=None
[I 20:34:29.966 NotebookApp] Writing notebook-signing key to /home/nbuser/.local/share/jupyte
r/notebook_secret
[W 20:34:29.968 NotebookApp] Notebook analysis-notebook.ipynb is not trusted
[I 20:34:30.509 NotebookApp] Kernel started: 318d6947-9136-4d3b-a96f-d80a888da879
[I 20:34:30.965 NotebookApp] Adapting to protocol v5.0 for kernel 318d6947-9136-4d3b-a96f-d80
a888da879
[I 20:36:12.299 NotebookApp] Adapting to protocol v5.0 for kernel 318d6947-9136-4d3b-a96f-d80
a888da879
[I 20:37:53.733 NotebookApp] Adapting to protocol v5.0 for kernel 318d6947-9136-4d3b-a96f-d80
a888da879
[I 20:38:46.117 NotebookApp] Saving file at /analysis-notebook.ipynb
[I 20:38:50.268 NotebookApp] Adapting to protocol v5.0 for kernel 318d6947-9136-4d3b-a96f-d80
a888da879
[I 20:38:56.364 NotebookApp] Saving file at /analysis-notebook.ipynb
[I 20:39:01.877 NotebookApp] Kernel shutdown: 318d6947-9136-4d3b-a96f-d80a888da879
TermSocket.open: 1
[I 20:39:34.579 NotebookApp] New terminal with specified name: 1
TermSocket.open: Opened 1
```
https://notebooks.azure.com/hideo-ishiguro/libraries/regression-millington

**Comment by KieranBrantnerMagee** [comment]
Hey aolney;
the very professional repro is much appreciated!

We've verified the issue and have a fix in the pipe.  Will update here as needed.
