### ISSUE TITLE
Support Markdown in library description

### ISSUE THREAD

**Issue by garth-wells** [Microsoft/AzureNotebooks#17]
It would be neat if the 'library description' section supported Markdown.

**Comment by smortaz** [comment]
Agreed.

**Comment by DinoV** [comment]
Currently we do have that WYSIWIG editor which allows you to do a limited subset of HTML.  Long term we'll need to:
   Get arbitrary file support (which is coming)
   Migrate existing descriptions to a README.html
   Then add support for a README.md in addition to README.html

And pick up some markdown editor support as well.

**Comment by garth-wells** [comment]
The WYSIWIG editor is a bit temperamental with some browsers. I have trouble with it using Chrome (under Linux).

It would be great if the description was picked up from README.md.

**Comment by DinoV** [comment]
Yeah, I'm actually not a big fan of the WYSIWIG editor either :)

**Comment by garth-wells** [comment]
Looks like this is done.
