### ISSUE TITLE
edit only shows first 11 lines

### ISSUE THREAD

**Issue by eric-camplin** [microsoft/AzureNotebooks#170]
### Azure Notebooks environment 
notebooks.azure.com

### Description
edit only shows first 11 lines and truncates the rest

### Repro Steps
library>right click a ,py or .ipynb file

### Usage Scenario 
edit a .py file

### Recommended Metadata
The Jupyter Kernel  Python3
Occurrence Time: Any
Web Browser: chrome, edge
LibraryID and Notebook Name: Any

**Comment by smortaz** [comment]
bug verified.  investigating. 

thanks!

**Comment by KieranBrantnerMagee** [comment]
I'd add the following:  For a temporary workaround, simply mouse over/click on the invisible text, it will force it to render.

Thanks++ (both for the repro and your patience!) :)
