### ISSUE TITLE
file .read() bug Python

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/AzureNotebooks#174]
### Azure Notebooks environment   
notebooks.azure.com  

### Description  
code below will not read unless the uncommented .read() is run

### Repro Steps
```python
new_file = open('new_file.txt', 'w+')
new_file.write("This is line #1 with 'w+'\nThis is line #2 with 'w+'\n")
new_file.seek(0)
# new_file.read()
new_text = new_file.read()
print(new_text)
new_file.close()
```

### Usage Scenario 
edX course - teaching file i/o

### Recommended Metadata
The Jupyter Kernel Python3, 3.6
Occurrence Time: 9/4 student report - repo 9/12 
Web Browser: edge/chrome

**Comment by crwilcox** [comment]
Hi @eric-camplin, This seems to repro in all 3 (python 2.7, 3.5, 3.6) kernels. It is fine in python itself via the terminal. This seems it may be an issue with the IPython Kernel. I also tried it with a slight change in syntax (using with) but same issue exists.

Repro:
```
with open('new_file2.txt', 'w+') as f:
    f.write('line1\nline2\n')
    f.seek(0)
    print("#1")
    text = f.read()
    print(text)
    print("#2")
    text = f.read()
    print(text)
```

Expect:

```
#1 
line1
line2
#2 
```

Actual:

```
#1
#2 
line1
line2
```

**Comment by crwilcox** [comment]
Hey @eric-camplin , so it seems this is likely an issue with our Azure Files FUSE implementation. I have made a bug on that repo and will work to fix it. 

Thanks!
Chris

**Comment by eric-camplin** [comment]
the fix on the azureml test site doesn't repo the bug 🥇
