### ISSUE TITLE
how to version control notebooks, integration with github or cloud storage?

### ISSUE THREAD

**Issue by denfromufa** [microsoft/AzureNotebooks#177]
How can I version control the notebooks in Azure Notebooks? Is there any way to sync with GitHub or VSTS?

**Comment by smortaz** [comment]
Currently it's manual - you can drop into Terminal and use git.

proper auto sync is coming!

**Comment by ptbrowne** [comment]
How do you set up your SSH key to push to private repos ? I added a priavte SSH key (`ssh-keygen`erated), and the corresponding public one on GitHub. It works on my local machine : 

```
ssh -i ~/.ssh/id_rsa.azure -T git@github.com
Hi ptbrowne! You've successfully authenticated, but GitHub does not provide shell access.
```

but on an Azure machine, I have

```
ssh -i ~/library/.ssh/id_rsa -T git@github.com
ssh: connect to host github.com port 22: Connection refused
```

It seems that a firewall blocks outgoing connections to port 22 :/

**Comment by KieranBrantnerMagee** [comment]
Hey ptbrowne,

despite the very reasonable request, we don't currently support this.  I've added it to our backlog, but there would be some effort needed to thread the port through the various layers of our backend such that we can't just do this ad-hoc.

Thanks for your report and patience,
-Kieran

**Comment by ptbrowne** [comment]
I understand ;) Thanks for the quick response !

**Comment by denfromufa** [comment]
In my case everything is public and I would be happy to have simplified storage through Google Drive, OneDrive, or Dropbox:

https://github.com/jupyterlab/jupyterlab-google-drive

One of my students claims to have lost some home work due to "Error loading notebook Bad Request".

I realize that more advanced users would prefer git-based version control, but this is too much for simple cases.

**Comment by acgetchell** [comment]
Proper auto sync would be awesome. I’m excited you put in Slides (reveal.js) integration!

**Comment by denfromufa** [comment]
related: https://github.com/Microsoft/AzureNotebooks/issues/110

**Comment by huynhthaihoa** [comment]
Is there any solution now ?

**Comment by smortaz** [comment]
There isn't full integration, but you can do git commands from the
Terminal...  proper integration is coming in JupyterLab later on & we'll
see how that works out.

Meanwhile:

https://medium.com/@mikeclymer/integrating-azure-notebooks-jupyter-notebooks-with-github-fd847e941e4

**Comment by huynhthaihoa** [comment]
Thank you so much, I'll try it.

**Comment by yn-coder** [comment]
My two cents. Competing `Google Colab` project (Jupyter notebooks at a Google Cloud) have a good integration with Google Disk. It's great feature.

It's looking reasonable if Microsoft could add OneDrive support for Azure Notebooks.

**Comment by smortaz** [comment]
We agree 100% :-)    Please file this request with the one drive team who
needs a bit of encouragement!

**Comment by yn-coder** [comment]
@smortaz Where to post it?

**Comment by smortaz** [comment]
I'd start here & let them know that collab has this already ;)

**Comment by hansen-m** [comment]
Having OneDrive integration would be a huge win for education because of the OneDrive integration already in place with our LMS (Canvas). This would allow instructors to create provide a set of notebooks for the course within a Git repo, the students could clone the repo, complete their coursework, save the notebook to OneDrive, and then within the LMS submit it from OneDrive.

This might be a really big ask, but adding nbgrader or similar functionality would be phenomenal.

**Comment by robert4os** [comment]
True git integration would be really great :)  

Maybe putting together:
https://github.com/jupyter/nbdime 
https://github.com/iterative/dvc 
https://www.reviewnb.com/
