### ISSUE TITLE
Sign In page not responsive in Google Chrome

### ISSUE THREAD

**Issue by dynamicwebpaige** [microsoft/AzureNotebooks#179]
### Azure Notebooks environment 
Arrived via explicit entry of URL (http://notebooks.azure.com). 

### Description
Attempted to log in to http://notebooks.azure.com/ while using a Google Chrome web browser. Page fails to load. Login successful for Microsoft Edge. Service Unavailable error (503).

### Repro Steps
Attempt to log in to Azure Notebooks while in a Google Chrome browser.

### Usage Scenario (e.g. teaching a computing course at university foo)
Attempting to log in to Azure Notebooks.

### Recommended Metadata
Web Browser: Google Chrome, v.60.0.3112.113 (64-bit).
Time: 05:56am, Pacific Time

Thanks! :)

**Comment by smortaz** [comment]
hmmm... i just tried it from chrome, normal and incognito and it worked.

**Comment by crwilcox** [comment]
@dynamicwebpaige could you try again. It is possible that Microsoft Azure Active Directory (our sign in) had an outage. All seems well now.
