### ISSUE TITLE
Consider adding audit mode for HTTP Proxy service

### ISSUE THREAD

**Issue by jflam** [Microsoft/AzureNotebooks#18]
This is a feature request.

## Motivation

Customers have reported variations of this: "hey, this Jupyter notebook runs fine locally, but fails to run in the Azure Notebook service". In many cases, the root cause of this issue is some kind of blocking of outbound requests from the server that we (understandably) must continue to do.

Diagnosing these kinds of problems is very straightforward for the engineering team, but are not easy to do for customers. This feature will make it easier for the engineering team to diagnose these kinds of problems, and shorten the amount of time that it takes to resolve these customer issues.

## The Feature

We should have a way to have a user run in an environment where _all_ outbound filtering / blocking is disabled on the service, but where _all_ outbound calls are logged. This would let us generate a list of all of the domain names that were accessed by the user in that session, which would be candidates for inclusion in the whitelist of domains that we allow access to.

There could be many different ways that we can implement this feature:

1. Through a dedicated test deployment that only the engineering team can access. This would let us repro those issues on behalf of users. This is probably the quickest option available to us.

1. Enabling a flag on a user's account to put their account into Audit mode where we don't block, but log all outbound access. Clearly, this feature should only be done for trusted users (e.g., a Professor who is testing their course materials before deploying to a class), and perhaps has some form of auto-expiration of the Audit mode flag to prevent accidentally forgetting to turn off Audit mode. 

1. We may want to consider granting users the privilege of enabling Audit mode for their account so they can toggle on / off. This way, they can verify fixes as we make additions to the whitelist. Again, that privilege should probably auto-expire, as well as having some form of UX that indicates that they are running a notebook in Audit mode.

**Comment by QuantMonk** [comment]
Agree with this requirement. On a similar note, are there any plans to allow access to open up outbound requests in general rather than limiting to Azure, github and so on. Is this requirement being tracked/discussed anywhere?

**Comment by smortaz** [comment]
+1 to john's idea.

QuantMonk - it's not limited to azure, github, etc.  most any destination
can be opened - just need to file a request on github & it'll be white
listed, usually within 24 hrs.

I agree that the current method is too cumbersome & needs to be improved.

**Comment by crwilcox** [comment]
As network access has now been relaxed greatly from previous iterations I am closing this.
