### ISSUE TITLE
notebooks frequently unrespponsive

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/AzureNotebooks#181]
### Azure Notebooks environment 
 Azure Notebooks (notebooks.azure.com) 

### Description
many students reporting notebook responsiveness issues lately

### Repro Steps
- run some cells to load function code or variable values    
- then edit cells and run  
- Result: often unresponsive and need interrupt/reconnect or restart or shutdown to get to run

### Usage Scenario  
student developing code - any one developing code

### Recommended Metadata
The Jupyter Kernel Python3
Occurrence Time: at least sept 10 - current
Web Browser: edge, chrome
LibraryID and Notebook Name (if applicable): Any or https://notebooks.azure.com/eric/libraries/DEV236x

**Comment by smortaz** [comment]
Thanks for the heads up. We are aware of the issue and are looking into
it.

**Comment by denfromufa** [comment]
not sure if this is related, but yesterday the notebooks suggested to overwrite the original one with a popup window. Once the kernel died, but other times the kernel was still alive. Couldn't take any screenshots during the lecture.

**Comment by denfromufa** [comment]
I don't think there were multiple tabs of same notebook. Also I had multiple similar issues with 2-3 different notebooks.

**Comment by smortaz** [comment]
ok, we'll have to see if that happens again.  if it does, please ping
nbhelp@microsoft.

meanwhile, we've rolled out a fix for the site unresponsive issue.  pls see
if it has fixed what you were seeing.

thanks!

**Comment by crwilcox** [comment]
Thank you for reporting your connectivity and bearing with us. The system should be fully operational. If you want to know more though, here is a short write-up on what was going on.

Last week we deployed a new feature to automatically refresh user’s libraries list and the contents of the libraries.  Shortly after deploying the new feature we started seeing performance issues and drastically scaled back the feature from refreshing once every 5 seconds to once every 60 seconds.  We also scaled up the system to handle the increased load until the existing open web browsers were refreshed with the latest version of the site.  After that the site appeared to be behaving normally.

Unfortunately as time went on more and more users ended up parked on a library page but were generally inactive.  Some of these users had extremely large libraries (some with over 40,000 files) and this put considerable load on our front ends.  We pushed out a new update of the site that completely disabled this feature and scaled the site up even more to accommodate the load.  But despite this there were still many browsers with the old version of the site that continued to hit the front end.  Some of the web server instances remained responsive and others would end up taking the bulk of the load and would end up cycling.  Depending on how Azure decided to load balance you there was a chance you would hit a stable server or one under considerable load.  The end result was that a hit-or-miss experience for different users – or even the same user in different browsers.

Today we’ve pushed out another update which greatly reduces the load from the existing clients.  While we continue to see some high load the web servers are no longer cycling and appear to have stabilized.

We’ll be rolling out some additional tweaks soon which should help further reduce the load of large libraries and generally improve the experience there. 

Thank you for your patience and sorry for the inconvenience!

**Comment by eric-camplin** [comment]
so far fix seems great - makes me appreciate how fast the service usually runs
