### ISSUE TITLE
Getting data in azure notebook, 403 Forbidden error

### ISSUE THREAD

**Issue by jtorcasso** [Microsoft/AzureNotebooks#182]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
I use notebooks.azure.com

### Description
Simply try to grab data from a URL. The faq indicate this is possible, but I get an error. I get a similar error using both R and Python.

```python
import pandas as pd
df = pd.read_csv("http://jaketorcasso.com/wp-content/teaching/econ210_fall2017/problem_sets/ps1/psid_1968.csv")
```

```R
df = read.csv("http://jaketorcasso.com/wp-content/teaching/econ210_fall2017/problem_sets/ps1/psid_1968.csv")
```
that latter has the following error output:

```
Warning message in file(file, "rt"):
"cannot open URL 'http://jaketorcasso.com/wp-content/teaching/econ210_fall2017/problem_sets/ps1/psid_1968.csv': HTTP status was '403 Forbidden'"
Error in file(file, "rt"): cannot open the connection
Traceback:

1. read.csv("http://jaketorcasso.com/wp-content/teaching/econ210_fall2017/problem_sets/ps1/psid_1968.csv")
2. read.table(file = file, header = header, sep = sep, quote = quote, 
 .     dec = dec, fill = fill, comment.char = comment.char, ...)
3. file(file, "rt")
```
### Usage Scenario (e.g. teaching a computing course at university foo)
I want to create notebooks for teaching using real data. I can make the data available on a website for students.

### Recommended Metadata
Kernels: Both Python3 and R kernels.
Occurrence Time: 3:00PM, September 20, 2017
Web Browser: Google Chrome

**Comment by smortaz** [comment]
Hi.   We need to put that site on our white list. If you are in a hurry,
you can put it on github or Azure or somewhere else that’s  already
accessible. Thx

**Comment by jtorcasso** [comment]
I'll add somewhere else. Thanks.

**Comment by jtorcasso** [comment]
Except now I can't figure out how to pull the data directly from github. Any idea how to pull the csv file instead of the html?

**Comment by denfromufa** [comment]
@jtorcasso use raw link: https://raw.githubusercontent.com/jtorcasso/teaching/master/econ210_fall2017/psets/ps1/psid_1968.csv
