### ISSUE TITLE
Service seems to be down

### ISSUE THREAD

**Issue by DJCordhose** [Microsoft/AzureNotebooks#183]
At least from Germany the service seems to be down. I get 500 timeout errors.

**Comment by DJCordhose** [comment]
Seems to be back, sorry for the noise.

**Comment by smortaz** [comment]
hi - we indeed had connection issues for some customers.  it was caused by a bug in an updated version of a websocket library that we depended on.  we've pushed out a workaround until the owners fix the issue.  site should be functional now.  pls let us know if you experience any problems.  thanks!
