### ISSUE TITLE
feature request: PDF export from reveal slideshow

### ISSUE THREAD

**Issue by jhconning** [Microsoft/AzureNotebooks#185]
### Description

This is a feature request. 

The Azure notebook environment already includes a very useful button to 'Enter/Exit Live Reveal Slideshow'. It works flawlessly for presenting a jupyter notebook in slideshow mode.  

I use this for classroom presentations. Students often ask for the slideshow version of the notebook because its often more compact and easier to follow than the full notebook.  

**Would it be possible for you to enable a PDF export function?**  This is different from the already built in  'download as PDF' option in that it preserves the reveal slideshow formatting.

This seems technically feasible according to the creators of reveal.js framework as described here: https://github.com/hakimel/reveal.js#pdf-export  

The solution they point to seems to require that the browser be chrome or chromium, that a certain CSS file be available and a few other steps, but there seem to be some other solutions that may do it more directly (e.g. using decktape, deck2pdf etc).. 

I don't know if this would be easy or hard to implement (TBH I've had only limited success making a local windows machine export to PDF but as with much else installing on Unix is easier). If you could get this to work it would be a fantastic feature .

### Usage Scenario
This would make Azure notebooks everyone's preferred platform for distributing reveal.js slideshows made from jupyter notebooks (i.e. slideshows with interactive content such as what can be done with ipywidgets).   

### Recommended Metadata
The Jupyter Kernel (Python3):
Web Browser: Chrome

Thanks!

**Comment by crwilcox** [comment]
@jhconning ,

That is an interesting and could be useful. We do not own the code that does the reveal slideshow. However, you can find the source and issue tracker on GitHub -> https://github.com/damianavila/RISE. I suggest you create a similar issue on their repo here.

Thanks!
Chris

**Comment by crwilcox** [comment]
Also, it seems Damian put a little hack together a while back to do this. So perhaps you can use it?
http://www.damian.oquanta.info/posts/a-little-hack-to-get-a-pdf-from-your-ipython-slides.html

**Comment by jhconning** [comment]
Thanks.  It was a bit of wishfully thinking on my part that perhaps the Azure notebook team could make that hack work  (step one by making the needed CSS file always available) but as you point out the step involving the http server would be a barrier.  To be completely honest I have not been able to get the hack or other superior PDF export alternatives such as using [decktape](https://github.com/astefanutti/decktape) to work on windows machines (installing such packages is notoriously difficult on windows).

By making Azure notebooks a smooth running service with useful extensions such as that slideshow button already installed you are making it easier to move tasks to the cloud that we previously did mostly on local machines. For example I now often make quick edits to markdown files or notebooks on Azure first to make them immediately available and only later push changes to local machine.  So it's tempting to start requesting features to make this cloud environment even more customized.  

But the right way to get this feature to work is to raise the issue with the jupyter and RISE/reveal.js developers so they update or create a new extension.  The discussion at the RISE repo suggests Damian is already attempting to automate the process.. but it doesn't look like it's been implemented yet.   I'll add my voice to those asking for this. 
 
Closing the issue.

Thanks again.
