### ISSUE TITLE
ProxyError connecting to api.airtable.com

### ISSUE THREAD

**Issue by DavidPatShuiFong** [Microsoft/AzureNotebooks#188]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
using airtable-python-wrapper

```
!pip install airtable-python-wrapper
mytable_airtable = airtable.Airtable('base_key','MyTableName',api_key='myAPIkey')
```

```
~/anaconda3_410/lib/python3.5/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    500 
    501             if isinstance(e.reason, _ProxyError):
--> 502                 raise ProxyError(e, request=request)
    503 
    504             if isinstance(e.reason, _SSLError):

ProxyError: HTTPSConnectionPool(host='api.airtable.com', port=443): Max retries exceeded with url: /v0/appdwrdeOIWRZuRVf/SpurAfrika2017?maxRecords=1 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

```

### Usage Scenario

sharing data summarizing tools with other collaborators in a free clinic

### Recommended Metadata
Python3
Occurrence Time:
Web Browser: Chromeium
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/DavidFong/libraries/SpurAfrika2017

**Comment by crwilcox** [comment]
@DavidPatShuiFong 
This library makes calls to api.airtable.com which was not on our whitelist. I have added it. You should be able to access it now.

-Chris

**Comment by DavidPatShuiFong** [comment]
Thank you, much appreciated!
