### ISSUE TITLE
plotly requires read/write access to your home directory or to your ~/.plotly directory

### ISSUE THREAD

**Issue by jflam** [Microsoft/AzureNotebooks#19]
I'm getting this error:

```
import plotly.plotly as py

/usr/bin/anaconda/lib/python2.7/site-packages/plotly/tools.py:128: UserWarning:

Looks like you don't have 'read-write' permission to your 'home' ('~') directory or to our '~/.plotly' directory. That means plotly's python api can't setup local configuration files. No problem though! You'll just have to sign-in using 'plotly.plotly.sign_in()'. For help with that: 'help(plotly.plotly.sign_in)'.
Questions? support@plot.ly
```

**Comment by crwilcox** [comment]
Hey @jflam,

This was on the HDI Jupyter Instance they run on the head node correct? This works fine on notebooks.azure.com (we do have some warning about matplotlib fonts but otherwise it is fine).

@aggftw, do you have any ideas?

```
import plotly.plotly as py

/home/nbuser/anaconda2_410/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning:

Matplotlib is building the font cache using fc-list. This may take a moment.
```

**Comment by jflam** [comment]
Yes, this was Jupyter running on head node of HDI cluster.

**Comment by jflam** [comment]
Another observation - offline plotly plots are not working either:

```{Python}
import plotly
plotly.offline.init_notebook_mode()
plotly.offline.iplot(data)
import plotly
plotly.offline.init_notebook_mode()
plotly.offline.iplot(data)
<IPython.core.display.HTML object>
<IPython.core.display.HTML object>
/usr/bin/anaconda/lib/python2.7/site-packages/IPython/paths.py:69: UserWarning:

IPython parent '/home' is not a writable location, using a temp directory.
```

**Comment by aggFTW** [comment]
You need to use the `%%sql --ouput myvar` and `%%local` combo, as explained here: https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Pyspark%20Kernel.ipynb

**Comment by smortaz** [comment]
btw some of the notebooks don't render on github.  not sure why:

https://github.com/jupyter-incubator/sparkmagic/blob/master/examples/Pyspark%20Kernel.ipynb

**Comment by jflam** [comment]
I think it would be helpful to figure out whether we can have better error messages than some of the ones that I saw. Yes, I understand that it's important that customers read the docs :) but sadly, if you just come in thinking "hey, I already know Jupyter", the multiple python execution environments is going to be a surprise.

Sadly, I don't really have any good suggestions for how to improve the error messages in these cases either and hate being the guy that points out the problem without proposing a reasonable solution.

**Comment by jflam** [comment]
Closing this issue as this is really a problem with HDI and not the Azure Notebook service.

**Comment by aggFTW** [comment]
Thanks @jflam 

We know it's not the best user experience. We have ideas on how to make it work with the new JupyterLab mimetype rendering mechanisms.
