### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by jmdatulsaxena** [Microsoft/AzureNotebooks#190]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebooks from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Description

URL: https://notebooks.azure.com/n/XtMWDFG5Ddw/notebooks/Azure%20Notebooks%20-%20Welcome.ipynb#intro_about
has the following link, it seems to be broken.

=>The samples library on Azure Notebooks provides a great set of starter notebooks.

Above link does not work, it gives me error Page not found.

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
That link is to an old path. I have updated the sample. Thanks for letting us know!
