### ISSUE TITLE
debug magic does not show the interactive prompt for debugging

### ISSUE THREAD

**Issue by denfromufa** [microsoft/AzureNotebooks#195]
![image](https://user-images.githubusercontent.com/7870949/31241416-68742ca4-a9c9-11e7-8e0b-4dad1c368de0.png)

**Comment by smortaz** [comment]
just tested it, seem to work for me.  whats before it?


![image](https://user-images.githubusercontent.com/742484/31241945-4d559d68-a9ba-11e7-8bda-6e849bfda37d.png)

**Comment by denfromufa** [comment]
It is this notebook that I'm debugging:

https://notebooks.azure.com/denfromufa/libraries/cvxflow

**Comment by denfromufa** [comment]
Python 2.7, tensorflow, cvxpy, cvxflow

**Comment by denfromufa** [comment]
more info here: https://github.com/cvxgrp/cvxflow/issues/4

**Comment by smortaz** [comment]
i cloned & repro'd the issue.  currently we're seeing an issue with "input()" function.  i'm wondering whether this is also related as it puts up an input field.  stayed tuned.

**Comment by smortaz** [comment]
hi denfromufa - so we talked to the jupyter folks and apparently there is a general issue with anything that throws up an input field - if you use "input("xxxx") and dont actually enter something, you can wedge the notebook.  the same is true for debug which displays an input field.  they said they are redesigning it for jupyterlab.  

one that generally should work is the first execution - but after that, especially if no input is provided can get it wedged.  sorry :(.
