### ISSUE TITLE
Invalid characters in preview of notebook.

### ISSUE THREAD

**Issue by consideRatio** [Microsoft/AzureNotebooks#196]
### Description
When I open a notebook in the preview mode, I can't see characters Swedish characters like å ä and ö correctly, but I can if i view the notebook in the non-preview mode.

### Repro Steps
Visit https://notebooks.azure.com/consideRatio/libraries/exempel/html/PyPlot.ipynb and preview my notebook, then notice that the characters will show correctly if you clone it and go into edit-mode.

**Comment by crwilcox** [comment]
Thanks for reporting this. It seems it does create the pdf fine if using File > Download As > PDF.

We do some additional steps for previews, such as sanitation of executable scripts(javascript),  that could be causing this.

**Comment by einarmagnus** [comment]
I have the same problem, and the same strange behaviour that å, ä and ö work in headers but not elsewhere.
https://notebooks.azure.com/einarmagnus/libraries/mathtest/html/Ma3c%20exempel.ipynb

**Comment by crwilcox** [comment]
@einarmagnus , the characters in the notebook you attached seem to be rendering properly. Can you verify?

The block quote issue is separate and it seems that is still broken.

![image](https://user-images.githubusercontent.com/638797/31486511-91651b00-aeec-11e7-842e-065d9bbb2220.png)

**Comment by consideRatio** [comment]
@einarmagnus 

We are both Swedish math teachers working on utilizing Jupyter in education! I'd love to keep in touch with you! You can find me on facebook as the user consideRatio, or by email erik.i.sundell@gmail.com, or in the facebook group "Programmering för matematiklärare" (https://www.facebook.com/groups/progfml/).

// Erik Sundell

**Comment by consideRatio** [comment]
@crwilcox, the characters in the notebook Einar attached is **almost** be rendering properly to me.

If you hoover a heading, this display bug appears. It also exist for non-swedish notebooks and owners, such as this one: https://notebooks.azure.com/roywilliams/libraries/LIGOOpenScienceCenter/html/First_start_here.ipynb

![image](https://user-images.githubusercontent.com/3837114/31499652-b1883254-af65-11e7-99ff-0243f6fadba9.png)

**Comment by DinoV** [comment]
It looks like that weird character is showing up on any heading anchor

**Comment by DinoV** [comment]
Looks like this is the fix we're missing: https://github.com/jupyter/nbconvert/commit/77d4956ddd252f5d1c05f440acd5b53bd9d996c4#diff-babb94d0a6e7e66a712cf98f6c656460
So we'll need to upgrade nbconvert

**Comment by consideRatio** [comment]
I did not experience this anymore, and the update @DinoV spoke about probably did the trick!
