### ISSUE TITLE
Bypassing limitation of white-listed sites

### ISSUE THREAD

**Issue by versae** [Microsoft/AzureNotebooks#197]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com) accessed via Stanford University login.

### Description
The white-list of sites you can request using `urllib` or `requests` is an extremely annoying /feature/ when you are teaching Python.

### Repro Steps
```python
!pip install -U requests
import requests
requests.get('https://www.propublica.org/trump-administration/')
```

### Usage Scenario (e.g. teaching a computing course at university foo)
At Stanford we run a series of workshops every quarter and given the problematics of setting up Python locally for beginners we thought about using Azure Notebooks since they are available to every Stanford student. But for teaching web scrapping and basic text manipulation, well, it's becoming nearly impossible. Is there a way to bypass this limitation? Is there someone I should be talking to?

### Recommended Metadata
The Jupyter Kernel: Python 3
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/versae/libraries/workshops

**Comment by smortaz** [comment]
Hi Javier, we limit network access to avoid abuse.  White listing requests
usually get processed in 1-2 days.

thanks!

**Comment by smortaz** [comment]
i also noticed that the linking to your notebooks might be wrong:

![image](https://user-images.githubusercontent.com/742484/31253782-fceafe9c-a9da-11e7-8598-fff530f77520.png)

eg: https://notebooks.azure.com/data_manipulation.ipynb  doesnt exist

it should be 

https://notebooks.azure.com/versae/libraries/workshops/html/data_manipulation_filled.ipynb

thanks.

**Comment by smortaz** [comment]
it's been added to the white list.  

pls confirm that it works for you.  thanks!

**Comment by versae** [comment]
@smortaz thanks! Propublica seems to be working now (although they deleted the specific page we were using). We also use `https://python.swaroopch.com/` and `https://archive.org/web` (and the wayback machine`https://web.archive.org/web`), would it be possible to white-list those too?

About the links, they are working on GitHub since they are just relative links. I think that perhaps Azure is not building the link properly.

**Comment by smortaz** [comment]
great, we'll add.

re links - ah ok - i thought you had built those manually.  if not, it's probably our bug.  will create a new issue.

**Comment by smortaz** [comment]
white list updated meanwhile.

**Comment by versae** [comment]
Awesome! Thank you so much. I'll close the issue.

One more (off-topic) question, when is the git importer going to support folders? We have some data in folders that would be nice to be able to import and use. It makes easier writing code that works locally, in a clone repo, and in Azure Notebooks.

**Comment by versae** [comment]
My bad. It's working perfectly. Thanks!
