### ISSUE TITLE
Upgrade dplyr to 0.7.x

### ISSUE THREAD

**Issue by neaorin** [Microsoft/AzureNotebooks#198]
### Azure Notebooks environment 
notebooks.azure.com

### Description
Currently notebooks only offers version 0.5.0 of dplyr. This version contains several [annoying bugs](https://github.com/tidyverse/dplyr/pull/2190) which have since been fixed on 0.7.x
The bug I run into most frequently when using the service is [this one](https://github.com/tidyverse/dplyr/issues/2125).

### Repro Steps
In a new R notebook, run the following code, and observe error message:

```r
library(dplyr)
df = data.frame(col1=rep(1:5, c(3,3,2,1,1)))
df <- df %>%
     mutate(rle=sequence(rle(col1)$lengths)) 
```

`Error in eval(expr, envir, enclos): invalid subscript type 'closure'`

**Comment by smortaz** [comment]
Thanks Sorin - we'll update R image soon & update this bug.

**Comment by KieranBrantnerMagee** [comment]
Sorry for the slow response time on this, I believe this was resolved a while back, closing this as I'm going through and resolve solved bugs.  Thanks for your patience!

![image](https://user-images.githubusercontent.com/29314371/34848988-b0fafa26-f6d5-11e7-9ec9-055803bb694f.png)
