### ISSUE TITLE
Can you whitelist random.org in your proxy?

### ISSUE THREAD

**Issue by soundstripe** [Microsoft/AzureNotebooks#199]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
notebooks.azure.com

### Description
Cannot connect to proxy when accessing https://www.random.org

### Repro Steps
import requests
resp = requests.get('https://www.random.org')

### Usage Scenario (e.g. teaching a computing course at university foo)
Using the random.org API to get true random numbers from atmospheric noise.

**Comment by KieranBrantnerMagee** [comment]
You should be all set.

Thanks for taking the time to ping, feel free to let us know if any other issues.
