### ISSUE TITLE
None of the contents (links) under Welcome.ipynb is working.

### ISSUE THREAD

**Issue by namso-greg** [microsoft/AzureNotebooks#200]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Verified. Will fix soon. Thx very much for reporting!

**Comment by consideRatio** [comment]
My images link to youtube when I'm looking at my notebook locally, but when I use your preview they malfunction and take me to a blank Azure page.

Example - click on the images in this notebook:
https://notebooks.azure.com/consideRatio/libraries/jupyter-math/html/source/gradient-descent/gradient-descent.ipynb
