### ISSUE TITLE
Pytorch not working

### ISSUE THREAD

**Issue by jmandivarapu1** [microsoft/AzureNotebooks#201]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebook from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)
notebooks.azure.com
### Description
cant use the pytorch,torchvision after the installation

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):Python3.6
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

<img width="873" alt="screenshot 2017-10-09 17 46 25" src="https://user-images.githubusercontent.com/21245519/31359895-f8794a02-ad19-11e7-9cdb-cd37fbab4101.png">

**Comment by smortaz** [comment]
Sorry about that.

However there isn’t enough info here to go on. What’s not working? Is there
a notebook we can look at? Thanks!

**Comment by jmandivarapu1** [comment]
I just added the screenshot of the code i ran in jupyter notebook

Here is the link https://notebooks.azure.com/n/MmVNsNqKjxM/notebooks/Untitled.ipynb

<img width="873" alt="screenshot 2017-10-09 17 46 25" src="https://user-images.githubusercontent.com/21245519/31359986-4f7bd676-ad1a-11e7-9b55-c851e7552695.png">

**Comment by smortaz** [comment]
Thx. Does it work install and import locally fine?

**Comment by smortaz** [comment]
Also note that the VMs don’t have gpus. Not sure if the cuda install is
causing problems

**Comment by jmandivarapu1** [comment]
Yeah its working absolutely fine in the local environment.will try removing the cuda in it

**Comment by smortaz** [comment]
actually i think the problem is the import - shouldn't it be:

import torch

?

but i'm confused how import pytorch is working locally...

**Comment by goldengrape** [comment]
This works: 
```python
!conda install pytorch torchvision -c soumith --yes
import torch
```

1. no GPU, no CUDA
2. import torch , not import pytorch

![](https://ws2.sinaimg.cn/large/006tNc79gy1fkmsc6setlj31kw0ten3u.jpg)

**Comment by goldengrape** [comment]
However, when the project is stopped, the pytorch is gone. 
I have to reinstall pytorch every time.
It's a kind of waste.

**Comment by smortaz** [comment]
hi - each time you start, you get a fresh container.   azure notebooks comes w about 300+ python pkgs.  it can't include everything.  however we try to include new pkgs as they become popular gradually.  we'll look into including this - will have to look at usage stats to justify it. thx

**Comment by goldengrape** [comment]
understand. 
maybe MS can provide a set of recipes for different purpose
eg:
* for Machine Learning: tensorflow + pytorch + keras
* for BigData: pandas + h5py...

when starting a new Library,  users can choose what recipe to use.

**Comment by smortaz** [comment]
Yes, currently we have a one base image that has support for R, Python, F#.  in the future we hope to enable "bring your own VM" where you can basically bake in whatever you need.  we're not there yet...

**Comment by geekwhocodes** [comment]
@goldengrape You can configure a startup script for each notebook, please refer more information here https://notebooks.azure.com/help/jupyter-notebooks/server-initialization. 
Steps:
1. Go to your library > settings > Environment
2. Select ShellScript and select your notebook 
3. Save

Please find the script attached.
[script.txt](https://github.com/Microsoft/AzureNotebooks/files/1404777/script.txt)

**Comment by whatevergeek** [comment]
@smortaz "bring your own VM" is a great idea... i love that! 
looking forward to that :-)

**Comment by JWiersema** [comment]
!conda install pytorch torchvision -c soumith --yes

This works for me in Azure notebooks, but not in Azure ML Notebooks, error is:
UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.4*
  - pytorch -> python 3.6*
Use "conda info <package>" to see the dependencies for each package.

I couldnt find versions of pytorch and torchvision that actually worked with python 3.4 in Azure ML Notebooks. Do I need to wait until Azure ML Notebooks are updated?

**Comment by antkmsft** [comment]
We now have pytorch 1.1.0 and torchvision 0.3.0 pre-installed for Python 3.6 kernel. Thank you for using Azure Notebooks!
