### ISSUE TITLE
How to read a CSV into Azure (solved)

### ISSUE THREAD

**Issue by jsaue003** [Microsoft/AzureNotebooks#202]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Description

`data = pd.read_csv('https:/notebooks.azure.com/run/jsx03//Python3?dest=/notebooks/Advertising.csv', index_col=0)`
..
**URLError: urlopen error no host given**

This is the code to read a simple CSV that is uploaded into my own repo... It gives me a host error, from my own notebook. I've tried reading from a public URL on Google drive, too, but that won't work either. 

### Repro Steps

Upload a CSV file to your repository, and try to grab the url or path to it. GL 

### Usage Scenario (e.g. teaching a computing course at university foo)

Prototyping code, testing the Azure notebook and comparing it to regular computer use offline. 

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Python 3
Occurrence Time:
Web Browser:
Chrome 
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

Solution : 
Added the following to the code 
```
!ls ~/library
data = pd.read_csv("~/library/csv.csv", index_col=0)
```

**Comment by smortaz** [comment]
hi - linking like that wont work.  to read a csv, you can upload to your container, under the "library" directory, and then use something like this:


![image](https://user-images.githubusercontent.com/742484/31366670-204814de-ad27-11e7-9d24-0267d30f9fb3.png)

**Comment by jsaue003** [comment]
@smortaz Doesn't work though. "FileNotFoundError: File b'~library/Advertising.csv' does not exist". See the image below. It is put directly into my library as specified, with the exact format you specified in your code, but it doesn't work.. 


![csvtolda](https://user-images.githubusercontent.com/32148757/31366792-04fc1a62-ad41-11e7-90cc-fd07194bfff2.PNG)

**Comment by smortaz** [comment]
you said:

~library/Advertising.csv

did you mean:

~/library/Advertising.csv

?

also, in your notebooks do a !ls to ensure you can see the file and what
its path is.

**Comment by jsaue003** [comment]
Solved... @smortaz I have dyslexia that first / got me good.

**Comment by smortaz** [comment]
no worries, it's easy to miss.
