### ISSUE TITLE
Upload a file into a specific folder

### ISSUE THREAD

**Issue by taupalosaurus** [Microsoft/AzureNotebooks#205]
### Azure Notebooks environment 
Arrived at a notebook from Azure Notebooks

### Description
If my repository/library contains one or more folders under its root, is there a way to upload a file from my computer into one of these folders specifically ? When I try, it always uploads the files to the root of the library.
Thanks

### Repro Steps
Import a library with a folder under the root (for instance https://github.com/ggorman/Introduction-to-programming-for-geoscientists)
Go in the library, go in a sub-folder
click "+ New" then "from computer"
select a notebook and upload it
It was uploaded to the root, not in the current folder

### Usage Scenario (e.g. teaching a computing course at university foo)
We are starting to use Azure notebooks at Imperial College London for undergraduate "introduction to programming" classes, migrating from github + class website.
As the students are far from mastering git, uploading files is our best guess at how to edit

### Recommended Metadata
The Jupyter Kernel: Python3
Occurrence Time: 10th Oct. 2017
Web Browser: Firefox 56.0
LibraryID and Notebook Name (if applicable): for instance: https://notebooks.azure.com/nbarral/libraries/testupload

**Comment by smortaz** [comment]
dear taupalosaurus,

when i click the upload button, the pop up does offer a choice of where to upload to the file to.  is it not showing for you?  see the pic below:

![image](https://user-images.githubusercontent.com/742484/31396069-3c489b8e-ad97-11e7-8b82-672967673c08.png)

i checked and it seems to put the file in that directory.

wrt students, is uploading files absolutely necessary?  note that if you as the instructor put all the needed files in your ~/library folder, then when students Clone your lib, they get a deep copy.  

thx

**Comment by taupalosaurus** [comment]
Dear @smortaz,

thanks for the reply. I am  not sure we are doing the same thing though, I am trying to upload from the "home" of the library. I took screenshots to illustrate what I am trying to do. Hopefully that makes sense.
![screenshot from 2017-10-10 16-56-40](https://user-images.githubusercontent.com/17987031/31396823-58e217d0-addc-11e7-8857-979406fe04b9.png)
![screenshot from 2017-10-10 16-57-04](https://user-images.githubusercontent.com/17987031/31396845-5fadd3d8-addc-11e7-8777-ce2ab07d501e.png)
![screenshot from 2017-10-10 16-57-20](https://user-images.githubusercontent.com/17987031/31396853-629b8f4a-addc-11e7-804e-bf692f9e4c9d.png)

After a discussion with other lecturers of this course, we thought uploading was the best workaround in these two cases:
  - a student messes up so much with a notebook that he wants to re-download it and start from scratch (without re-cloning the entire library, which would erase modifications on other notebooks)
  - the lecturers want to update a notebook after the students have cloned the course library.
Of course, we are aware this could be done through git, but our students would not be able to use it.

thanks,

**Comment by smortaz** [comment]
aha, got it.

yes, that's a limitation and we need to improve it so that an uploaded notebook can be placed anywhere.  i have filed a request internally. will update this bug when it's rolled out.

i originally thought you meant upload a data file.  note that my method is a workaround meanwhile, but unfortunately but you have to start a notebook server.  ie:

1. click on a any existing notebook to get your container going
2. in the jupyter UI, click the Data upload/download button
3. select the ipynb file and place it anywhere.

thanks

**Comment by taupalosaurus** [comment]
Ok, I see. I guess it gets a bit messy if I try to overwrite a notebook, but that will do for now. Thanks!

**Comment by MarkUoLeeds** [comment]
It is as if we need a custom per file "restore" feature. I was looking for the same sort of solution for our first year environmental scientists. Keeping the original library small and repeat the cloning seems only solution at the moment. I see we can diff the libraries but it is not the clearest of output.

**Comment by antkmsft** [comment]
It looks like this is fixed now, so I am closing this issue.  I tried uploading files to subfolders, and they ended up being uploaded to a specific subfolder, as you were expecting.  If there's any issue, please let us know!
