### ISSUE TITLE
Organization accounts?

### ISSUE THREAD

**Issue by versae** [microsoft/AzureNotebooks#206]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
There are no organization accounts.

### Usage Scenario (e.g. teaching a computing course at university foo)
I work at a unit at Stanford University Libraries and we use Azure to teach several Python related workshops. We have a GitHub organization account where we put all our content and then import it to Azure. But to do this import we can only use a personal account. Is there any plan to support organization accounts in the near future?

In the lack of this feature, having the option to automatically update Azure Notebooks with a push to a GitHub repo would be very useful.

**Comment by smortaz** [comment]
Thanks Javier -

At this point we're gathering all the various account related requirements
(github, o365, ...) based on user feedback and will post an update on the
relevant threads and in the What's New tab.   But to answer the actual
question, ie *near* future (as in days/a few weeks), it's doubtful :(.

**Comment by versae** [comment]
Fair enough. Thanks for the quick reply. If there is anything I could do to help speed up the process, please, let me know.

**Comment by smortaz** [comment]
np.  any data on the # of people affected, etc. would be good.  you can
always email nbhelp@microsoft if you rather not state here. thx.

**Comment by versae** [comment]
👍

**Comment by johnagillespie** [comment]
Is this related to this issue ?

https://github.com/Microsoft/AzureNotebooks/issues/162

**Comment by versae** [comment]
Not really. I log in fine, but there is no support for the equivalent of
GitHub organizations.

--
Sent using a cell-phone, so sorry for the typos and wrong auto-corrections.
