### ISSUE TITLE
Cartopy installation not stable and cannot load Natural Earth datasets: http://www.naturalearthdata.com

### ISSUE THREAD

**Issue by slainteprod** [Microsoft/AzureNotebooks#207]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebook from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

**From Azure Notebooks via the University of Illinois.**

### Description
Attempted to install cartopy- it seems to work, but is not permitted to import natural earth datasets. Also, after leaving the notebook idle for a few hours, the cartopy modules was uninstalled and geotiff was reinstalled. 

It looks like a urlopen command is not permitted at some point (top part of error) which is followed ultimately with the below error.

~/anaconda3_410/lib/python3.5/site-packages/cartopy/io/__init__.py in _urlopen(self, url)
    263         """
    264         warnings.warn('Downloading: {}'.format(url), DownloadWarning)
--> 265         return urlopen(url)
    266 
    267     @staticmethod

****** Some errors in between

~/anaconda3_410/lib/python3.5/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    587 class HTTPDefaultErrorHandler(BaseHandler):
    588     def http_error_default(self, req, fp, code, msg, hdrs):
--> 589         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    590 
    591 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

### Repro Steps

#After an uninstall of geotiff and conda install of xarray, geos and cartopy via terminal  

import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

# Use Either
#wget https://www.esrl.noaa.gov/psd/thredds/fileServer/Datasets/gistemp/combined/250km/air.2x2.250.mon.anom.comb.nc
#nc=xr.open_dataset('air.2x2.250.mon.anom.comb.nc')

#Or
nc=xr.open_dataset('https://www.esrl.noaa.gov/psd/thredds/dodsC/Datasets/gistemp/combined/250km/air.2x2.250.mon.anom.comb.nc')

jan1976 = nc.sel(time=pd.datetime(1976,1,1))
jan2017 = nc.sel(time=pd.datetime(2017,1,1))

#Clean up data masking - this will maske where data is nan, and put the good values in there
#data = np.ma.masked_where(np.isnan(jan2017['air'].values),jan2017['air'].values)
data = jan1976['air']
data2 = jan2017['air']

# create figure, axes instances.
fig = plt.figure()
ax = fig.add_axes([0.05,0.05,0.9,0.9])

ax = plt.axes(projection=ccrs.Orthographic(-80, 35))
data.plot.contourf(ax=ax, transform=ccrs.PlateCarree());
ax.set_global(); ax.coastlines();
    
plt.show()

### Usage Scenario (e.g. teaching a computing course at university foo)
Teaching a University Course- Atmospheric Sciences 305- Computing and Data Analysis at the University of Illinois

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):  Python 3
Occurrence Time: On demand 
Web Browser: Chrome
LibraryID and Notebook Name (if applicable): atms305cda-1, M7PB_xarray_cartopy.ipynb
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
hi,

that's because  http://www.naturalearthdata.com isnt on our white list.  we can add it shortly.  we use a white list to limit abuse (spam, ddos, etc.)

regarding pkgs being gone - each time you start a container, you get a clean slate of r/py/f# w various preinstalled libs.  anything on top of that has to be installed.  you can installed via a "setup.ipynb" type notebook and run manually, or you can add commands in the aznbsetup.sh file which will be run automatically.

if the container is unused for a period of time it will be reclaimed.  see the faq for more info.

thanks!

**Comment by crwilcox** [comment]
Hi @slainteprod, I whitelisted NaturalEarthData.com last week. You should be able to download the content now. Also @smortaz is correct. The packages are not part of our base image. On Restart you go back to the base image.

Thanks!
Chris

**Comment by aenesbitt** [comment]
Yeah, I'm not sure the white listing worked completely... I can even use commands like this:
states = NaturalEarthFeature(category='cultural', scale='50m', facecolor='none',name='admin_1_states_provinces_shp')
ax.add_feature(states, linewidth=0.5)
without getting the HTTPError: HTTP Error 403: Forbidden 

Is this what needs to be on the white list: http://naciscdn.org/ . Thanks!!

**Comment by jmo808** [comment]
There is still something funny going on. Some shape files form Natural Earth seem to work but not others. The coastline files do, but as referenced admin_1_states_provinces does not ever load. 

/home/nbuser/anaconda3_420/lib/python3.5/site-packages/cartopy/io/__init__.py:264: DownloadWarning: Downloading: http://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_1_states_provinces_lines.zip
  warnings.warn('Downloading: {}'.format(url), DownloadWarning)

![untitled](https://user-images.githubusercontent.com/6784537/36271365-05f45804-1244-11e8-8802-fef5b4c359e1.png)

as seen in the attached picture the states_provinces_lines shapes never load. Code below:

```
# An arbitrary choice.
canada_east = -63
canada_west = -123
canada_north = 75
canada_south = 37

standard_parallels = (49, 77)
central_longitude = -(91 + 52 / 60)

fig = plt.figure()
ax_map = fig.add_subplot(1, 1, 1,
                     projection=ccrs.LambertConformal(central_longitude=central_longitude,
                                                      standard_parallels=standard_parallels))
ax_map.set_extent([canada_west, canada_east, canada_south, canada_north])
ax_map.stock_img()
ax_map.coastlines()
#ax_map.gridlines()

#land_50m = feature.NaturalEarthFeature('physical', 'land', '50m',
#                                        edgecolor='k',
#                                        facecolor=feature.COLORS['land'])
provinces_50m = feature.NaturalEarthFeature('cultural',
                                             'admin_1_states_provinces_lines',
                                             '50m',
                                             facecolor='none')
ax_map.add_feature(feature.OCEAN)
ax_map.add_feature(feature.LAND)
ax_map.add_feature(feature.LAKES)
ax_map.add_feature(feature.BORDERS)
ax_map.add_feature(feature.COASTLINE)
ax_map.add_feature(feature.RIVERS)
ax_map.add_feature(provinces_50m)
```

**Comment by smortaz** [comment]
Does the same exact notebook work properly on a local Jupyter instance?

**Comment by jmo808** [comment]
Hmm, I tried it in my local instance of Jupyter and in IPython and it's still not working. I wonder if it's a cartopy bug. Probably.

**Comment by smortaz** [comment]
ok. aznb is basically a hosted version of the stock jupyter.  so ideally
it's best to try it locally as well to see if it's jupyter / the pkgs /
data / etc. vs aznb.
