### ISSUE TITLE
Making curl calls on Windows - Sentiment Analysts with Tweets 

### ISSUE THREAD

**Issue by DaveVoyles** [Microsoft/AzureNotebooks#208]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebook from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

Azure Notebooks.

### Description
Cannot execute *!curl* command on Windows, per instructions in the following sample:
**Sample:** [Sentiment Analysis with Tweets](https://notebooks.azure.com/Microsoft/libraries/samples/html/Discover%20Sentiments%20in%20Tweets.ipynb)

### Repro Steps
1.  **Instructions from Jupyter Notebook:**

> Download this dataset by running the following command
!curl -L -o mydatafile.csv http://azuremlsamples.azureml.net/templatedata/Text%20-%20Input.csv

2. Cannot run !curl on Windows

3. You CAN however run it through GNU bash on Windows. 

4. Suggested Solution:

a) Instruct users to open the Windows Command Line
b) In the CLI, enter *bash*
c) Copy the command above
d) Remove the *!* preceding the *curl* command
e) Run the command:
*curl -L -o mydatafile.csv http://azuremlsamples.azureml.net/templatedata/Text%20-%20Input.csv*

![image](https://user-images.githubusercontent.com/1786053/31523056-55436fa8-af7f-11e7-982d-ce6524494009.png)

**Comment by smortaz** [comment]
Hi Dave,

 Just want to clarify: how are you running the notebook on windows? Azure
notebooks  runs on Linux. Are you perhaps downloading the notebooks and
running them on windows  locally?

**Comment by DaveVoyles** [comment]
You know what, that explains my confusion. 

Yes, I am running this on my Windows desktop and just navigate to the Azure Notebooks page. I download the .csv locally, then import it into the notebook's workspace. 

![image](https://user-images.githubusercontent.com/1786053/31559746-c6e482d2-b01f-11e7-924e-bb9f72339187.png)

I'd like to use the **Featured Libraries ** as part of a two-day [data.sci.conf in Atlanta](http://www.datascicon.tech/) which Microsoft will be a part of. Some of the developers in attendance will have ML / data science backgrounds, but others will not. 

I see now that I could literally just put the !curl command within the Jupyter notebook cell and it will work!
![image](https://user-images.githubusercontent.com/1786053/31560121-1e51472a-b021-11e7-9e1f-18e618d96de5.png)

**Comment by smortaz** [comment]
Ah good, that explains it.  

Yes, the idea behind Azure Notebooks is that you can run the notebooks directly in your browser / on Azure w/o doing a boatload of installs.  ie, as an instructor you should be able to:

* show the URL to your library to the students
* they click, login, Clone
* Run!

(at least that's the ideal path...)

PS the .csv getting a download prompt instead of just being rendered is a known bug that'll be fixed.

**Comment by DaveVoyles** [comment]
Thanks for the clarification. I realized I was using incorrectly (user error), so I'm going to close this.
