### ISSUE TITLE
Preview / Edit - Discrepancies

### ISSUE THREAD

**Issue by consideRatio** [Microsoft/AzureNotebooks#209]
```latex
\begin{align}
f(x)     & = x^2         & f(2)     & = 4  \\
g(x,y)   & = x^2+y^2     & f(2,3)   & = 13 \\
h(x,y,z) & = x^2+y^2+z^2 & f(2,3,4) & = 29 \\
\end{align}
```

PREVIEW:
![image](https://user-images.githubusercontent.com/3837114/31605493-a2e9b7aa-b266-11e7-9466-8af19383252f.png)

EDIT:
![image](https://user-images.githubusercontent.com/3837114/31605552-cf216994-b266-11e7-8819-62204bd551e9.png)

**Comment by crwilcox** [comment]
@consideRatio, are the discrepencies in swedish characters?

**Comment by crwilcox** [comment]
I looked again. It seems the issue is that instead of an = in `f(x) = x^2` you are getting an `amp; =` as in `f(x) amp; = x^2`.

It seems something about the specified latex math formatting is getting sanitized.

**Comment by DinoV** [comment]
The issue here is that the nbconvert sanitizer uses html5lib to do the sanitization.  When it parses text it turns html entities into their correct text form (e.g. "&amp;" becomes "&").  For a bare ampersand that isn't an HTML entity it also just remains as "&".  When the output is serialized these entities are re-escaped and they are then turned into "&amp;".

**Comment by DinoV** [comment]
And if we avoid the escaping in the sanitizer then we still hit it explicitly escaping in the nbconvert code:

https://github.com/jupyter/nbconvert/blob/master/nbconvert/filters/markdown_mistune.py#L92

**Comment by DinoV** [comment]
But that 2nd escaping is okay, it looks like MathJax handles it

**Comment by consideRatio** [comment]
Uploaded some clues [here ('download as html' files and screenshots)](https://github.com/consideRatio/azure-notebooks-issues/tree/master/issue-209) from minor detective work and made a notebook that you can utilize in order to reproduce the discrepancies I notice available [here on azure](https://notebooks.azure.com/consideRatio/libraries/azure-notebooks-issues/html/issue-209.ipynb).

There are discrepancies between notebooks.azure.com's **preview**, **run**, and **download as HTML** like this, while the differences between a local jupyter instances **run** and **download as HTML** is minor.

# BELOW --- AZURE-RUN
![](https://github.com/consideRatio/azure-notebooks-issues/raw/master/issue-209/issue-209-azure-run.png)
# BELOW --- AZURE-PREVIEW
![](https://github.com/consideRatio/azure-notebooks-issues/raw/master/issue-209/issue-209-azure-preview.png)
# BELOW --- AZURE-DOWNLOAD
![](https://github.com/consideRatio/azure-notebooks-issues/raw/master/issue-209/issue-209-azure-download.png)
# BELOW --- LOCAL-JUPYTER-INSTANCE-RUN
![](https://github.com/consideRatio/azure-notebooks-issues/raw/master/issue-209/issue-209-local-run.png)
# BELOW --- LOCAL-JUPYTER-INSTANCE-DOWNLOAD
![](https://github.com/consideRatio/azure-notebooks-issues/raw/master/issue-209/issue-209-local-download.png)
