### ISSUE TITLE
Natural Earth Dataset at http://naciscdn.org/

### ISSUE THREAD

**Issue by aenesbitt** [Microsoft/AzureNotebooks#211]
Please consider the template below to file your issue. 

My issue was closed today, but I still can't download assets from natural earth dataset.  I am thinking that the site that needs to be whitelisted is http://naciscdn.org/     rather than http://www.naturalearthdata.com/ 

based on the recommendation that I download the following when evoking ax.coastlines() :
http://naciscdn.org/naturalearth/110m/physical/ne_110m_coastline.zip

Any chance this can happen?  Thanks!  slaniteprod/anesbitt

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
It was whitelisted and closed. I have also whitelisted this cdn.
