### ISSUE TITLE
SAMPLE: Creation and Deployment of an Azure ML Web Service.ipynb throws AttributeError: 'Arguments' object has no attribute 'keywords' error

### ISSUE THREAD

**Issue by DaveVoyles** [Microsoft/AzureNotebooks#212]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Arrived from Azure Notebooks 

- (notebooks.azure.com)
- Python 3.6

## AttributeError: 'Arguments' object has no attribute 'keywords' error ##

Error appears in the **Deploying the model as a web service** section.

![image](https://user-images.githubusercontent.com/1786053/31638255-9e80a6ee-b2a0-11e7-976f-a91a3482e29e.png)

### Repro Steps
[Run through sample](https://notebooks.azure.com/Microsoft/libraries/samples/html/Creation%20and%20Deployment%20of%20an%20Azure%20ML%20Web%20Service.ipynb) until you get to that step.

### Recommended Metadata
[You can find my notebook with the issue, here.](https://notebooks.azure.com/n/7tnY5pcWwL8/notebooks/Deploy%20Azure%20ML%20service.ipynb)

Happy to provide more details. My MSFT alias is **dvoyles**.

**Comment by smortaz** [comment]
Hi dave - on the menu bar, click Kernel, switch to Python 2 and it should run.  i'll create an issue.

**Comment by DaveVoyles** [comment]
Perfect, I'll do that. Thanks!

**Comment by getroyer** [comment]
You may want to try the new AML offering:  [AML getting started project](https://notebooks.azure.com/azureml/projects/azureml-getting-started).
