### ISSUE TITLE
I can't execute any cell in my azure notebook on macbook 

### ISSUE THREAD

**Issue by Colinwantstoknow** [microsoft/AzureNotebooks#213]
I was doing some simple coding on my macbook pro, it was fine in the beginning, then there was no response whatsoever when i click the "run the cell". And the kernel connection showed no problem, and the internet worked well. I wonder how to solve this. Was it something I did that caused this?
The Jupyter Kernel is Python3
Occurrence Time:
Web Browser:Safari and chrome, it didn't work on both.

**Comment by smortaz** [comment]
Hi Colin - was there more than an hour of inactivity by any chance?  after
a while we figure youve gone and reclaim the container.  if this wasnt the
case, can you provide a link to your notebook that i can look at?   thx.
