### ISSUE TITLE
Several crashes during lab session

### ISSUE THREAD

**Issue by taupalosaurus** [microsoft/AzureNotebooks#215]
Hi,

We've been using azure notebooks  (notebooks.azure.com) for our undergrad computer lab sessions for two weeks now, and both weeks we had a certain number of unexplained crashes, and cases when the notebook freezes and we cannot execute any kernel. The first week I assumed the students were doing something wrong, but yesterday I checked in some cases and I couldn't see anything wrong, except that no kernel (even a simple print("hello")) would execute. We tried to interrupt kernels, we tried to reload the notebook (reload the page), one student even said they tried to log off and on again but it still didn't work
I suggested switching browsers in most cases (from Chrome to Firefox) and it seemed to fix the problem at least until the end of the lab.

Do you have any idea why this is happening, and what could be done to avoid this situation ? We were planning to use azure for our lab sessions and for the exam, but I am a bit worried about the exam if this keeps happening.

I have noted a few details on 2 cases (browser version, user name and lib id, approximate time, I didn't think of exporting the logs though)

Thanks for your help!

**Comment by smortaz** [comment]
Sorry about that! Can you please include some library links and
times/dates?  If you prefer send the information to nbhelp@microsoft  and
we can take a look.  There were some issues when we upgraded to the latest
version of Tornado which we have reverted since.

**Comment by taupalosaurus** [comment]
thanks for your reply @smortaz . I have sent the details by email as I don't know how public these things are supposed to be, but I'm happy to continue the conversation here.
