### ISSUE TITLE
Getting PermissionDenied error while installing TensorFlow v1.3.0

### ISSUE THREAD

**Issue by geekwhocodes** [Microsoft/AzureNotebooks#217]
Hi there,

I'm getting permission denied error while installing tensorflow version 1.3.0.  any solution?
here is the terminal screen-shot 
![image](https://user-images.githubusercontent.com/10639200/31866494-cf67d5c8-b79d-11e7-9a44-5065a90110f4.png)

**Comment by smortaz** [comment]
howdy - i just used conda and it seems to install ok:

![image](https://user-images.githubusercontent.com/742484/31904614-a69082c4-b7e0-11e7-8267-d49304de2d06.png)

**Comment by geekwhocodes** [comment]
Thanks! 
but this is weird, take a look at image:
![image](https://user-images.githubusercontent.com/10639200/31911393-2034476e-b85e-11e7-9a8a-ff09ce0b37a5.png)

**Comment by geekwhocodes** [comment]
After running this bash script, that worked. 
#!/bin/bash
export PATH=~/anaconda3_410/bin:$PATH &&
echo 'y' | conda install tensorflow &&
echo 'y' | conda install tensorflow-tensorboard
echo y
