### ISSUE TITLE
Cannot connect to CARTO SQL API

### ISSUE THREAD

**Issue by jaakla** [Microsoft/AzureNotebooks#218]
### Azure Notebooks environment 
notebooks.azure.com

### Description
Trying to load data from CARTO SQL API, gives `ProxyError: HTTPSConnectionPool(host='nutiteq.carto.com', port=443): Max retries exceeded with url: /api/v2/sql?q=select%20*%20from%20ee_speedcam (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 403 Forbidden',))) `

Seems to be same as #32 - domain not whitelisted?

Affects probably all [CartoFrames](https://github.com/CartoDB/cartoframes/) users.

### Repro Steps
Simplest Notebook cell:
```
import requests
page = requests.get("https://nutiteq.carto.com/api/v2/sql?q=select * from ee_speedcam")
page
```

### Additional info
Please whitelist `*.carto.com` , every user on that service has own subdomain.

**Comment by smortaz** [comment]
hi @jaakla - can you try it now?  thx

**Comment by jaakla** [comment]
Thank you, works fine now!
