### ISSUE TITLE
ivate python36

### ISSUE THREAD

**Issue by Ali-TRIPLab** [Microsoft/AzureNotebooks#219]
Please consider the template below to file your issue. 

### Azure Notebooks environment 
Did you arrive at a notebooke from Azure Notebooks (notebooks.azure.com) or Azure ML Studio (studio.azureml.net)

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Hi, it’s hard to figure out what is wrong. Can you please describe your
issue in more detail? Thank you

**Comment by crwilcox** [comment]
closing due to insufficient details.
