### ISSUE TITLE
Cloud9 Whitelist Request

### ISSUE THREAD

**Issue by mohsinhaider** [Microsoft/AzureNotebooks#220]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
I have a server setup on Cloud9 that I am making requests to from Azure Notebooks, but am receiving the following ProxyError as "https://c9users.io" is not whitelisted. 

`HTTPSConnectionPool(host='user-name.c9users.io', port=443): Max retries exceeded with url: /time/ (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))`

### Repro Steps

```
import requests
requests.get("https://user-name.c9users.io" + "/time/").json()
```

### Usage Scenario
I am teaching university students about data science and have a server running under my username for Cloud9 and would like to introduce them to Azure Notebooks and Microsoft's other data science services. I have a specific user name that replaces the "user-name" in the full URL, and if it is more safe to whitelist that URL then I would be more than happy to provide that. We are only running this Azure Notebooks workshop event for 1 day, so if it's possible for just a temporarily whitelist that would be great and the students would be able to use Azure Notebooks for the workshop.

### Recommended Metadata
The Jupyter Kernel (Python2, Python3, R, N/A): Python3
Web Browser: Chrome
LibraryID and Notebook Name (if applicable): https://github.com/acmillinoistech/lyftstarter contains the same notebook being used for the data science workshop, except that the "URL" variable would be "https://user-name.c9users.io" instead of localhost.

**Comment by smortaz** [comment]
Howdy. I’ll add it tomorrow. Thanks!

**Comment by mohsinhaider** [comment]
@smortaz Thank you so much!

**Comment by smortaz** [comment]
Done.  should roll out from now till a few hours.  please verify & then close.  thanks!

**Comment by mohsinhaider** [comment]
@smortaz Working great! Thank you so much.
