### ISSUE TITLE
Broken link on clicking 'Get Started' button on the home page of https://notebooks.azure.com/

### ISSUE THREAD

**Issue by kapeed2091** [Microsoft/AzureNotebooks#221]
### Azure Notebooks environment 
Azure Notebooks (notebooks.azure.com)

### Description
Tried accessing 'Get Started' on the home page of https://notebooks.azure.com/
Link seems to be broken

<img width="1438" alt="screen shot 2017-10-26 at 9 30 01 am" src="https://user-images.githubusercontent.com/7793159/32034536-b52b0fa0-ba30-11e7-8d0c-e97d9542409f.png">

**Comment by smortaz** [comment]
Thanks kapeed2091.  we had a rollout that broken a few links, fixing now.

**Comment by DinoV** [comment]
Thank you for reporting this, we've got a fix deployed now!
