### ISSUE TITLE
nbgrader support for quizzes and assignments?

### ISSUE THREAD

**Issue by denfromufa** [microsoft/AzureNotebooks#222]
https://groups.google.com/forum/m/#!topic/jupyter-education/o0DU9mL-huo

I'm currently using Google Forms, but would like to build assignments in jupyter Notebooks using nbgrader and deploy them to Azure Notebooks

**Comment by smortaz** [comment]
Thanks for filing. Are there is please upvote if interested. We have it on
our backlog but need some customer evidence to prioritize it. Thx

**Comment by denfromufa** [comment]
Looks like other platforms are actively working on setting up nbgrader or already have done so. My understanding is that nbgrader works best with jupyterhub: 

https://blogs.msdn.microsoft.com/uk_faculty_connection/2017/07/21/nbgrader-to-automate-assessment-and-grading-with-jupyterhub-on-azure-data-science-vm/
http://nbgrader.readthedocs.io/en/latest/configuration/jupyterhub_config.html

Temporarily I'm going to collect and distribute assignments manually and use nbgrader just for building these notebooks with assignments.

**Comment by jaskarannagi19** [comment]
Any progress here guys any grading tools
