### ISSUE TITLE
Link to the library not working

### ISSUE THREAD

**Issue by Candicexiu** [Microsoft/AzureNotebooks#223]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I took a course on edx last month, and AzureNotebooks helped a lot. But yesterday when I tried to resume my course, I found the link -- https://notebooks.azure.com/eric/libraries/DEV236x  to the library does not work.
#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.5
 
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by smortaz** [comment]
Hi there. When you say it doesn’t work what is the error details? I just
clicked that link and the library seems to be there with all the notebooks…
Make sure you have signed in so you can see your own clone of the library.
  Should then be able to click on any of the notebooks which puts you in
jupyter.

**Comment by Candicexiu** [comment]
Thanks for your reply. I don't know what's wrong with the web, but--
When I clicked the link of the library, it merely showed up the basic page without any notebook.
Then I clicked sign in, it jumped out a page with a link "{{item.description}}".
I've tried on two other computers but it turned out to be the same.

**Comment by smortaz** [comment]
interesting.  what happens when you try the link in incognito mode in your browser.  also which browser?

**Comment by Candicexiu** [comment]
Then it just jumped back to the first page without any notebook...
I've tried IE browser, Chrome and UC browser.

**Comment by smortaz** [comment]
can you screen capture?  i just tried your link and it works fine:

0. signed in
1. clicked https://notebooks.azure.com/eric/libraries/DEV236x
2. clicked clone
3. gave it a new name 
5. got my cloned copy

https://notebooks.azure.com/smortaz/libraries/demo-DEV236x

6. clicked the 1st notebook:

![image](https://user-images.githubusercontent.com/742484/32158169-b44ed7c0-bd04-11e7-9611-70f0fc1066e1.png)

**Comment by Candicexiu** [comment]
Sorry, maybe it is due to the network connection... 
Now it works well. 
Thanks again for your reply.

**Comment by smortaz** [comment]
No worries!
