### ISSUE TITLE
Unable to point a variable to a text file using ~/library/

### ISSUE THREAD

**Issue by jsaue003** [Microsoft/AzureNotebooks#224]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering

I am trying to point a variable, data, to a text file stored in a library in Azure. The library contains the notebook, and one text file. I used the following code:

`data = ~/library/response.txt`

Unfortunately, I get an error:

` File "<ipython-input-15-951b17197b75>", line 7
data = ~/library/response.txt
        ^
SyntaxError: invalid syntax`

I have used this command before though in Azure Notebook without a problem:

`pokeframe = pd.read_csv("~/library/Poketypesmachinedecrypted.csv", index_col=0)`

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/n/iDby89Ve9hI/notebooks/CourseDataParsing.ipynb

Feel free to look through. Just want to put a text file from library into a variable, then put that into Beautiful Soup to read it like it would on a computer. 

#### Which language/kernel were you using when you experienced this issue?

    [x] Python 3.6 

#### What time (please include time zone) did this occur?
6:01 EST 
#### Which Web Browser(s) did you see the error in?
    [x] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

~/library/response.txt

**Comment by smortaz** [comment]
I believe the problem is that one is a python assignment, the other a shell command, ie:

this isn't legal python:

data = ~/library/response.txt

it should be:

data = '~/library/response.txt'

perhaps you were doing ! before where you used ~ directly?, ie

!ls ~/library/response.txt

and

data = !ls ~/library

in your code there also seems to be an extra directory node:

data = '/home/nbuser/library/**webscraping**/response.txt'

it looks like it should be:

data = '~/library/response.txt'

**Comment by jsaue003** [comment]
[I've updated it just like you said, at least format wise. The issue continues to persist](https://notebooks.azure.com/n/zwJSgACBy2A/notebooks/CourseDataParsing.ipynb). My exact code now is this:

`!ls ~/library

FIU = open('~/library/response.txt','r').read()`


Still, get the error: 

`FileNotFoundError                         Traceback (most recent call last)
<ipython-input-15-c18512375ba8> in <module>()
      1 get_ipython().system('ls ~/library')
      2 
----> 3 FIU = open('~/library/response.txt','r').read()
      4 #soup = BeautifulSoup(FIU, "html.parser")
      5 

FileNotFoundError: [Errno 2] No such file or directory: '~/library/response.txt'`


No idea why, but Azure just will not let me put a straight up link to a file in library. Even tried it as   '~/library/webscraping/response.txt' but it didn't change anything. Still no file found error. Maybe a bug in this version?

**Comment by smortaz** [comment]
The "~" works with ! commands (which are not sent to python, but to the system shell).  

for the file open call you need to specify the full path, ie: /home/nbuser/library/response.txt 

```
data = open('/home/nbuser/library/response.txt','r').read()

soup = BeautifulSoup(data, "lxml")
```

take a look at:

https://notebooks.azure.com/smortaz/libraries/webscraping-1

**Comment by jsaue003** [comment]
@smortaz Solved my issue. That was exactly what I was looking for. Now it works without fail. Another brilliant solution in the books. Thank you!
