### ISSUE TITLE
Visualizing  ggvis plot in R Notebook

### ISSUE THREAD

**Issue by ncdingari** [microsoft/AzureNotebooks#225]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I a unable to visualize ggvis plot in R Notebook, I ran a simple code

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

```
mtcars %>%
ggvis(x = ~wt, y = ~mpg) %>%
layer_points() 
```

#### Which language/kernel were you using when you experienced this issue?
    [] R 

#### What time (please include time zone) did this occur?
3pm EST

#### Which Web Browser(s) did you see the error in?
    [] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/n/PT2U4QD5Cn8/notebooks/ggvisDemo.ipynb

**Comment by smortaz** [comment]
I believe you need to install the pkg first before using it:

install.packages('ggvis')

**Comment by ncdingari** [comment]
I did install the package, before I tried above example

**Comment by smortaz** [comment]
Ah ok.  It looks like this is a limitation of Jupyter in that the plot cannot be shown inline :(.  See:

https://github.com/twosigma/beakerx/issues/2301

ie, it tries to open a separate page which currently isn't supported.  I can see other plots inline fine but not with this:

![image](https://user-images.githubusercontent.com/742484/32394480-80465702-c09a-11e7-816e-f9c3a6e40a03.png)

So it will work with Jupyter locally presumably, but not on Azure notebooks.

@DinoV - any comments from you?
