### ISSUE TITLE
I can't pip install turbodbc

### ISSUE THREAD

**Issue by gabomgp** [Microsoft/AzureNotebooks#226]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

In a new blank notebook in Azure Notebook, when i try the command:

    !pip install turbodbc

The installation is failed, and in the compilation process, the error message is:

    src/cpp_odbc/level2/level1_connector.cpp:17:28: fatal error: boost/locale.hpp: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/ggomez/libraries/prueba-parquet/html/traerInventarios.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

12:30 PM (-05 GMT)

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/ggomez/libraries/prueba-parquet/html/traerInventarios.ipynb
  
The Question is: is possible to install turbodbc in Azure Notebooks currently?

**Comment by smortaz** [comment]
Howdy - I tried conda and it worked:

![image](https://user-images.githubusercontent.com/742484/32408482-b728f67e-c155-11e7-9eb4-ec1f3822ab2b.png)

**Comment by gabomgp** [comment]
@smortaz I can confirm installing with conda works ok.

**Comment by smortaz** [comment]
Great, I’m glad it worked for you. Please close the bug if you’re happy
with this solution.

**Comment by gabomgp** [comment]
I cant reproduce the error, you can close the issue if you want.
