### ISSUE TITLE
Issues with external package astroquery

### ISSUE THREAD

**Issue by aleksthethird** [Microsoft/AzureNotebooks#228]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I'm building a Python notebook using the external package astroquery (http://astroquery.readthedocs.io/en/latest/index.html) which is installed via pip in the notebook. It installs without errors and loads without errors. But from that point onwards not a single routine I tried thus far gives any result. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Try this link for some examples: 
https://notebooks.azure.com/aleksthethird/libraries/Transients

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

21:00 British time

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? 
https://notebooks.azure.com/aleksthethird/libraries/Transients

**Comment by crwilcox** [comment]
It should be working now. Let us know and close this ticket if this is resolved for you.
Thanks!
Chris
