### ISSUE TITLE
Can the notebook remain running while I'm away?

### ISSUE THREAD

**Issue by ch-hristov** [microsoft/AzureNotebooks#229]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Is there a way the notebook to work when i'm away from the website? I'm usually training the model and it would be very nice if it could train itself in the cloud without closing itself after a period of inactivity. A nice way for this to be possible is that it could take away money from my azure account.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi ch-hristov - we are looking at enabling the fire-and-forget scenario in the future.  For now, the service is meant mostly for interactive use.  We'll document that constitutes more clearly soon - but basically after ~1hr of inactivity your container is reclaimed.

**Comment by nextofsearch** [comment]
Training a deep learning model usually takes long time so this is a must-have.

**Comment by smortaz** [comment]
Hi, it’s coming along w the ability to select hw, like gpu enabled
machines.  Date is tbd.

**Comment by sgkang** [comment]
Hi @smortaz. I want experiment running bit more large scale computing here by multiple users using jupyter platform. Is there an option that I can choose different machines as you guys do for general azure service? assuming we pay corresponding bill?

**Comment by smortaz** [comment]
Hi @sgkang - not quite yet, but it's coming.  Will update this bug when the trial is ready!  cheers!

**Comment by tomkom** [comment]
Any update on this?
