### ISSUE TITLE
"Clone and Run!" not working

### ISSUE THREAD

**Issue by ideaterminal** [Microsoft/AzureNotebooks#23]
Please consider the template below to file your issue. 

### Description
"Clone and Run!" button not working

### Repro Steps
Dont log in. Go to samples. Pick "An informal introduction to Python". Click "Clone and Run!"

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
GET https://notebooks.azure.com/api/libraries/samples/html/custom.css 
angular.js:13920 TypeError: Cannot read property '$window' of undefined
    at angular_site?v=ahE7dI0tIoO8BP52oieO7tYKR4mr3FaenPRUxCAjtWc1:840
    at angular.js:16383
    at m.$eval (angular.js:17682)
    at m.$digest (angular.js:17495)
    at m.$apply (angular.js:17790)
    at l (angular.js:11831)
    at J (angular.js:12033)
    at XMLHttpRequest.t.onload (angular.js:11966)

LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Thanks for the bug report - we did a last minute hot fix based so users
could view the samples w/o logging in and in the process have broken this i
think!   If you sign in it should work (just verified).  sorry about that &
fix is coming.

**Comment by smortaz** [comment]
Updated - wasnt the hot fix - a regression than crept in.  Fix is coming.
Thanks again for reporting.

**Comment by crwilcox** [comment]
Thanks for the report. I have a fix on the way to production that should resolve this.

**Comment by ideaterminal** [comment]
Cool, thx for the quick response!
