### ISSUE TITLE
please add avconv

### ISSUE THREAD

**Issue by ariovistus** [Microsoft/AzureNotebooks#230]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com
#### Describe the issue you are encountering
I would like to be able to use matplotlib's animation facilities, particularly `Animation.to_html5_video` to produce videos embedded in my notebook. In order to do this, I need a supported video writer. It looks like matplotlib supports ffmpeg, avconv, and imagemagick, but none of those seem to be installed.
If they were installed, matplotlib should detect them. If it does, `matplotlib.animation.writers.list()` should not be empty.
It looks like matplotlib embeds the video data in the page, so it should Just Work

**Comment by ariovistus** [comment]
here's an example application:
```
from matplotlib import animation, rc
import matplotlib.pyplot as plt
import numpy
from IPython.display import HTML
import matplotlib
assert matplotlib.rcParams['animation.writer'] in matplotlib.animation.writers.list(), 'choose an available writer!'
fig, ax = plt.subplots(subplot_kw={'projection': 'polar'})
beta = numpy.zeros(shape=(2,))
radii = numpy.linspace(0, 1, 2)
line, = ax.plot(beta, radii)
times = numpy.linspace(0, 60, 61)

def init():
    return (line,)
def animate(i): 
    theta = times[i]
    beta[:] = numpy.radians(90 - 6 * theta)
    line.set_data(beta, radii)
    return (line,)
    

anim = animation.FuncAnimation(fig, animate, frames=len(times), interval=1000, blit=True)
HTML(anim.to_html5_video())
```

**Comment by smortaz** [comment]
Hi - you should be able to install it via conda:

!conda install -c menpo ffmpeg

**Comment by ariovistus** [comment]
thanks smortaz
