### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by artieroggeband** [microsoft/AzureNotebooks#233]
Please describe your issue as completely as possible.

#### Which site did you access us from?

https://blogs.msdn.microsoft.com/visualstudio/2016/11/18/data-science-workloads-in-visual-studio-2017-rc/

a sentence bottom of the page 

"The actual notebooks used in the discovery of Gravitational Waves by the LIGO team"

    [] https://notebooks.azure.com

#### Describe the issue you are encountering

https://notebooks.azure.com/library/LIGOOpenScienceCenter

is broken

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/library/LIGOOpenScienceCenter

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

none

#### What time (please include time zone) did this occur?

between 2 and 3 PM EST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [X] Other (Please Specify)
EDGE
aha, let me try this link in Chrome, nope same thing:

Page not found
The page you're looking for was not found. Please check the address, verify you are signed in, or let us know about the broken link.

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

se link above

**Comment by smortaz** [comment]
thanks for the heads up!  looks like they moved their notebook to here:

https://notebooks.azure.com/roywilliams/libraries/LIGOOpenScienceCenter

i'll see if i can get the blog updated.

cheers.
