### ISSUE TITLE
Environment variable not set

### ISSUE THREAD

**Issue by rajesh-chawla** [Microsoft/AzureNotebooks#237]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Can't set environment variable before starting notebook.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1. I created a file named env.sh and added the lines:
#!/bin/bash
export MY_VAR=a
2. I added the file env.sh as a shell script after choosing 'Settings' / 'Environment'
3. I restarted the notebook
4. As a step in my notebook, I added:
print(os.environ['MY_VAR'])

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Thanks for the report - being tracked internally.  will update here.

**Comment by KieranBrantnerMagee** [comment]
Hey Rajesh, sorry for the slow reply.

The problem with this is that Export only persists the env variable through the current bash session; and the setup steps run prior to the session in which your notebooks will run.  

I'm looking into some potential workarounds we can apply; in the interim storing the variable in a file inside ~ would be a hacky way to prep your vars from setup.  Will follow up here if I can get you a better fix.

**Comment by marketneutral** [comment]
I don't find that this solution works. I have a file `setup.sh` which is set to run in the Environment tab as a Shell Script:

```
#!/bin/bash
echo 'export MY_VAR=a' >> /home/nbuser/.bashrc
cat /home/nbuser/.bashrc
```

I observe in the `.nb.setup.log` that the line is indeed appended.

However then when I launch the nb, I try

```
import os
ENV_VAR = os.environ['MY_VAR']
```

which returns with `KeyError: 'MY_VAR'`

**Comment by nuno-andre** [comment]
Shebangs are `#!/usr/bin/env bash` now, so sed strings should be:

```
sed -i 's/#!\/usr\/bin\/env bash/#!\/usr\/bin\/env bash\nsource ~\/.env_vars\n/g' ~/.kernels/python36/python3_path.sh
sed -i 's/#!\/usr\/bin\/env bash/#!\/usr\/bin\/env bash\nsource ~\/.env_vars\n/g' ~/.kernels/python3/python3_path.sh
sed -i 's/#!\/usr\/bin\/env bash/#!\/usr\/bin\/env bash\nsource ~\/.env_vars\n/g' ~/.kernels/python2/python2_path.sh
```
