### ISSUE TITLE
Is it possible to share private library to specific people?

### ISSUE THREAD

**Issue by tsaiichi** [Microsoft/AzureNotebooks#238]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [v] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Currently the library sharing seems only for public library.
Will it be possible to share private library to only ones who know my link?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
By clicking 'share' and the window will show 'This library is not currently public. Other users attempting to access this library will not be able to see it.'

**Comment by smortaz** [comment]
Hi.  Not at this time.  But it's a feature that will be available in the future.

**Comment by tsaiichi** [comment]
Got it.
This feature will be very helpful.
Looking forward to it.
