### ISSUE TITLE
Whitelist request: arcgis.com

### ISSUE THREAD

**Issue by khibma** [Microsoft/AzureNotebooks#239]
Hello,

Further to issue https://github.com/Microsoft/AzureNotebooks/issues/145 (request of opendata.arcgis.com), would you consider whitelisting the entire https://www.arcgis.com domain?

The [Esri arcgis package](https://developers.arcgis.com/python/) is used to interface with arcgis.com:

- manage arcgis.com items, users, groups, content
- create content
- perform analysis

#### repro
```
!conda install -c esri arcgis -y
from arcgis.gis import GIS
g = GIS("https://www.arcgis.com", "USER", "PASS")
```

#### error
> ~/anaconda3_420/lib/python3.5/site-packages/arcgis/gis/__init__.py in __init__(self, url, username, password, key_file, cert_file, verify_cert, set_active, client_id, profile, **kwargs)
>     262                                    "argument when connecting to the GIS.")
>     263             else:
> --> 264                 raise RuntimeError(e.args)
>     265 
>     266         if url.lower().find("www.arcgis.com") > -1 and \
> RuntimeError: (OSError('Tunnel connection failed: 403 Forbidden',),)

cc: @AtmaMani

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Should be open by end of day today. thx.

**Comment by khibma** [comment]
Very appreciated, thank you!

**Comment by khibma** [comment]
Hi @smortaz - it looks like it might be still blacklisted, I continue to get the error 
`RuntimeError: (OSError('Tunnel connection failed: 403 Forbidden',),)`
```

import urllib
urllib.request.urlopen("http://www.arcgis.com")
```

**Comment by smortaz** [comment]
That's probably something else?  perhaps you need some other permission?   seem to reach out ok:

![image](https://user-images.githubusercontent.com/742484/33140885-3e3818ca-cf66-11e7-9dc6-ff08e39d418b.png)

**Comment by khibma** [comment]
Very strange. In a python2 notebook, I can connect. Using Python 3 or 3.6, it fails with the forbidden error.

**Comment by smortaz** [comment]
I’d check on arcgis forums. Basically if from a local python script you get
the same behavior the problem isn’t with aznb.  Thx
