### ISSUE TITLE
library names can't contain underscores?

### ISSUE THREAD

**Issue by lheagy** [Microsoft/AzureNotebooks#240]
It appears that naming requirements were updated and underscores disallowed. This is a challenge when trying to share libraries with names that have underscores in it (especially when asking first-time users to clone a library) 

![image](https://user-images.githubusercontent.com/6361812/33151134-0db9db10-cfad-11e7-826e-ce8005987e5a.png)

**Comment by smortaz** [comment]
Thanks for the heads up.  Will look into this to see if it was a regression or on purpose & why.  Will update here.

**Comment by KieranBrantnerMagee** [comment]
Hey lheagy,

I believe this bug was handled a few months back, and we simply never cleaned up the ticket, apologies!  I've tested this scenario and it seems healthy, please don't hesitate to follow up if for any reason you're still having issues.

Thanks as always!
