### ISSUE TITLE
F# Notebook charting doesn't work

### ISSUE THREAD

**Issue by oleksandr-bilyk** [Microsoft/AzureNotebooks#243]
Please look at FSharp sample. No one charting sample is working initially. I have to run all cells above to make it workable.
https://notebooks.azure.com/Microsoft/libraries/fsharp/html/FSharp%20for%20Azure%20Notebooks.ipynb

![image](https://user-images.githubusercontent.com/17872879/33283687-47714620-d3b5-11e7-9c59-e94939c74af2.png)

**Comment by gilbertw** [comment]
Its a standard Jupyter model to configure the environment and data in previous cells.  Although it is possible to create a single cell to configure the environment and prep all data, that isn't the normal behavior for notebook authors.

In this particular tutorial the configuration steps are sprinkled in order as you work through the notebook.  If you work through the tutorial from top to bottom you'll see all the cells and widgets work as expected.

**Comment by oleksandr-bilyk** [comment]
I understand. Thank you.
