### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by hu6360567** [microsoft/AzureNotebooks#246]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [*] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Cannot access ipv6 websites.
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I‘m trying to pull my data from another place which doesn't have a public IPv4 address but has an IPv6 address.
```
curl http://ipv6.google.com
```
Snippets from return infomation:
```
Connection to 2607:f8b0:4000:814::200e failed.
```
Seems the webproxy is not IPv6 compatible.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [*] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by crwilcox** [comment]
@hu6360567 , thanks for the suggestion. We currently don't have IPv6 support enabled as you note. I have made an issue for the dev team to talk about. Thanks!

Also, in the meanwhile, you can download locally and upload to notebooks using the data menu we have in jupyter (or from our UI)
https://notebooks.azure.com/help/jupyter-notebooks/data/uploading/from-computer
![image](https://user-images.githubusercontent.com/638797/33393504-3dda80fa-d4f4-11e7-9dc8-301c834d83d7.png)

**Comment by hu6360567** [comment]
I've realized that I can upload from the web page.
However, the data is dynamic. I'd like to make it automated within the script.
I'll try to transfer via a private git repo.
Thanks.
