### ISSUE TITLE
FSharp.Collections.ParallelSeq not using more than 1 core

### ISSUE THREAD

**Issue by jamessdixon** [Microsoft/AzureNotebooks#247]
Please describe your issue as completely as possible.

The Library appears to not use mutliple cores when using Azure Notebooks
See here: the library owner thinks it is your docker image
https://github.com/fsprojects/FSharp.Collections.ParallelSeq/issues/14

#### Which site did you access us from?
 https://notebooks.azure.com

#### Describe the issue you are encountering
The Library appears to not use mutliple cores when using Azure Notebooks

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Log into Azure Notebooks
Clone my Library: http://bit.ly/fspydata
Open the Notebook entitled parallelSeq.ipynb
Run the parallel example: note that the sequental and the parallel runs are roughly equal
Run the processor count example: note the processor count is 8
*running this same code on my local machine returns the expected result: parallel is much faster than serial

#### Which language/kernel were you using when you experienced this issue?
    [] F#

#### What time (please include time zone) did this occur?
2PM Eastern

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
https://notebooks.azure.com/jamiedixon/libraries/PyDataNYC/html/src/parallelSeq.ipynb

**Comment by crwilcox** [comment]
@jamessdixon, we have made substantial changes to our container strategy. I see two cores reported and similar times though. This may be useful for the other thread, but the notebook system is ubuntu based, using a snapshot for mono and fsharp. It is possible this is something to do with our containerization but it seems just as likely we have an outdated/odd version of one of the tools for FSharp.

```
echo "deb https://download.mono-project.com/repo/debian xenial/snapshots/5.2.0 main" | \
    tee /etc/apt/sources.list.d/mono-xamarin.list \
apt-get update
apt-get install -y mono-complete
apt-get install -y fsharp
```
Mono:5.2.0.224 (tarball Tue Oct  3 19:49:47 UTC 2017).
FSharp: 4.1
IFSharp: https://github.com/fsprojects/IfSharp/commit/ab78108 (September 2017).

@dsyme and @cgravill since they often are in the know in this area.

**Comment by cgravill** [comment]
@crwilcox I posted some numbers and investigation on the referenced issue, hope this is useful.

**Comment by crwilcox** [comment]
@cgravill thanks! We don't do anything unusual regarding CPU virtualization in a container. If you see 2 cores reported, you have 2 cores as far as your user is concerned. You may very well be right regarding memory though. You are virtualized in Azure Notebooks and we utilize a decent size swap space. It is possible that is causing parallel running to not really get any gain.

**Comment by cgravill** [comment]
Great, going by the ratios of parallel to serial then Mono, on MacOS native, seems to be scaling worse. Virtualisation may also be having a disproportionate effect given it's a very garbage collection focused example.

The later adjusted code shows the Azure Notebook hosted environment getting clear speed-up in the parallel case code demonstrating it is able to use more than 1 core.

**Comment by crwilcox** [comment]
Thank you for lending your expertise @cgravill. The Notebooks team doesn't really have an F# aficionado and your assistance is truly appreciated. I am going to close this issue as it seems through your investigation everything is working as expected.
