### ISSUE TITLE
Feature Feedback - Add ability to create a folder from the Library View

### ISSUE THREAD

**Issue by jasonleehodges** [microsoft/AzureNotebooks#249]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
From the library view of azure, I'd like to be able to create a folder but I don't see an option to do that, only an option to create new files.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/jasonleehodges/libraries/textgenpydata

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi Jason - I believe this feature is coming.   Not sure if you know, but meanwhile you can create directories directly form the 1) notebook, 2) from the Jupyter file view and 3) from the Terminal:

![image](https://user-images.githubusercontent.com/742484/33444774-f9b70e68-d5af-11e7-9dc3-25975faa147a.png)
