### ISSUE TITLE
Plans to include product code here?

### ISSUE THREAD

**Issue by Analect** [Microsoft/AzureNotebooks#25]
I see from the README
> This GitHub repo is intended for reporting, discussing, and tracking customer issues. We don't have product code on it yet.

Having read the Reddit [post](https://news.ycombinator.com/item?id=13104200) from a few days ago and played around with the Azure notebook environment, it would be really useful to see you implementation in more detail.

Your README (extracted above) suggests you might share the platform implementation code, which would be interesting to see.  Any plans to release that on here any time soon?
Thanks.

**Comment by smortaz** [comment]
Hi, thanks for your note. Generally everything we do on my team is open
source: PTVS, RTVS, Azure SDK. We hope to continue that tradition but it is
not an immediate priority. We have a bunch of bugs and important features
to look after and once we come up for air we can discuss it and get
permission. Thanks!

**Comment by Analect** [comment]
Thanks for the quick response and clarity. Closing this for now.
