### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by ggorman** [microsoft/AzureNotebooks#251]
I have a set of tutorials running on notebooks.azure - 
https://notebooks.azure.com/ggorman/libraries/devito-tutorial-hands-on

It will works swimmingly, but the startup time is a pain because of all the additional packages that need installing, see:

https://notebooks.azure.com/ggorman/libraries/devito-tutorial-hands-on/html/aznbsetup.sh
https://notebooks.azure.com/ggorman/libraries/devito-tutorial-hands-on/html/environment.txt

Are there any optimisations I should be applying to speed up startup?

or

Is there potential to add an additional anaconda environment with more packages and packages updated to the conda-forge channel?

**Comment by gilbertw** [comment]
What you are doing is the optimal for the time being.  We are looking into ways to make this faster in future releases
