### ISSUE TITLE
.invalid file

### ISSUE THREAD

**Issue by pwichmann** [Microsoft/AzureNotebooks#252]
A student of mine reported the following problem (and that is why I cannot provide a comprehensive bug report):

>  I was just working on my coursework when my notebook suddenly stopped being able to load and **got replaced with a .invalid file** instead. I've tried all sorts of things (re-sign in, restart computer, use another computer, etc but to no avail.) the .invalid file does seem to contain some old data but in another form. Do you know how I can get around this without having to re-do everything?

Is that a known bug?
I never came across a similar problem.
If this has happened before, what causes the notebook to be replaced by an ".invalid" file?

**Comment by smortaz** [comment]
Hi, yes, it's a bizarre corner case that's been diagnosed & a fix will roll out soon.

See here for the background & a workaround:

https://github.com/Microsoft/AzureNotebooks/issues/252

**Comment by crwilcox** [comment]
The fix for this is rolled out. I am closing this issue. #184 is still open until this has been verified. Please comment on that thread if this isn't resolved.

Thanks!
Chris
