### ISSUE TITLE
notebook server won't start

### ISSUE THREAD

**Issue by DT-ZhangJia** [microsoft/AzureNotebooks#253]
I have uploaded a zip file (800mb) dataset of 25000 images.  It took me long time to unzip.
And the server won't start with those images in the library.

Is that normal?

**Comment by smortaz** [comment]
Hi. Link to library?  I can test it out.  There could be a bottleneck
somewhere with 25000 files...

**Comment by DT-ZhangJia** [comment]
https://notebooks.azure.com/darktemplar/libraries/librarywithissue

i can reproduce that issue. plz check it out.

**Comment by smortaz** [comment]
Thanks for the link DT.  I even have trouble cloning the library.  Stay
tuned while we figure out what's going on.

**Comment by DT-ZhangJia** [comment]
The problem is that: the more files in the "library" directory, the slower the server is.
Actions like opening notebook, opening terminal, changing settings...etc. will take very very very long time so that it seems the server won't start.

I tried wget and unzip the zip file into /home/nbuser/ directory. It took only 40 seconds. For the /home/nbuser/library directory, it will be hours.

**Comment by crwilcox** [comment]
@DT-ZhangJia , the library directory should essentially be considered a 'share' so copying does indeed take longer. If the data is read only, unzipping to /tmp or even just /home/nbuser is a sensible approach. While there are possibly some performance gains we can make to the library directory, those files aren't stored on the physical machine and so read/write performance is less than the rest of the system.

**Comment by DT-ZhangJia** [comment]
@crwilcox Thank you for the explanation! Hope there will be some enhancement on stored data, since all the files outside of the library will be reset when the server stopped.

**Comment by crwilcox** [comment]
@DT-ZhangJia, 

I am happy to explain a bit about what is going on. I am happy it was helpful. Also, there is definitely room for improvement. Though, for your case, this appears to be some sort of training data, which itself can be stored zipped in the lib and extracted to tmp for training. If you had outputs that were needed to be stored, that would be reasonable. I would actually recommend to still extract it to the local disk. Here is why:

Theoretically, at best, the library folder will match the rest of the disk of our running environment. Today it is much slower. The disk (/tmp) is virtualized but is 'local' to the machine you are running on. ~/library is a share that is communicating over the network to your running environment. So it is a bit slower. There are ways we can, and likely will, improve this in the future. Though my general guidance will still be true. For churning on files, it is going to be faster or equivalent to move them to the local disk for a large # of operations.

We are currently doing work that may very well substantially speed this up, for now, the above guidance should keep you unblocked I think.

Thanks!
Chris
