### ISSUE TITLE
Support for multiple kernels in one notebook using the SoS kernel

### ISSUE THREAD

**Issue by BoPeng** [microsoft/AzureNotebooks#254]
I am the developer of [SoS Notebook](https://vatlab.github.io/sos-docs/), which, if we ignore the workflow engine part, is a Python3 based kernel that allows using multiple kernels in one Jupyter notebook. More interestingly, it provides a data exchange model to transfer variables from one kernel to another, allowing, for example, one to retrieve data in Bash, load and clean in Python, analyze in R, and plot the results in JavaScript, all in one notebook. I have recently written a [blog post](https://vatlab.github.io/blog/post/sos-notebook/) to describe SoS Notebook in detail, which was well received on [Hacker News](https://news.ycombinator.com/item?id=15852821).

I came across AzureNotebooks and considered it as a great place for people to create and share notebooks, but I cannot help wondering how people can write long notebooks that involve multiple languages in AzureNotebooks. I create this ticket and would like to know

1.  Is there a real need for users of AzureNotebooks to use multiple kernels in one Jupyter notebook? I am a bioinformatician who routinely use multiple tools and libraries in multiple languages but I am not sure if this applies to a larger audience.
2. If there is a need, is there an existing solution by Microsoft/AzureNotebooks? There are magics such as `%%script` to execute scripts in other languages but these are very limited in function.
3. If answers to the above questions are Yes and No respectively, is it possible for AzureNotebooks to add SoS as one of the supported kernels?

At this point the blog post [SoS Notebook:  one notebook, multiple languages](https://vatlab.github.io/blog/post/sos-notebook/) is the best source for anyone to learn about SoS Notebook, and the [SoS website](https://vatlab.github.io/blog/post/sos-notebook/) has plenty of documentations on the [notebook interface](https://vatlab.github.io/sos-docs/doc/documentation/Notebook_Interface.html), [SoS Magics](https://vatlab.github.io/sos-docs/doc/documentation/SoS_Magics.html), [supported languages](https://vatlab.github.io/sos-docs/doc/documentation/Supported_Languages.html), and some [introductory videos](https://vatlab.github.io/sos-docs/index.html#documentation) to show how SoS Notebook works. We also provide a live server for visitors to test SoS Notebook without a local installation (press the rocket button at the top right corner of the [SoS homepage](https://vatlab.github.io/sos-docs/)). I would love to learn your opinions on SoS Notebook and will certainly be happy to work with AzureNotebooks to add support for the SoS kernel.

**Comment by szaydel** [comment]
I will comment, as this is something I have given some thought to as well. Those of us who do a lot of ad-hoc'ish work, often depend on a lot of various tools, big and small. And as a result tend to mix tools like C, R, Python, Julia, gnuplot, awk, sed, shells, etc. I do this a lot, and I know people around me do this a lot, so I imagine it is not that uncommon. I think multiple kernels in same notebook makes it much easier to remain ad-hoc'ish and have multiple powerful tools at one's disposal. Some types of data processing seem to just be more naturally done with R, while others seem to be better with python, and ability to move data within same notebook between them feels like an awesome feature.

**Comment by smortaz** [comment]
Hi Bo (and Sam),

Thanks for filing this.  In fact, I saw the HN article, and read your blog
and watched the videos with interest and told the team about it.  Congrats
on doing the work.  It is /definitely/ useful and worthwhile.

When we talked to Brian & Fernando about a year or so ago, they stated it
is an often requested feature and they were aware of the need.  In fact
most of the other 'modern' notebook systems like Beaker, DataBricks (?),
... all support cell-level specification and changing of kernels.  Back
then they said (paraphrasing) that the current architecture wasnt suitable
and that in the JupyterLab time frame they'd make it a priority.  So my
guess is that it's coming, probably once Jlab itself has stabilized.

As far as adding SoS to Azure Notebooks goes - we're doing some surveys in
the coming weeks and we can ping our audience and measure the demand.
Ultimately I believe this is a feature that should be in the base Jupyter
product.  So I'm curious as to why not work w the Jupyter team and
contribute your work there so that everyone benefits?

Cheers,

s

**Comment by BoPeng** [comment]
There were several reasons why we developed SoS Notebook as a Jupyter kernel, not something in the core of Jupyter or JupyterLab:

1. The first reason is timing. The Jupyter project is moving slowly and it is fair to say that it is in a maintenance status and would not accept major new features like multi-language support. JupyterLab was in alpha so we really did not know how long it would take for it to be mature if we contributed to JupyterLab.

2. Brian & Fernando was certainly correct in saying the current architecture of Jupyter wasn't suitable for  multi-language support. We could develop SoS Notebook by patching Jupyter (e.g. [wrap execute function with our own execute](https://github.com/vatlab/sos-notebook/blob/master/src/sos_notebook/kernel.js#L204)) for the SoS kernel without affecting other kernels, but changing the Jupyter core is a much more complex issue that might hit many dead ends. So basically multi-language support can only be implemented as a Jupyter kernel, not in Jupyter core. 

3. Adding multi-language support is difficult but it at least has a clear technical roadmap. Data exchange among kernels was a much more complex topic that we had to explore while we were developing SoS Notebook. We did not know what to propose to the Jupyter developers and we were afraid that (we were probably wrong) our needs (e.g. direct data exchange between subkernels, exchange of very complex datatypes, support for proprietary languages such as MATLAB and SAS) would not be supported by them.  

4. The most important reason was actually our vision to create a multi-language working environment backed by a workflow engine. As I have [commented in the hacker news](https://news.ycombinator.com/item?id=15852821), multi-language notebooks solve the "multi-language" but not the "large-scale" problems with bioinformatic (or data science) data analysis. A workflow engine can be counterproductive if it requires users to develop workflows in another environment and in another language, and a notebook platform would be rather limited if it can only execute the notebooks on a single machine.  Whereas it is possible to contribute multi-language support to JupyterLab, combining it with the SoS workflow engine would be a much harder sell because it goes well beyond the scope of Jupyter.

I guess the bottom line is that Jupyter would not have multi-language support in its core so the SoS kernel can be a good addition to the existing pool of supported kernels for AzureNotebooks. In the meantime, with our experience in developing SoS Notebook especially the underlying data exchange  mechanism, we are at a much better position than a few years ago to talk to the Jupyter developers on multi-language support for JupyterLab. It is unlikely they will accept SoS Notebook as a whole but we can at least contribute the parts they need and make sure that SoS notebooks will work in JupyterLab in one way or another when it is time for AzureNotebooks to switch from Jupyter to JupyterLab.

**Comment by BoPeng** [comment]
It turns out that JupyterLab does not want to change the default single-kernel setup and will welcome a multi-language kernel implementation such as SoS Notebook. Because I will certainly port SoS Notebook to JupyterLab after it matures, Jupyter notebooks with a SoS kernel will certainly be usable in JupyterLab in the future.

**Comment by smortaz** [comment]
That’s interesting to hear. Of course my information is more than two years
old so they may have change their minds. Do you have a link?

**Comment by BoPeng** [comment]
[jupyterlab/2815](https://github.com/jupyterlab/jupyterlab/issues/2815)

It says that in the May meeting the developers decided not to change the default single kernel model, and @blink1073 indicated that multi-language support could be provided in JupyterLab 2.0 as a super kernel like the SoS kernel.

**Comment by smortaz** [comment]
OK thanks. It sounds like they will look at it in the future. It would be
great if your implementation becomes mature and popular enough by that time
so that they consider integrating it into the main product.

**Comment by BoPeng** [comment]
It is possible that they will develop their own super kernel at some point. But given the timeframe that they provide, it will certainly not be in JupyterLab 1.0, even not in 2.0, so it sounds to me like a rather remote possibility. In the meantime, SoS Notebook will be ported to JupyterLab and integration with JupyterLab will be discussed (@blink1073 mentioned a few possibilities), but even if SoS Notebook stays as a third-party extension to JupyterLab, no work will be lost if AzureNotebooks switches from Jupyter to JupyterLab.

**Comment by BoPeng** [comment]
As for the "becoming mature and popular" part, I do have a history of producing mature software like [simuPOP](http://simupop.sourceforge.net/) and [Variant Tools](https://github.com/vatlab/VariantTools) but I also need all the help I can get to improve SoS Notebook. This is why I submitted the blog post to HackerNews to attract users, why I asked the Jupyter team to help promote SoS Notebook, and exactly why I am talking to you to see if I can get SoS Notebook into AzureNotebooks. Actually, if Microsoft has some funding mechanism to support such activities, I will be the first to apply. :-)

**Comment by smortaz** [comment]
Sorry by SoS becoming more mature I didn't mean to imply it was unstable or anything!  I meant as it becomes more awesome, more popular, more notebooks start using the multi-lingual support, etc. 

As far including in Azure notebooks, unfortunately, it's unlikely right now.  We're going thru some rework and rearchitecting and those currently have take priority.  People have also asked for Julia, C#, C++ support.  Currently we have some limits that doesnt allow us to put every interesting kernel on there.  Also, there's the larger question of maintenance, security update, etc etc whenever a new kernel is added.   But we'll definitely revisit the topic in the Jlab 2.0 time frame!  thanks again.

**Comment by BoPeng** [comment]
No need to apologize at all! **SoS is unstable at this stage** and I myself would hesitate to include it in AzureNotebooks if you request it right now. The purposes of this ticket are simply introducing SoS Notebook to you, asking how useful it could be to customers of AzureNotebooks, and discussing the possibility of including it in AzureNotebooks in the future, and I think I have got all the answers I need.

SoS Notebook will continue to evolve, you will collect user feedbacks and measure the demands for multi-language notebooks, Sam and friends will use it internally and send me your feedbacks (many thanks in advance!), and finally when there are enough demands and when SoS Notebook is ready, we can work together to include it in AzureNotebooks. I am confident that it will happen and the day might come sooner than we think now.
