### ISSUE TITLE
Not possible to import private github repo

### ISSUE THREAD

**Issue by FlippieCoetser** [microsoft/AzureNotebooks#255]
#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
When I want to create a new library using the from Github option, the import fails on **private** github repos. There is no place to add either a key or login so that AzureNotebooks can import the required data.

#### What steps can we take to reproduce this issue? 
Click new Library
Clock from Github Tab
Enter Repo Details
Click Import

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by crwilcox** [comment]
@FlippieCoetser, as we do not support GitHub auth at this time, this is a known limitation of the GitHub import feature. The easiest way to do this today is
1) locally, zip your repo (if you don't have it locally already you can download a repo from GitHub as a zip archive)
2) create a new library on Azure Notebooks
3) click '+' and add from computer. Add the zip file you have
4) click the terminal icon.
5) once in a terminal type `unzip githubRepository.zip`

Thanks!
Chris

**Comment by MateusAmin** [comment]
What is the rough ETA of this feature?

**Comment by leestott** [comment]
Adding support for importing private notebooks is key within the academic audiences where academic courses are deployed from private github repos using tools such as NBGitpuller https://github.com/jupyterhub/nbgitpuller ideally having the ability to import from a private repo is key.

**Comment by vackup** [comment]
You can open a Terminal in Azure Notebook and execute the git clone command inside the library directory
