### ISSUE TITLE
Libaries won't allow me to open my work

### ISSUE THREAD

**Issue by dangold18** [Microsoft/AzureNotebooks#256]
Please describe your issue as completely as possible.

    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I can log on to my notebooks but when I go in to my libraries to get some work for revision, I cannot open the files, and the message "We were unable to successfully create your notebook server" pops up.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/run/Dan-Goldsmith/intro-programming-exam-2015-1

#### What time (please include time zone) did this occur?
19.50 London GMT

#### Which Web Browser(s) did you see the error in?
    [] Chrome
  
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? 
https://notebooks.azure.com/run/Dan-Goldsmith/intro-programming-exam-2015?dest=%2Fnotebooks%2Fpython_class_test_2015.ipynb

**Comment by gilbertw** [comment]
Can you help us understand where you found the above links.  I would have expected the link to be, https://notebooks.azure.com/Dan-Goldsmith/libraries/intro-programming-exam-2015.

**Comment by smortaz** [comment]
Specifically, where the "run" node come from?

Nevertheless, there's an issue w how we deal w that link & should show a better error.

**Comment by gilbertw** [comment]
We now will correctly generate the link and do redirects on invalid link copies
