### ISSUE TITLE
Notebook server won't start

### ISSUE THREAD

**Issue by kczarn** [Microsoft/AzureNotebooks#257]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I attempt to start one of my notebooks stored on Azure, for example this one:
https://notebooks.azure.com/khczarnowski/libraries/anns-part-1-ex
And I get the following message:
"""
Error creating notebook...
We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: Internal error while creating notebook server (67d2148d-3d13-4854-bec3-8098e831d91f) at 12/12/2017 8:27:04 PM
"""

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/khczarnowski/libraries/anns-part-1-ex

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [X] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
CET 9:20pm

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

I can't get it --- nothing is working

**Comment by smortaz** [comment]
Hmmm... I just cloned & ran the notebook w/o problems.  What error are you seeing?

![image](https://user-images.githubusercontent.com/742484/33908784-55bc9934-df3e-11e7-8cca-933867e85f62.png)

**Comment by kczarn** [comment]
The error is as follows and it still persists.
(Note that I didn't clone the notebook and I'm trying to run it as myself.)

Error creating notebook...
We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: Internal error while creating notebook server (0754aa6f-f30d-4a5a-a067-5e179d72c705) at 12/12/2017 9:44:57 PM

**Comment by kczarn** [comment]
I cloned the library and I still get the error. I also get this error if I try to open a terminal.

**Comment by kczarn** [comment]
Signed out and signed in again - the problem persists.

**Comment by smortaz** [comment]
Interesting.  can you start in incognito mode, sign in and try clone/running again?

**Comment by kczarn** [comment]
Hope I go it well. Started new incognito chrome window, signed in, cloned the library, started notebook --- same error.

**Comment by kczarn** [comment]
@smortaz: I understand that you can access the logs? Nothing there?

**Comment by crwilcox** [comment]
@kczarn we have looked at this and it seems you are hitting a front end that has ended up in a bad state. We believe we have mitigated it. Do you want to try again?

**Comment by kczarn** [comment]
Yes, the problem is gone! Thank you guys for your help!
So I'm closing it, right?

**Comment by crwilcox** [comment]
No problem @kczarn , sorry you had an issue in the first place, but happy we could get it resolve. Thanks for letting us know!

**Comment by AC191** [comment]
I am also having the exact same problem!

The error message appears when I try to start any notebook or the Terminal. I cloned the library and still got the same error message.

I don't understand how to solve this - please help as I need the notebooks urgently!

**Comment by smortaz** [comment]
Hi.  We had a hiccup which appears to be due to load & it's been resolved.
