### ISSUE TITLE
create or opening a notebook triggers an exception (blocking)

### ISSUE THREAD

**Issue by Abdelkrim** [microsoft/AzureNotebooks#258]
#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
Creating a notebook using either python3.6, python2.7 generates errors 

> We were unable to successfully create your notebook server. Please try again or report the issue if it persists.
> 
> Error: Internal error while creating notebook server (04073845-047d-40ee-b45e-6cc4feeebb03) at 12/12/2017 10:34:23 PM
> 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

* Create a new folder
* Create a notebook
* Set a name: rc
* Select the languague: python 3.6
* hit 'New'
* the exception is triggered

#### Which language/kernel were you using when you experienced this issue?
    [x] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

12 Dec 2017 - 23:35 (brussels time)

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 7
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 

NOT RELEVANT
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

Starting the terminal triggers an excption too :-(

> We were unable to successfully create your notebook server. Please try again or report the issue if it persists.
> 
> Error: Internal error while creating notebook server (dc42a659-4f4f-4090-bd03-c99b93669c6a) at 12/12/2017 10:39:33 PM

**Comment by smortaz** [comment]
Might be related to:  https://github.com/Microsoft/AzureNotebooks/issues/257
