### ISSUE TITLE
Cannot load cntk model in azure notebook

### ISSUE THREAD

**Issue by AllanYiin** [Microsoft/AzureNotebooks#259]
I try everyway to solve but useless.
It's seens " is_file = path.exists(model)" always false, is there workround??

 if not is_buffer:
            try:
                is_file = path.exists(model)
            except:
                pass

----> 9 model=load_model('library/Models/VGG19_ImageNet_Caffe.model')
     10 print('讀取成功')
     11 

~/anaconda3_420/lib/python3.5/site-packages/cntk/internal/swig_helper.py in wrapper(*args, **kwds)
     67     @wraps(f)
     68     def wrapper(*args, **kwds):
---> 69         result = f(*args, **kwds)
     70         map_if_possible(result)
     71         return result

~/anaconda3_420/lib/python3.5/site-packages/cntk/ops/functions.py in load_model(model, device)
   1597     Alias for :func:`~cntk.ops.functions.Function.load`.
   1598     '''
-> 1599     return Function.load(model, device)
   1600 
   1601 class UserFunction(Function):

~/anaconda3_420/lib/python3.5/site-packages/cntk/internal/swig_helper.py in wrapper(*args, **kwds)
     67     @wraps(f)
     68     def wrapper(*args, **kwds):
---> 69         result = f(*args, **kwds)
     70         map_if_possible(result)
     71         return result

~/anaconda3_420/lib/python3.5/site-packages/cntk/ops/functions.py in load(model, device)
   1513             return cntk_py.Function.load(model, device)
   1514 
-> 1515         raise ValueError('Cannot load a model that is neither a file nor a byte buffer.')
   1516 
   1517     @staticmethod

ValueError: Cannot load a model that is neither a file nor a byte buffer.

**Comment by crwilcox** [comment]
Try changing `model=load_model('library/Models/VGG19_ImageNet_Caffe.model')` to be fully pathed.

`model=load_model('~/library/Models/VGG19_ImageNet_Caffe.model')`

The working directory for an ipynb should be ~/library/ so your written code would look at ~/library/library/Models/VGG19_ImageNet_Caffe.model

**Comment by AllanYiin** [comment]
I try several combination including with or without '~' ,start with library or Models or dir_path
dir_path = os.path.dirname(os.path.realpath('__file__'))

all fail.....

**Comment by crwilcox** [comment]
I found your user and a library with a models directory. The path you want is either `Models/...` or `/home/nbuser/library/Models/...`. It seems path.exists doesn't work with `~` paths.

    from os import path
    path.exists('Models/VGG19_ImageNet_Caffe.model') #true and preferred way
    path.exists('/home/nbuser/library/Models/VGG19_ImageNet_Caffe.model') # true also, but no need to do this
    path.exists('~/library/Models/VGG19_ImageNet_Caffe.model') # false as path.exists doesn't seem to translate the ~

**Comment by crwilcox** [comment]
Closing this. Feel free to open it again if you are still encountering issues.
