### ISSUE TITLE
Clone again broken

### ISSUE THREAD

**Issue by smortaz** [Microsoft/AzureNotebooks#26]
Please consider the template below to file your issue. 

### Description

 Don't sign in. Click on the F sharp sample.   There is a message that says clone again.  Bug?

 Click on it and it does not navigate. 

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by DinoV** [comment]
This appears to be working fine
