### ISSUE TITLE
An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details.

### ISSUE THREAD

**Issue by AllanYiin** [Microsoft/AzureNotebooks#263]
These days my notebooks cannot edit and save`, always get the error message and saved notebook become blank...

"An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details."

whats happened, anyway to solve it??

**Comment by smortaz** [comment]
Hi. Link to notebook?  Thx

**Comment by stephenndele** [comment]
getting the same error

**Comment by andneilmsft** [comment]
Please share a link to your notebook.

**Comment by stephenndele** [comment]
Am running the jupyter from my local machine

**Comment by stephenndele** [comment]
> Please share a link to your notebook.

http://localhost:8888/notebooks/module_1_introduction/1_3_loading_and_understanding_data.ipynb

here is how the error looks like
[E 13:09:32.695 NotebookApp] 500 GET /api/contents/module_1_introduction/1_3_loading_and_understanding_data.ipynb?type=notebook&_=1549620572233 (127.0.0.1) 221.37ms referer=http://localhost:8888/notebooks/module_1_introduction/1_3_loading_and_understanding_data.ipynb

**Comment by andneilmsft** [comment]
I wasn't able to access your notebook as you provided a local host path which is only addressable from your machine.  I was about to find the content on the internet here:

https://github.com/DeltaAnalytics/machine_learning_for_good

I uploaded this github repro into my azure notebooks project collection here:

https://machinelearningforgood-andneil.notebooks.azure.com/j/notebooks/module_1_introduction/1_3_loading_and_understanding_data.ipynb

and i was able to open the notebook successfully. 

When do you see the 500 GET error?

**Comment by andneilmsft** [comment]
..if you are running on a local jupyter then you are not using Microsoft Azure Notebooks. Please follow u with https://jupyter.org
