### ISSUE TITLE
I'm unable to open my azure notebook

### ISSUE THREAD

**Issue by shubhambangar** [Microsoft/AzureNotebooks#265]
I am unable to open my azure notebooks. It either doesn't show the page or sends a message that _it_ is taking too long to load the notebook's server, i.e. Python 3.6. 
Please provide a solution as soon as possible.

**Comment by smortaz** [comment]
Link to your library?

**Comment by shubhambangar** [comment]
https://notebooks.azure.com/ShubhamBangar/libraries/Dev274x

**Comment by smortaz** [comment]
I just cloned & successfully opened your notebook:

![image](https://user-images.githubusercontent.com/742484/34340802-8c27266e-e93f-11e7-939d-e5ef543e82df.png)

**Comment by smortaz** [comment]
I'm not 100% sure, but it could be that you've ended up on a bad VM.  Try using another browser in incognito mode and re-sign in to see if you end up on a different VM.

**Comment by shubhambangar** [comment]
got the issue solved after cloning the library and opening the notebook from the new one.

**Comment by shubhambangar** [comment]
Thanks for looking over the issue

**Comment by DinoV** [comment]
We deployed a fix last Wednesday. After being in production a week I'm willing to declare that everything appears to be functioning normal again. Sorry for the issues, please let us know if you see anything else!

**Comment by smortaz** [comment]
Stopped means your container was not used for a while and was shut down.
Can you log out and in and click on a notebook?  That should get you a
fresh container. Either way this looks like a bug.

**Comment by polpokpol** [comment]
similar experience

**Comment by Louis2000814** [comment]
re-sign in worked，thank you guys :)

**Comment by Arunkumar2611** [comment]
I am unable to open my azure notebook it shows me an error
Opening notebook failed. Notebook id: 7a371f4c3f254c61a30a8ad31b42191e.
what does it means...?

**Comment by AreteJJ** [comment]
When it comes to Azure ML Studio, Microsoft disabled notebook feature. 

https://docs.microsoft.com/en-us/answers/questions/39391/cannot-open-dataset-in-notebook.html
