### ISSUE TITLE
Always receive timeout when opening a library

### ISSUE THREAD

**Issue by JanosVrbata** [microsoft/AzureNotebooks#266]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by gilbertw** [comment]
The site experienced some issues last week which resulted in failures to connect for a small number of users.  We deployed a fix.  If you are still experiencing issues please let us know.  Details such as your browser and the library you were opening would also be helpful.
