### ISSUE TITLE
always "Page not found"

### ISSUE THREAD

**Issue by AllanYiin** [Microsoft/AzureNotebooks#268]
These I so frustrated , because my azure notebooks always show "Page not found" after I add any new notebook.

error link:
https://notebooks.azure.com/n/cj1MMAa7vNg/notebooks/LingXi.ipynb

it seen there is a url  is not a secure connection (edge always get error, chrome just pass by):
https://notebooks.azure.com/run/allanyiin/mylingxi?dest=/notebooks/LingXi.ipynb

**Comment by DinoV** [comment]
Can you click on your library on https://notebooks.azure.com/allanyiin/libraries and click Shutdown and then try again?

I think this is a dup of #267, we're currently investigating but shutting down the library and trying again should get you back into a good container for the time being.  Sorry for the inconvenience!

**Comment by AllanYiin** [comment]
Thanks so much, it works!!

**Comment by DinoV** [comment]
Great!  I'll update #267 as we work through the underlying issue.
