### ISSUE TITLE
Re-opening notebook nightmare

### ISSUE THREAD

**Issue by namso-greg** [Microsoft/AzureNotebooks#269]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
Opening the notebook I studied last is nearly impossible. Just because of this, I'm nearly failing my EDX Python course. After spending some time and get crazy, I'm getting able to open a notebook only after cloning the library... NOTE: I just realized that, all other right click functions are functioning ok (preview, edit, download) only "run" have this issue...

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Study Python for a few minutes, than leave the page open, after the system signs you out for inactivity, refresh the page, sign in and click on the notebook file you were studying...

#### Which language/kernel were you using when you experienced this issue? IT ONLY WRITES PYTHON 3 on the UP-RIGHT side of the page.
    [] Python 2.7 
    [x] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
I'm not sure +2 or +3 GMT but morning, afternoon doesn't matter...

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported) (You should alarm about this with capital..)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
Irrelevant BUT, there is /run/ before USER-NAME after writing this....
I've installed Firefox, instead of a blank page, the address line is existing which is
https://notebooks.azure.com/run/namso-greg/namso-greg-1?dest=%2Fnotebooks%2FNoteBook1.ipynb

**Comment by namso-greg** [comment]
I'm 50 years old, spending time for "waiting for response from notebooks.azure.com" is not working for me...

**Comment by smortaz** [comment]
Hi, sorry about that.  We are chasing down a bug in Docker/Windows and are
currently testing a hotfix.  Please see this thread:

https://github.com/Microsoft/AzureNotebooks/issues/267

As a workaround, click the "Shutdown" button in your Library view and
re-Run your library to see if you end up on a fixed VM.

thx.

**Comment by DinoV** [comment]
We deployed a fix last Wednesday. After being in production a week I'm willing to declare that everything appears to be functioning normal again. Sorry for the issues, please let us know if you see anything else!
