### ISSUE TITLE
RShiny in Azure Notebooks

### ISSUE THREAD

**Issue by b00nw33** [microsoft/AzureNotebooks#270]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [.] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I would like to use RShiny with my Azure Notebooks. May I know if it is possible?

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [.] Python 3.6 
    [.] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [.] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [.] Other (Please Specify): Chrmoe OS

**Comment by smortaz** [comment]
Sorry it’s not currently supported :(.  Can you describe your scenario/use
case?  Thx
