### ISSUE TITLE
How to access Sample AzureNotebook

### ISSUE THREAD

**Issue by jfendrich** [microsoft/AzureNotebooks#271]
Please describe your issue as completely as possible.

#### Which site did you access us from?
Accessed repository from : 

> https://notebooks.azure.com/undefined/libraries/undefined

 with "let us know about the broken link" link.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Was at the 
> https://blogs.msdn.microsoft.com/visualstudio/2016/11/18/data-science-workloads-in-visual-studio-2017-rc/
down where AzureNotebooks are recommended "The best to learn about Azure Notebooks is to try one of the samples:
•The actual notebooks used in the discovery of Gravitational Waves by the LIGO team"
"Gravitational Waves" is a link that brought up the error.

Thanks.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal
    [X] None

#### What time (please include time zone) did this occur?
11am UTC-5

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [X] Internet Explorer / Edge (Please note this is not supported) 
might be the issue?
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

The Gravitation Waves example link is : https://notebooks.azure.com/library/LIGOOpenScienceCenter

**Comment by gilbertw** [comment]
There are a number of different sample notebooks towards the bottom of the front-page on notebooks.azure.com.  Additionally you can see sample notebooks in this [library](https://notebooks.azure.com/Microsoft/libraries/samples)

**Comment by smortaz** [comment]
Rick you may have replied to wrong thread?

**Comment by crwilcox** [comment]
@smortaz, I think @gilbertw  responded to the right thread. The customer couldn't access the link they were going through and asked how to access samples. Rick answered that question. 

The link trying to be used at https://blogs.msdn.microsoft.com/visualstudio/2016/11/18/data-science-workloads-in-visual-studio-2017-rc/ is old (before we had users associated with libraries) and is formatted https://notebooks.azure.com/library/LIGOOpenScienceCenter

For that matter, each link in there is the old style. At one point we had code that should have translated those forward. It would appear that has degraded over time. As we (@smortaz wrote it) own that post we should likely update the links to match our current ways.

**Comment by smortaz** [comment]
@crwilcox  - ah ok.  sorry read too fast on cellphone!
