### ISSUE TITLE
Cannot open ipynb

### ISSUE THREAD

**Issue by erhuttk** [Microsoft/AzureNotebooks#272]
Cannot open ipynb file but CSV is ok to view.

The message appear below and nothing seems going on:

We're starting your notebook server now, this should only take a second...

**Comment by smortaz** [comment]
Please see:

https://notebooks.azure.com/status

**Comment by gilbertw** [comment]
We apologize for the startup issues you encountered.  Our team is constantly working to improve and enhance the site.  Unfortunately in our attempts to provide a best a notebooks security model some users faced delayed or even failing notebook startup.  Fixes to address the issue have been deployed.

**Comment by DinoV** [comment]
We deployed a fix last Wednesday.  After being in production a week I'm willing to declare that everything appears to be functioning normal again.  Sorry for the issues, please let us know if you see anything else!
