### ISSUE TITLE
I Have Been Unable to Open a Notebook for 3 Hours Now

### ISSUE THREAD

**Issue by kslader8** [Microsoft/AzureNotebooks#275]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering

I have been unable to launch a notebook for the past 3 hours... It results in the below error when I try to open a notebook.

Error creating notebook...
We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 

#### What time (please include time zone) did this occur?
~1pm EST (New York)
#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/kslader8/libraries/AdvancedAnalyticswithSpark/

**Comment by smortaz** [comment]
Sorry about the problems.   Please see:  https://notebooks.azure.com/status

**Comment by kslader8** [comment]
I saw the issue on the status page. However, in my case there isn't anything to shutdown... I just can't launch an actual notebook server anymore today. It was working fine for me yesterday too.

**Comment by smortaz** [comment]
OK.  did you try the 1) go incognito, 2) clone 3) Run approach?  did that
work?

**Comment by kslader8** [comment]
I did not try with clone. I did try in incognito though. However, it magically just started working again for me. :)

**Comment by smortaz** [comment]
Sorry about that.  It's a tough bug and we're working hard to root cause it.
