### ISSUE TITLE
can't open library page in EdgeSCRIPT5009: SCRIPT5009: 'angular' is not defined

### ISSUE THREAD

**Issue by ghost** [microsoft/AzureNotebooks#276]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Which Web Browser(s) did you see the error in?
    [] Internet Explorer / Edge (Please note this is not supported)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

Can't open Library page in Edge. The error is ' SCRIPT5009: SCRIPT5009: 'angular' is not defined'.
Please fix it.

**Comment by smortaz** [comment]
Hi, please note the line:

[] Internet Explorer / Edge (Please note **this is not supported**)

we recommend chrome, FF, opera.

**Comment by crwilcox** [comment]
@WenqiangXie, what is the exact link of the page you are visiting? @smortaz is correct that we do not support IE or Edge. Though, this error is still odd and I want to be sure that something more interesting isn't going on. Also, are you able to try accessing that page from another browser? If you could and provide the result of the attempt that would be helpful in us root causing the issue.

Thanks!
Chris

**Comment by crwilcox** [comment]
@WenqiangXie, do you have any further information?

Thanks!
Chris
