### ISSUE TITLE
Will it be available as a part of Azure portal?

### ISSUE THREAD

**Issue by zakimaksyutov** [microsoft/AzureNotebooks#277]
Hello,

I really would like to use Azure Notebooks but it would be great to have it in Azure portal with all other services. Are there plans to deliver this?

Thank you!
Zaki

**Comment by DinoV** [comment]
Can you describe a little more what you're looking for?  Do you just want to launch notebooks from the portal?  Or do you want to be able to create more customized options (e.g. configure VM size, etc...)?  Or are you looking for integration between Azure services and notebooks - so something like the cloud shell but with a notebook UI.  Or something else entirely?

Obviously we've thought about it a little bit, but we don't have any immediate plans to do so.  So having some concrete feedback on how people would like to see it integrated would be helpful.

**Comment by zakimaksyutov** [comment]
I was referring to integrating notebook UI inside portal.azure.com.

Scenario: I'd like to use notebooks for creating troubleshooting guides for my services and share them with my team.

Reasons for integration:
1. Familiar environment, people don't need to learn another portal. People can easily find TSGs, pin them to dashboard, etc.
2. Single sign on (tried to login into notebooks portal and don't see my name there, not sure what it means)
3. RBAC
