### ISSUE TITLE
python3_tk

### ISSUE THREAD

**Issue by Seenivasanseeni** [Microsoft/AzureNotebooks#279]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
In order to use matplotlib i need to install python3_tk package in a system. How can i do that..?
#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
    [] Terminal

#### What time (please include time zone) did this occur?
Jone-IST
Date and Time: 10/1/2018 7:40 am
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    
#### Which Operating System are you using? Please specify version as well if possible:
    [] Ubuntu

**Comment by smortaz** [comment]
Matplotlib  is already installed for all Python versions via anaconda. All
you have to do is import it. Or maybe I am misunderstanding your question…

**Comment by Seenivasanseeni** [comment]
But When i use import matplotlib.pyplot as plt.It says import error

**Comment by smortaz** [comment]
can you send a link to your library?

here's mine w an example:

https://notebooks.azure.com/smortaz/libraries/6pEgqAWKcP4/html/simple.ipynb

**Comment by Seenivasanseeni** [comment]
Okay. You are correct. the error happened while executing python3 script in terminal. I got it now. those libraries are installed only on conda.
