### ISSUE TITLE
Add C# support to Azure Notebooks

### ISSUE THREAD

**Issue by crwilcox** [microsoft/AzureNotebooks#28]
Add a Kernel to support C# in Azure Notebooks

The C# kernel was started here: https://github.com/zabirauf/icsharp but it doesn't appear to be under active development as far as I can tell.

**Comment by rogersachan** [comment]
@crwilcox Ever heard of Xamarin Workbooks?

**Comment by asw** [comment]
I've used Azure Notebooks for python, and recently F#, and I think a C# kernel would be exceptionally useful. It would hit a spot where I currently use a lot of LINQPad and cscript.

**Comment by danvanderboom** [comment]
Goes without saying. +1

**Comment by MikeTheGreat** [comment]
I'd love to see this too.  It would be wonderful for teaching C#. +1

**Comment by denfromufa** [comment]
shameless plug - C# magic cells for IPython kernel:

https://github.com/pythonnet/clrmagic

This works in Azure Notebooks already, but only with the Mono runtime.

**Comment by denfromufa** [comment]
@crwilcox if you need any help with icsharp, let me know. it used to work on my machine and I even fixed one issue :)

**Comment by whatevergeek** [comment]
any update on this?
would be nice especially in the advent of ML.NET

**Comment by kkampf** [comment]
Thanks for the feedback on this. We are exploring it for the future, but no dates to share just yet as we undergo some service updates

**Comment by TravisEz13** [comment]
there is now https://github.com/dotnet/interactive, which would also solve: https://github.com/microsoft/AzureNotebooks/issues/655

**Comment by whatevergeek** [comment]
https://github.com/dotnet/interactive looks interesting

hope they add these to azurenotebooks soon :-)
