### ISSUE TITLE
html5lib not found in notebooks

### ISSUE THREAD

**Issue by kentang2017** [microsoft/AzureNotebooks#280]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [v] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
ImportError: html5lib not found, please install it

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [v] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [v] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [v] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi.  Did you try installing the package yourself? You can install via pip
or conda.  Please check out the help tab on the top row on package
installation.
