### ISSUE TITLE
unable to execute python codes in azure notebooks. 

### ISSUE THREAD

**Issue by DavidMike** [Microsoft/AzureNotebooks#282]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [

#### Describe the issue you are encountering
I have been learning python using the azure notebooks as my environment. For the last 4 days, I have been unable to run my codes. Each time I run it with 'ctrl + enter' or use cells to run it, absolutely nothing happens.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Simply try to execute the code will reproduce it. https://samples-anon-cotffq.notebooks.azure.com/nb/notebooks/assignment%201.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur? 
all day thursday, friday, saturday, today(sunday)

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 7
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
*(https://notebooks.azure.com/help/there is no jupyter-notebooks/troubleshooting/jupyter-debug-log)

**Comment by smortaz** [comment]
Howdy.  I just cloned your library & tried "assignment 1" and shift-enter'd
through and it worked fine.

what are you seeing?

note that some cells have "input" fields and that's known to be flake in
Jupyter in general (independent of Azure - misbehaves locally as well).


[image: Inline image 1]

**Comment by DavidMike** [comment]
Ok. Something must have changed. As you can see in assignment1, I have had lots of successes in the past that worked. what result are you getting? THe last cell is what I am trying to execute and I just did it now at 2:13pm EST and I can say for sure, it is not executing.

**Comment by DavidMike** [comment]
So, I tried to execute the cells again, but especially the very last cell. I tried to execute the code first by 'shift + enter' and again by 'ctrl + enter'. In both of these, I see no result . So, it doesn't look like my code is being executed. I have also commented off all the other codes except the very last one that I am interested in and it was not execute.

Thanks!

**Comment by smortaz** [comment]
it looks like you're trying to define a function... so you need to call it
for it to execute.  if you comment out your "def adding_report()", then the
cell runs.  if you put the code in a function, you need to call it.  here
it's commented out:

[image: Inline image 1]

**Comment by DavidMike** [comment]
@smortaz, you pinpointed something that made sense. I didn't realize that azure and its notebooks is this flaky. I just commented out the function and it executed for the first time. I am going to work on this some more and call the function to make sure that this doesn't hangup again. I was thinking that it would always execute and give errors. I didn't know that it would hangup and not do anything at all.

Thank you , sir!

**Comment by smortaz** [comment]
Hi David - perhaps there's a misunderstanding... the code in that cell is
defining a function.  until you call it, nothing in there will execute.
it's completely unrelated on jupyter, or azure notebooks.  if you download
that code and just run it on your local python environment, the same thing
will happen.   the flakyness i mentioned has to do with Jupyter interaction
with  "input()", again, unrelated to *Azure* notebooks.


in [2], a function is being defined, like your adding_report.  when i hit
shift-enter, the function f is now 'defined' (ie, available for calling),
but /// no input will occur ///

in [3], it's straight line code, so it gets executed & output is returned

in [3], now i actually *call* the function f, so it gets executed and
output is returned.

i hope that's clear!

[image: Inline image 1]

**Comment by DavidMike** [comment]
You are great. Please accept my appreciation for your the help you rendered. I am now having a different issue. import os
string_container = ""
add_container = 0



def adding_report(integerToadd):

        if integerToadd.isdigit():
            string_container += integerToadd + "\n"
            add_container += int(integerToadd)
        else:
            if integerToadd == 'A':
                response = Add_container
            else:
                if integerToadd== 'T':
                    response = string_container
                else:
        
                    if integerToadd=="q":
                        os._exit(0)
                    else:
                        
                        response = "invalid input"
        return response
    
while True:    
          number = input("input a number or digit")
          workdone = adding_report(number)

    
          print(workdone)

can you help me with the following error ? : " UnboundLocalError: local variable 'string_container' referenced before assignment". That's the error I am getting.

Please help. 

Thanks.

**Comment by crwilcox** [comment]
@DavidMike, you are attempting to use a global variable in a function. If you want to do this you would have to write `global string_container` before attempting to modify `string_container`

Here is a brief write-up on the error you found. https://docs.python.org/3/faq/programming.html#why-am-i-getting-an-unboundlocalerror-when-the-variable-has-a-value
