### ISSUE TITLE
Notebooks do not obey Python scoping rules

### ISSUE THREAD

**Issue by fonnesbeck** [Microsoft/AzureNotebooks#283]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

When running Python code in a notebook, some variables defined globally cannot be accessed from local scope

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

For example, I have a variable called `FOI_mat`, which is a numpy array:

![](https://d.pr/i/t1BxxM+)

which further down in the notebook is passed as an argument to a numpy function:

![](https://d.pr/i/YUU0zP+)

Yet this line fails, claiming that the variable is referenced before assignment, which is clearly untrue:

![](https://d.pr/i/lad6tG+)

Python scoping rules dictate that when a variable is unavailable locally, the call looks to the enclosing scope. This is not occurring here.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
On mobile… What happens when you click the very first cell in the notebook
and do a run all? In notebooks the order in which you execute the cells
matters.

**Comment by fonnesbeck** [comment]
The cells have been executed in order. Moreover, the notebook runs fine locally.

**Comment by smortaz** [comment]
can you post a link to your notebook that i can look at?  thx.

**Comment by fonnesbeck** [comment]
It's not a public project but [here is the notebook](https://d.pr/f/IUAHty)

**Comment by smortaz** [comment]
needs a data file it seems.  pls shoot to smortaz@microsoft.com.  thx.

**Comment by fonnesbeck** [comment]
Sending it now, thanks.

**Comment by fonnesbeck** [comment]
User error. Sorry for the time wasted!

**Comment by smortaz** [comment]
no worries!

On Fri, Jan 19, 2018 at 10:10 AM, Chris Fonnesbeck <notifications@github.com
