### ISSUE TITLE
Delete folder in a library:azure notebooks

### ISSUE THREAD

**Issue by avinashsai** [microsoft/AzureNotebooks#284]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by avinashsai** [comment]
I am using azure notebooks through https://notebooks.azure.com.

I have a folder consisting of 1000 text files in a library.

I need to delete that folder at once. But when i try to delete the folder, it was unsuccessful.

Does azure allows deleting folder at once or do we have to delete every file to delete folder ??

**Comment by smortaz** [comment]
Hi Avinash, to remove a non empty directory:

1. go to your Library page,
2. click Terminal
3. cd library
4. rm -rf <directoryname>

alternatively, while in your *notebook*:

1. click the Jupyter logo on top left to see the Jupyter file view
2. click the directoryname
3. select all, delete
4. go up one level & delete directory
