### ISSUE TITLE
Unable to install.packages('tidyverse')

### ISSUE THREAD

**Issue by WadeTsai** [microsoft/AzureNotebooks#287]
#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Unable to install.packages('tidyverse')
Because installation of package 'lubridate' had non-zero exit status.
please see below info:

I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c RcppExports.cpp -o RcppExports.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'RcppExports.o' failed
make: [RcppExports.o] Error 127 (ignored)
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c datetime.c -o datetime.o
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c period.c -o period.o
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c tparse.c -o tparse.o
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c update.cpp -o update.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:141: recipe for target 'update.o' failed
make: [update.o] Error 127 (ignored)
gcc -std=gnu99 -I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"   -fpic  -DU_STATIC_IMPLEMENTATION -O2 -g  -c utils.c -o utils.o
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_fixed.cc -o cctz/src/time_zone_fixed.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_fixed.o' failed
make: [cctz/src/time_zone_fixed.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_if.cc -o cctz/src/time_zone_if.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_if.o' failed
make: [cctz/src/time_zone_if.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_impl.cc -o cctz/src/time_zone_impl.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_impl.o' failed
make: [cctz/src/time_zone_impl.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_info.cc -o cctz/src/time_zone_info.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_info.o' failed
make: [cctz/src/time_zone_info.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_libc.cc -o cctz/src/time_zone_libc.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_libc.o' failed
make: [cctz/src/time_zone_libc.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_lookup.cc -o cctz/src/time_zone_lookup.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_lookup.o' failed
make: [cctz/src/time_zone_lookup.o] Error 127 (ignored)
I/usr/lib64/microsoft-r/3.3/lib64/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -DU_STATIC_IMPLEMENTATION -I"/home/nbuser/R/Rcpp/include"      -c cctz/src/time_zone_posix.cc -o cctz/src/time_zone_posix.o
sh: I/usr/lib64/microsoft-r/3.3/lib64/R/include: No such file or directory
/usr/lib64/microsoft-r/3.3/lib64/R/etc/Makeconf:139: recipe for target 'cctz/src/time_zone_posix.o' failed
make: [cctz/src/time_zone_posix.o] Error 127 (ignored)
ar rcs libcctz.a ./cctz/src/time_zone_fixed.o ./cctz/src/time_zone_if.o ./cctz/src/time_zone_impl.o ./cctz/src/time_zone_info.o ./cctz/src/time_
zone_libc.o ./cctz/src/time_zone_lookup.o ./cctz/src/time_zone_posix.o
ar: ./cctz/src/time_zone_fixed.o: No such file or directory
Makevars:18: recipe for target 'libcctz.a' failed
make: *** [libcctz.a] Error 1
ERROR: compilation failed for package 'lubridate'

#### What steps can we take to reproduce this issue? 
1. New a R notebook
2. install.packages('tidyverse')

#### Which language/kernel were you using when you experienced this issue?
    [] R 

#### What time (please include time zone) did this occur?
2018/1/23 17:50 (Taipei Time Zone)

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by smortaz** [comment]
Thanks Wade for reporting.  We'll investigate today & update here.

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update that could potentially resolve this problem.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!
