### ISSUE TITLE
Install a kernel (ITypeScript)

### ISSUE THREAD

**Issue by BartNetJS** [microsoft/AzureNotebooks#289]
Is it possible to install a custom Kernel?

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
I tried to install a kernel, but got stuck on the nbuser password

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

I followed the instructions [here](https://github.com/nearbydelta/itypescript)

**Comment by smortaz** [comment]
Hi Bart.  Not at this time unfortunately :(.
