### ISSUE TITLE
500 response when running a notebook with a unicode file name

### ISSUE THREAD

**Issue by ogwh** [Microsoft/AzureNotebooks#290]
Notebooks with unicode file names trigger a 500 error on https://notebooks.azure.com when an attempt is made to run them.

To reproduce create a notebook named "Bézier Curves.ipynb" and attempt to run it. Note the accent in Bézier (not Bezier).

**Comment by crwilcox** [comment]
@ogwh , if you look at `~/.nb.log` does it have a more specific error? I can start looking into the name but knowing if there is more specific information there could be helpful.

**Comment by ogwh** [comment]
@crwilcox where do I find that file? Does Azure Notebooks provision a VM per-account that I can ssh into? I'm not seeing anything in the UI.

**Comment by crwilcox** [comment]
in the library UI (url will be in the form https://notebooks.azure.com/chris/libraries/somelibrary), there is a terminal button you can use to access a shell.

**Comment by gilbertw** [comment]
Fix is deployed, thanks again for using Azure Notebooks
