### ISSUE TITLE
Launch in Azure Notebooks button

### ISSUE THREAD

**Issue by versae** [Microsoft/AzureNotebooks#292]
It would be really nice and maybe relatively straightforward to be able to add a button, such as <img src="https://camo.githubusercontent.com/70c5b4d050d4019f4f20b170d75679a9316ac5e5/687474703a2f2f6d7962696e6465722e6f72672f62616467652e737667">, to launch a GitHub or other public git repository containing notebooks in Azure Notebooks. Sane defaults for syncing would need to be in place (library name, slug, etc).

**Comment by crwilcox** [comment]
@versae , this does exist. Here is a PR to a repo that adds it. if you need help, I can send a PR for you.
https://github.com/CamDavidsonPilon/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/pull/355/commits/ddbc80a2d334ebfb219c1b0e200b21e1e28ca7dc

-Chris

**Comment by versae** [comment]
Awesome! Thanks.
