### ISSUE TITLE
RISE - Slide Type missing

### ISSUE THREAD

**Issue by neshdev** [Microsoft/AzureNotebooks#293]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Cells do not have a slide type dropdown.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/Nesh/libraries/this-is-a-test-2

**Comment by crwilcox** [comment]
By default that dropdown isn't visible. You need to enable that bar on the cells.
![image](https://user-images.githubusercontent.com/638797/35531159-10b4f340-04eb-11e8-9d87-807363dee32e.png)

**Comment by neshdev** [comment]
Thanks! That worked.
