### ISSUE TITLE
 C++11 standard requested but CXX11 is not defined

### ISSUE THREAD

**Issue by pafik13** [microsoft/AzureNotebooks#295]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When I tried to install package 'Forecast' I had exception with 'CXX11' parameter.

Output:
```
* package 'RcppArmadillo' successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... almost
configure: WARNING: Compiler self-identifies as being compliant with GNUC extensions but is not g++.
checking LAPACK_LIBS... fallback LAPACK from R 3.3.0 or later used
checking for macOS... not found as on Linux
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
Error in .shlib_internal(args) :
  C++11 standard requested but CXX11 is not defined
* removing '/home/nbuser/R/RcppArmadillo'
ERROR: dependency 'RcppArmadillo' is not available for package 'forecast'
* removing '/home/nbuser/R/forecast'
```

I tried to change '{R_HOME}/etc/Makeconf' file like [here](https://github.com/Microsoft/microsoft-r-open/issues/26) but couldn't (Access Denied).

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
install.packages('forecast')

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [X] R 
    [] F#
    [X] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/pashqa88/libraries/petolau/html/RegressionTrees.ipynb

**Comment by smortaz** [comment]
Hi, please check out the notebook in this lib for a potential workaround.

https://notebooks.azure.com/smortaz/libraries/rem-userbug

**Comment by pafik13** [comment]
@smortaz , thank you! It helped me.

**Comment by fulky** [comment]
@smortaz.  Thank you for your solution!  It worked like a charm.   I will say it was a little hard to decipher and figure out being new to Azure Notebooks.    Ideally it will be fixed in the service.   I could not load the package "mosaic" without it.  Thanks again!~

**Comment by fulky** [comment]
Can we get this fixed permanently by updating the R version?  The patch works but everytime I restart the service container we're back to the 3.4.1
