### ISSUE TITLE
Install software on server

### ISSUE THREAD

**Issue by goodalljl** [microsoft/AzureNotebooks#297]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
This is more of a feature request / question than an issue. We'd like to use a Notebook to interact with a scientific model we use. The model would need to be compiled and run on the server for this to work. Is it possible to install 3rd party software like scientific models so that users can interact with them via Jup? The model is difficult to compile (like many scientific models) but we can run it in a Docker container.  This would be a very helpful set up for teaching and research if it is possible to do. 

-Jon Goodall, UVA 
https://engineering.virginia.edu/faculty/jonathan-l-goodall

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
We have a start to a Python library for interacting with our specific model of interest here: https://github.com/DavidChoi76/pysumma_alpha

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [x] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
If you make it into a pip or conda package, then it’s installable easily.
See help for package installation.

**Comment by goodalljl** [comment]
We will look into making a conda package. The code has a lot of dependencies, so it may not be possible. Are there alternatives if that path doesn't work?

**Comment by smortaz** [comment]
Is it more complex than matplotlib, or Pandas, or SciPy?  those are pretty
complex with C++, Fortran, etc. code.  Check out creating python "wheels":
https://pythonwheels.com/

We are looking into providing user custom images, but nothing in the very
immediate future.

**Comment by goodalljl** [comment]
It is probably no more complex than those packages -- just will require some effort to get in the right form. We'll see! I'll also keep an eye out for the custom images in the future too. Appreciate your help and quick replies. We are making use of the Azure Notebook in teaching and really appreciate the service!

**Comment by smortaz** [comment]
Awesome. Glad it’s working for you!
