### ISSUE TITLE
Sorting Libraries by status doesn't work

### ISSUE THREAD

**Issue by nagamalli9999** [microsoft/AzureNotebooks#299]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Sorting Libraries by status doesn't work
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Click on Status in Libraries view

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Bug verified.  this is a regression as I recall it was working fine.
Thanks for the heads up.
