### ISSUE TITLE
How to reference MathNet and F# Data in  F# Notebook

### ISSUE THREAD

**Issue by naoyaikedabc** [Microsoft/AzureNotebooks#30]
Can I reference MathNet and F# Data in F# Notebook.
I tried, But I can't find these libraries.

**Comment by sylvanc** [comment]
Hi @naoyaikedabc ,

You can use any library available via nuget by using Paket. For this specific example, you can do:

```fsharp
#load "Paket.fsx"

Paket.Package
    [   "MathNet.Numerics.FSharp"
        "FSharp.Data"
    ]
```

And then in a new cell:

```fsharp
#r "packages/MathNet.Numerics.FSharp/lib/net40/MathNet.Numerics.FSharp.dll"
#r "packages/FSharp.Data/lib/net40/FSharp.Data.dll"
```

We will soon be adding an API to make the second part much simpler!
