### ISSUE TITLE
what is the sudo password in azure notebooks ?

### ISSUE THREAD

**Issue by fastcampuskang** [Microsoft/AzureNotebooks#303]
Hello, I'm Joseph.

I want use the command like "sudo pip install virtualenv" on the terminal in azure notebooks.

But, When I type the commnad "sudo pip install virtualenv" on the terminal, the terminal asks me the password for the sudo.

I haven't set any password for the sudo.

what's the password ? or can I reset the sudo password ?

**Comment by smortaz** [comment]
Hi.  There's not sudo support on Azure notebooks.  you get drop into the
Terminal and issues normal commands.   You can also install pkgs via !pip,
!conda etc.

**Comment by smortaz** [comment]
We hope to enable sudo support in the future.  Closing bug, feel free to reopen to file a feature request. thx!

**Comment by somnathrakshit** [comment]
Any progress on this?

**Comment by andneilmsft** [comment]
sudo support remains on our backlog but is not scheduled.
