### ISSUE TITLE
install package `wget` in Python 3.6

### ISSUE THREAD

**Issue by swnesbitt** [microsoft/AzureNotebooks#306]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Could the `wget` module be installed in Python 3.6 as it is in Python 2 in Azure Notebooks?  Thanks!

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
`import wget`

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
1:46 pm CST, 12 Feb 2018

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
it's on the machine & can be pip installed.  or do you mean pre-baked in?

![image](https://user-images.githubusercontent.com/742484/36124374-a13163bc-1004-11e8-96e5-51f7e6a86ffb.png)
