### ISSUE TITLE
Very slow file handling 

### ISSUE THREAD

**Issue by markolonius** [microsoft/AzureNotebooks#308]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am attempting to extract a .tar.gz file from [http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz](url) and process the files into a pandas data frame.  However extraction took over 10 hours (I used the terminal) and processing the files into a data frame is estimating to take 5 hours.  

On my MacBook Pro from year 2010 with 2.4 GHz Intel Core 2 Duo, 8 GB 1067 MHz DDR3 and SSD extraction of the files takes less than 30 seconds and processing the files into a pandas data frame takes 5 minutes and 29 seconds.

Am I missing some optimization?

note: I am following the book Python Machine Learning by Sebastian Raschka which has a GitHub repository [https://github.com/rasbt/python-machine-learning-book-2nd-edition](url) for reference.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

[https://notebooks.azure.com/markolonius/libraries/pythonMLbook/html/code/ch08/ch08.ipynb](url)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? 

[https://notebooks.azure.com/markolonius/libraries/pythonMLbook/html/code/ch08/ch08.ipynb](url)
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

No log found.

**Comment by smortaz** [comment]
hi mark - there are actually two file systems.  one is the local temp file system (attached SSD) and it's fast.  but it's not permanent.  the other is whatever you put in ~/library/.  that's persisted but goes thru a slower http interface.  perhaps you could get the zip files, unzip in the fast FS, then put what you actually need persisted in ~/library?

**Comment by smortaz** [comment]
mark - you've also hit some limits on the service due to the library having a large # of files.  we've filed bugs internally and will update this thread when fixed.  sorry :(.
