### ISSUE TITLE
Charts in R don't work when notebook is not running

### ISSUE THREAD

**Issue by einarmagnus** [microsoft/AzureNotebooks#309]
#### Which site did you access us from?
    [✔︎] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

When a notebook contains charts they are displayed as broken images in the public preview of the notebook and also when trying to print it. Additionally it is impossible to export it as pdf, I only get "The page cannot be displayed because an internal server error has occurred.".

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Look at this, or try to print it: https://notebooks.azure.com/einarmagnus/libraries/stat-r/html/Print%20error.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [✔︎] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [✔︎] Chrome
    [✔︎] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [✔︎] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/einarmagnus/libraries/stat-r/html/Print%20error.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
This happens when exporting to pdf:
```
 13:35:37.986 NotebookApp] 404 GET /nb/nbconvert/html/custom.css (10.36.15.1): No such file or directory:custom.css
[W 13:35:37.987 NotebookApp] 404 GET /nb/nbconvert/html/custom.css (10.36.15.1) 24.98ms referer=None
/bin/sh: inkscape: command not found
[E 13:36:06.272 NotebookApp] nbconvert failed: Inkscape svg to pdf conversion failed
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/notebook/nbconvert/handlers.py", line 122, in get
        resources=resource_dict
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/pdf.py", line 162, in from_notebook_node
        nb, resources=resources, **kw
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/latex.py", line 82, in from_notebook_node
        return super(LatexExporter, self).from_notebook_node(nb, resources, **kw)
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/templateexporter.py", line 280, in from_notebook_node
        nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/convertfigures.py", line 46, in preprocess_cell
        self.from_format, output.data[self.from_format])
      File "/usr/local/lib/python2.7/dist-packages/nbconvert/preprocessors/svg2pdf.py", line 102, in convert_figure
        raise TypeError("Inkscape svg to pdf conversion failed")
    TypeError: Inkscape svg to pdf conversion failed
[W 13:36:06.273 NotebookApp] 500 GET /nb/nbconvert/pdf/Print%20error.ipynb?download=true (10.36.15.1): nbconvert failed: Inkscape svg to pdf conversion failed
[E 13:36:06.275 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.7,sv;q=0.3",
      "Accept-Encoding": "gzip, deflate, br",
      "Was-Default-Hostname": "ans-prod-ussouth.azurewebsites.net",
      "X-Forwarded-For": "94.191.143.100:6991",
      "X-Arr-Log-Id": "1aff59d0-90a2-4d31-96a3-2ef27d609b79",
      "X-Notebook-Container": "0015_ansprod4173nb",
      "Host": "52.173.190.189:6999",
      "Upgrade-Insecure-Requests": "1",
      "X-Waws-Unencoded-Url": "/nb/nbconvert/pdf/Print%20error.ipynb?download=true",
      "X-Arr-Ssl": "2048|128|C=US, S=Washington, L=Redmond, O=Microsoft Corporation, OU=Microsoft IT, CN=Microsoft IT TLS CA 5|CN=*.notebooks.azure.com",
      "X-Forwarded-Proto": "https",
      "Cookie": "ARRAffinity=43f5b0957f8f1c102716ce1f95718e23236444ef5f03b38d8cf73f922f6d1afe; _ga=GA1.2.2047124429.1518684128; _gid=GA1.2.257440660.1518684128; __UserAccess=1p5d3f24DEqcC0mn8ASRq9wM9zP5V1HPB79CxySRZlozaLHyLL5ueABrpGLFS23jTc2njUKaFEosQTVt0s5w5g==e27MLgD3yS9G38EsvclHbaMIYDNlTo9C65/ia7cJyAUQRIdEe18dpkJVFXDvgoVB17qqXllFPgLbA0FjmPQr2Lo3HRorQ2dEZsipFNmUiFvNBs0INJochIVJ2ZRUiH1axKVb2mVfrSmA4dlFS7LsYUJGtv6X3mEbOeV6Q2Oizl9XrJi38r3h2Ikgot2L4OqIKSzka+Y4uJjYH79UI5A0szbXeiiwVGr5cqc0gk2bWs19MA4kUuKldvDTyDvKcPoPR+PCrkUPtK4w2TliaE8InsCeE5/ssZSmwNuLTyb+vAQsKhxR2acRDxJbVAe/eqPtKvdomRbKHCSpOuht0x/kCaCFvqQBL3LVuCcbJp4YNdwx023ncRfozZ2EDxrMcdJVwJKCdCL7N0EDVRTV+y7YSkRSc1nVdbVO1Gh9CfZArwS9f7Rt4ymruFH66Ai2BdJ2jvosp12+ag/iBXuQxacs5/Qtfwsb9IHXT4ZaecgL0Uviq143eH0cHt4HQTLkIguyfZyIai2rlYXvIWcZGNtrP4EHDTJmC1TgQe7sYfuDwOhGNd310WNI7l52htpwR53Fsq/b7GWh/hP59zvNDghE9n/69NbvpopgXQwcSmN6DniGFFCHmZeO4AUrf1DGJShy2DRJVS1Vf/chtUTx4wnjdCO+sAEZ2oJTT1/I0vQQ67hmfqgIAdZO6/CQ04mUrOmmGRROSZGygpPW+I5tLf3qdJgtZJYJC7YJVg8fJ9KmXF9D/DVNW7p0qGTqwRNm4/9t0013kTpQ21P7DjCqBJn+kOz1qkoYj7LU004Fk6vvb+M7Cq7Ju8yRRWqoIolqDxvmZ7c0xtgMmJS+vfZhMn4FhA==; SessionId=a3fdf2ca85d145bf96bc3e37a4712181194f420936924d5890f5aad286af91ef; _xsrf=2|49cb8836|3ab28796296f87472963aad0147f113b|1518684455",
      "X-Notebook-Accesskey": "a7e8a98ff5394ec8894a207920d599dfcdf4bce1b959427abef63a7fbfd79a9f",
      "X-Site-Deployment-Id": "ANS-Prod-USSouth",
      "Disguised-Host": "statr-einarmagnus.notebooks.azure.com",
      "Max-Forwards": "10",
      "X-Original-Url": "/nb/nbconvert/pdf/Print%20error.ipynb?download=true",
      "Connection": "close"
    }
[E 13:36:06.275 NotebookApp] 500 GET /nb/nbconvert/pdf/Print%20error.ipynb?download=true (10.36.15.1) 317.19ms referer=None
```

**Comment by zouden** [comment]
I just came across this bug myself and I'm surprised there's been no response!

Easy way to reproduce it: clone the "Introduction to R" notebook from here: https://notebooks.azure.com/Microsoft/libraries/samples

Run the notebook. Now view the **notebook preview**. The images are now broken.

**Comment by zouden** [comment]
The issue arises when the notebook is viewed outside of the live editor,
such as with the preview feature.

**Comment by smortaz** [comment]
Sorry I’m not sure I understand what that means. Outside of what editor?
Are you talking about Jupyter or Jupyter lab ?

Can you give me exact repro steps? Thanks

**Comment by zouden** [comment]
Sure:

1. Clone the R sample notebook: https://notebooks.azure.com/Microsoft/libraries/samples
2. Open the notebook into the Jupyter editor, as in your screenshot above.
3. Run the first two cells. The plot changes a bit, as in your screenshot.
4. Close the notebook and return to the Library view.
5. **Select** the notebook (don't open it) and choose Preview from the toolbar.
6. The notebook opens in the viewer (not the editor). This is the same view that others will see if you provide the link to the notebook. 

It's in this viewer that the inline plots don't work.

**Comment by erkcan** [comment]
The same issue is also present for python.

See for example the following ipynb file on a public folder:
https://notebooks.azure.com/erkcan/projects/testplots/html/test.ipynb

Out[2] appears a proper plot when the notebook is "run", but nothing appears in the "preview" mode (which is the only thing that a third party can do unless they clone the entire project and run the notebook themselves). This is very inconvenient (particularly for those of us who are used to previewing notebooks on say github).

PS: It doesn't matter if we have either of "%matplotlib notebook" or "%matplotlib inline" or neither in the first In[1] cell.
