### ISSUE TITLE
Unable to see the typing window / Coding window in Edx.Please refer the following screen shot

### ISSUE THREAD

**Issue by 522034404** [Microsoft/AzureNotebooks#311]
I am trying to practicing the code as per the instructor instructions. I have followed the instructions in the video and copied and paste the sharedlibrary URL(https://notebooks.azure.com/eric/libraries/DEV236x)

However, I couldn't see the IN(input) and Output interface. I mean, I couldn't see the following screen by clicking the following shared library notebook. My expectation was to get the respective interface to practice the Python code. Please help in resolve.

![image](https://user-images.githubusercontent.com/36515581/36273597-fe853908-1252-11e8-8b8b-02a608f0ccd1.png)

I tried to double click the following note books and unable to see / get the python coding window.

![image](https://user-images.githubusercontent.com/36515581/36273805-b93cb492-1253-11e8-9607-0d5e6de0a88d.png)

Once clicking I could see the following screen. My expectation was to see the python code window. I tried to search for the instructor referring notebook in the shared library (which ends with Login), however, I couldn't find the notebook in the shared library. Please help in resolve. thank you.

![image](https://user-images.githubusercontent.com/36515581/36273933-1eb2eb52-1254-11e8-934a-3586df182a3d.png)

and simply, I am unable to perform the following actions to do:
So let's go to File > New Notebook, and let's choose Python 3.
Note there are other languages, including Python 2.
We'll use Python 3 in this course.
When I create a new notebook, I can give it a title.
The first cell created in a Jupyter Notebook is a code cell by default.
We can change that to something called a markdown cell as well.
Markdown cells are where the instructions and
explanations are written for these Jupyter Notebooks.
========================================
*******Please refer the following responses****
#### Which site did you access us from?
    [] https://notebooks.azure.com

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

I tried to logged out and logged in again...
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] **Python 3.5**
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
4:30 PM EST / 02/14/18
#### Which Web Browser(s) did you see the error in?
    **[] Chrome**
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] **Windows**
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

    https://notebooks.azure.com/eric/libraries/DEV236x

**Comment by 522034404** [comment]
Please reach out to me if you have any questions +1-330-6455-091.

**Comment by smortaz** [comment]
Hi  522034404  - since this is an Edx course, please post your issue on
their forum so that the author of the course can respond to you.  This
forum is for generic bugs/issues with the notebook service, not content
created by other folks.  Thanks!

**Comment by 522034404** [comment]
Ok thank you for the response, Have a goodday.
