### ISSUE TITLE
Request clone from Gitlab

### ISSUE THREAD

**Issue by gregorydillon** [microsoft/AzureNotebooks#312]
Please describe your issue as completely as possible.

I have some notebooks on gitlab that I would like to clone into an Azure notebook.   Could the Github clone be extended to Gitlab?

Thanks

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [x] Other (Please Specify) Chrome OS 63 Stable, Chrome OS 64 Stable, Ubuntu LTS

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

NA
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

NA

**Comment by crwilcox** [comment]
Hi Gregory. It could be extended to do that. In the meanwhile, you can use the terminal to run `git clone`.
