### ISSUE TITLE
Add user setting to select jupyter or jupyterlab by default

### ISSUE THREAD

**Issue by smortaz** [microsoft/AzureNotebooks#314]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

now that Jlab is hitting beta, it'd be nice to have a choice as to which environment is launched by default.  this could be at the global setting or per library.  probably per user is good enough.

**Comment by saschagottfried** [comment]
I have noticed in release notes that you have jupyterlab installed? How to run JupyterLab? I could not find any hint how to do this ...

**Comment by smortaz** [comment]
Hi.  In the list of your libraries, select one, right click, select
JupyterLab.

**Comment by saschagottfried** [comment]
@smortaz Thanks for giving me a hint.

**Comment by blacng** [comment]
@smortaz @saschagottfried  - please how do i launch jupyterlab from azure notebooks?

**Comment by smortaz** [comment]
@blacng 

1. jupyterlab is already installed.

to open in jlab:

1.  go to your list of libraries
2. highlight one by clicking on its row
3. right click
4. select Run in jupyterlab

![image](https://user-images.githubusercontent.com/742484/37308958-b0e47282-25fc-11e8-94da-77f3a76df738.png)

**Comment by blacng** [comment]
Thank you very much @smortaz.

**Comment by kkampf** [comment]
Hi all, apologies for the slow close on this. This option has been available for a bit now. Below is how to access it:

Click on your account
![image](https://user-images.githubusercontent.com/16325997/61420494-a0b1d000-a8b7-11e9-98d4-810415e94c03.png)

Edit profile information
![image](https://user-images.githubusercontent.com/16325997/61420506-ad362880-a8b7-11e9-9d09-3c2a991fcf3d.png)

Scroll down to "Enable Site Features" and you'll see it there!
![image](https://user-images.githubusercontent.com/16325997/61420488-968fd180-a8b7-11e9-9a0d-a35bc4f82b1d.png)
