### ISSUE TITLE
Can't import .txt file

### ISSUE THREAD

**Issue by demetrii** [Microsoft/AzureNotebooks#315]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I am trying to run a notebook because my machine doesn't have enough computing power to train my Neural Network. The input consists of a 327MB .txt file.

Unfortunately I cannot import this file into azure, copy paste the text, nor read it from local memory. Therefore I would like to ask if there is any way to do it, and if so how?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Create a variable containing a large body of text, or use open("path to text file", 'r') to read a large text file.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] MacOS

**Comment by crwilcox** [comment]
Hi @demetrii,
Have you looked at the help documentation on uploading? https://notebooks.azure.com/help/jupyter-notebooks/data/uploading

If you have and are encountering an error, how does it fail?

**Comment by demetrii** [comment]
@crwilcox 

I have but the file simply does not upload after clicking the upload button. Probably because it is too big.

**Comment by smortaz** [comment]
Perhaps compress it first then unzip?

Or try wget?

**Comment by demetrii** [comment]
@smortaz 

wget will work, thanks. Didn't think of it
