### ISSUE TITLE
Unresponsive notebooks

### ISSUE THREAD

**Issue by mvolarte** [microsoft/AzureNotebooks#316]
Please describe your issue as completely as possible.
I have been having connectivity issues since I made notebooks that I created for courses I took/am taking at edx. For instance, I try to run to test a code and it doesn't resolve. Restarting multiple types does not work. Can you please help? I decided to make them private because another course said that part of the honor system is to not post class codes online. 
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Shift+enter would not result to an answer, even if that cell has been previously shown to contain a valid code. It also takes an interminable amount of time to connect compared to before, usually resulting to going to the restart page: https://notebooks.azure.com/MVOlarte/libraries/Dev274x/restart
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/MVOlarte/libraries/Dev274x/restart

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
starting around 10 pm (Pacific Standard Time)
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

  https://notebooks.azure.com/MVOlarte/libraries/Dev274x/restart
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log) cannot even connect to the notebook
<img width="960" alt="dev_274" src="https://user-images.githubusercontent.com/36647420/36528958-b30ba552-176b-11e8-9c37-a711d73e1c47.png">

**Comment by smortaz** [comment]
Sorry about that. Unless we can look at the book it’s going to be very
hard to diagnose.

**Comment by mvolarte** [comment]
Do you mean you want me to make it public?
I can do that. It can remain public also as long that is not an issue with
the edx course that I am taking.

Thanks,
Mariefel

**Comment by mvolarte** [comment]
It's public now.
Mariefel

**Comment by moeenuddin** [comment]
I am having the similar issue. Any tips please.

**Comment by moeenuddin** [comment]
For some weird reason, open the azure notebooks com  in the chrome and worked :(. dont know why?

**Comment by solusman** [comment]
I faced same issue with Chrome.  Used Firefox instead and issue got resolved.

**Comment by salmanmkc** [comment]
Same issue on Edge Next Canary
