### ISSUE TITLE
Link to starred library broken

### ISSUE THREAD

**Issue by yeemey** [Microsoft/AzureNotebooks#317]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [/] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I starred [this library](https://notebooks.azure.com/mtpatter/libraries/open-data-seattle), but when I try to access it from the Starred Libraries on my profile, I get a 'Page not found'

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Star [the library](https://notebooks.azure.com/mtpatter/libraries/open-data-seattle), and see if you can access it from your profile's Starred Libraries.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
11:10AM PST

#### Which Web Browser(s) did you see the error in?
    [/] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [/] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/mtpatter/libraries/open-data-seattle

**Comment by crwilcox** [comment]
Thank you for reporting this. There appears to be a bug in the link we are providing. I am now tracking this and we will issue a fix.

Thanks!

**Comment by gilbertw** [comment]
Fix deployed, thanks for using Azure Notebooks
