### ISSUE TITLE
Cannot import Github repo: Unable to access the provided repository URL

### ISSUE THREAD

**Issue by zhiyzuo** [Microsoft/AzureNotebooks#318]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I always got this error when trying to import my Github repo as a library:
> Unable to access the provided repository URL

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

![image](https://user-images.githubusercontent.com/7501149/36695399-d3c00f06-1b06-11e8-9ab7-2b2d6e0b28fa.png)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
02-26-2018 15:08 CST

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi, this is a known issue due to changes in how github handles SSL.  A fix
is coming.  Sorry about that!

**Comment by russelljjarvis** [comment]
I too am having this problem.

**Comment by smortaz** [comment]
Thanks for you patience.  This /should/ be fixed with this thursday's roll
out.

**Comment by russelljjarvis** [comment]
Awesome, great. I have turned into a heavy Azure user.

**Comment by smortaz** [comment]
Hi - new bits rolled out - please try it.  thx.

**Comment by zhiyzuo** [comment]
Just tested it and it worked! Thanks!

**Comment by ggorman** [comment]
I am seeing exactly this problem again with a public repository. Attempting to import https://github.com/ggorman/math-gym

**Comment by OlliePage** [comment]
Hi, I am also experiencing this issue with ‘https://github.com/OlliePage/dataquest.git‘

**Comment by svanbodegraven** [comment]
Also experiencing this for a private repo

**Comment by MSA8D8** [comment]
@smortaz I got the same problem as that of @svanbodegraven. My repo is private one, too.

**Comment by kkampf** [comment]
Thanks for the feedback! We only support public repos at this time.
