### ISSUE TITLE
How to use Tensorboard?

### ISSUE THREAD

**Issue by demetrii** [Microsoft/AzureNotebooks#320]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I am trying to use tensorboard but can't get it to work, and can't find any solution.

The code I'm trying to run is `import TensorBoard
tb = TensorBoard.start(model_dir)`

Error:
`ModuleNotFoundError                       Traceback (most recent call last)`
`<ipython-input-3-a54b14b828f0> in <module>()`
`      1 # Start a tensorboard to see the curves in Datalab.`
`----> 2 import TensorBoard`
`      3 tb = TensorBoard.start(model_dir)`

`ModuleNotFoundError: No module named 'TensorBoard'`

When I run `!python -m tensorboard.main --logdir=/home/nbuser/library/lstm-punctuator` tensorboard gets activated but no other lines of codes after that line will be executed even though the kernel is running. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://lstmpunctuator-anon-g5tgzw.notebooks.azure.com/nb/notebooks/LSTM.ipynb#

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [] MacOS

**Comment by crwilcox** [comment]
Tensorboard requires you to have access to port 6006 on the machine. We do not allow this for Azure Notebooks at this time. For this reason, Tensorboard is unsupported.

As for the blocked command: The reason that command blocked is you have started tensorboard, which runs a webserver to my understanding. This will not return until that process is closed.
