### ISSUE TITLE
Creating a New Library in Azure Notebook from Github Repository

### ISSUE THREAD

**Issue by blacng** [Microsoft/AzureNotebooks#323]
Hello,

I was trying the following the steps for creating a new library in Azure Notebooks from a github repository as described [here](https://medium.com/@mikeclymer/integrating-azure-notebooks-jupyter-notebooks-with-github-fd847e941e4), but when I tried to create my own library from github in Azure Notebook, I got this error: "**Unable to access the provided repository URL.**"

#### Which site did you access us from?
- https://notebooks.azure.com

#### Describe the issue you are encountering

- I cannot create a new library in Azure Notebook from a Github repository

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

- Create a new library in Azure Notebook from a Github repository

- Please see the attached screen shot

![create_library_azure_notebook_github](https://user-images.githubusercontent.com/13294689/36794980-d55d802c-1c6f-11e8-872b-68e4a3457635.JPG)
#### What time (please include time zone) did this occur?

- EST

#### Which Web Browser(s) did you see the error in?
   

- Chrome

 

#### Which Operating System are you using? Please specify version as well if possible:
    

- Windows

**Comment by smortaz** [comment]
Hi. Sorry about that. This is a known issue and will be fixed with the
rollout this Thursday.

**Comment by blacng** [comment]
Thank you @smortaz.

**Comment by smortaz** [comment]
Hi - this should be fixed now!

**Comment by andneilmsft** [comment]
Please use this button to start a import from git:

![image](https://user-images.githubusercontent.com/42391274/49324353-c1701580-f4e0-11e8-83ac-c4348ab96b74.png)

For the moment, when pasting the link from git hub into the dialog, please remove the .git extension.

**Comment by tcox04-su** [comment]
I tried following your advice for the importing a github repository but even when i remove the .git extension, i get the same issue. Is there a way to fix this?
![Screenshot 2019-08-22 at 10 54 24 PM](https://user-images.githubusercontent.com/35647748/63563663-cde54400-c52f-11e9-9734-db5f792dce34.png)
