### ISSUE TITLE
Loading R packages

### ISSUE THREAD

**Issue by ccrosetti** [microsoft/AzureNotebooks#326]
Please indicate the right method lo load  R poackages, like caret, prophet, etc.
I am getting error from install.packages() giving non-zero result, thanks, Carlos

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi there - this could be due to a change in how R was built & is looking for compiler.  please see this notebook here for a workaround (see the the one called caret):

https://remuserbug-smortaz.notebooks.azure.com/nb/notebooks/caret.ipynb
