### ISSUE TITLE
Azure Notebook integration with Github

### ISSUE THREAD

**Issue by rupreetg** [microsoft/AzureNotebooks#327]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
  

#### Describe the issue you are encountering
I created a repo on Github - https://github.com/rupreetg/Kaggle. I cloned this to Azure Notebook (https://notebooks.azure.com/marshaler/libraries/Kaggle). I added one file and put some data in it. Now when I want to push it back to Github, I couldn't find a convenient way to do. I opened the terminal on the notebook and tried using git command there. I always get auth failure (my github has 2 factor auth enabled). I can setup ssh keys and try doing a push (not sure if it'll work or not, haven't tried). As it's a VM underneath, my ssh keys will be lost when i close this instance and run this instance at a later point of time. How do we have a smooth git integration?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/marshaler/libraries/Kaggle 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [Y] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [Y] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [Y] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/marshaler/libraries/Kaggle

**Comment by vhrique** [comment]
I agree. I would also like to see a better integration with github.
