### ISSUE TITLE
Scheduling the weekly run of a Azure Notebook

### ISSUE THREAD

**Issue by dirkjobosman** [Microsoft/AzureNotebooks#328]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I would like to know how I can set-up an automated scheduler to execute my python notebook on Azure.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Create a Notebook in Azure. 

#### Which language/kernel were you using when you experienced this issue?
    [x] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
CET

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
Not Applicable. 
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
Not Applicable.

**Comment by smortaz** [comment]
Hi there - currently the free notebook service is meant to be an interactive experience.  As such after about 1 hr of inactivity your container is reclaimed, assuming you've walked away.  In the future we'll likely offer what you ask for, but nothing on the immediate horizon.    Note that if you're willing to /log in/ once a week, you can the aznbsetup.sh script run whatever you desire, but it's not fully automatic...

**Comment by dirkjobosman** [comment]
Could you recommend anything else through AZURE for implementing a Notebook on a separate instance ?

**Comment by smortaz** [comment]
Azure Batch might be useful here.
