### ISSUE TITLE
Sharing private notebooks

### ISSUE THREAD

**Issue by lfr** [microsoft/AzureNotebooks#329]
Is there any way to share private notebooks with other people in my Azure directory?

**Comment by serdar-** [comment]
I am wondering about this too, it looks like you can share a link via e-mail but that does not work.

**Comment by smortaz** [comment]
Hi - there is no private sharing yet.  It's on the roadmap however.

**Comment by casaout** [comment]
@smortaz Great to know this is on the roadmap. Any expected launch date yet?

**Comment by smortaz** [comment]
Sorry no info.  @jflam would be the right person to update when more info is available.

**Comment by jflam** [comment]
We don't have a date yet, but this is definitely on our backlog of things that we will build. To add some color to this, we're thinking about this feature in the following context:

1. A set of users are granted access to a specific instance of Azure Notebooks (think an instance that is shared within your team / org)
2. A new sharing option will appear to enable sharing with all other users of that instance of Azure Notebooks.

Do you think this will meet your requirements? Also happy to have you contact me directly as well jflam at microsoft.com. Thx!

**Comment by lferrao** [comment]
@jflam the instance-based access solution that you describe sounds simple and sweet, can't wait to see it live

**Comment by jflam** [comment]
@casaout I'm pretty sure we can get this all to work with MSA (and Github - see https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-setup-github-app). Of course, we still need to plan and spike some of this work so consider this in the "I think we can do it" bucket of features :)

**Comment by lcorrigan** [comment]
Would be nice if we could control access to this implicitly through the access rights provided by an organization's office 365 setup. I.e: My team has a sharepoint site, where I would like to put my host my jupyter notebooks live and don't care if others in my organization (but outside my team) can access it. But absolutely cannot have this code and data available to those outside my company.

**Comment by smortaz** [comment]
Proper sharing is coming. This version is more of an open playground /
learning / teaching environment.

**Comment by myidealab** [comment]
I would appreciate this feature as well. I'm slowing migrating some of team towards using notebooks and this would be a huge plus. I recently got back into using Azure DevOps (formerly Team Services) and similar project management user control functionality would be great, especially if it's integrated with Office 365 and Azure AD.

**Comment by jflam** [comment]
This is a point in time feature right now - the “group” sharing via the private instances feature will unblock a lot of common scenarios. It will take more time, really a lot more UI which is expensive, to build out the finer grain sharing that I think you’re asking for above. 

We’re still on track to get this out early next year.

**Comment by peteshub** [comment]
Is there any update regarding the timeline? Would be keen on getting this feature :)

**Comment by amcardenasatms** [comment]
Ditto.  This would be a great feature.  I'd definitely use it if this feature were available.

**Comment by serdar-** [comment]
It has almost been a year since this question was asked. I expected more support from Microsoft on this project. Meanwhile, Google implemented this feature successfully in [Colaboratory](colab.research.google.com) project. Currently I am using that one and I am really happy with it.

**Comment by lupino3** [comment]
@jflam Hey John, are there any updates on the feature? The current sharing model makes it very hard to work on non-public data / code and share the work with a set of people. It would be very helpful to have any sort of finer-grained sharing control (as opposed to today's "all-public" or "all-private" model). Thanks!

**Comment by nawapoom** [comment]
@jflam Hi John, do you have the time frame for this feature?

**Comment by jflam** [comment]
Hi folks, sorry for being silent on this important question. We've had to work on a different set of tasks and had to move this feature to our backlog. Right now, I don’t have a good timeline on when this will ship, but will respond back to this thread when I have more information.

Thanks for using Azure Notebooks!

**Comment by sasauz** [comment]
We also need share notebooks between AD-users! It will be also greate to push and pull the Notebooks to/from Azure DevOps #694

**Comment by dbartz** [comment]
@jflam Hi John,
Do you have an update on this?
Without proper access management, we unfortunately cannot use  azure notebooks in our enterprise.

**Comment by RockScience** [comment]
@jflam with google colab we feel the pressure from our teams to move to google. It would be helpful to have insights from Microsoft on their plan for notebooks collaboration and sharing

**Comment by dgolden** [comment]
A quick-and-dirty solution would be to emulate Vimeo, where access is allowed by domain name.

**Comment by RockScience** [comment]
@dgolden could you elaborate?

**Comment by mechaman** [comment]
Any update on this feature?

**Comment by charlie9578** [comment]
Hi @jflam, is Azure Notebooks still being developed? If so, is there a chance the ability to share private notebooks will be deployed in the next couple of months? My IT director is keen we use MS, but without the ability to share private notebooks this really limits its use. Thanks, Charlie

**Comment by Bregor-Mar-Rian** [comment]
Is this the new direction? Can it replace Azure Notebooks?
https://techcommunity.microsoft.com/t5/azure-ai/bringing-intellisense-collaboration-and-more-to-jupyter/ba-p/1362009

**Comment by dbartz** [comment]
https://notebooks.azure.com/ states
> The Microsoft Azure Notebooks preview website will be retired on October 9th, 2020. 
EOL announced here:
https://github.com/microsoft/AzureNotebooks

This sounds as if the feature will not come - nor any other feature...
Have a look at
https://notebooks.azure.com/Content/alternatives.html

**Comment by charlie9578** [comment]
Thanks @Bregor-Mar-Rian and @dbartz. I'll try out some of those alternatives :)
