### ISSUE TITLE
Add Microsoft R Server (latest official release) to notebook service

### ISSUE THREAD

**Issue by regijohn** [microsoft/AzureNotebooks#33]
### Description
Currently notebooks.azure.com has only Microsoft R Open installed. 
Please get Microsoft R Server installed instead as it has more extensive functionality, such as machine learning (Microsoft ML package)

### Usage Scenario (e.g. teaching a computing course at university foo)
With Microsoft R Server, we can have a more extensive set of samples to showcase the ever expanding capabilities of Microsoft R Server

**Comment by crwilcox** [comment]
@regijohn, thanks for filing this request.

This is something we are looking into adding in the future. We will keep you up to date on the progress.

-Chris

**Comment by regijohn** [comment]
Hi Chris, the ask here therefore is to have this on an accelerated course.

Thanks in advance.

Regi

**Comment by marabout2015** [comment]
With the recently released MRS+MML 9.0.1 available from notebooks, I could immediately publish three examples of using machine learning. One is for churn prediction, another uses convolutional neural networks for deep learning, and the last assigns sentiment to Twitter text.
