### ISSUE TITLE
Attempt to install `grf` package from CRAN exists with error.

### ISSUE THREAD

**Issue by pjpaulpj** [microsoft/AzureNotebooks#335]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I'm getting the following error when I run the command `install.packages("grf")`

```
Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
Warning message in install.packages("grf"):
“installation of package ‘grf’ had non-zero exit status”
```
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
``install.packages("grf")``

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [X] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/pjpaulpj/libraries/grftest

**Comment by smortaz** [comment]
Hi.  Sorry about that.  We've seen caret not install as well.  Can you see if it's the same issue / workaround as caret?  Link:

https://notebooks.azure.com/smortaz/libraries/rem-userbug
