### ISSUE TITLE
Notebooks and Libraries are lost.

### ISSUE THREAD

**Issue by vinitrinh** [microsoft/AzureNotebooks#336]
Please describe your issue as completely as possible.
### Required:

Libraries are missing. 

This happened when I tried to log in after a month of no use. The website oddly directed me to a page to put in an email address, one that is different from my usual login email address. Upon following the instructions and logging in, all the libraries are gone and my username is changed to some random non-descript name.

#### Which site did you access us from?
    [1] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Recently my libraries are missing. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [1] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
GMT +8
#### Which Web Browser(s) did you see the error in?
    [1] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [1] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Is it possible that your company/schools admin changed something?  Please
send your login ID to nbhelp@Microsoft and we will investigate. Thanks

**Comment by vinitrinh** [comment]
Hi,

Thanks for the prompt reply.

I just logged in, with either email login IDs, and the libraries are back.

But in case you'd still like to investigate it anyway, my id is
limpetuponarock@gmail.com.

Regards,
Jeremy

**Comment by smortaz** [comment]
Thx we’ll take a look.

**Comment by DinoV** [comment]
What sort of environment are you in, e.g. could you have been behind a web proxy of some form?  Also, it looks like you logged in twice, once around 5:41 AM PST and once around 5:43 AM PST, does that align with what you saw, and the 2nd login cleared it up?

**Comment by vinitrinh** [comment]
Ive only ever logged in via google chrome. Im not sure what a web proxxy is.

If these two logins were yesterday: The first login was via
limpetuponarock@gmail.com. the second login was my alternate email address,
jeremytanjianle@gmail.com. on both logins, the libraries were safely
inside.

Perhaps you could check my logins on the 20th of March. That was when i
discovered the issue.

**Comment by DinoV** [comment]
So I do see records in our system for both of those emails. It would appear that your libraries are associated with limpetuponarock@gmail.com though and your jeremytanjianle@gmail.com email has the user-id "anon-hdggza".  If you're seeing the libraries under both logins then my only guess is that you have the two IDs associated together: https://support.microsoft.com/en-us/help/12407/microsoft-account-manage-aliases

You could go to the https://account.microsoft.com/ site and click on Your Info->Manage your sign in email and verify that they are the same.  

If those are linked then maybe it was just a hiccup on the sign-in side of things where it reported you as a different user to us.
