### ISSUE TITLE
Can't open any Notebook (or File) from my library, it opens a new windows of my available libraries

### ISSUE THREAD

**Issue by Alfonsovelva** [microsoft/AzureNotebooks#338]
Please describe your issue as completely as possible.

Accessing site from: http://notebooks.azure.com

Whenever I try to open (or Run) a notebook or csv file from my library, whether is cloned or a new file, it won't let me open, it will open a new tab saying that the notebook server is starting and after a few seconds it will return me to my Library section page. No way to open them.

This has been happening all day long today, in PST Time.
Im using Mozilla Firefox latest version on Windows 8 and Python 3.5 version of notebooks.

It used to be working but not anymore. I already cleaned my cache and cookies.

**Comment by smortaz** [comment]
Sorry about that!  Do you have a link to your library?  thx.

**Comment by smortaz** [comment]
I just tried it on my library & it works fine.  Both notebook file & a .csv file.

Is it possible that:

* you have changed your browser's "open links in new tab", etc. option?
* a pop up blocker is interfering

?

**Comment by Alfonsovelva** [comment]
Interestingly I had that option enabled, I just deactivated it but it still persists. 
When I try to run a file, it will now open a new windows (instead of tab) and I get back to the Library section. 

Does your files open in the same window/tab ?

I feel so noobie with this haha :(  
Here is the link to my library: https://notebooks.azure.com/DataWithPoncho/libraries

**Comment by smortaz** [comment]
Just cloned your notebook, ctrl-clicked each item (see each tab), and ran them... all worked fine.  My guess is something related to your brower and/or pop up blocker still.

![image](https://user-images.githubusercontent.com/742484/38334377-0369ffac-3810-11e8-9421-1429fc5d17bb.png)
