### ISSUE TITLE
output is not processing.

### ISSUE THREAD

**Issue by Namishk** [microsoft/AzureNotebooks#339]
![screenshot 80](https://user-images.githubusercontent.com/28803064/38344348-b9b60760-38a6-11e8-9b99-54ea07d0a177.png)
I have tried many times to process output, by shortcut and manually also but still no result.please help.

**Comment by smortaz** [comment]
Hi. I've heard that Jupyter itself has some issues with the "input" function.   I'll dig it up but it seems to be sporadic.  For example, I just tried it and it works ...

![image](https://user-images.githubusercontent.com/742484/38344836-935ecfea-3840-11e8-94fd-f337f92b346d.png)

**Comment by smortaz** [comment]
One thing to try:

1. restart the kernel (Kernel/Restart on menu)
2. Run your cell with the dat/time/print - at this time you should get input fields.  Make *sure* to enter something and hit Return to both prompts.  You should then see your print output.
3. If rerun the cell WITHOUT entering values + hitting Return,  Jupyter will get stuck.

Here I ran the cell, but before enter values, I ran the cell again.  Jupyter is stuck:

![image](https://user-images.githubusercontent.com/742484/38345050-d5d6bc7e-3841-11e8-90dd-670aaec25e0c.png)


LMK how that goes.
