### ISSUE TITLE
Whitelist https://transfer.sh/

### ISSUE THREAD

**Issue by mhils** [Microsoft/AzureNotebooks#34]
### Description
While getting data from GitHub works straightforward, there seems to be no good way to export data at the moment. Until better ways for data im- and export are introduced, it would be nice if transfer.sh (or a similar service) could be whitelisted as a workaround.

### Repro Steps

1. Save plot graphic as file.
2. `!curl --upload-file ./plot.pdf https://transfer.sh/plot.pdf`
3. `curl: (56) Received HTTP code 403 from proxy after CONNECT`

**Comment by DinoV** [comment]
Thanks for the suggestion, I've added trans.fer.sh to the white list!

**Comment by mhils** [comment]
Ha, thanks for the amazing turnaround time! :smiley:
