### ISSUE TITLE
Widget support in Jupyterlab

### ISSUE THREAD

**Issue by Rasmusmp** [microsoft/AzureNotebooks#342]
Hi
I am interested in knowing if Azure Jupyterlab is going to support widgets? 
For me the power of Jupyter lie in Jupyterlab. I want to be able to use bqplot to create interactive graphs, but get the message 'A Jupyter Widget' when executing. I'm not able to install any labextensions using ` !jupyter labextension install`. Is there a way around this, so I can display widgets in jlab?

**Comment by smortaz** [comment]
Hi there - the support for jupyterlab is preliminary right now.  We'll update it with support for plugins soon.  Thanks for your patience!
