### ISSUE TITLE
Images uploaded in a folder, Images, when referenced from a python notebook shows a broken link?  How to fix it?

### ISSUE THREAD

**Issue by FareedKaleem** [Microsoft/AzureNotebooks#343]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by FareedKaleem** [comment]
Dear Smortaz,

Thanks for your response.

I have resolved the issue of the broken link to display the image in the
notebook file..

Thanks & Best Regards,
Fareed Kaleem.

**Comment by smortaz** [comment]
great!
