### ISSUE TITLE
No link directly to any single notebook?

### ISSUE THREAD

**Issue by jsaue003** [Microsoft/AzureNotebooks#344]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering'

It's simply arbitrary to link to your entire library, and expect users to know what thing they're supposed to be clicking. The fact that there is no static link to any notebook is laughable, and downright insane. I've been directed to directories with hundreds of notebooks and had to rely on the instructions of the blog post that provided the link to understand what it was I was looking for. We NEED static links for our notebooks, or they're impractical. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi there.  Perhaps i'm misunderstanding, but you can link to an individual notebook:

https://notebooks.azure.com/smortaz/libraries/arcgis-sample/html/arcgis-sample.ipynb

Basically click on on Preview and then grab the link.

**Comment by jsaue003** [comment]
Very interesting. I was attempting to pull them up on incognito browsers/other computers, and kept reverting back to the directory, rather than the notebook. Preview seems to work.
