### ISSUE TITLE
Matplotlib+CNTK+Python 3.6 kill the kernel with simple code

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/AzureNotebooks#346]
Running (Run All Cells) this simple code in Azure Notebooks results in "The kernel appears to have died. It will restart automatically." with 100% repro.

```
import cntk as c
import matplotlib.pyplot as plt
%matplotlib inline 

ys=c.exp([1,2,3]).eval()

plt.plot([1,2,3], [1,2,3])
```

**Comment by smortaz** [comment]
Thanks for the heads up. I cannot tested right now but do you know if the
same code kills the kernel on a local installment of the notebook? Or is it
Azure notebook specific? Thanks

**Comment by smortaz** [comment]
@Hellek1  - is this an issue w notebooks.azure.com or your local jupyter+cntk ?  hard to tell.

**Comment by smortaz** [comment]
@Ark-kun  hmmm...

![image](https://user-images.githubusercontent.com/742484/40327031-432c4806-5cf6-11e8-92f1-1081bc21e4ee.png)
