### ISSUE TITLE
Support for installing JupyterLab extensions (e.g. for plotly and bokeh)

### ISSUE THREAD

**Issue by whatevergeek** [microsoft/AzureNotebooks#348]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
JavaScript output is disabled in JupyterLab

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
In JupyterLab, launch a new notebook (e.g. Python 3),     
Run the following:    
```python
#importing bokeh
from bokeh.io import output_notebook
output_notebook()
```

you'll have an error like this:    
```
Loading BokehJS ...
JavaScript output is disabled in JupyterLab
```

​

#### Which language/kernel were you using when you experienced this issue?
    [x] Python 2.7 
    [x] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Wednesday, 18 April 2018 7:42:40 AM Singapore

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by whatevergeek** [comment]
please add as feature
or share a workaround in jupyterlab

**Comment by smortaz** [comment]
@DinoV  - I believe this is scheduled to go out soon?

**Comment by whatevergeek** [comment]
@smortaz and @DinoV

please keep me in loop
i'm planning to use it in a jupyterlab workshop in an upcoming python conference.

would be great if holoviews and bokeh can work...

**Comment by whatevergeek** [comment]
Feel free to let me know also if you're facing any issue implementing... I'll try to help figure out possible solutions also...

**Comment by whatevergeek** [comment]
Is there a special way of launching this version of jupyterlab?
I'm still having the same issue.
![image](https://user-images.githubusercontent.com/7351683/39404821-1b7c3f12-4bcd-11e8-9678-f52e6a8167dc.png)

Here's the notebook i'm trying to run:     
https://notebooks.azure.com/datascientist/libraries/scipy-2017-holoviews-tutorial     
in jupyterlab, open and run the following notebook:     
/notebooks/notebooks/00-welcome.ipynb

**Comment by whatevergeek** [comment]
would be great if we can have this working soon    
i'm planning to use azure notebooks in my workshop     
in the upcoming PyCon APAC Conference: https://pycon.sg/workshops/

**Comment by KeremKaratas** [comment]
In [Release Notes](https://notebooks.azure.com/new) for April 2018 I see Bokeh support added as a feature yet when I run the following in a cell;
```
from bokeh.io import output_file, output_notebook

output_notebook()
```
output is;
```
Loading BokehJS ...
JavaScript output is disabled in JupyterLab
```

I also tried the following suggested in [bokeh docs](https://docs.bokeh.org/en/latest/docs/user_guide/notebook.html);
```
!jupyter labextension install @bokeh/jupyter_bokeh
```
output is;
```
> /usr/bin/npm pack @bokeh/jupyter_bokeh
npm notice 
npm notice 📦  @bokeh/jupyter_bokeh@1.1.1
npm notice === Tarball Contents === 
npm notice 570B    lib/extension.js  
npm notice 728.5kB dist/index.js     
npm notice 240B    lib/index.js      
npm notice 546B    lib/manager.js    
npm notice 73B     lib/metadata.js   
npm notice 1.9kB   lib/plugin.js     
npm notice 4.0kB   lib/renderer.js   
npm notice 3.2kB   lib/widgets.js    
npm notice 1.4kB   package.json      
npm notice 3.2MB   dist/index.js.map 
npm notice 2.9kB   README.md         
npm notice 25B     lib/extension.d.ts
npm notice 91B     lib/index.d.ts    
npm notice 536B    lib/manager.d.ts  
npm notice 587B    lib/plugin.d.ts   
npm notice 1.4kB   lib/renderer.d.ts 
npm notice 1.1kB   lib/widgets.d.ts  
npm notice 1.5kB   LICENSE.txt       
npm notice === Tarball Details === 
npm notice name:          @bokeh/jupyter_bokeh                    
npm notice version:       1.1.1                                   
npm notice filename:      bokeh-jupyter_bokeh-1.1.1.tgz           
npm notice package size:  1.0 MB                                  
npm notice unpacked size: 4.0 MB                                  
npm notice shasum:        85a038212f33e0fe8a778e05e4e9b1297b013348
npm notice integrity:     sha512-tf4Jrmp5yF0H3[...]2QkK5ISYhetaw==
npm notice total files:   18                                      
npm notice 
bokeh-jupyter_bokeh-1.1.1.tgz

Errored, use --debug for full output:
ValueError: 
"@bokeh/jupyter_bokeh@1.1.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=1.1.4-0 <2.0.0-0      >=4.1.1-0 <5.0.0-0   @jupyterlab/services
>=0.15.4-0 <0.16.0-0    >=1.1.3-0 <2.0.0-0   @jupyterlab/application
>=0.15.5-0 <0.16.0-0    >=1.1.3-0 <2.0.0-0   @jupyterlab/notebook
>=0.15.5-0 <0.16.0-0    >=1.1.3-0 <2.0.0-0   @jupyterlab/apputils
```

Any guidance?
