### ISSUE TITLE
Johann Brendel notebook????

### ISSUE THREAD

**Issue by Vorheez** [microsoft/AzureNotebooks#349]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
If I navigate from a favorite to notebooks.azure.com and I am not logged in, rather than send me to login page it sends me directly to

https://notebooks.azure.com/JohannBrendel/libraries/PythonUnit2

#### Which Web Browser(s) did you see the error in?
    [] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

See above
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

See above

**Comment by smortaz** [comment]
Thanks for the heads up - having trouble repro'ing.  i starred a library, logged out, clicked on the starred library, it took me to the library as expected.  from there if i click clone, it get the sign-in prompt.  

Can you provide a step by step repro pls?  thanks!

**Comment by Vorheez** [comment]
Oddly enough the steps I used yesterday aren't repeating it.  It started with cleaning all cache/cookies etc then going to link of my library.  I guess someone just really wanted me to see his python unit 2 library LOL
