### ISSUE TITLE
libR.so is not linked to libRblas.so 

### ISSUE THREAD

**Issue by bestxolodec** [Microsoft/AzureNotebooks#35]
### Description
I experience serious problems with shared libraries. In particular the default R installation does not  link to ` libRblas.so` which is needed for a proper work of python `rpy2` package. 
```
import rpy2.robjects as ro
```
leads to 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-739b61ecdff5> in <module>()
----> 1 import rpy2.robjects as ro

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/rpy2/robjects/__init__.py in <module>()
     14 import itertools
     15 from datetime import datetime
---> 16 import rpy2.rinterface as rinterface
     17 import rpy2.rlike.container as rlc
     18 

/home/nbuser/anaconda3_410/lib/python3.5/site-packages/rpy2/rinterface/__init__.py in <module>()
     90 del(os)
     91 
---> 92 from rpy2.rinterface._rinterface import (baseenv,
     93                                          emptyenv,
     94                                          endr,

ImportError: libRblas.so: cannot open shared object file: No such file or directory
```
because  `rpy2.rinterface._rinterface` depends on `libR.so` and it in turn is not linked to `libRblas.so`. 

```
> ldd /usr/lib64/MRO-3.3.0/R-3.3.0/lib/R/lib/libR.so
	linux-vdso.so.1 =>  (0x00007ffd17bbd000)
	libRblas.so => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6ac25b6000)
	libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f6ac236f000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f6ac20ff000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6ac1edd000)
        .....
```
This problem could be easily solved with LD_LIBRARY_PATH environment variable. But the problem is that I have failed to find a proper place to export that variable – `.bashrc` is being rewritten every time the parent of jupyter notebook is starting. And `.profile` is not a proper place because it has been read only on login. Setting this env variable from inside the ipython kernel does not help because it does not affect dynamic loader. 

I have tried to build R from sources and hack a little bit with ELF headers to include proper `rpath`. It helped but created  a tremendous dependence conflict which is very hard to get rid of. 

### Repro Steps
``` 
bash>  pip install rpy2 
jupyternotebook > import rpy2.robjects as ro
```

### Usage Scenario (e.g. teaching a computing course at university foo)
Interfacing  R with Python 

### Recommended Metadata
The Jupyter Kernel: Pyhton3
Web Browser: is not related 
LibraryID and Notebook Name (if applicable): n/fnngEUWeNCI/notebooks/Copy-gpy.ipynb

**Comment by bestxolodec** [comment]
If anyone would be so kind to suggest any workaround (no matter how dirty and hacky it is)  it would be very great. I have spent whole day trying to set things up to run `rpy2` and was very dissapointed.

**Comment by smortaz** [comment]
sorry about the delay - it's on the list of items to look at - we are in
the middle of rolling out a series of updates. thx for your patience.

**Comment by bestxolodec** [comment]
I am sorry, but i am still struggling from invisibility of libRblas.so to linker.  
Could you consider adding to `.bashrc` the line 
`export  LD_LIBRARY_PATH=/usr/lib64/MRO-3.3.0/R-3.3.0/lib/R/lib/ `
 as a possible temporary workaround until you get some time to properly fix it?

**Comment by bestxolodec** [comment]
Is there any plans about what to do with this broken R installation?

**Comment by loisks317** [comment]
I am also having this problem

**Comment by loisks317** [comment]
So even with !pip install rpy2 going through fine on Azure notebooks for me, I get the error message:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-40-198882ca5b70> in <module>()
----> 1 get_ipython().magic('load_ext rpy2.ipython')
      2 get_ipython().magic('R -i data')

~/anaconda3_431/lib/python3.6/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2144         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2145         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2146         return self.run_line_magic(magic_name, magic_arg_s)
   2147 
   2148     #-------------------------------------------------------------------------

~/anaconda3_431/lib/python3.6/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2065                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2066             with self.builtin_trap:
-> 2067                 result = fn(*args,**kwargs)
   2068             return result
   2069 

<decorator-gen-65> in load_ext(self, module_str)

~/anaconda3_431/lib/python3.6/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~/anaconda3_431/lib/python3.6/site-packages/IPython/core/magics/extension.py in load_ext(self, module_str)
     31         if not module_str:
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 
     35         if res == 'already loaded':

~/anaconda3_431/lib/python3.6/site-packages/IPython/core/extensions.py in load_extension(self, module_str)
     83             if module_str not in sys.modules:
     84                 with prepended_to_syspath(self.ipython_extension_dir):
---> 85                     mod = import_module(module_str)
     86                     if mod.__file__.startswith(self.ipython_extension_dir):
     87                         print(("Loading extensions from {dir} is deprecated. "

~/anaconda3_431/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

~/anaconda3_431/lib/python3.6/importlib/_bootstrap.py in _gcd_import(name, package, level)

~/anaconda3_431/lib/python3.6/importlib/_bootstrap.py in _find_and_load(name, import_)

~/anaconda3_431/lib/python3.6/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

~/anaconda3_431/lib/python3.6/importlib/_bootstrap.py in _load_unlocked(spec)

~/anaconda3_431/lib/python3.6/importlib/_bootstrap_external.py in exec_module(self, module)

~/anaconda3_431/lib/python3.6/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/anaconda3_431/lib/python3.6/site-packages/rpy2/ipython/__init__.py in <module>()
----> 1 from .rmagic import load_ipython_extension

~/anaconda3_431/lib/python3.6/site-packages/rpy2/ipython/rmagic.py in <module>()
     51 # numpy and rpy2 imports
     52 
---> 53 import rpy2.rinterface as ri
     54 import rpy2.robjects as ro
     55 import rpy2.robjects.packages as rpacks

~/anaconda3_431/lib/python3.6/site-packages/rpy2/rinterface/__init__.py in <module>()
     48 del(os)
     49 
---> 50 from rpy2.rinterface._rinterface import (baseenv,
     51                                          emptyenv,
     52                                          endr,

ImportError: libRblas.so: cannot open shared object file: No such file or directory
```
When I try to execute:

```
%load_ext rpy2
```

which, the identical statement works in a jupyter notebook on my local machine.

**Comment by JWMB** [comment]
Since notebooks' R ODBC SQL driver is missing (https://github.com/Microsoft/AzureNotebooks/issues/75), I wanted to try connect with Python and pass the data to R, but b/c of the libRblas.so problem, that doesn't seem like an option either. Any ETA for this?

**Comment by crwilcox** [comment]
RPy2 appears to work for Python2 and Python3, but not Python 3.6. We do not install it at this time.

When I did what you did I receive a different error when import rpy2.robjects

> --------------------------------------------------------------------------
> ImportError                               Traceback (most recent call last)
> <ipython-input-1-739b61ecdff5> in <module>()
> ----> 1 import rpy2.robjects as ro
> 
> ~/anaconda3_431/lib/python3.6/site-packages/rpy2/robjects/__init__.py in <module>()
>      14 import itertools
>      15 from datetime import datetime
> ---> 16 import rpy2.rinterface as rinterface
>      17 import rpy2.rlike.container as rlc
>      18 
> 
> ~/anaconda3_431/lib/python3.6/site-packages/rpy2/rinterface/__init__.py in <module>()
>      48 del(os)
>      49 
> ---> 50 from rpy2.rinterface._rinterface import (baseenv,
>      51                                          emptyenv,
>      52                                          endr,
> 
> ImportError: /home/nbcommon/anaconda3_431/bin/../lib/libreadline.so.6: undefined symbol: PC


If I `import readline` before rpy2.robjects though it works. This appears to be an old issue that has the same issue, https://github.com/ContinuumIO/anaconda-issues/issues/152

**Comment by roguetrainer** [comment]
Hi, I am having a similar problem using `rpy2` in Azure notebooks when using **Python 2.7** and **`rpy2` 2.8.6**. (With Python 3 & Python 3.6 I make even less progress.)  Please see the error messages in:
https://notebooks.azure.com/ian-buckley/libraries/systemic-risk/html/Py-rpy2.ipynb
```
unable to load shared object '/opt/microsoft/ropen/3.4.1/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory
```
Locally hosting the same notebook on my PC it works fine.
Any suggestions for work arounds would be great. Thanks.

**Comment by gilbertw** [comment]
Correct packages are deployed, thank you for using Azure notebooks

**Comment by dylanbraithwaite** [comment]
Has this issue resurfaced? I'm experiencing the same error on a notebook using rpy2 that was previously working fine.

**Comment by wangjun-sh** [comment]
Hi there,

I tried to execute below code before the "import rpy2.rinterface", looks like it works for me.
```
import sys
sys.path.append("/opt/microsoft/ropen/3.4.1/lib64/R/lib/")
print(sys.path)
```

**Comment by michaelsilverstein** [comment]
I had to set `R_HOME` in my Jupyter notebook before loading rpy2

```
%env R_HOME=/path/to/lib/R
%load_ext rpy2.ipython
```
Inspired by: https://stackoverflow.com/questions/12698877/how-to-setup-environment-variable-r-user-to-use-rpy2-in-python
