### ISSUE TITLE
Unable to upload data to Azure Notebooks.  File menu never comes up.  This worked 1-2 months ago.

### ISSUE THREAD

**Issue by mazudo** [Microsoft/AzureNotebooks#352]
I am unable to upload file to Azure Notebooks via menu: Data->Upload.  When I click on upload nothing happens.  This worked about 1-2 months ago, when a file dialog would pop up.  Data->download works fine.

This repros on Chrome and Safari.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
See above

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1. Open https://investments-mazudo.notebooks.azure.com/nb/notebooks/AssetAllocation-Calculator.ipynb
2. From menu click: data->upload

result:
nothing happens

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [x] Python 3.6 
one of the two above.  not sure which one.
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
4/21 PST 7:30AM

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) - Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

See above

**Comment by smortaz** [comment]
Thanks for the heads up.  It is indeed a regression.  A fix should be coming shortly; will update here.

**Comment by mazudo** [comment]
Thanks.  Please let me know when the fix is deployed and I can verify from my end.

**Comment by smortaz** [comment]
Hi - thx for your patience.  It's now fixed & deployed.

**Comment by mazudo** [comment]
works great now.  thanks!
