### ISSUE TITLE
Error in creating the Jupitor Notebook

### ISSUE THREAD

**Issue by tapan67** [Microsoft/AzureNotebooks#353]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
**Error creating notebook...

We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.**

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] **Windows**
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
We had some issues this morning. Please try again and let us know if it
has been mitigated thank you

**Comment by smortaz** [comment]
Root cause identified and mitigated.  Pls let us know if you experience the issue again.  Thanks!
