### ISSUE TITLE
Notebook Error

### ISSUE THREAD

**Issue by mahdifat** [Microsoft/AzureNotebooks#354]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
As soon as I click on my file this comes out. 

Error creating notebook...
We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
fix it. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
12 pm EST 
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [SAFARI] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi. We are looking into this. Thx. Will update here.

**Comment by smortaz** [comment]
Should be mitigated now. However we are seeing some sluggishness. Will
continue to investigate

**Comment by smortaz** [comment]
Root cause identified and mitigated.  Pls let us know if you experience the issue again.  Thanks!
