### ISSUE TITLE
!pip install pyaudio error portaudio.h not found

### ISSUE THREAD

**Issue by imacs1** [microsoft/AzureNotebooks#356]
The command:
!pip install pyaudio 

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
Collecting pyaudio
  Using cached https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Building wheels for collected packages: pyaudio
  Running setup.py bdist_wheel for pyaudio ... error
  Complete output from command /home/nbuser/anaconda3_501/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vi_rqys8/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp85g_oi0gpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -B /home/nbuser/anaconda3_501/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/nbuser/anaconda3_501/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for pyaudio
  Running setup.py clean for pyaudio
Failed to build pyaudio
Installing collected packages: pyaudio
  Running setup.py install for pyaudio ... error
    Complete output from command /home/nbuser/anaconda3_501/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vi_rqys8/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wjscab9i-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.6
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -B /home/nbuser/anaconda3_501/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/nbuser/anaconda3_501/include/python3.6m -c src/_portaudiomodule.c -o build/temp.linux-x86_64-3.6/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:23: fatal error: portaudio.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/nbuser/anaconda3_501/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vi_rqys8/pyaudio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wjscab9i-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vi_rqys8/pyaudio/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
!pip install pyaudio

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Internet Explorer / Edge (Please note this is not supported)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://textdemo-michaellustig.notebooks.azure.com/nb/notebooks/Add%20pyAudio.ipynb

**Comment by smortaz** [comment]
Does it work on a local notebook install?

**Comment by imacs1** [comment]
My goal is to get this running in Azure Notebooks.  That’s why I posted the question in this highly-specific group location.

From what I’ve read, portaudio.h is installed by running something like:
·        sudo port install portaudio # or
·        sudo brew install portaudio

Tthe Azure Notebook environment does not support “sudo”.  Therefore another method is required to install portaudio.  I’m wondering how to load portaudio in the Azure Notebook environment (and nowhere else).

BTW: I know Azure Notebooks’ Python environment supports pyaudio because the instructor is using it in a class I’m taking.

**Comment by smortaz** [comment]
My question regarding running local 1st was to test whether the pkg installed fine regardless of azure notebooks.  I checked around and it looks like it needs sudo for installing libaudio2.  Unfortunately that cant be done now :(.  I'd suggest using a local jupyter notebook where you have sudo access.  Azure notebooks is meant primarily for work where pkgs can be !pip or !conda installed... sorry about that.

**Comment by imacs1** [comment]
“Sorry about that” doesn’t cut it.  edx.org/Microsoft is using Azure Notebooks in their DAT263x Introduction to Artificial Intelligence (AI) class and pyaudio is clearly installed.  How do you think that the did that in their instance of Azure Notebooks?  Without the ability to install pyaudio, Azure notebooks is not a viable tool for AI development, much less, completing the course.

Clearly, there is a solution better than “sorry about that.”

For example, in addition to the last two commands I listed, this command would also solve the problem: sudo apt-get install portaudio19-dev

**Comment by smortaz** [comment]
Can you point me to the link where the instructor has successfully installed pyaudio using an azure notebooks?    Hopefully I'll learn something today.   There is no sudo option on Azure Notebooks.  

Also if you can paste a link to the course, I can talk to the instructor.

**Comment by imacs1** [comment]
Graeme Malcolm is the instructor.  Somewhere in the Text Analytics section he switched to a local machine (to use the PC’s microphone) and stopped using Azure Notebooks.  I missed that the first time I watched the video and kept using Azure Notebooks.  It makes sense from a security POV that a cloud-based product wouldn’t be able to access the PC’s microphone.

Thanks for getting me rolling again.  Your initial response was, in fact, the “answer.”

**Comment by Aditya0103** [comment]
I have addressed the same issue while solving the error related to speech recognition application.

No worries , I have found a  solution that helped solve my problem. 

> Firstly visit this site for pyaudio packages 
    https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio  

> Then get the wheel file , in my case it was " PyAudio-0.2.11-cp37-cp37m-win_amd64.whl ". 

> Visit the folder where the wheel is located and execute the following command : 
      pip install --ignore-install PyAudio-0.2.11-cp37-cp37m-win_amd64.whl --upgrade PyAudio-0.2.11-cp37-cp37m-win_amd64.whl

This should work as the pyaudio function must have a version installed that is **PyAudio-0.2.11 of later than that**
( Note that just trying to upgrade pyaudio may not be fruitful , you must upgrade the wheel file )
