### ISSUE TITLE
azure notebooks library surfaced in subscription resource group

### ISSUE THREAD

**Issue by myusrn** [microsoft/AzureNotebooks#357]
Please describe your issue as completely as possible.
I like the way that azure subscription resource group allows me to keep all my project specific big data & AI resources within an resource group, which I have role based access control support over.  Are azure notebooks libraries going to be something I can eventually create from the subscription portal environment and associate with a project specific resource group?  I'd like to have this support in order to have a similar experience to what azure [ Hadoop based ] databricks workspace web portal provides where notebooks, analytics jobs, and storage for a given big data & AI project effort are all accessible from one place.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Azure notebooks libraries are created and maintained in a separate place from my azure subscription portal resource group that otherwise hosts, and keeps cost reports, for all services being used for a given project or group of people. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Visit azure portal resource group and try to add a new resource.  The options list includes most other big data & AI types of resources but azure notebooks libraries is not one of the options. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Thanks for you feedback!  This capability is exactly what we’ll be offering
in the not too distant a future.

**Comment by myusrn** [comment]
Thanks it helps to know that is coming.  On a similar vein will azure data factory v2 be getting an additional pipeline execution option for azure notebooks in addition to the databricks notebook support that is already there?
