### ISSUE TITLE
Cannot shutdown notebook server, getting an "Internal Server Error" message

### ISSUE THREAD

**Issue by 1CodingGirl** [microsoft/AzureNotebooks#358]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
"Internal Server Error" message on Shutdown of a running server (python), occurring on selecting OK on Shutdown prompt.  Server is not shut down.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1) Start a Python notebook server.
2) On the Library list page, right click on the running Status and select SHUTDOWN
3) On the resulting prompt for Shutdown, select Ok

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 

#### What time (please include time zone) did this occur?
2:30 pm Eastern Time (US)
#### Which Web Browser(s) did you see the error in?
    [] Chrome
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by 1CodingGirl** [comment]
Thanks.

**Comment by adolfoguimaraes** [comment]
If help: I get the same error, but this happen only the notebooks that I have install some library. In my cases, I have used requirements.txt to install these libraries. In notebooks that I've had not install libraries I have been able shutdown the notebook. I used python 3.6 in my notebooks.

**Comment by ozak** [comment]
Same problem...is Microsoft giving up on Jupyter Notebooks? Seems odd that this is still open 2 years after. Also issues with environment.yml...
