### ISSUE TITLE
AzureNotebooks vs MS Azure Cosmos DB

### ISSUE THREAD

**Issue by chaochou2** [microsoft/AzureNotebooks#361]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x]https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
A question, not an issue. Can I connect to an Azure Cosmos DB thru AzureNotebooks as described in the MS Azure article "[Azure Cosmos DB: Build a SQL API app with Python and the Azure portal](https://docs.microsoft.com/en-us/azure/cosmos-db/create-sql-api-python)"?

If so, how can I make that article succeed using AzureNotebooks?

Thanks, Gary: ghottinger@gmail.com

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
US Eastern

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi - check out this sample:

https://notebooks.azure.com/smortaz/libraries/AzureCosmosDB

**Comment by chaochou2** [comment]
Wonderful!!!!!!

You be da bestest!!!!

Thank you.
