### ISSUE TITLE
Deteriorated performance of the Azure Notebook env

### ISSUE THREAD

**Issue by tomkom** [Microsoft/AzureNotebooks#362]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am using notebooks for a class of grad student this term. The performance has deteriorated substantially over the term, to not being able to run even basic demo of python using geopandas (pip install geopandas). I have noted this here: https://twitter.com/dinomirMT/status/993003462966231040
Using the approach from http://www.walkingrandomly.com/?p=6351shows
I get:

![image](https://user-images.githubusercontent.com/1487646/39685791-41f0d9f0-5208-11e8-842d-5426746dff79.png)

So only about 10 gflops.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
http://www.walkingrandomly.com/?p=6351shows

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Throughout multiple days

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi - just replied on twitter - basically walkingrandomly had one of the entire server to himself :).  The servers are shared now and each person gets a bound cpu limit to avoid hogging an entire system.  But as soon as cpu load reaches a certain limit, new servers are brought it automatically.  What type of computation are you running & what's the perf delta you're seeing?  Note that it could be the files over http slowness that you're seeing also.  Are you doing a lot of file operations?  If so, try doing that in /tmp (SSD), instead of ~/library (file io over http).

**Comment by tomkom** [comment]
This helped to improve the performance of reading and writing - thank you!

`
path = os.path.join("/tmp","data","Segment_BTW_subset.shp")
print(path)
os.path.exists(path)
`

**Comment by smortaz** [comment]
Great!  I ran the L10 notebook and it spends a fair amount of time installing pkgs too.  The with fiona.open loop is still running for me... good to see it helps to put it in /tmp.  Note that nothing in there is persisted, so you may wish to copy any needed files back to ~/library.

**Comment by monkeydust** [comment]
service down at the moment :(

**Comment by smortaz** [comment]
System is back up and running.  Apologies.

**Comment by monkeydust** [comment]
Great. Appreciated
