### ISSUE TITLE
!pip install pint not working

### ISSUE THREAD

**Issue by mathzorro** [Microsoft/AzureNotebooks#363]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

When my students and I try to install pint using !pip install pint, there appears to be an issue accessing the pint distribution.  Error messages here:

Collecting pint
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out',))': /packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out',))': /packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out',))': /packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out',))': /packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', timeout('timed out',))': /packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz
Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/1e/40/6938f7d544eef208a8183c2c80624289e8a4f4e0aea43f4658b9527077de/Pint-0.8.1.tar.gz (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://modsimpy-qzqz.notebooks.azure.com/nb/notebooks/code/chap07-inclass.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [X] Python 2.7 
    [X] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

10:00-11:55am Eastern Time

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://modsimpy-qzqz.notebooks.azure.com/nb/notebooks/code/chap07-inclass.ipynb

**Comment by smortaz** [comment]
Hi, there seems to be some large network issues.  Escalating asap.  

Oddly enough, !conda install pint -y seems to work...

**Comment by smortaz** [comment]
It seems to be related to this CDN issue:

https://status.fastly.com/

will update here when we have more info.

**Comment by smortaz** [comment]
Alright while this is being worked on, here's the temporary workaround:  insert at top of notebook:

import os
del os.environ['http_proxy'],  os.environ['https_proxy']

**Comment by smortaz** [comment]
Alright, it looks like the weird azure/fastly CDN issue has been cleared.  It cut off access to pypi and stackoverflow (at least).  Closing this bug.

![image](https://user-images.githubusercontent.com/742484/39737222-d7da022c-5238-11e8-925f-93b14c13b3a8.png)

**Comment by mathzorro** [comment]
Thank you so much for your help @smortaz!  My students and I appreciate it.
