### ISSUE TITLE
pydotplus

### ISSUE THREAD

**Issue by techgopu** [microsoft/AzureNotebooks#367]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
pydotplus package is not importing!

ImportError                               Traceback (most recent call last)
<ipython-input-123-b7d16578ff11> in <module>()
----> 1 import pydotplus

ImportError: No module named 'pydotplus'

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://0001-techgoppu.notebooks.azure.com/nb/notebooks/6.Decision%20Trees_V3.ipynb

#### Which language/kernel were you using when you experienced this issue?
   
    [] Python 3
   
#### What time (please include time zone) did this occur?
    Fri May 11 11:05:03 2018
#### Which Web Browser(s) did you see the error in?
    [] Firefox
#### Which Operating System are you using? Please specify version as well if possible:
    [] Ubuntu

#### What is the path to the notebook file (if relevant) that reproduces the issue? 

https://0001-techgoppu.notebooks.azure.com/nb/notebooks/6.Decision%20Trees_V3.ipynb

**Comment by antkmsft** [comment]
`pydotplus` is not installed by default, but running `!conda install pydotplus --yes` will install it correctly.
