### ISSUE TITLE
Error while starting notebook server

### ISSUE THREAD

**Issue by NikhilBagal** [Microsoft/AzureNotebooks#368]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    

#### Describe the issue you are encountering
       Error creating notebook...
We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/run/NikB/learnmath?dest=%2Fnotebooks%2F01-05-Polynomials.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 

#### What time (please include time zone) did this occur?
from 2pm IST
#### Which Web Browser(s) did you see the error in?
     Chrome
    

#### Which Operating System are you using? Please specify version as well if possible:
     Windows
    

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/run/NikB/learnmath?dest=%2Fnotebooks%2F01-05-Polynomials.ipynb

**Comment by erika9891** [comment]
Same issue here:

**Which site did you access us from?**

[] https://notebooks.azure.com

**Describe the issue you are encountering**

We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.

Which language/kernel were you using when you experienced this issue?

[] Python 3

What time (please include time zone) did this occur?

about 12:00 GMT

Which Web Browser(s) did you see the error in?

 Firefox

Which Operating System are you using? Please specify version as well if possible:

 Windows 10

**Comment by pskoo** [comment]
Same issue here:

Which site did you access us from?

[] https://notebooks.azure.com

Describe the issue you are encountering

We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.

Which language/kernel were you using when you experienced this issue?

[] Python 3

What time (please include time zone) did this occur?

about 9:19 GMT+8

Which Web Browser(s) did you see the error in?

Firefox

Which Operating System are you using? Please specify version as well if possible:

Windows 7

**Comment by LAITRUNGMINHDUC** [comment]
Same issue here:

Which site did you access us from?

[] https://notebooks.azure.com

Describe the issue you are encountering

We were unable to successfully create your notebook server. Please try again or report the issue if it persists.

Error: The system is currently experiencing higher than normal usage. We are unable to provide a free notebook at this time.

Which language/kernel were you using when you experienced this issue?

[] Python 3

What time (please include time zone) did this occur?

about 9:03 GMT+7

Which Web Browser(s) did you see the error in?

Chrome

Which Operating System are you using? Please specify version as well if possible:

Windows 10

**Comment by smortaz** [comment]
System is back up and running.  Apologies.
