### ISSUE TITLE
Internal Server Error when cloning from github

### ISSUE THREAD

**Issue by psychemedia** [Microsoft/AzureNotebooks#369]
#### Which site did you access us from?
 https://notebooks.azure.com
#### Describe the issue you are encountering

Error encountered when trying to clone github repo: https://github.com/mwermelinger/Learn-to-code-for-data-analysis

`Internal Server Error`

#### What steps can we take to reproduce this issue? 

Clone from button link: https://notebooks.azure.com/import/gh/mwermelinger/Learn-to-code-for-data-analysis

#### What time (please include time zone) did this occur?

15.00, May 14, 2018 London time

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] MacOS

**Comment by smortaz** [comment]
Back up & running.
