### ISSUE TITLE
Autocomplete (IntelliSense) is unreliable for F# notebooks

### ISSUE THREAD

**Issue by codec-abc** [Microsoft/AzureNotebooks#37]
### Description
Autocomplete (IntelliSense) is unreliable for F# notebooks

### Repro Steps
Create a F# notebook. Type some valid F# code like and press Ctrl+Space or wait for it when writing a dot on a module (for example  Array.)
It didn't worked for me on my 1st session.
Worked on the 2nd.
Work no more..
It seems to be quite random. I tried to restart Kernel and stuff. It doesn't seem to change anything.

### Usage Scenario (e.g. teaching a computing course at university foo)
Any

### Recommended Metadata
The Jupyter Kernel : F#
Occurrence Time: variable.
Web Browser: Chrome

**Comment by crwilcox** [comment]
Hi @codec-abc, thanks for the feedback. I am looping in people from the https://github.com/fsprojects/IfSharp project. They are likely who you want to talk to for these sort of things. They own the F# Kernel implementation.
@sylvanc

**Comment by sylvanc** [comment]
Yes indeed, this looks like an IfSharp bug. @codec-abc, I've created an IfSharp issue here:

https://github.com/fsprojects/IfSharp/issues/135

**Comment by crwilcox** [comment]
Closing as it is an external issue.

**Comment by codec-abc** [comment]
@crwilcox Like [38](https://github.com/Microsoft/AzureNotebooks/issues/38) I tested using a DockerFile some time ago and the intelliSense was reliable contrary to the one on AzureNotebooks. So probably an update of the F# notebook used in AzureNotebooks will help here too.
