### ISSUE TITLE
.csv wouldn't upload to the notebook

### ISSUE THREAD

**Issue by petattanasov** [Microsoft/AzureNotebooks#373]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering

I'm trying to upload a .csv file from my computer to my library, but it can't upload it. When I try to upload it from Dropbox, it gives me an EmptyData error. The file is not empty, it is 422 MB .csv. It is the same size in Dropbox also. Jupyter notebook runs it on my computer without an issue. But when I try to upload it, it never works.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I'm sending you screenshots from the error messages. Please, let me know, what should I do, in order to be able to work with the data in my notebook.
[untitled.pdf](https://github.com/Microsoft/AzureNotebooks/files/2018327/untitled.pdf)
[untitled1.pdf](https://github.com/Microsoft/AzureNotebooks/files/2018328/untitled1.pdf)

#### Which language/kernel were you using when you experienced this issue?
   
    [] Python 3.6 
    
#### What time (please include time zone) did this occur?

It happened several times, no specific time of the day.

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by smortaz** [comment]
Hi - Can you copy the file to non-dropbox folder (eg C:\data.csv) and use the Data/Upload menu to select & upload it to see if that works?   I just uploaded a 400mb file and it worked fine...  i'm wondering if it's a size limit issue.  Does a small .csv file upload from DB ok?

thx.

**Comment by petattanasov** [comment]
The first file - "untitled", is the error I receive, when I try to upload it directly from my computer. I don't know, if it is a size issue, I tried to find through the azure documents if some file size limitations exist, but couldn't find anything.

**Comment by smortaz** [comment]
sorry, i can't download the .pdf files due to security.  can you paste images?

also - what was the answer to: can you upload a 1k .csv file from C:\ ?  yes/no?

thx

**Comment by smortaz** [comment]
i verified that i can upload .csv files ok...

**Comment by petattanasov** [comment]
It was probably a size issue... when I split the file and uploaded it chunk by chunk it went flawless. I believe Azure should disclose somewhere what the file size limit is. 

What other questin about Azure, kind of unrelated... does anyone know if and how it is possible to keep a notebook running, if you want to close the browser you're using it on (for example to change devices).

**Comment by smortaz** [comment]
Thx, i'll investigate the size and put it in the docs.

re batch mode use: it isn't - after an hour of inactivity the container is relcaimed.  this will change in the future.
