### ISSUE TITLE
Installing R package RcppArmadillo fails

### ISSUE THREAD

**Issue by neaorin** [microsoft/AzureNotebooks#374]
#### Which site did you access us from?
https://studio.azureml.net

#### Describe the issue you are encountering
In an R notebook, trying to install package [RcppArmadillo](https://cran.r-project.org/web/packages/RcppArmadillo/index.html) fails with error:

```
install.packages("RcppArmadillo")

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
Warning message in install.packages("RcppArmadillo"):
“installation of package ‘RcppArmadillo’ had non-zero exit status”
```

This used to work a few months ago. 
Attached is a screenshot of the relevant portion of the log file.
![rcpparmadillo](https://user-images.githubusercontent.com/3250626/40306588-e91d2c10-5d07-11e8-9caf-694da64605ff.png)

#### Which language/kernel were you using when you experienced this issue?
R

#### Which Web Browser(s) did you see the error in?
Firefox

#### Which Operating System are you using? Please specify version as well if possible:
Windows

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update that should resolve this problem.
Please reactivate this issue if you still see the problem. Thanks for using Azure Notebooks!
