### ISSUE TITLE
story for downloading an entire library or folder within it

### ISSUE THREAD

**Issue by myusrn** [Microsoft/AzureNotebooks#375]
Would like a story for downloading an entire library or folder within it.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Have a library I cloned which contains a bunch of *.py supporting files and would like to download entire library and/or subfolder contents so as to open in vs17 or vscode so I can quickly and easily scan through their contents.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi - did you try the download button on the library ?

**Comment by myusrn** [comment]
doh, that works.  I had been looking at subfolders layer and not noticing that if I backed up to top layer libraries view I could select library at which point download UI option lit up and let me pull down entire library.

**Comment by smortaz** [comment]
No worries.
