### ISSUE TITLE
update the R version possible?

### ISSUE THREAD

**Issue by HenrikEckermann** [microsoft/AzureNotebooks#376]
Is it possible to update to R version 3.5 or at least 3.4.5? I tried doing it via the terminal but I require the password for sudo. Independent of that: Is there a default sudo password? I might need it also for pip install or whenever I want to install something else.

Thanks!

**Comment by smortaz** [comment]
Howdy - we have a work item to update a bunch of stuff, including R.  stay tuned.  it can't be done by users.  In the future we hope to allow you to have your own docker images, which enables putting your favorite version + other bits in there.

**Comment by HenrikEckermann** [comment]
@smortaz :+1: 
thanks a lot. 
Can you maybe roughly let me how long it will take until R will be updated? Likely not before upcoming Sunday, right?

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update to version 3.5.3.
Thank you for using Azure Notebooks!
