### ISSUE TITLE
R ggplot shows broken image icon instead of plot

### ISSUE THREAD

**Issue by omri374** [microsoft/AzureNotebooks#377]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Plots are broken when using R (ggplot). It takes a lot of the for the cell to process, and then I see a broken image icon. I also tried playing with the jupyter options to make all plots png but that didn't solve the problem.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Run this cell:
library(ggplot2)
ggplot(diamonds, aes(x=carat, y=price)) + geom_point()

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [X] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
5/24/18 2:05PM GMT+2

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://qzbecn01jee1-omri-m.notebooks.azure.com/nb/notebooks/Blank.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

Sorry, can't copy/paste from the terminal for some reason

**Comment by gilbertw** [comment]
R may be sending an invalid image/png format for display.  You can try switching to render both svg and jpeg

`options(jupyter.plot_mimetypes = c('image/jpeg', 'image/svg+xml'))`

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update that could potentially resolve this problem.
Please reactivate this issue if you still see the problem. Thanks for using Azure Notebooks!
