### ISSUE TITLE
caret package is not working in the R notebook file.

### ISSUE THREAD

**Issue by techgopu** [microsoft/AzureNotebooks#378]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Not able to install or load the caret package

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://0004-techgoppu.notebooks.azure.com/nb/notebooks/8.%20Neural%20Network/neural_network.ipynb 
Input : 67

#### Which language/kernel were you using when you experienced this issue?
   [] R 
  
#### Which Web Browser(s) did you see the error in?
    [] Firefox
  

#### Which Operating System are you using? Please specify version as well if possible:
   [] Ubuntu
   
#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://0004-techgoppu.notebooks.azure.com/nb/notebooks/8.%20Neural%20Network/neural_network.ipynb

**Comment by Dproso** [comment]
Is there any feedback?
Solution?

**Comment by techgopu** [comment]
No. Not yet.

Regards,
Gopal Kumar
+91 9113945195

**Comment by LaurentPetit2019** [comment]
Any news? I experience the same issue...
Does anybody read those messages?

**Comment by antkmsft** [comment]
Sorry for the delayed response! We have recently deployed an R kernel update that could potentially resolve this problem.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!
