### ISSUE TITLE
Notebooks don't exist anymore in library

### ISSUE THREAD

**Issue by D4D3VD4V3** [microsoft/AzureNotebooks#379]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Library doesn't show the notebooks I created anymore.
 On 25th May 2018, while working on a notebook, I encountered an 'Internal Service Error' and the cell I was running gave an error saying 'The history saving thread hit an unexpected error'. And when I refreshed the page, it gave me an error saying the notebook doesn't exist. As of now, I still don't have access to any of my notebooks and my library is empty.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
No idea what caused the error so I can't help here.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal
#### What time (please include time zone) did this occur?
UTC 7:30AM May 25 2018
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
The notebook in which I noticed the error doesn't exist anymore.

    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
I created a new notebook and ran the above command:
"cat: .nb.log: No such file or directory"

**Comment by smortaz** [comment]
Hi @D4D3VD4V3  - well that's not good at all.  What's your user id so we can look & see what happened.  

Can you try going incognito, logging back in, and tell me what you see?

thx.

**Comment by KieranBrantnerMagee** [comment]
Apologies in advance for any trouble, that's not a great situation.  I'd echo what Smortaz asked re: your user ID, as well as the library this failure occurred within.

In parallel, I'd ask if the following turns up anything for you:  In the library the notebook is missing from, can you click the "show hidden" button and navigate into the .ipynb_checkpoints folder?
![image](https://user-images.githubusercontent.com/29314371/40582016-3b57069a-611d-11e8-8920-c39d55a0d69c.png)
There may be recent checkpoints, even if something went wrong with that particular checkpointing step.

We do have additional backup functionality, depending on how long your notebook has been around it may have been picked up, but we'd need the account and library details for that as well.

**Comment by D4D3VD4V3** [comment]
@smortaz and @KieranBrantnerMagee,

User ID: davidsundararaj
Library: stuff (It's a public library)

I tried logging in using incognito mode but I still can't see my files.
Also, I navigated to the `.ipynb_checkpoints` folder and could only find a checkpoint for the file that I used to run the `!cat: .nb.log`command.

**Comment by D4D3VD4V3** [comment]
For the record, the error I got was “The history saving thread hit an unexpected error (OperationalError(‘attempt to write a readonly database’,)).History will not be written to the database.”

**Comment by smortaz** [comment]
We'll have to look at the logs to reconstruct what happened.  And possibly restore from backup.  Stay tuned pls.  thx.

**Comment by KieranBrantnerMagee** [comment]
Hey D4D3, 
Sorry for the delay, just got back in office.  Will start the process of seeing what we can pull from backups.  Will loop back here ASAP.
