### ISSUE TITLE
[F#] Plotting vertices is limited to a number of points and do not show error when limit is exceeded

### ISSUE THREAD

**Issue by codec-abc** [microsoft/AzureNotebooks#38]
### Description
Plotting vertices is limited to a number of points and do not show error when limit is exceeded. I tried to plot a csv of 3D vertices. It works when there are 23 points but not when more than that. When it fails it does not produce any error in the which is quite annoying.

### Repro Steps
Run the following script in a F# notebook.

```fsharp
let COUNT_MAX = 24

open System
open System.Net

#load "XPlot.Plotly.Paket.fsx"
#load "XPlot.Plotly.fsx"
open XPlot.Plotly

let readUrlAsString (url : string) = 
    use client = new WebClient()
    let s = client.DownloadString url
    s

let url = "https://raw.githubusercontent.com/sharkdp/curiosity/master/levels/level009/shape.csv"

let content = readUrlAsString url

let mutable lines = content.Split [|'\n'|]

lines <- Array.filter (fun a -> a.Contains ",") lines

let numbers_as_string = Array.map (fun (line : string) -> line.Split [|','|]) lines
let toFloat = Array.map (fun (str : string) -> float32 str)
let numbers = Array.map (fun arr_of_str -> toFloat arr_of_str) numbers_as_string

let mutable (xs : List<float32>) = []
let mutable (ys : List<float32>) = []
let mutable (zs : List<float32>) = []

let mutable i = 0
for vertex in numbers do
    if i < COUNT_MAX then
        xs <- List.append xs [vertex.[0]]
        ys <- List.append ys [vertex.[1]]
        zs <- List.append zs [vertex.[2]]
    i <- i + 1

printfn "%i " xs.Length

Scatter3d(
        x = xs,
        y = ys,
        z = zs
    )
    |> Chart.Plot
    |> Chart.WithLayout (Layout(title = "Simple Heatmap"))
```

Note if you change the COUNT_MAX value from 24 to 23 it plots correctly.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): F#
Occurrence Time: Always
Web Browser: Chrome

**Comment by crwilcox** [comment]
Hi @codec-abc, thanks for the feedback. I am looping in people from the https://github.com/fsprojects/IfSharp project. They are likely who you want to talk to for these sort of things. They own the F# Kernel implementation.
@sylvanc

**Comment by codec-abc** [comment]
I tested this weekend using the dockerfile of IfSharp and it worked great. So I suspect there is a problem occurring only on AzureNotebooks.

**Comment by crwilcox** [comment]
@codec-abc , what specific versions were you using in the Dockerfile? F# seems to change the kernel rapidly.
Is it possible you have a fix that we don't.

**Comment by codec-abc** [comment]
I don't remember the version but I took the one on the master branch of https://github.com/fsprojects/IfSharp at the time I did it. You are probably right about the missing fix but since I don't know what version you are running in Azure I am not sure I can help you.

**Comment by crwilcox** [comment]
Thanks @codec-abc. We will have to look at the versions and see. I don't remember off hand which version we pinned to of IFSharp and Mono but this just sounds like that sort of thing.

**Comment by antkmsft** [comment]
We have updated F# kernel a while ago, and I confirm the code above can plot 5000 vertices now.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!
