### ISSUE TITLE
HTML preview broken on opening a shared notebook link

### ISSUE THREAD

**Issue by mpant** [Microsoft/AzureNotebooks#383]
HTML preview broken on opening a shared notebook link

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering

When someone shares a notebook link, I cannot open it ( see attached) 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Try opening the shared .ipynb file link : https://notebooks.azure.com/Jiya/libraries/mynotebooks

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
   

#### What time (please include time zone) did this occur?
PST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
  

#### Which Operating System are you using? Please specify version as well if possible:
    [] MacOS

#### What is the path to the notebook file (if relevant) that reproduces the issue? 
https://notebooks.azure.com/Jiya/libraries/mynotebooks

    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
![htmlpreview](https://user-images.githubusercontent.com/6592/40745566-a468b90c-640c-11e8-8d23-fdee72c1a559.png)

**Comment by smortaz** [comment]
I just tried that link while not signed in & signed in and preview worked... hmmm... which specific notebook fails?

**Comment by mpant** [comment]
Yes seems to work now!. I did see the attached message earlier
