### ISSUE TITLE
Preview for guests not working on new Python 3.6 notebooks

### ISSUE THREAD

**Issue by gruntfutuk** [Microsoft/AzureNotebooks#384]
Preview for **non-logged in** users no longer working on new notebooks created since 31st May.

Example: https://notebooks.azure.com/kyber/libraries/ppl-exercises

My latest notebook, PPL Spiral of Numbers.ipynb, works fine when I am logged in BUT unlogged in users get:

* Loading notebook preview...

then

* There was an error loading the HTML preview for this notebook. Please try again or report the issue.

The notebook has been saved and check pointed more than once.

Previously created notebooks continue to work fine. All additional notebooks I've created since identifying this problem demonstrate same behaviour. All at Python 3.6.

Tried by several people over last 24 hours, spread around world, and using a variety of operating systems and browsers including desktop and mobile. I've tried on Android P with latest Chrome, Firefox and Opera; on MacBook Pro using Safari, Chrome, Firefox, and on Ubuntu 18.04 desktop using Firefox and Chrome.
    
Most recent log entries:
[I 12:58:56.446 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[I 12:58:56.489 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 12:58:56.869 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 12:58:56.870 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 12:58:57.034 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 12:58:57.110 NotebookApp] JupyterLab beta preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 12:58:57.110 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 12:58:57.138 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 12:58:57.139 NotebookApp] 0 active kernels
[I 12:58:57.139 NotebookApp] The Jupyter Notebook is running at:
[I 12:58:57.139 NotebookApp] http://[all ip addresses on your system]:25198/nb/
[I 12:58:57.139 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 15:00:08.485 NotebookApp] Could not open static file ''
[W 15:00:08.487 NotebookApp] 404 GET / (10.36.50.1) 69.51ms referer=None
[I 15:00:16.467 NotebookApp] Writing notebook-signing key to /home/nbuser/.local/share/jupyter/notebook_secret
[W 15:00:16.469 NotebookApp] Notebook PPL Spiral of numbers.ipynb is not trusted
[I 15:00:17.227 NotebookApp] Kernel started: e68e9f68-4306-4b89-b93f-85016d11f671
[W 15:00:18.503 NotebookApp] 404 GET /nb/static/base/images/favicon-busy-1.ico (10.36.50.1) 2.90ms referer=None
[W 15:00:18.514 NotebookApp] 404 GET /nb/static/base/images/favicon-busy-1.ico (10.36.50.1) 2.45ms referer=None
[I 15:00:20.311 NotebookApp] Adapting to protocol v5.1 for kernel e68e9f68-4306-4b89-b93f-85016d11f671
[W 15:00:20.755 NotebookApp] 404 GET /nb/static/base/images/favicon-notebook.ico (10.36.50.1) 2.58ms referer=None
[W 15:00:20.762 NotebookApp] 404 GET /nb/static/base/images/favicon-notebook.ico (10.36.50.1) 2.33ms referer=None
[W 15:03:42.225 NotebookApp] Notebook PPL Spiral of numbers.ipynb is not trusted
[I 15:03:43.369 NotebookApp] Adapting to protocol v5.1 for kernel e68e9f68-4306-4b89-b93f-85016d11f671
[I 15:14:22.037 NotebookApp] Saving file at /PPL Spiral of numbers.ipynb

**Comment by smortaz** [comment]
Hi sorry about that.  None of them render or a specific one? I just picked
a random dude book and it seems to render OK on my phone:

**Comment by gruntfutuk** [comment]
The recently created notebooks fail to render, namely the one I mentioned, PPL Spiral. The older notebooks preview fine. 

Another admin on the same python group on Facebook created his own new Azure account and created a new notebook from scratch covering the same challenge and it also has the same issue.

**Comment by gruntfutuk** [comment]
The previews are not working correctly again. No information about the cause of the problems.

I had several other people in different countries try and they experienced the same problem both with my notebook and with notebooks they created with very different content.

**Comment by smortaz** [comment]
Hi Grunt -  is there a reason you have closed the bug? Did the issue
somehow get resolved? If not let’s keep it open until we figure out what
the problem is.

**Comment by SeaDude** [comment]
This same issue is occurring on the [Python Data Science notebook](https://notebooks.azure.com/jakevdp/libraries/PythonDataScienceHandbook/html/01.00-IPython-Beyond-Normal-Python.ipynb). 

**The error message is:** 
There was an error loading the HTML preview for this notebook. Please try again or report the issue. 

**The mailto: address in the error message is incorrect**
Its missing the "o" in microsoft. Therefore when I reported this issue initially on 6/15, the email bounced back. Please update.

---
**Steps to reproduce:**

1. Click the Preface notebook:
![screenshot from 2018-06-16 14-13-53](https://user-images.githubusercontent.com/8636973/42127168-a5fc8920-7c48-11e8-8cee-088f1346d14e.png)


2. Click the "iPython: Beyond Normal Python" link at bottom of page
![screenshot from 2018-06-16 14-13-39](https://user-images.githubusercontent.com/8636973/42127171-adc8413a-7c48-11e8-8b75-e6a8f98d69f9.png)


3. Received error shown, emailed this to you.
![screenshot from 2018-06-16 14-13-29](https://user-images.githubusercontent.com/8636973/42127174-b4a3603e-7c48-11e8-975e-05fc155ab144.png)
