### ISSUE TITLE
Download as PDF Truncates to 1 Page

### ISSUE THREAD

**Issue by bendman** [Microsoft/AzureNotebooks#385]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
When I try to download the notebook as a PDF via LaTeX I only get one page, starting at the beginning, when the resulting document should actually be closer to 11 pages.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Try to download the included notebook (maybe any notebook, although I haven't tested this) as a PDF via LaTeX

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.5

#### What time (please include time zone) did this occur?
    12:30pm PST

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] MacOS 10.13.4

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
    https://notebooks.azure.com/bendman/libraries/public/html/Lab%203%20-%20Zaller-Deffuant.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
I tried, but got

    cat: .nb.log: No such file or directory

**Comment by smortaz** [comment]
Hi. Does this covert ok on a local jupyter setup?

Thx

**Comment by bendman** [comment]
@smortaz after some more testing, I found it outputs all the pages up to an equation (which happens to be on the second page in the original notebook), at which point it cuts out the page the equation is on and all following pages.

The simplest breaking case I can find after deleting everything else in the paper is this:
```
$$
\text{<}
$$
```
The original equation in question is here, which includes a similar nested `$$\text{<}` situation:

```
$$
o_{i,(t+1)}(o_{i,t}, \vec{o_t}, \mu, d) =
\begin{cases}
    o_{i,t} & \text{if $o_{i,t}-o_{j,t} < d$} \\
    o_{i,t} + \frac{1 - \varepsilon}{n}(o_{j,t} − o_{i,t}) & \text{if $o_{i,t}-o_{j,t} \ge d$} \\
\end{cases}
$$
```

Note that the formula prints just fine if I remove the `<` from the first case.

**Comment by smortaz** [comment]
Ok thx for investigating. In general we just install the stock jupyter++
stack from anaconda and don’t dig deep into each of the sub features such
as pdf printing. Our focus is mostly running the service. Nevertheless l’ll
file an  internal bug and hopefully we can take it deeper look. Or perhaps
a software update will fix it.   Meanwhile it looks like downloading the
notebook locally and printing it is a workaround - however inconvenient.

**Comment by bendman** [comment]
Thanks!
