### ISSUE TITLE
Package Numba is outdated

### ISSUE THREAD

**Issue by nunocalaim** [microsoft/AzureNotebooks#389]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

import numba as nb
nb.__version__
> 0.28.0

But the current version is 0.38! I know I can update manually (!conda update numba) but this takes a long time and only lasts for 1 hour according to the documentation I read

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
All of anaconda is due for an update - almost 1 yr + 4 months old.  @gilbertw - any update on when?

**Comment by patwadeepak** [comment]
and now pandas is outdated too!! it is using 0.19.x but current version is 0.24.2 and a lot of new features are there which are not in older version.

**Comment by antkmsft** [comment]
Currently, numba is 0.40.0 and pandas is 0.24.2.
