### ISSUE TITLE
Javascript + ipywidgets

### ISSUE THREAD

**Issue by lheagy** [microsoft/AzureNotebooks#39]
When using ipywidgets, there appear to be some javascript defaults that may have been over-written. For example, when using `ipywidgets.interact` with multiple widgets, they are typically stacked vertically, but on Azure Notebooks, they are stacked horizontally. This is an issue if you are using several widgets together (https://notebooks.azure.com/library/jUEYTq5Y2ko) 

![image](https://cloud.githubusercontent.com/assets/6361812/22864341/8a3cdad0-f104-11e6-8a4e-7869f73e52dc.png)

Additionally, a warning is displayed that the widget Javascript version is the wrong version (eg: DC_Building_Pseudosections.ipynb in https://notebooks.azure.com/library/em_apps). The widgets are still working though. 

![image](https://cloud.githubusercontent.com/assets/6361812/22864330/3fecbaea-f104-11e6-8c94-814f04fd5be4.png)

Both examples are running python 2. 

Thanks for your help!

**Comment by crwilcox** [comment]
Could you share the versions of the product you are comparing with?

For instance, Azure Notebooks:
IPyWidgets: 5.2.2 installed.
Jupyter Notebooks: 4.3.1

Under Help->About the following Dialog should show up:
![image](https://cloud.githubusercontent.com/assets/638797/22988460/0ce0b56a-f367-11e6-9040-d8ce255ba015.png)

Also, we will want to know the version of IPyWidgets. Run the following in a cell
```
import ipywidgets
ipywidgets.__version__
```

**Comment by lheagy** [comment]
Thanks @crwilcox. sorry for my late reply! 

- The version of the notebook server is 4.3.1 
- The ipywidgets version is: 5.2.2 

![image](https://cloud.githubusercontent.com/assets/6361812/23441018/a2a789e4-fdd4-11e6-9302-bf06c28fa744.png)
