### ISSUE TITLE
bsts - install package failure

### ISSUE THREAD

**Issue by shakanand** [microsoft/AzureNotebooks#390]
Please describe your issue as completely as possible.

#### Which site did you access us from?
 https://studio.azureml.net

#### Describe the issue you are encountering

I am trying to install bsts package with the below command and it fails with an error

install.packages("bsts")

error

Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
also installing the dependencies ‘BoomSpikeSlab’, ‘Boom’

Warning message in install.packages("bsts"):
“installation of package ‘Boom’ had non-zero exit status”Warning message in install.packages("bsts"):
“installation of package ‘BoomSpikeSlab’ had non-zero exit status”Warning message in install.packages("bsts"):
“installation of package ‘bsts’ had non-zero exit status

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

install.packages("bsts")

#### Which language/kernel were you using when you experienced this issue?
    [] R 

#### What time (please include time zone) did this occur?
  CST
#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by smortaz** [comment]
Hi - does it install ok on the version of R that we have on Azure notebooks locally on your machine?  Trying to narrow down the cause... thx.

**Comment by shakanand** [comment]
Azure notebooks has R version of "3.4.1", i tried this on my local R "3.4.3" and it installed fine.
As of now, I do not have a local R 3.4.1 version to test this.

As per the R documentation, this package is supported  on version >= 3.3.1
https://cran.r-project.org/web/packages/bsts/index.html

**Comment by shakanand** [comment]
i tried the same on Jupyter notebooks on Azure Data Science VM and the installation went thru fine.
Jupyter notebooks on DSVM has R version 3.4.3 (2017-11-30)

**Comment by smortaz** [comment]
Ok it looks like it's due to old bits.  I've pinged @gilbertw internally to see when we'll be able to update the distro.
