### ISSUE TITLE
AzureNotebooks - memory issues - The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by giusbi** [microsoft/AzureNotebooks#391]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I have a Jupyter Notebook on AzureNotebooks that is supposed to display a graph using networkx and plotly. The graph contains around 4000 nodes. When I run the notebook it gives an error "The kernel appears to have died. It will restart automatically.'. I also tried to plot a much smaller graph with around 10 nodes and in this case the notebooks does not fail. I do think this is a memory issue. Is that possible to customize the memory allocated ?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
notebook shared via email.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Amsterdam

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
notebook shared via email.

**Comment by smortaz** [comment]
Sorry about that. There is currently a four gig limit per user.    This
will be adjustable in the future but not currently.

**Comment by KPCoenbla** [comment]
hi, has this been changed to be ajustable yet? Can't seem to easily change specs.
