### ISSUE TITLE
Read_Excel not working to spec

### ISSUE THREAD

**Issue by kompartners** [Microsoft/AzureNotebooks#392]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I am trying to read excel files, and need leading zeros left on with numbers:
http://pd.read _excel(filename, sheet_name=None, dtype=str)

the dtype parameter appears to not be supported in Azure Jupyter.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Try to open an excel file using a dtype of str or object and you get a ValueError.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [X] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
5:20P MST

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [X] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
It's sensitive, and I don't think my notebook will be a unique issue.

**Comment by smortaz** [comment]
what the URL for your notebook?

highly doubtful if it's azure as we just install the standard bits from
anaconda.

**Comment by kompartners** [comment]
https://notebooks.azure.com/brandonwatson/libraries/setcreation

I reverted to my uploaded ipynb, so there isn't a variable for the azure directory to pre-pend to the filenames. Let me know if you need me to do that.

By reading in the Excel file without the dtype parameters, I lose ability to treat numerica as strings.

Thanks,
Brandon
(I'm on my mobile: 425-985-5568
or FB messenger: http://m.me/brandonwatson)

________________________________

**Comment by smortaz** [comment]
It might be related to this:

https://datascience.blog.wzb.eu/2016/06/22/reading-textual-data-csv-excel-files-correctly-pandas/

Also, is your local pandas version the same as Azure's (0.19.2) ?

**Comment by kompartners** [comment]
I solved this problem using the blog post pointed to above. Thank you.
