### ISSUE TITLE
Requesting support for HTML anchors and links within a notebook

### ISSUE THREAD

**Issue by sadukie** [microsoft/AzureNotebooks#393]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Cleaning up a Jupyter notebook for a presentation on 13 June showing Python to C# devs.  Would like to include links that drop down to their respective sections.  This works in Jupyter Notebooks locally but does not work in Azure Notebooks.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

This is the Steps Recorder zip file of how it works in my local Jupyter Notebook instance.

[JupyterNotebook-SupportsAnchors-20180611.zip](https://github.com/Microsoft/AzureNotebooks/files/2088620/JupyterNotebook-SupportsAnchors-20180611.zip)

You can see this in Azure Notebooks here:

https://notebooks.azure.com/sadukie/libraries/pythonforcsharpdevs

Specifically in the notebook named "Broken Links - Intro to Python for CSharp Devs.ipynb"

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Hong Kong Time - just now.  

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/sadukie/libraries/pythonforcsharpdevs/Broken%20Links%20-%20Intro%20to%20Python%20for%20CSharp%20Devs.ipynb

**Comment by sadukie** [comment]
After uploading my local ipynb to Azure Notebooks and rerunning (?  rerendering?) the markdown sections with the links, they still do not work.  

I was using this as a guide on creating a ToC in my notebook: http://sebastianraschka.com/Articles/2014_ipython_internal_links.html

**Comment by smortaz** [comment]
There seems to be an issue w generating HTML preview for anything right now.  I've logged an internal bug.  but the links as you have them _should_ work in HTML preview.

![image](https://user-images.githubusercontent.com/742484/41212174-e30fec24-6cf0-11e8-824b-253b3dde2d37.png)
