### ISSUE TITLE
Trouble loading data

### ISSUE THREAD

**Issue by m-r-cooper** [microsoft/AzureNotebooks#394]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I have a block of code to load table service data that worked up until Friday (6/8) (today is 6/12) and then started receiving the error "ImportError: cannot import name 'CloudServiceAccount'" and "cannot import name TableService"

## Original code that got first error (cannot import 'CloudServiceAccount'"):
from azure.storage import CloudStorageAccount
from azure.storage.table import TableService, Entity
from azure.storage.table.models import Entity

Changed to this to get 2nd error ("cannot import 'TableService'"):
from azure.storage.common import CloudStorageAccount
from azure.common.cloud import TableService, Entity
#from azure.storage.common.models import Entity

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
EST: this worked fine from sometime in May until 6/8/18 when I started receiving the error
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi - can you try your code outside of azure notebooks to see if it's notebooks related (unlikely...).  thx.

**Comment by m-r-cooper** [comment]
Hi smortaz, where would I try it outside of notebooks? Thanks

**Comment by smortaz** [comment]
Any python environment:

- vscode
- python prompt

**Comment by m-r-cooper** [comment]
will it work even though the code is trying to import from azure storage?

**Comment by smortaz** [comment]
If you have permissions to read from that storage, it doesn’t matter
whether it’s on Azure or local, in a notebook or at the prompt.

**Comment by m-r-cooper** [comment]
ah ok, when I type it in my local prompt it gives me the error "ModuleNotFoundError: No module named 'azure'"

**Comment by smortaz** [comment]
Have you installed the azure package?  If you haven’t, it won’t find it.

**Comment by m-r-cooper** [comment]
I can try that, a coworker has the account with the data, but why was I able to run this program until Friday?

**Comment by smortaz** [comment]
I have no idea honestly - it could be something that expired, credentials changed, etc.

**Comment by m-r-cooper** [comment]
Hi smortaz,  I installed the azure package on my computer and still am getting an import error when trying to get azure.storage.table. 

>>> from azure.storage.table import TableService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'azure.storage.table'


I tried installing it directly and got the error below:

C:\Users\coop>pip install azure-storage-table
Collecting azure-storage-table
  Could not find a version that satisfies the requirement azure-storage-table (from versions: )
No matching distribution found for azure-storage-table

please let me know if you can help! Thanks!

**Comment by m-r-cooper** [comment]
I have gotten this to work on my local device but the azure jupyter notebook says "ImportError: No module named 'azure.cosmosdb'

from azure.storage.common import CloudStorageAccount
from azure.cosmosdb.table.tableservice import TableService
from azure.cosmosdb.table.models import Entity

**Comment by smortaz** [comment]
Can you send me a link to your notebook that exhibits the errors?  I can take a look.

But basically, if you can make this sample to run locally, you should be able to run in Azure notebooks as is as well:

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python

**Comment by marco-rossi29** [comment]
I'm getting the same error:

````
# Required for Azure Resource Manager
from azure.mgmt.resource.resources import ResourceManagementClient
from azure.mgmt.resource.resources.models import ResourceGroup

# Required for Azure Data Lake Store account management
from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient
from azure.mgmt.datalake.store.models import DataLakeStoreAccount

# Required for Azure Data Lake Store filesystem management
from azure.datalake.store import core, lib, multithread

# Required for Azure Data Lake Analytics account management
from azure.mgmt.datalake.analytics.account import DataLakeAnalyticsAccountManagementClient
from azure.mgmt.datalake.analytics.account.models import DataLakeAnalyticsAccount, DataLakeStoreAccountInfo

# Required for Azure Data Lake Analytics job management
from azure.mgmt.datalake.analytics.job import DataLakeAnalyticsJobManagementClient
from azure.mgmt.datalake.analytics.job.models import JobInformation, JobState, USqlJobProperties

# Required for Azure Data Lake Analytics catalog management
from azure.mgmt.datalake.analytics.catalog import DataLakeAnalyticsCatalogManagementClient

from azure.datalake.store.core import AzureDLFileSystem

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e3c53be59375> in <module>()
      1 ## Required for Azure Resource Manager
----> 2 from azure.mgmt.resource.resources import ResourceManagementClient
      3 from azure.mgmt.resource.resources.models import ResourceGroup
      4 
      5 ## Required for Azure Data Lake Store account management

ModuleNotFoundError: No module named 'azure'
````

**Comment by romyvalencia** [comment]
I am not quite sure if this is related to the same error as I execute the below command from Microsoft Azure notebook.   Below is code snippet sample.

from azure.cosmosdb.table.tableservice import TableService
from azure.cosmosdb.table.models import Entity
table_service = TableService(account_name='myaccount', account_key='mykey')


ImportError: No module named 'azure.cosmosdb'
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<command-248191914124709> in <module>()
     37 from pyspark.sql.types import *
     38 
---> 39 from azure.cosmosdb.table.TableService import TableService
     40 #from azure.cosmosdb.table.models import Entity
     41 

ImportError: No module named 'azure.cosmosdb'
