### ISSUE TITLE
Okpy client pre-installed in Azure notebooks

### ISSUE THREAD

**Issue by taupalosaurus** [Microsoft/AzureNotebooks#396]
Hi,

This issue is to ask whether it would be possible to have the [okpy client](https://okpy.org/) installed on Azure notebook VMs.

### Context:
[Okpy](https://okpy.org/) is an opensource project building an auto-grading tool designed to facilitate the submission and grading of programming assignments. Our group at Imperial College London (with @ggorman), which has been using Azure notebooks for a year for undergraduate teaching, is planning to extend its use to graduate teaching, in combination with okpy. 
We have started a collaboration with people from Microsoft Commercial Software Engineering team (@marrobi), in order to deploy the okpy server on Azure VMs. Efforts to install the client on Azure Data Science VM were also initiated. This strategy has recently been publicly advertised: https://www.imperial.ac.uk/news/186669/innovative-assessment-deploying-online-software/ 
It is part of a bigger strategy at the whole University level to promote and develop the use of both tools and, we believe, of a larger trend in education.

The okpy client is used by students to a) run the tests locally for formative auto-assessment and b) submit their assignments to the server. For now, we need to install it manually at the beginning of each notebook with `pip install -U okpy`, and repeat the operation everytime the notebook is opened, which results in a considerable waste of time for the students.

Hence this request to have the client pre-installed, which would be immensely helpful to us, but also potentially to many other users.

Thanks!

**Comment by smortaz** [comment]
Thanks for the +1 on OkPy.  If there are other who want it, it'd be great to +1 this request so we can prioritize it.

**Comment by andneilmsft** [comment]
okpy is now available in our image.

**Comment by leestott** [comment]
You can test the current version of OKpy but the following command 

!pip freeze | grep okpy

Here a test file https://notebooks.azure.com/LeeStott-Microsoft/projects/ok-test
