### ISSUE TITLE
Where you track your outages? 

### ISSUE THREAD

**Issue by gitsupersmecher** [microsoft/AzureNotebooks#397]
Do you have an outage ? I cannot access my notebooks:

![image](https://user-images.githubusercontent.com/23306234/41371506-66a1efd2-6eff-11e8-849a-eb3ebbd73a24.png)

**Comment by smortaz** [comment]
Yes. Pls see status on twitter for @azurenotebooks. Azure storage is out
affecting lots of services unfortunately
