### ISSUE TITLE
Download ZIP file and directory with same name issue.

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/AzureNotebooks#399]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net
notebooks.azure.com

#### Describe the issue you are encountering
Use right click and select download from menu. When you get the ZIP file, you cannot unzip it. Every sub-folder has a 0kb file with the same name. That's why we cannot unzip it to target directory. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal
Python 3.6

#### What time (please include time zone) did this occur?
few days ago and just fixed at 2018/06/14 10:00 UTC+8 Shanghai

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)
Just tested on  Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)
Both Windows and MacOS. But can manually fix it via Windows Explorer

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/HaoHu/libraries/PythonDataScienceHandbook

**Comment by smortaz** [comment]
Thanks for the heads. We’ll take a look. Seems like a regression.
