### ISSUE TITLE
Add support for Julia

### ISSUE THREAD

**Issue by eclectir** [microsoft/AzureNotebooks#4]
Add Julia language kernel & provide samples.

**Comment by sc0ttwad3** [comment]
### Julia support is essential! 

With F#, R, Python, and others already supported, it should be nearly trivial to install **Julia** kernels (preferably v0.6 and v0.7-dev nightlies) on host servers running **Azure Notebooks**. Then with Jupyter already obviously running well, a simple **IJulia** package add and you're there. As an alternative example, [Julia Box](https://juliabox.com/) is a cloud-based solution; but, I would really prefer to have Julia in combination with other notebooks in a collected library in **Azure Notebooks**.

Any status on this after nearly 8 months? I'm more than willing to help. Yet, there is nothing in this repository to work with and there has been no response to this issue (or another similar open issue asking for Julia support) since it became a **feature** issue.

If this isn't the place, please let me know who I can contact to get this moving?

**Comment by crwilcox** [comment]
@sc0ttwad3, I just received an email from our Connect team saying you are requesting we add Julia. This was closed by mistake (It seems both issue tracking this closed when I called it duplicate?)

As far as why after all this time we still don't have Julia: We lack information on the impact of adding Julia. We have found adding kernels does have a maintenance cost and, unless we believe a large number of people will use the new kernel, it isn't worth it for our small team to invest in supporting it.

I have no personal familiarity with Julia. This means I cannot validate it effectively. To my knowledge, no member of the Azure Notebooks development team has sufficient knowledge. While it may seem small to add the kernel, it involves us investigating dependencies, updating packages, monitoring for security concerns, etc. This all ultimately adds up to a relatively large tax.

If we had reason to believe that this would be used by a large subset of our users, we could consider investing the time to support Julia, but at this time we do not have supporting evidence of that.

**Comment by szaydel** [comment]
@crwilcox, I actually think Julia will eventually gather a lot of interest, but its adoption has been slow(ish), for a number of reasons I suppose. It is still a fairly new language, but may well place Azure Notebooks ahead of competition, perhaps call it future-proofing. It is too bad that it is not easy, or perhaps feasible to get community help to support these sorts of things, which would take some of the burden off of the shoulders of Azure Notebooks development group.

**Comment by crwilcox** [comment]
@szaydel, the initial work for a kernel is usually pretty low, but we have had enough issue with other kernels (R, F#) compared to their usage levels it is just hard to justify a third right now. We operate as a very small team and effort to support Julia will take away from our ability to produce features and infrastructure improvements to the service that will help users of all kernels.

So, even if a user provided all of the setup, the team will still have to maintain it and that ultimately takes away development time. I do think we will have Julia eventually, I just want to be transparent and realistic in the timeline. It is likely a ways off.

**Comment by szaydel** [comment]
@crwilcox, I completely understand. Support is usually the hardest part. As you described there are several factors all of which must be considered. Perhaps once there is enough interest in Julia more broadly, this conversation will make more sense.

**Comment by smortaz** [comment]
Others who would like to have Julia supported please upvote this thread.
That might give us a sense of how many are interested

**Comment by sc0ttwad3** [comment]
Maybe there's a _collaboration_ or _integration_ possibility for the **Microsoft Azure Notebooks** team and the **Julia Computing** team running/supporting/maintaining the Microsoft Azure hosted Julia kernal powered notebooks at **[JuliaBox](https://next.juliabox.com)** already? 

No one better than the creators and developers of Julia, maintaining and supporting the Julia kernel in notebooks and data already ready to be shared and synced with cloud providers and remote git repositories.  Maybe if nothing else inclusion of JuliaBox hosted notebooks and data in Azure Notebooks, Azure ML Studio Notebooks, and elsewhere, might be possible?

![juliabox-01](https://user-images.githubusercontent.com/1682691/32312110-510ebaac-bf72-11e7-91d9-ee7b82f9759a.jpg)

**Comment by sje30** [comment]
Any likely resolution of this before the next academic year?  It would be great to have Julia support.

**Comment by Tokazama** [comment]
Bump

**Comment by datnamer** [comment]
I'm also interested in this!

**Comment by utotch** [comment]
I also request Julia support.

In this time, I have no reason to choose Azure notebook compared to GCP and CoCalc.
But if Azure notebook supports Julia and Haskell, I will use it.

**Comment by kkampf** [comment]
Hi all, thanks for the feedback! We have no specific timelines to share regarding Julia support at this time. I'll update here if we have any news to share! Thanks for using Azure Notebooks

**Comment by HumaMilisic** [comment]
Bump, happy new year!

**Comment by Cardoza2** [comment]
I also request Julia support.

**Comment by lewisl** [comment]
It's not like F# has any meaningful interest outside of Microsoft.

**Comment by akscse** [comment]
Any plans to have Julia onboarded sooner?
