### ISSUE TITLE
Speed reduction in Azure Notebooks

### ISSUE THREAD

**Issue by KeithQuille** [microsoft/AzureNotebooks#400]
Please describe your issue as completely as possible.

I am using Azure Notebooks to teach AI, and at the start of the semester September - November 2017 the speed of the notebooks were impressive, even outperforming my gaming laptop, however, since February or March the speed has dropped significantly, to an extent that the notebooks are slower than a poor performing Laptop, or lab PC. Thus making it unusable in a lab, even for basic ANN's. Can you let me know if this is an intentional action, or not so I can plan my teaching for next academic year.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Speed / Performance 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/kquille/libraries/dal9

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Continuous

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/kquille/libraries/dal9

**Comment by veonua** [comment]
```
import cv2 # computer vision library

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

%matplotlib inline

```

takes 2 minutes to execute. sorry but it is unusable

**Comment by ramkd12** [comment]
Our free compute offering is always contended. However with new features, one can bring a DSVM of higher specs to execute same notebooks. Here is how one can do that : https://docs.microsoft.com/en-us/azure/notebooks/configure-manage-azure-notebooks-projects#compute-tier

**Comment by mtlive** [comment]
I appreciate your free service, but please consider that other companies provide faster services and more resources like GPU, more RAM,... . Even though they are free.
As an example They run a portion of my codes (CPU only) 6 times faster than Azure Notebooks.

**Comment by adideva98** [comment]
I am facing the same issue on an Azure for students subscription. While I can get only one 6 core Tesla K80 as a VM, even general preprocessing takes forever. I am working on the ELMO embeddings and it requires a huge directory of training files for training. As per my data , my code cell has to create a new directory and create about 129235 text files within that. This has taken over 7000 seconds and counting. On a separate platform this process took about 15 seconds.  Any known issues or just slowness of the service?
