### ISSUE TITLE
Upload document to jupyter azure ml not working - library missing

### ISSUE THREAD

**Issue by sunettew1** [microsoft/AzureNotebooks#401]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [1] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When I try and upload a text document and I get to the upload window, I cannot select Library. And when I upload to the ~ one,  it says was uploaded to home/nbuser. How do I access home/nbuser as it says that the directory doesn't exist

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
textfile=open('~/home/nbuser/textfile.txt','r')

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [1] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [1] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
If you open the terminal and check the path, that’s what you should use in
the call. Thx

**Comment by sunettew1** [comment]
How do I open the terminal? I'm new to this

**Comment by sunettew1** [comment]
![libraryissue](https://user-images.githubusercontent.com/40404990/41619452-6d1d8b4a-745a-11e8-845d-a3eef450b87b.JPG)

**Comment by smortaz** [comment]
You are in Jupyter.  Go to your Library view:

![image](https://user-images.githubusercontent.com/742484/41619842-87b716b8-73bc-11e8-9c98-d133d8143b78.png)

**Comment by sunettew1** [comment]
Hi, I'm working in the jupyter azure ml eviroment.
![image](https://user-images.githubusercontent.com/40404990/41619967-4d1aa5a6-745c-11e8-9ddd-f6568be6d66c.png)
Do I need to change to azure notebook?

**Comment by smortaz** [comment]
Ahhh sorry you're in Azure ML Studio -  in the form you said:

[1] https://notebooks.azure.com

hence my confusion.  the path to your file should be:

textfile=open('/home/nbuser/textfile.txt','r')

(no ~)

**Comment by sunettew1** [comment]
Brilliant. Thanks so much.
