### ISSUE TITLE
Import of most scikit-image modules kills kernel

### ISSUE THREAD

**Issue by lcurielramirez** [microsoft/AzureNotebooks#402]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When importing most of the scikit-image modules such as io, exposure, filters the kernel dies and it will not restart or execute. The notebook executes correctly on Jupyter from a local Anaconda install.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://imagefourier-lcurielramirez.notebooks.azure.com/nb/notebooks/Image_Edge.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [X] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
1PM MNT

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://imagefourier-lcurielramirez.notebooks.azure.com/nb/notebooks/Image_Edge.ipynb

**Comment by smortaz** [comment]
Sorry about that.  It looks like that library needs some MKL bits & pieces that are not installed:

![image](https://user-images.githubusercontent.com/742484/41619523-670bdcec-73bb-11e8-9d1b-9770ec210e8c.png)

@dino - do you know why these arent installed (or wrong/old version?)

**Comment by lcurielramirez** [comment]
No idea... but it seems that if I use a Kernel Python 3 in Azure this is fixed.
Too bad I have some things I still want to run in Python 2, but this is a fix.

**Comment by antkmsft** [comment]
We have updated Python 2.7 kernel a while ago, but after the last comment in this thread.
`scikit-image` as well as `skimage.exposure` and `skimage.filters` can now be imported, and kernel doesn't crash.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!
