### ISSUE TITLE
package installation - the terminal gets stuck

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/AzureNotebooks#403]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

pip install shap

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
    [] Terminal

#### What time (please include time zone) did this occur?

~2pm Central Time US June 20, 2018

#### Which Web Browser(s) did you see the error in?
    [] Chrome
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
 
#### What is the path to the notebook file (if relevant) that reproduces the issue? 

https://notebooks.azure.com/denfromufa/libraries/SHAP/tree/notebooks
   

![image](https://user-images.githubusercontent.com/7870949/41680153-33e83b9a-7496-11e8-8c83-766c9b14f196.png)

**Comment by denfromufa** [comment]
Otherwise installation works OK from the notebook interface, just wasn't sure if SHAP would overwrite any notebook components already loaded in memory:

![image](https://user-images.githubusercontent.com/7870949/41680379-eda61fca-7496-11e8-9f4d-1e2f5c363d33.png)

**Comment by smortaz** [comment]
Does it work from the notebook?  The terminal has longevity issues.

**Comment by denfromufa** [comment]
@smortaz yes, shap appears to be working ok from the notebook. but i have not tested the full d3.js interactivity yet.

**Comment by denfromufa** [comment]
Yep, the terminal was really bad idea. I thought it is pre-configured for Anaconda paths, but it is actually using system python!

```
Stored in directory: /home/nbuser/.cache/pip/wheels/98/b0/dd/29e28ff615af3dda4c67cab719dd51357597eabff926976b45
Successfully built shap iml simplegeneric backcall
Installing collected packages: numpy, scipy, parso, jedi, ptyprocess, pexpect, pickleshare, simplegeneric, backcall, wcwidth, prompt-toolkit, pygments, ipython, pytz, pandas, iml, scikit-learn, pyparsing, kiwisolver, cycler, matplotlib, tqdm, shap
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.5/dist-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.5/dist-packages/numpy'
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
nbuser@nbserver:~$
```

**Comment by smortaz** [comment]
Thanks. Hopefully when we update anaconda & jupyter the Terminal longevity issues go away.
