### ISSUE TITLE
Launch localhost for flask app from within notebook environment

### ISSUE THREAD

**Issue by dhsgisc** [microsoft/AzureNotebooks#405]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
How do I launch a localhost window for a flask app from within the notebook environment?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://computingtrytry-gisc.notebooks.azure.com/nb/notebooks/flaskapp.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Singapore time 3 am

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
I don’t think that’s possible currently.
