### ISSUE TITLE
'Internal Server Error' when trying to upload compressed zip files

### ISSUE THREAD

**Issue by majetic2** [microsoft/AzureNotebooks#408]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [yes] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
 I keep getting this error today:  "Error: Internal Server Error" whenever I try to upload a compressed zip file that I downloaded containing raw air data off of the EPA website.  I believe I just successfully did this yesterday when a colleague of mine sent me the first zip file to try out.  I thought Azure would allow these zip files to be uploaded, and I believe the files meet the limit requirements since they are less than 100mb (if I am correct on that number).  I tried uploading them one at a time, and this error keeps popping up.
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1.  Download a zip file from this link:  https://aqs.epa.gov/aqsweb/airdata/download_files.html#Raw
2.  Go to the "New" option on Azure and go to "From computer" to try to upload that zip file from your computer onto the notebook.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [yes] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
tried this for hours, but between 7:30-10:15 p.m. CDT
#### Which Web Browser(s) did you see the error in?
    [yes] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [yes (version 10)] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
N/A

**Comment by smortaz** [comment]
Can you !wget  the file from inside the notebook?

**Comment by majetic2** [comment]
It said "Scheme missing" when I tried it one way, and another time it said "503 Service Unavailable".

**Comment by smortaz** [comment]
Hi - i just did the upload & it worked fine.

While in Jupyter, click on "Data" menu, then "Upload", select destination:

~/library is the permanent one:

![image](https://user-images.githubusercontent.com/742484/42054905-7e123e66-7aca-11e8-83c4-53f720be4a7d.png)

you should then see it:

![image](https://user-images.githubusercontent.com/742484/42054506-69f6afee-7ac9-11e8-8c15-e307f77b85f2.png)

**Comment by majetic2** [comment]
That works great, but now when I go into the terminal to unzip the files (and when I "ls" it does show the zip files in there) it says this:  

Archive:  hourly_42401_2017.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of hourly_42401_2017.zip or
        hourly_42401_2017.zip.zip, and cannot find hourly_42401_2017.zip.ZIP, period.

Why is it saying that the zipfile does not exist or that it cannot be found?

**Comment by smortaz** [comment]
That i dont know.  I would try to zip a very simple small .csv file and upload it and then unzip it.  See if that works.  If it does, then the issue is that w that particular large zip file.
