### ISSUE TITLE
FSharp for Azure Notebooks - ML.Net exception `DllNotFoundExceptionCpuMathNative`

### ISSUE THREAD

**Issue by roguetrainer** [microsoft/AzureNotebooks#409]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
This may not be a bug - just my lack of understanding using F# in Mono on Linux. If so, my apologies. 
Despite adding the paths to the dlls & .so files in `win-x64` & `linux-x64` to the Unix variables `$PATH` & `$LD_LIBRARY_PATH`, we still get an exception: `DllNotFoundExceptionCpuMathNative`.   

AFAIK, the dlls are available up the tree from `~/IfSharp/bin/` _and_ `~/.nuget`? Perhaps it matters which instance is added to the path?

Any advice on how to fix this gratefully received. Thanks.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/ian-buckley/libraries/ml-dotnet/html/1-sentiment-analysis.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [X] F#
    [] Terminal

#### What time (please include time zone) did this occur?
On-going! 19:00 EST.

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/ian-buckley/libraries/ml-dotnet   
https://notebooks.azure.com/ian-buckley/libraries/ml-dotnet/html/1-sentiment-analysis.ipynb   
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

```
...  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <77c9551943624fd18301ba6f78a841e5>:0 
DllNotFoundExceptionCpuMathNative
  at (wrapper managed-to-native) Microsoft.ML.Runtime.Internal.CpuMath.Thunk:SumSqU (single*,int)...
```

**Comment by cgravill** [comment]
@roguetrainer Looks like an interesting library to demo. I haven't tried using it yet.

At the moment, IfSharp is NET461 while Microsoft.ML is netstandard2.0, that's why you're having to manually reference those .net libraries. It might be possible to update the framework target which could make this a lot smoother. 

I have had .net libraries be able to load their respective .so on Azure Notebooks previously. It's a totally different library, and I had to manually download and unzip but I'm not having to do the sort of tricks Isaac did with paths. Might be useful as a reference: https://notebooks.azure.com/cgravill/libraries/z3sample/html/z3sample.ipynb

Can take a more detailed look at getting Microsoft.ML working next week.

By the way, I'll be giving a talk on a related area at Open FSharp with Azure Notebooks/F# so it'd be great to catch up there too if you're going.

**Comment by roguetrainer** [comment]
Colin,
Thanks so much for taking a look. This is not at all urgent.  An evenings and weekends fun project. But _exactly_ the sort of application in which F# IFSharp will shine. And out-shine python IMHO.
I would love to join the conference, but can't really justify it as a work or personal expense.
I really appreciate your hard work on making F# available in Azure notebooks. I can happily switch back and forth between R, python & F# all my working day, always choosing the best & most productive tool for job. Amazing.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by roguetrainer** [comment]
Your link to `z3sample` reminds me of something similar that we tried to demo `Infer.net`, a powerful Microsoft library for doing probabilistic programming & inference. The file `Infer.FSharp.dll` is missing from the Nuget package, we had to copy it over explicitly. I had some help from Tomas Petricek & Eugene Tolmachev. However, it's possible that the preferred solution has changed since then. See:
https://notebooks.azure.com/ian-buckley/libraries/probabilistic-programming/html/Create-paket-script.ipynb

**Comment by cgravill** [comment]
Great, glad you're finding it productive! There are many folks working on the different parts. :-)

On the linked notebook, yes, the original approach isn't advised anymore as it ends up embedding a lot of noise, and version numbers that are fragile as the system is upgraded. You're free to use it but we recommend the compact more portable approach.

```fsharp
#load "Paket.Generated.Refs.fsx"
```

is a link to

```fsharp
#load "paket-files/include-scripts/net45/include.main.group.fsx"
```
so you can leave that out too!

Btw in that example, I saw you're using files off GitHub, there's a new approach in IfSharp being worked on for this: https://github.com/fsprojects/IfSharp/pull/179 which would be great to get your feedback on. That should make Eugene Tolmachev's approach even better.

Back on the original issue. I did some tests and while it's possible to make an F# console app with net461 and reference https://www.nuget.org/packages/Microsoft.ML/ then Paket appears to be more strict. I'll see if we can update IfSharp, tracked here: https://github.com/fsprojects/IfSharp/issues/181

For the issue about loading the native DLL under Paket, @isaacabraham raised an issue here: https://github.com/fsprojects/Paket/issues/3222 which would potentially help.

**Comment by roguetrainer** [comment]
Problems using `DiffSharp` in Azure notebooks -` DllNotFoundException`: `libopenblas`
========================================================

I am getting a `DllNotFoundException` error message for a notebook created from this great code: [http://diffsharp.github.io/DiffSharp/examples-hamiltonianmontecarlo.html] by Atılım Güneş Baydin (@gbaydin).

In this case the missing library is `libopenblas` (`.so` or `.dll`). 

My (work in progress) notebook is: [https://notebooks.azure.com/ian-buckley/libraries/probabilistic-programming/html/FSharp/Fs-DiffSharp-HamiltonianMonteCarlo.ipynb]. 

This might be of interest to @gbaydin & @dsyme who are working on the `DiffSharp` framework. 

No need to respond. I am still trying to get this working, so might yet succeed!
