### ISSUE TITLE
Unable to open the notebook server

### ISSUE THREAD

**Issue by rejoyt** [microsoft/AzureNotebooks#410]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [#####] https://notebooks.azure.com
    [] https://studio.azureml.net

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/run/anon-s7fmva/rejoyt-1?dest=%2Fnotebooks%2FNewNotebook1.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [#####] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [####] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [####] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/run/anon-s7fmva/rejoyt-1?dest=%2Fnotebooks%2FNewNotebook1.ipynb

**Comment by smortaz** [comment]
Hi, can you share the actual library?  ie, notebooks.azure.com/YourId/YourLibraryName  thanks
