### ISSUE TITLE
Do I have to reinstall packages every time I open a Server?

### ISSUE THREAD

**Issue by ConorSpottitt** [microsoft/AzureNotebooks#411]
#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountered
When I shutdown the server and start it up again the next day, I appear to need to install all the packages again that I have used previously. This includes having to install Miniconda and a range of packages using the 'conda install' command. This is a tedious and time-consuming process, is there a way around having to reinstall these packages every time? 

#### Which language/kernel were you using when you experienced this issue?

    [] Terminal

#### What time (please include time zone) did this occur?
Everyday

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by smortaz** [comment]
Hi - there are some 400 pkgs already installed so hopefully what you need can just be imported.  Is there a particular pkg you need?  If it isn't already installed, you do need to !conda or !pip install it.  You can do this two ways:

1. from inside the notebook (!conda install pkg --yes)

2. set it up in the Environment for the Library which does it for you when the container is starting up

Custom docker images are coming in the future where you can put whatever you wish in there.
