### ISSUE TITLE
'Internal Server Error' when trying to save/checkpoint my work

### ISSUE THREAD

**Issue by majetic2** [microsoft/AzureNotebooks#412]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [yes] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I cannot save my work in any of my notebooks due to an 'internal server error' that keeps popping up and stays up for the duration of my sessions (message just to the left of the 'not trusted' icon).
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1)  Go to any library in Azure
2) Select/Open any notebook
3) Try to make any addition/deletion and save that (it will not allow you to nor will it save if you try closing the tab and selecting 'leave'; your revisions to your work will not be saved).

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [yes] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
From Monday around 7:00 p.m. CDT until now (Tuesday, July 3, 4:00 CDT)
#### Which Web Browser(s) did you see the error in?
    [yes] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [yes] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

Just any general notebook file reproduces this issue.  I know there is similar advice on this same issue on here, and I looked into it, but I am still unsure how to actually go about correcting this since it seems to be beyond my control and does not seem like it will self-correct any time soon.

**Comment by gilbertw** [comment]
Does this happen for all your notebooks or just one in particular?

**Comment by majetic2** [comment]
All of my notebooks as far as I can tell when I try multiple notebooks.

**Comment by DinoV** [comment]
Can you do a !cat ~/.nb.log from a Python notebook or go to the terminal and do cat .nb.log and report back if you see any errors in there?

**Comment by majetic2** [comment]
In the terminal it says that there is no such file or directory, but in the notebook I don't believe there is an error.  However, at the bottom of the output in the notebook, it says that the notebook is not trusted.  I'm not sure if that makes a difference, but the error is still persisting.
