### ISSUE TITLE
Unable to Access Notebook or Terminal : "Bad Request - Request Too Long"

### ISSUE THREAD

**Issue by birlaakhand** [Microsoft/AzureNotebooks#413]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I am not able to open Terminal or my Notebook. It is throwing an Error 400.
"
Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.
"

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Sample url I am getting this error for : https://pmanalysis-akhand.notebooks.azure.com/nb/terminals/1

#### Which language/kernel were you using when you experienced this issue?
    [] Terminal

#### What time (please include time zone) did this occur?
9:00 AM Singapore time (GMT+8)

#### Which Web Browser(s) did you see the error in?
    [] Chrome
 Tried it on Chrome in Phone and on IE in PC and the issue is not there in those browser

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
We made some changed to our auth flow this month. We've not heard of any reports of this since then. Please let us know if this is resolved for you now.
