### ISSUE TITLE
'No Space Left on Device' Error

### ISSUE THREAD

**Issue by ConorSpottitt** [microsoft/AzureNotebooks#414]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
  

#### Describe the issue you are encountering

After running a machine learning model through a terminal using a python script which runs successfully through a local ubuntu server, I keep running into the same error.:

 filename = './ImagesLearning_H5PYs/1/test.h5py', file descriptor = 5, errno = 28, error message = 'No space left on device', buf = 0x559bf6d4ef70, total write size = 11010048, bytes this sub-write = 11010048, bytes actually written = 18446744073709551615, offset = 33032192)
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (unable to extend file properly, errno = 14, error message = 'Bad address')
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 193, in h5py._objects.ObjectID.__dealloc__
RuntimeError: Can't decrement id ref count (unable to extend file properly, errno = 14, error message = 'Bad address')
Segmentation fault

It appears that too many bytes are being written, possibly due to the voluminous nature of the datasets being used, being high resolution satellite imagery. I'm not sure if this is the issue or how to resolve it. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://24601-conorspottitt.notebooks.azure.com/nb/terminals/1

Running 'python Main.py' should reproduce the issue

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [x] Terminal

#### What time (please include time zone) did this occur?
GMT - 10am

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Sorry about that. As mentioned in the documentation, there is a 1G gtorage
limit.

If you use /tmp,  it’s both much faster and has a higher limit, but is not
persistef across sessions.

**Comment by ConorSpottitt** [comment]
Thanks for getting back to me. The total storage i'm using is 147 mb. I've tried reducing the data to 5 mb and am still getting the same error message. 

Also, just to clarify, would using /tmp mean creating a folder named tmp and moving the data in that folder for use in the model?

**Comment by wtam** [comment]
I have the same issue but I goto the prj folder....tree/model/log dir and delete some nbserver log to free some space to resolve it
