### ISSUE TITLE
Kernel busy - execution stopped 

### ISSUE THREAD

**Issue by sudiptawipro** [microsoft/AzureNotebooks#416]
Please describe your issue as completely as possible.
Hi,
I have been using free version of ML Studio for quite some time, from today evening I am unable to execute any commands in the notebooks - it's not showing any issue , just not executing anything. I noticed at the top right corner (Python 3 button), it's showing kernel is busy with a grey colored symbol.

I am able to see all my notbooks, datasets etc, able to create new notebook but unable to execute anything.

#### Which site did you access us from?
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Kernel is busy
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/n/jf7xrzrpzrilyq/notebooks/Panda-numpy-addon.ipynb

#### Which language/kernel were you using when you experienced this issue?
Python 3

#### What time (please include time zone) did this occur?
IST 6:30 PM

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

 https://notebooks.azure.com/n/jf7xrzrpzrilyq/notebooks/Panda-numpy-addon.ipynb

**Comment by adriatic13** [comment]
I'm currently (July 6, 2018 2pm EST) experiencing a similar problem using Azure Jupyter Notebooks, using both Python 3.6 and R. Kernels are busy, can't run code, notebooks are frozen. Kernal interrupt and shutdown, file close and halt, etc, do not work. Shutting down and restarting libraries does not work. Checked using both Linux on laptop and Android on tablet, running Firefox.

**Comment by DylanDmitri** [comment]
Probably related to issue #417. We believe we have a fix, looking to deploy soon.

**Comment by RalphTurchiano** [comment]
Just as a heads up, the proposed fix as related to issue [#417] by clearing out the browser cookies did work for me. Thanks 👍
