### ISSUE TITLE
Saving a notebook is "forbidden"

### ISSUE THREAD

**Issue by mrRobot62** [Microsoft/AzureNotebooks#417]
I'm not sure what happens.

In the past I created several notebooks and everything was ok. But since today it's not longer possible.

Every time if I try to save the notebook, I got and orange "bubble" right up in the corner "forbidden". I tried it several time, on several PC (Macbook/Windows) and from different networks (private/office).

Any idea what happens? It's important for me, because I can't go forward.

Thanks and regards
Bernd

Notebook Python 3.6
not possible from Safari, Firefox, IE

*************************************
update (1): I started from scratch again (17:30)
create a new lib
create a notebook python 3.6 => save not possible "forbidden"
create a notebook python 2.7 => save not possible "forbidden"

Open OLD notebooks -> save again => possible

update (2) - 19:03
I check old notebooks in my library. Unfortunately most of them are not longer usable. I can't save them. I got above error.
I NEED HELP :-O

If I open the notebook I get following screen

<img width="681" alt="bildschirmfoto 2018-07-06 um 18 55 48" src="https://user-images.githubusercontent.com/949032/42391415-96311824-814f-11e8-84e7-851e58608757.png">

**Comment by misterhay** [comment]
I'm having the same issue, can't save notebooks or run code in them. Tested two different accounts in Edge and Chrome.

**Comment by DylanDmitri** [comment]
Same thing, in (Edge/Firefox/Chrome), on all python versions. Tried making a new notebook and couldn't run anything.

**Comment by mrRobot62** [comment]
Seems this is a global problem - as I wrote, I did it with my private account and my office account. I can't save & run anything.

Hope MS (or  somebody else ) help us asap

**Comment by smortaz** [comment]
Thanks everyone for the heads up. We will take a look immediately.

**Comment by DylanDmitri** [comment]
`SCRIPT12038: SCRIPT12038: WebSocket Error: Network Error 12038, The host name in the certificate is invalid or does not match`

Seems to be the source of the errors. Also fails to open a jupyter terminal for the same reason.

**Comment by DinoV** [comment]
Thanks for the reports, we're looking into it.

The issue appears to be with a cookie not getting routed down to Jupyter properly which is used to prevent _xsrf attacks.  

We've seen some success with switching browsers.

**Comment by mrRobot62** [comment]
how can I check something - !cat ... log file didn't work on my notebook

**Comment by DinoV** [comment]
Unfortunately it seems like the same cookie check prevents you from opening terminals or executing code as well.  If you have another browser which you've used to access Azure Notebooks in the past and it still has the cookie you might be able to open the library in that browser and be able edit/save/etc...  Otherwise we believe we have a fix and are looking to deploy it now.  It might require clearing your cookies on the domain your notebook server opens in.

**Comment by mrRobot62** [comment]
as I said, on my Mac I tried it without success with Safari, on Win7 with IE & firefox - both with no success.

BTW: This problem occurred since around lunchtime - this morning I created 2 or three notebooks without a problem

**Comment by mrRobot62** [comment]
On my MAC with Chrome - no success

**Comment by DinoV** [comment]
Okay, the fix is rolled out now.  Sorry for the trouble, we were trying to tighten up some 
cookie handling for security, and once you lost the existing cookie you would gain a new cookie
which wasn't working with Jupyter.  We missed this in our testing because we had a previous
version of the cookie which was set for us.

If you're hitting this you'll need to clear the now bad cookie.  There's a few possible ways to do this:
	1) Close all of your browser tabs, it's a session cookie so it should get cleared after all browser instances are shutdown
	2) Open a new in private / incognito tab, and access the site there
	3) In edge:
		Use F12 developer tools, in the tab that's running the Jupyter notebook hit F12, and then:
		click on Network, and choose the "Clear Cookies for domain" button
	   In Chrome:
		At the top right, click More Settings.
		At the bottom, click Advanced.
		Under "Privacy and security," click Content settings.
		Click Cookies.
		Under "All cookies and site data," search for domain name of your notebook server
		To the right of the site, click Remove .
  	   In Firefox:
		Click Firefox button or Tools menu, then click Options.
		Select Privacy panel.
		Set Firefox will: to "Use custom settings for history"
		Click Show Cookies.
		In the search field, type the name of the site whose cookies you want to remove.
		Select the "_xsrf" cookie to remove and click "Remove Cookie"
		Click "Close"

After that go back to the library page and re-open the notebook/library.  

Again, sorry for the difficulty this has caused!

**Comment by mrRobot62** [comment]
and in Safari?

**Comment by DinoV** [comment]
Sorry, I updated the instructions to include Safari as well now.

**Comment by mrRobot62** [comment]
#############################
Success :-)
#############################
Safari -> delete all cookies -> restart notebook -> save -> work -> OK
Chrom -> delete all cookies -> restart notebook -> save -> work -> OK

On Monday (earliest)
Try to do the same under Win7->Firefox & IE

**Thanks to the team for your efforts !**

Nice weekend

**Comment by DinoV** [comment]
Awesome, glad it's working for you now!

**Comment by Shahbaz921** [comment]
just go to the main Jupyter page and click the jupyter icon.
now the jupyter will restart.
now go back to the codes page and save happily.... :-D
