### ISSUE TITLE
ipyvolume not displaying

### ISSUE THREAD

**Issue by amcmorl** [microsoft/AzureNotebooks#418]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Trying to display volume data using ipyvolume. I can install ipyvolume, load the module and run an example, but only get a blank output, no 3-D display. I'm not sure if this is expected to work or not, but would love it to for some data display for a teaching application.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

[link to example notebook - test_ipyvolume.ipynb](https://202fmri-amcmorl-uoa.notebooks.azure.com/nb/notebooks/test_ipyvolume.ipynb)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Between 8:30 pm (NZST) 2018-07-08 and 8:30 am (NZST) 2018-07-09.

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows - 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://202fmri-amcmorl-uoa.notebooks.azure.com/nb/notebooks/test_ipyvolume.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

I get >> cat: .nb.log: No such file or directory

**Comment by smortaz** [comment]
Do any of the basic examples work at all? I haven’t researched this but it
possibly needs a plug-in for the browser?

**Comment by smortaz** [comment]
Also, does it work for you locally?

**Comment by amcmorl** [comment]
> Do any of the basic examples work at all?

Neither of the two examples I've tried on an Azure notebook work for me.

> I haven’t researched this but it possibly needs a plug-in for the browser? 

[This page](https://github.com/maartenbreddels/ipyvolume) describes ipyvolume not needing nbextensions in jupyter notebook > 5.3. 

> ... Also, does it work for you locally?

It works beautifully locally for me. I don't remember having to install any browser extensions to make that happen, and presume, since I'm using the same browser, that problem would be solved in my case anyway. When I tried this in Azure's jupyterlab, I got an error message: 

![image](https://user-images.githubusercontent.com/996394/42423580-9aab6a78-8350-11e8-8fb1-a7bb78c1f7d3.png)

**Comment by smortaz** [comment]
OK thanks. Can you print out the versions of Jupiter lab? I want to see
how far ours is behind yours. Also does it work in regular Jupiter on
Azure?    Jupiter typos by Siri :-)

**Comment by psychemedia** [comment]
I'm getting the same issue - `ipyvolume` not rendering demos on py3.6 on Azure notebooks.

```
require.js:1952 GET https://notebooks.azure.com/Scripts/Jupyter/5.5.0/jupyter-threejs.js?v=5.5.0 net::ERR_ABORTED 404 (Not Found)
GET https://notebooks.azure.com/Scripts/Jupyter/5.5.0/ipyvolume.js?v=5.5.0 net::ERR_ABORTED 404 (Not Found)
```

I wonder if it's the same issue as this? https://github.com/akaihola/jupyter_abc/issues/2

Notebook extensions that need to load assets seem to be broken in Azure notebooks and it seems to be down to extension writers changing their code to suit Azure notebooks rather than Azure side fixing things.

(Memories of all the clunky hacks folk had to do to get web pages to render in Microsoft browsers come flooding back...)
