### ISSUE TITLE
"Page not found" clicking on a link in my libraries

### ISSUE THREAD

**Issue by awf** [microsoft/AzureNotebooks#419]
Please describe your issue as completely as possible.

#### Which site did you access us from?
https://notebooks.azure.com/awfidius/libraries/autodiff

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
![image](https://user-images.githubusercontent.com/128119/42458250-7063311a-8391-11e8-90f6-1d08e47b36d8.png)

Click on "F#..."

![image](https://user-images.githubusercontent.com/128119/42458801-6180493e-8392-11e8-8d0a-d24f0020c5da.png)

Fails on Edge.   [edit: works on Chrome]  [further edit: doesn't work on Chrome, if I'm logged in]

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [x] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

Folks, you need to separate out IE and Edge.

And I _really_ _really_ need not to be half way through filing an issue before I find out Edge is not supported.  I am shaking with rage at the moment.

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by gilbertw** [comment]
The # character in the name is causing trouble.  If you rename the notebooks to not have a #, then it will open.  Sorry for the inconvenience, we will hopefully have this fixed shortly
