### ISSUE TITLE
YouTube API access

### ISSUE THREAD

**Issue by sheyenne** [Microsoft/AzureNotebooks#42]
### Description
Unable to access the YouTubeAPI  - HTTP 403 error

### Repro Steps
Python code:
import requests
print(requests.get('https://www.youtube.com'))

### Usage Scenari
Preparing a user group presentation

### Recommended Metadata
Python3

MaxRetryError: HTTPSConnectionPool(host='www.youtube.com', port=443): Max retries exceeded with url: / (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden',)))

**Comment by smortaz** [comment]
Thanks for filing.  YT is not white listed for network access. 

It's unlikely that we'd open access to YT.  Can you presentation be done in another way?  github is white listed for example.   

Note that you can embed a YT video in you notebook directly via its link and play it - tho not sure if that's your end goal or not.

**Comment by sheyenne** [comment]
Is it possible to white list the googleapis domain?

**Comment by smortaz** [comment]
Generally we open access when there is good justification for it as there's always the possibility of abuse.  can you describe your scenario in more detail as to why access to google apis is needed?   

can you share a link to your use group presentation?   

thx

**Comment by sheyenne** [comment]
My company produces SSW TV (https://www.youtube.com/user/sswtechtalks).  We have a large number of videos that we want to analyse for viewing and like statistics, and compare that against length and topic.

We want to pull the data down into an Azure notebook for analysis and display.

The user group presentation is at https://www.ssw.com.au/ssw/NETUG/Sydney.aspx.  Its the third one down.

**Comment by smortaz** [comment]
got it.   looks like an interesting presentation.

will it suffice if we white list it for a few days before & during your presentation?   we'd close it after that.

also, are we talking AML Studio notebooks or notebooks.azure.com ?

**Comment by crwilcox** [comment]
What are the specific domains to whitelist? For example, we whitelist raw.githubusercontent.com. You mention two sites but I am unsure of the specific (sub-)domain for the properties you would like access to.

**Comment by sheyenne** [comment]
The actual URL would be https://www.googleapis.com/youtube/...  It would be great to have it permanently white-listed to allow you data analyse of YouTube usage, but a temporary white-list would be okay too.

**Comment by DinoV** [comment]
Thanks for the feedback, I've added googleapis.com to the whitelist
