### ISSUE TITLE
Say that Edge is not supported prominently. Or support edge.

### ISSUE THREAD

**Issue by awf** [microsoft/AzureNotebooks#420]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I use Edge, nothing tells me not to.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Visit site using edge.   Search screen for an indication the browser is unsupported.

**Comment by gilbertw** [comment]
Jupyter has some less than optimal behaviors in Edge.  Even with those Edge should be mostly usuable.  Are there bugs which prevent you from using Edge?  If so, please open issues for them so we can look into addressing them properly.
