### ISSUE TITLE
Repository Name is invalid! Expected format [user]/[repository]

### ISSUE THREAD

**Issue by zeroesones** [microsoft/AzureNotebooks#422]
When tried to download a github repository into Azure Notebook, I am receiving the following error "Repository Name is invalid! Expected format [user]/[repository]"

Steps:
1. Click New Library
2. Select From Github
3. Entered the URL and Library Name 
3. Entered the valid Library Id (Eg., Inceptez)
4. When click the button to download, received the error "Repository Name is invalid! Expected format [user]/[repository]"

**Comment by gilbertw** [comment]
Sorry you've had this issue.  Can you share the github repository name that you are trying to create from?
