### ISSUE TITLE
Altair Support in Python3.6 Kernel

### ISSUE THREAD

**Issue by emanueles** [Microsoft/AzureNotebooks#423]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I can't run altair code in a Python 3.6 notebook. I tried a simple code:

```
import altair as alt
import pandas as pd

# for the notebook only (not for JupyterLab) run this command once per session
alt.renderers.enable('notebook')

data = pd.DataFrame({'x': ['A', 'B', 'C', 'D', 'E'],
                     'y': [5, 3, 6, 7, 2]})
alt.Chart(data).mark_bar().encode(
    x='x',
    y='y',
)
```
 and at first, I got an error of vega is not installed. I added this line to the beginning of the code:
!pip install vega

The error does not happen anymore but the bar graph is not displayed either. 
I opened the javascript console and the following error appears:
<img width="1275" alt="screen shot 2018-07-12 at 11 12 25 am" src="https://user-images.githubusercontent.com/2118994/42638632-858aa0e8-85c4-11e8-9f27-ca690f9e8a29.png"> 
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://testpython-emanueles.notebooks.azure.com/nb/notebooks/altair.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Around 11 AM -3
#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://testpython-emanueles.notebooks.azure.com/nb/notebooks/altair.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
It seems the instructions aren't working anymore, no log files found:

cat: nb.log: No such file or directory

**Comment by edesz** [comment]
I am experiencing the exact same issue. It is quite disappointing.

1. My azurenotebooks details:
   ```
   !jupyter notebook --version
   5.0.0
   ```
2. Python version is 3.6

According to [this link from the Altair documentation](https://altair-viz.github.io/user_guide/troubleshooting.html#notebook-vegalite-2-object), Jupyter notebook version 5.3 is required. I don't know if this is the only problem, but it could be part of the problem.

__Question:__
Is it safe to upgrade `jupyter notebook` using
```
$ pip install -U jupyter notebook #or conda update jupyter notebook
```
from the azurenotebooks terminal, like shown [here](https://notebooks.azure.com/help/jupyter-notebooks/terminal), or [step 2. from here](https://blogs.msdn.microsoft.com/uk_faculty_connection/2017/09/20/installing-python-packages-to-azure-notebooks/)?

**Comment by jflam** [comment]
@rachelgshaffer is working on updating jupyter this week. Adding her to this thread.

**Comment by jflam** [comment]
Last time I checked the work in progress it was still not working correctly. We're still investigating. @rachelgshaffer FYI I reactivated the bug last week.

**Comment by rachelgshaffer** [comment]
Hi @gglanzani and @emanueles, good news to share. Altair should be working when the site feature "Unified Frontend for Notebooks" is enabled under your settings (work in progress to get this enabled even without this setting). You will need to run the following two commands
`!pip install vega`
`alt.renderers.enable('notebook')` 

You can reference my project here: https://notebooks.azure.com/rashaf/libraries/altair

Let me know if you are still running into errors. Thanks for using Azure Notebooks!

**Comment by emanueles** [comment]
It works with now, thanks! 
I am closing this ticket.
