### ISSUE TITLE
aznbsetup.sh is not run

### ISSUE THREAD

**Issue by yn-coder** [microsoft/AzureNotebooks#424]
I've create the library from this repo https://github.com/yn-coder/CodingTeacherJupyter, and aznbsetup.sh doesn't run.

`.aznbsetup.log` file is not created.

Lib is https://notebooks.azure.com/yn-coder/libraries/test161661

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

UPDATE

`.aznbsetup.log` file is not created, but I found some information in `.nb.setup.log`

    Running setup script at /home/nbuser/library/aznbsetup.sh at Sat Jul 14 14:12:59 UTC 2018

**Comment by yn-coder** [comment]
Now I see

1. `aznbsetup.sh` is working
2. Doc page https://notebooks.azure.com/help/jupyter-notebooks/server-initialization is incorrect, becouse setup log is in `.nb.setup.log`, not in `aznbsetup.log `

**Comment by smortaz** [comment]
Thanks for the heads up.  We'll update.  thanks!
