### ISSUE TITLE
Should chmod +x work?

### ISSUE THREAD

**Issue by penguian** [microsoft/AzureNotebooks#427]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com

#### Describe the issue you are encountering

At https://glucat-penguian.notebooks.azure.com/nb/terminals/1 I am attempting to build my software using autotools, gmake, C++, etc, and am encountering a fundamental problem. The chmod +x command does not change the mode of shell scripts to make them executable. There is no error message. The command just has no effect. Is this expected behaviour? Why? It prevents ./configure from starting, and even if I run "bash ./configure" it does not complete.
```
nbuser@nbserver:~/library$ which chmod
/bin/chmod
nbuser@nbserver:~/library$ ls -lh configure
-rw-r--r-- 1 nbuser nbuser 270K Jul 25 11:00 configure
nbuser@nbserver:~/library$ chmod 755 configure
nbuser@nbserver:~/library$ ls -lh configure
-rw-r--r-- 1 nbuser nbuser 270K Jul 25 11:00 configure
nbuser@nbserver:~/library$ chmod +x configure
nbuser@nbserver:~/library$ ls -lh configure
-rw-r--r-- 1 nbuser nbuser 270K Jul 25 11:00 configure
nbuser@nbserver:~/library$ id
uid=1000(nbuser) gid=1000(nbuser) groups=1000(nbuser)
```
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

1. Clone https://notebooks.azure.com/penguian/libraries/GluCat
2. Open a terminal and cd to ~/library
3. As per INSTALL, run 
>make -f admin/Makefile.common cvs
4. The file ./configure should be created, but it should be executable and is not.
5. Try changing it to executable.
6. Try changing any other file in ~/library or its subdirectories to executable.
7. Expected result is that the change works. Current result is that it does not work.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [X] Terminal

#### What time (please include time zone) did this occur?

8:22 AM Sao Paulo time

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [X] Ubuntu 16.04
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://glucat-penguian.notebooks.azure.com/nb/terminals/1 
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

Not applicable.

**Comment by ybrnathan** [comment]
I hit the same issue, is there a solution?
