### ISSUE TITLE
How can we share editable notebook without doing clone

### ISSUE THREAD

**Issue by 79rpm** [microsoft/AzureNotebooks#429]
I am currently sharing a notebook with a colleague. We are both working on the same notebook and need to be able to write code separately from each other (we are not in the same office). The sharing is currently doing with ping-pong clone where I need to copy the notebook on my account. If I want to share it so my colleague can edit it, he needs to do a copy of my notebook in his library and so on.

I do not see anything that would allow the edition of the same notebook from two different locations. Please confirm, unless I am missing something.

**Comment by smortaz** [comment]
Hi. Not currently, but proper sharing is in the plans. JupyterLab itself is
also workaround on collaborative editing.  You could also split up into
multiple notebooks and call one from another.
