### ISSUE TITLE
Bash command inside R kernel

### ISSUE THREAD

**Issue by suensummit** [Microsoft/AzureNotebooks#43]
### Description

One could run bash command using `!` pre-fix (e.g, `!ls -al`) in python kernel, but this trick doesn't work inside R kernel.

### Repro Steps

`system("ls -al")`

No response and no error message at all.

### Usage Scenario (e.g. teaching a computing course at university foo)

Preparing a user group hands-on demo and I need to display Chinese character in plotting. I tried to run the commands `!fc-list` and `system("fc-list")` accessing the font family but didn't work.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): R
Occurrence Time: 2017-02-22 19:02 CST (UTC+8)
Web Browser: Chrome Version 56.0.2924.87 (64-bit)

**Comment by smortaz** [comment]
Thanks.  Meanwhile as a workaround you can switch kernel:

eg:

[image: Inline image 1]

After the first cell, do

"Kernel / Change kernel / Python" for the ls -la & then change back to R

**Comment by smortaz** [comment]
Thanks.  Meanwhile as a workaround you can switch kernel:

eg:

![image](https://cloud.githubusercontent.com/assets/742484/23217716/0b2989aa-f8cf-11e6-9887-78f1d5dfb66c.png)


After the first cell, do 

"Kernel / Change kernel / Python" for the ls -la & then change back to R

**Comment by suensummit** [comment]
@smortaz Looks like it's the current solution, haha 😄 Thanks!

Btw, my problem now shifts to that there is no Chinese font in the environment...
<img width="602" alt="screen shot 2017-02-23 at 1 29 36 am" src="https://cloud.githubusercontent.com/assets/5906989/23224651/2d1249c6-f96a-11e6-8964-9d8b69571d31.png">

Is there any possible way to install fonts there?

**Comment by smortaz** [comment]
hmmm... how did you get the chinese font output?

when i do fc-list :lang:zh i dont get anything.

re font - i've filed an issue internally.

**Comment by crwilcox** [comment]
I suggest you reach out to https://github.com/IRkernel/IRkernel and file this as an ask. This is the open source R Kernel provider we use in Azure Notebooks.

**Comment by crwilcox** [comment]
I wanted to clarify. I tried running system('ls') on a different Jupyter instance and it doesn't print anything there either leading me to believe the bug you are reporting is in the IRKernel implementation and you should file this as an issue against their repository.

Thanks!
Chris

**Comment by suensummit** [comment]
Thanks! @crwilcox 

@smortaz I got nothing as well while running `!fc-list :lang=zh`. Actually the Chinese output above was a markdown cell which indicates that the Chinese font was not founded.

**Comment by crwilcox** [comment]
@suensummit, no problem. Also, I found out that you need to run
`system('ls', intern=TRUE)` if you want the output

**Comment by suensummit** [comment]
@crwilcox It works, thanks!

Now I need to open another issue for Chinese font (maybe also other languages did not appears on a clean Ubuntu environment) support, haha 😆
