### ISSUE TITLE
markdown cell with ![alt text](...), to show an image from a file, doesn't work

### ISSUE THREAD

**Issue by mbnshtck** [Microsoft/AzureNotebooks#433]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
showing an image from a file, in markdown cell, doesn't work
~~~~
![alt text](images/picture.jpg "my picture")
~~~~

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1. create in library folder 'images'
2. upload a jpg image, picture.jpg
3. create a markdown cell in  notebook with the following text:
~~~~
![alt text](images/picture.jpg "my picture")
~~~~
4. run cell

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by vasiljevic** [comment]
I hope this issue will be resolved soon since it is a major obstacle for those who need images in markdown cells.

**Comment by jeffreyjhaywood** [comment]
I'm experiencing this issue as well on MacOS. Looking forward to updates.

**Comment by rachelgshaffer** [comment]
Thank you for reporting this issue and for using Azure Notebooks. I'll reply on this thread when there is an ETA for the fix.

**Comment by CarlKCarlK** [comment]
I'm seeing this, too.

**Comment by rachelgshaffer** [comment]
I'm happy to announce that the fix for this issue is deployed in production now. Please let me know if you're still experiencing anything unexpected. Thanks again for your patience and for using Azure Notebooks!

**Comment by CarlKCarlK** [comment]
Rachel,

Thanks for working on this. I’m still not seeing the picture. Here is the notebook. The picture is in the 2nd cell.
https://notebooks.azure.com/carlk/projects/Blog2/html/UnderstandingPandasIndexesEtc.v5.ipynb

Thanks,
Carl

p.s. I also opened a new bug 3 weeks ago about mis-rendered dataframes. I’d love if someone could look at it. I’m hoping that after it is fixed to publish a  guest item in the MSFT Python engineering blog
https://github.com/Microsoft/AzureNotebooks/issues/606



________________________________
