### ISSUE TITLE
"inline script removed for security reasons "

### ISSUE THREAD

**Issue by awf** [microsoft/AzureNotebooks#435]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I see `<inline script removed for security reasons>`.   

![image](https://user-images.githubusercontent.com/128119/43731051-3d26e948-99a5-11e8-8618-09adf6da414b.png)

It would be nice to add to this message a suggested fix, e.g. change settings on browser etc

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/awfidius/libraries/general/html/Robust%20fitting.ipynb

I'm not logged in.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [x] F#
    [] Terminal

#### What time (please include time zone) did this occur?

1820 BST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by MaxVortman** [comment]
I have the same problem, but with XPlot.Plotly in any browser.
