### ISSUE TITLE
How to install fancyimpute library

### ISSUE THREAD

**Issue by chetanambi** [microsoft/AzureNotebooks#437]
Hi,

I am trying to install fancyimpute library from azure notebook (https://notebooks.azure.com) but running into error. Kindly help me install fancyimpute library.  I am using Python 3.6 and access notebook from Chrome browser from Window OS.  

Thanks
Chetan

**Comment by andneilmsft** [comment]
Sorry to read that you are having problems installing this library. What is the error that you are seeing?
