### ISSUE TITLE
Getting Error when trying to Upload CSV to Notebook

### ISSUE THREAD

**Issue by sheilagithub** [Microsoft/AzureNotebooks#440]
When attempting to upload a CSV via the Data->Upload menu item, I receive the following error after the file is uploaded:

Error: {"data":"<!DOCTYPE html>\r\n<html>\r\n <head>\r\n <title>The resource cannot be found.</title>\r\n <meta name=\"viewport\" content=\"width=device-width\" />\r\n <style>\r\n body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;color:red }\r\n H2 { font-family:\"Verdana\";font-weight:normal;font-size:14pt;color:maroon }\r\n pre {font-family:\"Consolas\",\"Lucida Console\",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}\r\n .marker {font-weight: bold; color: black;text-decoration: none;}\r\n .version {color: gray;}\r\n .error {margin-bottom: 10px;}\r\n .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }\r\n @media screen and (max-width: 639px) {\r\n pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }\r\n }\r\n @media screen and (max-width: 479px) {\r\n pre { width: 280px; }\r\n }\r\n </style>\r\n </head>\r\n\r\n <body bgcolor=\"white\">\r\n\r\n <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>\r\n\r\n <h2> <i>The resource cannot be found.</i> </h2></span>\r\n\r\n <font face=\"Arial, Helvetica, Geneva, SunSans-Regular, sans-serif \">\r\n\r\n <b> Description: </b>HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. &nbsp;Please review the following URL and make sure that it is spelled correctly.\r\n <br><br>\r\n\r\n <b> Requested URL: </b>/sheilashahpari/libraries/iotforml/restart<br><br>\r\n\r\n </body>\r\n</html>\r\n","status":404,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/nb/api/nbsvc/files/library/DATA/","data":{},"cache":false,"headers":{"Metadata":"true","Accept":"application/json, text/plain, */*"},"uploadEventHandlers":{}},"statusText":"Not Found","xhrStatus":"complete"}

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
3:16 MST
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://iotforml-sheilashahpari.notebooks.azure.com/nb/notebooks/01-Standardize%20Data.ipynb

**Comment by smortaz** [comment]
Sorry about that.

How large was it?

**Comment by andneilmsft** [comment]
Please reactivate if you have more information: e.g file size.

**Comment by edervishaj** [comment]
What is the file size limit for uploading to a Notebooks VM? Currently I am trying to load a 170MB file and I am getting the following error: 

Error: {"data":"","status":404,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"/j/api/nbsvc/files/library/","data":{},"cache":false,"headers":{"Metadata":"true","Accept":"application/json, text/plain, */*"},"uploadEventHandlers":{}},"statusText":"Not Found","xhrStatus":"complete"}

**Comment by smortaz** [comment]
I believe the limit is 100 MB. You are better off putting your data on
Azure blobs and importing it. If you have a notebook that has lots and lots
of images inside of it, you can strip those off and then upload the
notebook itself.
