### ISSUE TITLE
How can I upload a csv file from my computer into the Python for Azure Notebooks

### ISSUE THREAD

**Issue by amitsharma23** [Microsoft/AzureNotebooks#446]
I am not able to view the data which I uploaded to the notebook. I uploaded via clicking on the Data tab and then selecting the file. After that, it seems like nothing happened and I can not see the data in the cell
Python 3.6 
Chrome
Windows

**Comment by DinoV** [comment]
Here's an example notebook on how you can do this with a couple of different ways:

https://notebooks.azure.com/dino/libraries/readcsv/html/readcsv.ipynb
