### ISSUE TITLE
Issues Cloning Libraries with aznbsetup.sh files, cloned library execution is not consistent with original

### ISSUE THREAD

**Issue by BgRva** [microsoft/AzureNotebooks#447]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I'm trying to create a library with a setup script so that when it are cloned, networkx is upgraded to v2.1 for the conda installation for python 3.6 (current version of networkx is 1.11).  But when this library is cloned and run, it does not provide the same feedback when the notebook server is being setup.  Additionally, if you to not sit and wait long enough.  If you interact with the cloned library to soon, it does not properly update the conda installation to networkx v2.1 and the feedback it displays is misleading and in fact may not upgrade networkx to v2.1 but will use the current version 1.11.

Note, I do not this this is particular to networkx , rather how cloned libraries run the aznbsetup.sh script, but because of this inconsistent behavior I will have to resort to older versions of networkx and other python packages.

Note2:  A library with the setup file (as described below) can be found at [https://notebooks.azure.com/moosie-finnster/libraries/clone-setup-test](https://notebooks.azure.com/moosie-finnster/libraries/clone-setup-test)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1) Create a public library
2) Create a **aznbsetup.sh** with the following content

    `#!/bin/bash`
    `source /home/nbuser/anaconda3_501/bin/activate`
    `conda update networkx -y`
    `source /home/nbuser/anaconda3_501/bin/deactivate`

3) Run the library
You will get an Azure Notebooks Page with the message  "Creating notebook server ..." with an additional dialog captured below:

![image](https://user-images.githubusercontent.com/3044102/44619964-4d77fe80-a85b-11e8-84ac-b66b8b65dffc.png)

note:  This update can take anywhere from 5 to 20 minutes
The Azure Notebooks Page will _eventually_ transition to the Jupyter 'dashboard' page

4) Create a new python 3.6 notebook
5) Enter the following in the top cell
    `import networkx as nx`
    `print(nx.__version__)`

execute the cell and the output is  _2.1_

6) Login to Azure Notebooks with a different account
7) Clone the library created earlier
Examine the cloned library - it will contain the aznbsetup.sh file with the same content
8) Run the cloned library
It opens directly to the Jupyter 'dashboard' page, you **do not** get any Azure Notebook message that it is taking longer than usual to create the notebook server
9) In the Jupter dashboard launch the notebook
The notebook displays, but the kernel indicated is 'filled in' indicating the kernel is busy
Jupyter displays a message 
![image](https://user-images.githubusercontent.com/3044102/44620043-02aab680-a85c-11e8-91ba-95a81fa590b3.png)

Even if the notebook server is already running, if I close the notebook and re-open it, the same message is displayed :

![image](https://user-images.githubusercontent.com/3044102/44620067-71880f80-a85c-11e8-871c-094e7d753b87.png)

The behavior on the cloned library is misleading and, when you are running the notebook for the first time and do not give the server adequate time to set up (I waited 15 min) then it does not upgrade the version of networkx.  Basically, the ability to clone libraries that have required setup is not consistent with how the original library is run and can be misleading and can result in errors if you don't let it sit long enough to update.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Starting about 1000 EST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by BgRva** [comment]
Ok, I kept poking around and found the following:  In the second account - the one from which I cloned library, the profile settings had **Experimental Notebooks** set to _On_ (default behavior BTW).  I changed to off and then tried cloning the library again

![image](https://user-images.githubusercontent.com/3044102/44621159-21ff0f00-a86f-11e8-8144-c87399d37bc0.png)

This time, when I ran the cloned library, the expected Azure Notebooks message was displayed

![image](https://user-images.githubusercontent.com/3044102/44621164-3cd18380-a86f-11e8-87df-10b2400551d3.png)

I still do not believe that the startup behavior when running a cloned library with a setup file and  Experimental Notebooks = On is valid (it is quite misleading), but at least changing this setting appears to go back to the default/expected behavior.

**Comment by andneilmsft** [comment]
The Experimental notebook feature is async by design. If you wait just a little longer your notebook will be ready to use. We've got a backlogged feature to provide status on the progress of async operations. including any setup that you have specified. Apologies for the confusion with this new feature. Thank you for using Azure Notebooks and dogfooding the experimental features.
