### ISSUE TITLE
"please confirm that you're human" - error

### ISSUE THREAD

**Issue by tbendsen** [Microsoft/AzureNotebooks#449]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am giving a course on R based on azure notebooks. After initially having been able to work succesfully, today 5 of my students are met by a dialog saying "please confirm that you're a human", when they try to start a notebook. The problem is that the reCaptcha never appears, so they are effectively blocked out. It dosn't matter if they try to open my cloned notebooks, or a new empty notebook. 
They have tried a lot of different browsers. We have also tried creating a new user, with the same result. When they use my computer it works, so it seems that the problem is connected to a combination of user and computer. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I don't know. It dosn't appear to be notebook-specific.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
2018-08-27 14.00 GMT+2 hours
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
I'mm sorry that  the Captcha is not behaving correctly. We will take a look at this today and get back to you with an update the solution. Thanks for using azure notebooks.



________________________________

**Comment by KieranBrantnerMagee** [comment]
Hey tbendsen,
Sincere apologies for the issue.  I've applied a mitigation, please let me know if you continue to hit the issue.  

Thanks very much both for your patience and for bringing this to our attention, don't hesitate to repoen/email us again if any further issues or questions.
