### ISSUE TITLE
ipynb download unicode problem

### ISSUE THREAD

**Issue by tjwei** [Microsoft/AzureNotebooks#45]
### Description
When download a .ipynb notebook, it is  iso8859-1 encoded, instead of utf-8.

### Reproduce Steps
Make an .ipynb on Azure notebook with non-ascii character (like CJK character) in any cell,
and open it in the jupyter notebook and use the menu-> file->download as->ipynb  
You will see the coding messed up.

### Cause
The python code that jupyter notebook handles file donwloads are in
`notebook/files/handlers.py`
it calls the content manager with this line
```python
model = cm.get(path, type='file')
```
The rest content manager of Azure notebook decodes ipynb files with utf8
```python
            with StringIO(response.content.decode('utf-8')) as f:
                nb = nbformat.read(f, as_version=4)
```
which is correct.
The problem is, it only treats a rest content as ipynb format when
```python
        elif type == ItemType.Notebook or (type is None and path.endswith('.ipynb')):
            model = self._notebook_model(path, modified, created, content=content)
```
which is not the case, because jupyter calls it with `type='file'` when download.
A proposed fix is 
```python
        elif type == ItemType.Notebook or ((type is None or type =='file') and path.endswith('.ipynb')):
            model = self._notebook_model(path, modified, created, content=content)
```

### Usage Scenario (e.g. teaching a computing course at university)
This is a general issue. Download in other format like .py may have the same issue.
Only code are supposed to be saved in the rest content manager,  use 'utf-8' by default seems to be a good idea.

**Comment by crwilcox** [comment]
@tjwei, thank you for the detailed bug report and proposing the solution. I am going to put this on work to do. We will have to validate that this fix works fully, but I suspect it will.

Thanks again. I will respond and close this once it goes live.

**Comment by crwilcox** [comment]
This has been live for some time. I am closing this.
