### ISSUE TITLE
Principles-of-Machine-Learning-Python module 1  IntroductionToMachineLearning.ipynb can't open by Jupyter

### ISSUE THREAD

**Issue by Mashimarowewe** [Microsoft/AzureNotebooks#450]
#### Which site did you access us from?
    [] https://notebooks.azure.com
    

#### Describe the issue you are encountering
Principles-of-Machine-Learning-Python module 1  IntroductionToMachineLearning.ipynb can't open by Jupyter.
It will show "Unreadable Notebook: /home/nbuser/library/Module1/IntroductionToMachineLearning.ipynb NotJSONError('Notebook does not appear to be JSON: u\'{\\n "cells": [\\n {\\n "cell_type": "...',)" error message
#### Which language/kernel were you using when you experienced this issue?

    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
When i clone this from Git hub  https://github.com/CambridgeEngineering/PartIA-Computing-Michaelmas I am able to work with the notebook. Please open the issue again with more information including a link to your clone of this library so i can debug further.

**Comment by Mashimarowewe** [comment]
1.Which site did you access us from?
=>https://notebooks.azure.com/TomChuang/libraries/DAT275x/tree/Module1

2.Which language/kernel were you using when you experienced this issue?
=>Python 3.6

3.What time (please include time zone) did this occur?
=>This issue still happen now. GMT 16:00

4.Which Web Browser(s) did you see the error in?
=>Chrome

5.Which Operating System are you using? Please specify version as well if possible:
=>Windows 10

Thanks a lot
