### ISSUE TITLE
Bad Request - Request Too Long

### ISSUE THREAD

**Issue by kramaswa** [Microsoft/AzureNotebooks#451]
Hi, 
I get the following error when trying to access any of my notebooks: 

"Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long."

My account is 'Kishore6487' on Jupyter Azure Notebooks and a sample URL that I am trying to access is: 
https://dev236x-kishore6487.notebooks.azure.com/j/notebooks/Kishore%27s%20Notebook%205.ipynb

Can you please assist? This is happening for all of the notebooks. 

This is a library that contains the above notebook: 
DEV236x_Introduction_to_Python_Unit_1

Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Appologies for this. Please clear cookies on your machine. Under certain circumstances MS authentication strings can get too long. Thanks for getting in touch and for using Azure Notebooks. Let us know if this doesn't resolve the problem, we'll certainly take another look.

**Comment by kramaswa** [comment]
Thanks, I restarted my machine/browser and that fixed the problem. 

Sent from Mail for Windows 10

**Comment by andneilmsft** [comment]
Glad to hear you're unblocked.
