### ISSUE TITLE
Seaborn 0.9.0 not installed

### ISSUE THREAD

**Issue by JanosVrbata** [microsoft/AzureNotebooks#452]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

the current seaborn package in the notebooks does not know "catplot()"

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

try to call seaborn.catplot()

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/Janos-Vrbata/libraries/17-03-1951

**Comment by antkmsft** [comment]
Sorry for the delayed response! We have updated our Python 3.6 kernel several times since this issue was logged. I just verified that we now have seaborn 0.9.0 pre-installed, and it can `catplot()`.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!

**Comment by knitinsingh** [comment]
Hi, I am still facing this issue using catplot.
