### ISSUE TITLE
I can't to access my Azure Notebooks !! What do I have to do??

### ISSUE THREAD

**Issue by ericsantos27** [Microsoft/AzureNotebooks#453]
When I try to access my account on Azure Notebooks the site stay trying to connect and after someti-me give the message of runtime error as below

"Runtime Error 
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine. 

Details: To enable the details of this specific error message to be viewable on remote machines, please create a <customErrors> tag within a "web.config" configuration file located in the root directory of the current web application. This <customErrors> tag should then have its "mode" attribute set to "Off"."

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [X] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by zap1295** [comment]
Having the same problem here!

**Comment by andneilmsft** [comment]
Appologies. Our engineering team is looking into this. Next update before 9am PST.



________________________________

**Comment by shibbas** [comment]
Our apologies about the interruption. It looks like there is a wider Azure incident in the South Central US region that is causing Notebooks to be offline. The Azure team is looking into it. Status: https://azure.microsoft.com/en-us/status/ 

https://twitter.com/AzureNotebooks/status/1036997654713065472

**Comment by andneilmsft** [comment]
The notebooks site front end is back up, but some functionality is still impaired. We are sharing the latest updates via twitter: https://twitter.com/AzureNotebooks
