### ISSUE TITLE
problem opening my libraries , cant access jupyter

### ISSUE THREAD

**Issue by suckmacode** [Microsoft/AzureNotebooks#454]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [1] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [1] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [1] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by vicente-iii** [comment]
https://notebooks.azure.com
https://notebooks.azure.com/run/Vicente-iii/Dev274x

Error Message: There was an error attempting to create your notebook. Forbidden

Language: Python 3

Time: 12 midnight (Singapore Time)

Web Browser: Chrome

OS: Windows

**Comment by Michal-Mat** [comment]
https://notebooks.azure.com/MichalMatuszczak/libraries/MLPythonCourse

Error Message: Uh-oh, something went wrong..

Language: Python 3.6 

Time: 21:10 (Central European Time)

Web Browser: Chrome

OS: Windows

**Comment by andneilmsft** [comment]
Thanks for reaching out.  There is a Azure incident occurring right now that impacts the notebooks service. The notebooks site front end is back up, but some functionality is still impaired. We are sharing the latest updates via twitter: https://twitter.com/AzureNotebooks
