### ISSUE TITLE
cannot open jupyter notebooks libraries

### ISSUE THREAD

**Issue by menchacj** [Microsoft/AzureNotebooks#455]
Cannot access to jupyter notebooks in Azure to complete course tasks. 

Error code: cd2b4131-6740-4a57-b2f1-723c4b51c180

#### Which site did you access us from?
    [] https://notebooks.azure.com
    

#### Describe the issue you are encountering
stucked
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Thanks for reaching out, there is a wider Azure incident occurring right now. Latest updates on the status of this issue can be followed via our twitter account: https://twitter.com/AzureNotebooks
