### ISSUE TITLE
File not found error while importing .csv in pandas

### ISSUE THREAD

**Issue by Michal-Mat** [microsoft/AzureNotebooks#459]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I have opened a notebook that worked previously and today I am getting file not found error while importing through pandas.read_csv('file.csv'). I know the file is there in the folder and can be opened normally.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Please try reading any csv file in "https://notebooks.azure.com/MichalMatuszczak/libraries/MLPythonCourse/tree/Module2"

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
8:18 PM Central European Time

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://mlpythoncourse-michalmatuszczak.notebooks.azure.com/j/notebooks/Module2/data-exploration-lab-notes.ipynb

**Comment by andneilmsft** [comment]
Is this still reproing for you? We've had some outages this week. Please confirm it still repros and we'll debug.

**Comment by andneilmsft** [comment]
Thanks for checking, can you link to a notebook that has a cell that is trying to do the pandas read. This will help us to scope the repro to the right SDKs/Kernals/APIs.

**Comment by andneilmsft** [comment]
Please share a repro. We'd love to look into this. We'll leave this open another week.
