### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by marco-rossi29** [Microsoft/AzureNotebooks#460]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Running any import with azure is failing

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
````
## Required for Azure Resource Manager
from azure.mgmt.resource.resources import ResourceManagementClient
from azure.mgmt.resource.resources.models import ResourceGroup

## Required for Azure Data Lake Store account management
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-e3c53be59375> in <module>()
      1 ## Required for Azure Resource Manager
----> 2 from azure.mgmt.resource.resources import ResourceManagementClient
      3 from azure.mgmt.resource.resources.models import ResourceGroup
      4 
      5 ## Required for Azure Data Lake Store account management

ModuleNotFoundError: No module named 'azure'
````

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
It's been happening for a few weeks now

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Is this still reproing for you? Azure had data center outages this week. If it still repros we'll take a look. Thanks!

**Comment by marco-rossi29** [comment]
Yes, it is still happening.

Now I'm getting:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-7a7f73617c83> in <module>()
      4 
      5 ## Required for Azure Data Lake Store account management
----> 6 from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient
      7 from azure.mgmt.datalake.store.models import DataLakeStoreAccount
      8 

ModuleNotFoundError: No module named 'azure.mgmt.datalake'
```

**Comment by marco-rossi29** [comment]
Thank you for the quick response. I did install that, and I got another error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-49e9a1c0decc> in <module>()
     21 #from azure.mgmt.datalake.analytics.catalog import DataLakeAnalyticsCatalogManagementClient
     22 
---> 23 from azure.datalake.store.core import AzureDLFileSystem
     24 ## Use these as needed for your application
     25 #import logging, getpass, pprint, uuid, time

ModuleNotFoundError: No module named 'azure.datalake'
```
I that point I just ran ``!pip install azure`` which solved it.

**Comment by marco-rossi29** [comment]
This issue is still happening even after running `!pip install azure` on the same notebook last week!

```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f8a448ec89e7> in <module>()
     21 #from azure.mgmt.datalake.analytics.catalog import DataLakeAnalyticsCatalogManagementClient
     22 
---> 23 from azure.datalake.store.core import AzureDLFileSystem
     24 ## Use these as needed for your application
     25 #import logging, getpass, pprint, uuid, time

ModuleNotFoundError: No module named 'azure.datalake'
```

Why is Azure not found on Azure Notebooks?

**Comment by ramkdmsft** [comment]
Sorry to hear that you are facing this. We are investigating on Azure module not found in the Azure notebook. I am assuming you are still working on Python 3.6 kernel. I tried to repro your scenario.

After explicitly installing _azure_ module (_!pip install azure_), i could not see any error while importing _azure.datalake.store.core_.

In case you have installed _azure_ module last week, your previous terminal might be disconnected by now and you may be now working on completely different terminal on back end. So would request you to reinstall the _azure_ module explicitly and try again.

Please let us know if that is not the case.

**Comment by marco-rossi29** [comment]
By running every time I start the notebook:
`!pip install azure-datalake-store`
the issue is resolved. Please let me know when the issue is resolved.
Thank you!
