### ISSUE TITLE
notebook does not open in Chrome, does not open in IE

### ISSUE THREAD

**Issue by opaline2467** [Microsoft/AzureNotebooks#463]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Library opens, but notebook does not.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/anon-tefasg/libraries/DEV236x

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

9 a.m. ET

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/anon-tefasg/libraries/DEV236x

**Comment by tbendsen** [comment]
I am experiencing extreme instability in general. Half the times I try to open a library or a notebook it dosn't work, half the times in works perfect. And when I succeed in opening a notebook, often i loses connection to the kernel, or something like that. Could it be the same problem?

**Comment by mohitagr18** [comment]
I am experiencing similar issues where libraries would open but opening the notebook either throws a 'Bad Request' or is generating an error saying 'something went wrong...' (error id: b0146259-c463-417a-ade1-938391dfd260)

**Comment by andneilmsft** [comment]
Thanks for getting in touch and apologies for the disruption earlier this week and again today. Azure notebooks is currently experiencing degradation due to Azure Networking issue, likely related to the data center outage earlier this week. We are actively investigating.  Please follow our twitter for updates. https://twitter.com/AzureNotebooks

**Comment by mohitagr18** [comment]
I am facing the same issue again since yesterday. Sometimes its bad request and then other times this error id: 88cf1f14-2021-486c-be80-b6f15d4ee740
