### ISSUE TITLE
Issue with Tensorflow Updating

### ISSUE THREAD

**Issue by c0d1st** [Microsoft/AzureNotebooks#464]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [*] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

- I am working as part of a team.
- We are attempting to develop an NN with Tensorflow.
- We are encountering an error with the NN code.
- Based on [this issue post](https://github.com/kamalkraj/Named-Entity-Recognition-with-Bidirectional-LSTM-CNNs/issues/6) we reviewed what version of Keras and Tensorflow we were using. (Please see the section below.)
- **_We have confirmed the code works using Python on Visual Studio 2017 in Windows 10._**

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Please review the following:
**Initial Keras & Tensorflow versions && Tensorflow upgrade to 1.8.0**
![1](https://user-images.githubusercontent.com/22267141/45257318-45977e80-b372-11e8-8168-356e8df66c9d.PNG)

**Continuation of Installation**
![2](https://user-images.githubusercontent.com/22267141/45257330-5d6f0280-b372-11e8-9796-072d5a45a50d.PNG)

**Finalized Installation && Confirmation via PiP**
![3](https://user-images.githubusercontent.com/22267141/45257336-7bd4fe00-b372-11e8-9763-fb62d4af00e4.PNG)

**Cross Validation with Version Check (Notice the miss-match?)**
![4](https://user-images.githubusercontent.com/22267141/45257337-87282980-b372-11e8-91d5-c846b87b96d8.PNG)

**NN Code Check**
![errorwhenrunningrnn1](https://user-images.githubusercontent.com/22267141/45257342-97d89f80-b372-11e8-87d2-5febed03d01c.PNG)

**NN Code Check Continuation && Error**
![errorwhenrunningrnn2](https://user-images.githubusercontent.com/22267141/45257349-e71ed000-b372-11e8-8d0a-1af63f1e45a8.PNG)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [*] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Current/Ongoing -> Last Attempt 9/7/18 3:00 PM EST

#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [*] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by rachelgshaffer** [comment]
Hi @c0d1st, I tried running the pip install before importing and it reports the correct version - can you try doing the same and let me know if that resolves your issue? Notebook preview: https://notebooks.azure.com/anon-tppjzq/libraries/tensorflow2/html/test2.ipynb

**Comment by c0d1st** [comment]
Hi Rachel,

Thank you for the feedback.  That resolved the package issue.  Thanks!
