### ISSUE TITLE
Kernal is dead: XSRF cookie does not match POST argument

### ISSUE THREAD

**Issue by Xenophule** [Microsoft/AzureNotebooks#465]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Kernal is dead and has been for a week and a half.
It gives the issue: XSRF cookie does not match POST argument

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can 
All of my notebooks.
Here's just one of them:

https://machinelearningudemy-xenophule.notebooks.azure.com/j/notebooks/PART%207.%20NATURAL%20LANGUAGE%20PROCESSING/Section%2036%20-%20Natural%20Language%20Processing%20Algorithms/NLP.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#

#### What time (please include time zone) did this occur?
I don't remember exactly when.

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [] Chromebook

**Comment by andneilmsft** [comment]
i think this is a dupe of https://github.com/Microsoft/AzureNotebooks/issues/448. Please close if so.

**Comment by andneilmsft** [comment]
dupe of 448

**Comment by earlnoli** [comment]
I was able to fix this by doing a change kernel
"Kernel" > "Change Kernel" >  (eg.  change from Python 3.6 to Python 3)

**Comment by acrigney** [comment]
Got this again yesterday and today, the last fix did not work for me, I had to restart my machine last time this happened

**Comment by akuchotrani** [comment]
I tried all the above methods but it didn't work for me.

I closed the browser and logged off.
Opened a new window in incognito mode.
Logged in again 
Tried running the notebook and the kernel ran fine.

**Comment by muhammadnaumanshahid** [comment]
Interrupt the kernel and shut it down. Restart after 10 minutes and it should work fine.

**Comment by briglx** [comment]
Got this today... Tried restarting kernel, tried switching kernel, tried logging out. Nothing works

**Comment by davidefiocco** [comment]
@briglx Try deleting Azure and Azure-related cookies in your browser as well. 
https://github.com/Microsoft/AzureNotebooks/issues/448#issuecomment-473858463

**Comment by RabbitJackTrade** [comment]
This happened to me - again. I'm tired of deleting cookies, restarting, etc. Can't somebody over there just resolve this once and for all?

**Comment by philipbel** [comment]
I am getting this error, too.  This is a showstopper for me.

**Comment by luckymalik** [comment]
Clear the cookies will work fine to you ... Happy Coding :)

**Comment by mr007rin** [comment]
I del all my cookies it works again, it's a fatal bug.

**Comment by MuqadderIqbal** [comment]
Getting this same error today (for the first time). My notebooks were working fine until 12 hours ago but not anymore. Why is this issue marked as Closed??

**Comment by RabbitJackTrade** [comment]
@MuqadderIqbal  - It shouldn't have been closed. It happened so frequently that I finally just had to give up and move somewhere else.

**Comment by davidefiocco** [comment]
@MuqadderIqbal @RabbitJackTrade 
This is a duplicate of https://github.com/microsoft/AzureNotebooks/issues/448, that's why this was closed (see this very thread).

**Comment by bbreweril01** [comment]
I'm tired of deleting cookies, restarting, etc too!. 
this is insanely tedious.

**Comment by jordibartolome** [comment]
Use incognito window

**Comment by duplys** [comment]
This is a really annoying bug in the otherwise nice service/product. Switching the kernel back and forth worked for me the last time.

**Comment by nebevk** [comment]
Happened to me today in Chrome.  
Fixed it with deleting _xsfr cookie inside cookies of my notebook  (click the locket icon next to link  to browse cookies).
After refreshing the page it worked just fine.

**Comment by nikhilsinha** [comment]
Deleting the _xsfr cookie worked for me.
