### ISSUE TITLE
Clooning broken for subdirectories

### ISSUE THREAD

**Issue by berndmeyer** [microsoft/AzureNotebooks#466]
Please describe your issue as completely as possible.

#### Which site did you access us from?
     https://notebooks.azure.com

#### Describe the issue you are encountering

Cloning a library with subdirectories does not seem to work any longer if HTML/markdown links refer to items in subdirectories. In this case, the files in the subdirectories are not found. 

For example, the folloiwing public library works fine on the owners account: 

https://notebooks.azure.com/resolve-algorithmics/libraries/patterns

However, after cloning, images in the notebooks, which are in subdirectories, will not be displayed anymore even though the image subdirectories have been cloned. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

1. Clone the library https://notebooks.azure.com/resolve-algorithmics/libraries/patterns
2. Open the notebooks Application units/Patterns main.ipynb
3. The first tow cells will display broken image links even though the items have been cloned. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
 
#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/resolve-algorithmics/libraries/patterns

**Comment by rachelgshaffer** [comment]
Thanks for letting us know about this issue. We've added it to our bug backlog and we'll update this thread when it gets fixed!
