### ISSUE TITLE
Error on open PNG

### ISSUE THREAD

**Issue by dudustefanello** [microsoft/AzureNotebooks#467]
Please describe your issue as completely as possible.

#### Which site did you access us from?
https://notebooks.azure.com

#### Describe the issue you are encountering
The following error has ocurred on trying to open a png file n a Jupyter Notebook:

    Uh-oh, something went wrong...

    We're sorry, an error has occured while processing your request.

    Please try again or report the issue on GitHub or via e-mail. 

    The error is tracked by id: 81a292d8-acef-46dc-9100-798fe83efff6

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Running a Notebook Jupyter, click to open a file with extension .png. 

#### What time (please include time zone) did this occur?
2018/09/11 00:12 (GMT-3)

#### Which Web Browser(s) did you see the error in?
    [] Other (Vivaldi Browser - Chromium based)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Ubuntu

**Comment by andneilmsft** [comment]
Please could you create a notebook with the PNG that can't be opened and share a link to that notebook here so we can debug on an active repro. Thanks!
