### ISSUE TITLE
Unable to open notebook in folder in edit or lab modes: "Bad Request - Header Field Too Long"

### ISSUE THREAD

**Issue by roguetrainer** [Microsoft/AzureNotebooks#468]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am getting a repeated error message when attempting to open a notebook in edit or lab modes

* Sign in to Azure
* Navigate to https://notebooks.azure.com/ian-buckley/libraries/systemic-risk/tree/CIMDO
* Click on notebook to open it in edit mode: Py-CIMDO.ipynb
* New page opens with URL: 
    https://systemicrisk-ianbuckley.notebooks.azure.com/j/notebooks/CIMDO/Py-CIMDO.ipynb
    https://systemicrisk-ianbuckley.notebooks.azure.com/j/lab/tree/CIMDO/Py-CIMDO.ipynb
* New page contains error:
Bad Request - Header Field Too Long
HTTP Error 400. A request header field is too long.
* Work around is to open in preview mode, then click Run to open URL:
https://systemicrisk-ian-buckley.notebooks.azure.com/nb/notebooks/CIMDO/Py-CIMDO.ipynb
(note dash between first & last name?)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
See above.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
For past few days.

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
See above

**Comment by andneilmsft** [comment]
Sorry that this happened. Please clear cookies and sign back in. This is due to authentication tokens getting too long. We're working with the azure identity teams to understand why this can happen and what we can do about it.
