### ISSUE TITLE
pandas - update to latest version

### ISSUE THREAD

**Issue by pyfann** [Microsoft/AzureNotebooks#478]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
AzureNotebooks is not using latest version of pandas

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
df.drop(columns=[2,4,5]) - this API not available

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
pacific

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by pyfann** [comment]
Thanks!  Exactly what I needed.

**Comment by gbrault** [comment]
When do you update to a version of panda >0.20?

**Comment by gbrault** [comment]
!conda update pandas -y takes days...
