### ISSUE TITLE
Cloned Jupyter notebooks not opening on Azure notebooks

### ISSUE THREAD

**Issue by ashishrao7** [Microsoft/AzureNotebooks#479]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Cloned notebooks of DAT257x from the microsoft azure notebooks library. I am able to navigate through the cloned repo but when I try to open a jupyter notebook, it gives me an error stating "error loading notebook"
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://dat257x-ashishrao.notebooks.azure.com/j/notebooks/LabFiles/Module%202/Ex2.1B%20Round%20Robin.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Calcutta, India time zone

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://dat257x-ashishrao.notebooks.azure.com/j/notebooks/LabFiles/Module%202/Ex2.1B%20Round%20Robin.ipynb

**Comment by andneilmsft** [comment]
Please reopen this issue when you have an updated repro. We are not able to reproduce this.
