### ISSUE TITLE
conda update will update to python 3.7 causing 3.6 kernel notebook server errors

### ISSUE THREAD

**Issue by BgRva** [microsoft/AzureNotebooks#480]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
For the past several weeks we (myself and students) have been running python 3.6 notebooks in libraries for which the library NetworkX was updated from v1.11 to v2.1 using conda update.  Between last week and this week, python 3.7 is now considered and included when running conda update.  This is the exact command I am using:

`!conda update networkx -y`

When this was run last week, the output included the following (from a saved notebook executed Sept 15th 620 PM EST)

```
Downloading and Extracting Packages
python-3.6.5         | 29.4 MB   | ##################################### | 100% 
wheel-0.31.1         | 62 KB     | ##################################### | 100% 
decorator-4.3.0      | 15 KB     | ##################################### | 100% 
sqlite-3.23.1        | 1.5 MB    | ##################################### | 100% 
setuptools-40.2.0    | 556 KB    | ##################################### | 100% 
networkx-2.1         | 1.8 MB    | ##################################### | 100% 
readline-7.0         | 1.1 MB    | ##################################### | 100% 
certifi-2018.8.24    | 140 KB    | ##################################### | 100% 
pip-10.0.1           | 1.8 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

But today, when the same command is executed, the following is the output:

```
Downloading and Extracting Packages
pip-10.0.1           | 1.7 MB    | ##################################### | 100% 
certifi-2018.8.24    | 139 KB    | ##################################### | 100% 
decorator-4.3.0      | 15 KB     | ##################################### | 100% 
networkx-2.1         | 1.8 MB    | ##################################### | 100% 
setuptools-40.2.0    | 554 KB    | ##################################### | 100% 
conda-env-2.6.0      | 2 KB      | ##################################### | 100% 
wheel-0.31.1         | 62 KB     | ##################################### | 100% 
python-3.7.0         | 31.7 MB   | ##################################### | 100% 
sqlite-3.24.0        | 1.8 MB    | ##################################### | 100% 
readline-7.0         | 1.1 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Notice how python is being updated to v3.7?  When this happens the notebooks essentially fail.  For example, after I update networkx with the above command and then I run 

`import networkx as nx` 

I get the following inconsistent and odd behavior such as the following:

![image](https://user-images.githubusercontent.com/3044102/45919533-cb342780-be64-11e8-9baf-9eb9dfb46a77.png)

And python 3.6 notebooks started after this update seem to _always_ have the kernel die.  I have tried using the command 

`!conda update networkx -y --no-update-dependencies` 

but this _still_ resulted in conda updating python to 3.7 (and all dependencies btw).  

The only solution I have found so far is to pin the python version to 3.6.* in the conda environment (/home/nbuser/anaconda3_501) as outlined in the steps below:

1) Start your notebook server
2) Open terminal
3) Run the following command to create the file to pin python to version 3.6.*
`echo 'python 3.6.*' > anaconda3_501/conda-meta/pinned`
4) Now start your notebook and update networkx

 Ref: [conda pinning versions](https://conda.io/docs/user-guide/tasks/manage-pkgs.html#preventing-packages-from-updating-pinning)

Now start a python 3.6 notebook and update networkx with the same command as before:

`!conda update networkx -y`

This leads to the correct loading of v2.1 and python 3.6 notebook behavior prior to conda updating python

![image](https://user-images.githubusercontent.com/3044102/45919543-eef76d80-be64-11e8-8f74-423bb0b298ed.png)

 
While I realize that this is not a bug per-se, nevertheless is could significantly impact anyone who updates a python package with conda that results in an update of the python version relative the the notebook kernels being run.  Perhaps the pinned file should be included in the default conda environment for python 3.6 notebooks.

 #### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Clone this library https://notebooks.azure.com/moosie-finnster/libraries/conda-update-test which contains two notebooks. 

 - conda_update_networkx.ipynb: runs conda update without pinning
 - conda_update_networkx_with_pinned_py_version.ipynb: creates a pinned file, then runs conda update

1) Start the notebook server
2) Run conda_update_networkx.ipynb
3) Restart the notebook server
4) Run conda_update_networkx_with_pinned_py_version.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Sept 22 2018, first noticed about 0900 EST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by garth-wells** [comment]
I'm seeing this issue too. Installing conda packages, e.g. `pygraphviz`, with the Python 3.6 kernel is updating Python to 3.7 which then breaks everything.
