### ISSUE TITLE
 ⁨Run Cell not working on Azure Notebooks

### ISSUE THREAD

**Issue by areejibrahim** [Microsoft/AzureNotebooks#482]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Hello,
I tried every way to solve this problem
I tried to download Jupyter to my laptop and it did work 
but the version on your notebook dose not work 
Please help!

this is gif shows the problem 
https://im.ezgif.com/tmp/ezgif-1-4a487c961c.gif

thank you.
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I think the notebooks need to update the Jupyter system

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/eric/libraries/DEV236x

**Comment by andneilmsft** [comment]
Thanks for contacting us. As is, we can't take action on this issue. Please provide more detailed steps to reproduce the problem and reactivate. The GIF link does not appear to work.
