### ISSUE TITLE
Unable to load Extension since Sunday 9/23/2018

### ISSUE THREAD

**Issue by ahaflash** [Microsoft/AzureNotebooks#483]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by rachelgshaffer** [comment]
As a work around, disable "Experimental Notebooks" feature by editing your settings. We are working to fix a bug that will resolve this issue.
![image](https://user-images.githubusercontent.com/10291901/46159904-4c5d3700-c236-11e8-9e52-a5d50c04f167.png)
