### ISSUE TITLE
Can't open the new ipynb file from new library

### ISSUE THREAD

**Issue by yn-coder** [Microsoft/AzureNotebooks#484]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering

Can't open the new created notebook in browser

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Just create the new empty library, create the new `f.ipynb` file (python 3.6) and try to open in in browser

File doesn't open, just see the redirects to library root

https://notebooks.azure.com/yn-coder/libraries/empty

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? 

https://notebooks.azure.com/yn-coder/libraries/empty

**Comment by andneilmsft** [comment]
Sorry that this is happening. Can you repro this in Chrome or only Firefox?

**Comment by yn-coder** [comment]
I Chrome it's working well.

FireFox 62 for Windows

**Comment by andneilmsft** [comment]
Thanks for the report. We're working on supporting a range of browsers for our V1 General Availability release. We've added this bug to that workstream.  While in Preview, we recommend you use Chrome.

**Comment by yn-coder** [comment]
Few days before it's workied great in FF too.

Something breaks today
