### ISSUE TITLE
Notebook server not responding

### ISSUE THREAD

**Issue by vishnujakhoria** [Microsoft/AzureNotebooks#485]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### What time (please include time zone) did this occur?
IST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
Sorry that you've been experiencing connectivity issues. The site networking metrics (real and synthetic traffic) are looking good from our end. How long has this issue been occurring for? It's possible that your ISP is having trouble maintaining a connection to our servers in the USA. Please reactivate if this issue continues, if you are aware of others experiencing the same problem, or if you can reproduce it from another connection.

**Comment by vishnujakhoria** [comment]
Hi,

I am still getting the same issue. Even tried from different internet connection. Same issue. Please help.

Thanks,
Vishnu

**Comment by andneilmsft** [comment]
Have you tried shutting down your notebooks. This will force a connection to a new container on our back end. 

![image](https://user-images.githubusercontent.com/42391274/46060886-8684e680-c119-11e8-80ce-feab1ad3bc90.png)

**Comment by vishnujakhoria** [comment]
It started working now. Have also tried shutdown earlier but it didn't solved the issue.
Is this issue is caused because I didn't shutdown the notebook server after using it yesterday? Any other user faced this kind of issue earlier?

**Comment by andneilmsft** [comment]
We've not had any other reports of this. I'm sorry that your session got into a bad state, and i'm glad that you are now unblocked. Thanks for using Azure Notebooks. Please let us know if you have any other problems.

**Comment by chribonn** [comment]
Hello,

I am using https://notebooks.azure.com and using a Python unit. The unit is a fork from an edX training (Microsoft developed: Dev274x_Introduction_to_Python_Unit_2).

Frequently the interpreter malfunctions. It is still reactive but pressing the green arrow button does not commence code interpretation. The blue side bar that indicates where the focus is on shifts down.

How can I restart the environment without having to close the browser.

Thanks.
