### ISSUE TITLE
Cannot disable nb extensions in any notebook

### ISSUE THREAD

**Issue by jaskarannagi19** [Microsoft/AzureNotebooks#487]
I enable few nb extension since my extension was not working but now I cannot disable any of the enabled nb extension and my notebook looks haywired with lot of html stuff.

#### Which site did you access us from?
https://notebooks.azure.com
here's the screen shot
![image](https://user-images.githubusercontent.com/39240649/46099753-43904500-c1e5-11e8-9311-2efdc0350645.png)
and the link https://cancerdetectionbydna-jaskarannagi19.notebooks.azure.com/j/notebooks/Cancer.ipynb

#### Describe the issue you are encountering
Cannot disable the nb extension those are enabled once from GUI
#### Which language/kernel were you using when you experienced this issue?
  
  
    Python 3.6 
  

#### What time (please include time zone) did this occur?
All the time IST 
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
  
#### Which Operating System are you using? Please specify version as well if possible:
  
 Ubuntu 16

**Comment by yn-coder** [comment]
I have a reverse situation - can't enable the nb extensions in azure book

**Comment by jaskarannagi19** [comment]
@yn-coder  I tried enabling coding teacher no success to me as well

**Comment by yn-coder** [comment]
Looks like bad day for Azure today. I can't run the empty notebook! #488

**Comment by yn-coder** [comment]
Following the @ahaflash - try to switch off the `Experimental Notebooks` in your Azure-Notebook profile settings. It's make a help for me.

**Comment by jaskarannagi19** [comment]
@yn-coder Life saver done that and Notebook restored
