### ISSUE TITLE
Can't open the notebook

### ISSUE THREAD

**Issue by yn-coder** [Microsoft/AzureNotebooks#488]
Can't open the notebook

#### Which site did you access us from?
    [X] https://notebooks.azure.com

#### Describe the issue you are encountering
Can't open the notebook

Create the empty lib, create the empty notebook - and can't open in in browser

![jupyter notebook - google chrome_2018-09-26_21-32-43](https://user-images.githubusercontent.com/8451944/46101251-23a45580-c1d4-11e8-877c-a706f19aa874.png)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/yn-coder/libraries/empty

#### Which language/kernel were you using when you experienced this issue?
    [X] Python 3.6 

#### What time (please include time zone) did this occur?

Few minutes ego

21:36 MSK

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [X] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
https://notebooks.azure.com/yn-coder/libraries/empty

**Comment by yn-coder** [comment]
For FireFOx situation is #484

**Comment by andneilmsft** [comment]
tracking this issue as #487 as we currently think the root cause is the same
