### ISSUE TITLE
HTML rendering of Markdown URLs (<...>) is broken

### ISSUE THREAD

**Issue by garth-wells** [microsoft/AzureNotebooks#49]
The Markdown `<https://microsoft.com>` should be turned into <https://microsoft.com>, but in the HTML viewer it get messed up.

See <https://notebooks.azure.com/library/azure-notebook-bugs/html/HTML%20render%20bug.ipynb> for example of issue.

**Comment by DinoV** [comment]
I've opened an issue against nbconvert: https://github.com/jupyter/nbconvert/issues/541

**Comment by garth-wells** [comment]
I'm still seeing this problem on the Azure service, for example with `(<abc@abc.com>)`, but locally with `nbconvert` it works fine.
