### ISSUE TITLE
The Kernal seems not working

### ISSUE THREAD

**Issue by isaacgeng** [Microsoft/AzureNotebooks#490]
Please describe your issue as completely as possible.
i try to run my code today and i press ctrl + enter or shift+enter, nothing happens but it moves on. so i added in a block like "print('haha')", it did not run. and i restarted the browser using chrome and it still could not work. by the way, originally i used edge, sigh.
#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
could not run the notebook, no response
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://topjudge-isaacgeng.notebooks.azure.com/j/notebooks/test.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [*] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
GMT+8 13:00 pm---now
#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [*] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [*] Other (Please Specify): windows 10

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://topjudge-isaacgeng.notebooks.azure.com/j/notebooks/test.ipynb

**Comment by andneilmsft** [comment]
not heard back from you on this one. Please reactivate if you can isolate repro steps.
