### ISSUE TITLE
Help link in README.md link to nowhere

### ISSUE THREAD

**Issue by yn-coder** [Microsoft/AzureNotebooks#491]
Help link in README.md link to nowhere

See `https://github.com/Microsoft/AzureNotebooks/blob/master/README.md` file.

`Azure Notebook Help` link to `https://github.com/Microsoft/AzureNotebooks/blob/master/nbhelp@microsoft.com` raise 404.

**Comment by andneilmsft** [comment]
Thanks for reporting. I fixed the mailto: link
