### ISSUE TITLE
How to get the Azure user from Jupyter notebook

### ISSUE THREAD

**Issue by yn-coder** [microsoft/AzureNotebooks#492]
How to get the Azure user from Jupyter notebook?

I can parse the current book url and extract `Microsoft` name from `https://notebooks.azure.com/Microsoft/libraries/pycon2017/html/Plotting.ipynb`, but it's just the profile name - user can select it arbitrary or change.

It's not reliable.

My goal is get the WindowsLive login name to link to our another service with WL openauth.

**Comment by andneilmsft** [comment]
if you import Azure you can use !az commands via the azure SDK to enumerate your azure state.

**Comment by yn-coder** [comment]
> My goal is get the WindowsLive login name to link to our another service with WL openauth.

So commands like `az login` (forced to authorized uzer to authorize again with device code) doesn't resolve it.

I need to get the current authorized user info from jup code

**Comment by andneilmsft** [comment]
I see. We only inject the auth token down into the notebook, nothing of the user's root identity so unfortunately this is not possible at this time.

**Comment by yn-coder** [comment]
Does WL service provide some `Get_User_Public_Profile_by_Token` ? How do you think? Where I can start a research?
