### ISSUE TITLE
Bad Request - Request Too Long HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by wipk** [Microsoft/AzureNotebooks#493]
Please describe your issue as completely as possible.
When trying to access/open from my library a python file I get since 3 days the error:
"Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long."
Deleting cookies did not help

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I am doing a course on math for python for data science by Microsoft. When trying to access/open the ipynb files (including python code) a "bad request error - too long" occurs.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/wipkinger/libraries/Dat256x

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
CET -  since 3 days

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/wipkinger/libraries/Dat256x - all files ending on ipynb

**Comment by andneilmsft** [comment]
A fix for this issue is currently being validated for deployment ASAP.
