### ISSUE TITLE
HTTP Error 400. The size of the request headers is too long.

### ISSUE THREAD

**Issue by sta017** [Microsoft/AzureNotebooks#494]
Please describe your issue as completely as possible.
 I cannot access the chapter files on Module 2. 

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
 I cannot access the chapter files on Module 2.  Shows error. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://a001-anonalaa.notebooks.azure.com/j/notebooks/Module2/VisualizingDataForRegression.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [*] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
18:25 pm CST

#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [*] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://a001-anonalaa.notebooks.azure.com/j/notebooks/Module2/VisualizingDataForRegression.ipynb

**Comment by andneilmsft** [comment]
Please clear cookies and log in again to work around this problem.  We have a fix prepped to address this. It's currently undergoing validation.
