### ISSUE TITLE
dead kernel every time I open a project

### ISSUE THREAD

**Issue by onlyhavethisbecauseineedhelp** [Microsoft/AzureNotebooks#496]
Please describe your issue as completely as possible.
whenever I open my notebook the kernel will not load and I have tried to reconnect and restart the kernel but it won't actually do anything when I click the restart button, this is happening on all of my notebooks and on both chrome and safari across two separate computers
#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
the kernel will not load even when I try to restart it
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
the one it first happened on: https://python1unit1-wilsonmj585.notebooks.azure.com/j/notebooks/40460_Mod03_3.2.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
oct 1 at around 9:30 EST
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) : safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS High Sierra
    [] Ubuntu
    [] Other (Please Specify)

**Comment by jsilverm** [comment]
I am having similar issues.
https://dev274x-jvsnyc.notebooks.azure.com/j/notebooks/Mod2_2-2.1_Intro_Python.ipynb

Python 3, both Chrome and Edge....from a recent Windows 10.

![image](https://user-images.githubusercontent.com/42704112/46436085-0caab980-c726-11e8-8795-79867f8219a4.png)

**Comment by jsilverm** [comment]
It is always a bad thing when it says "unable to contact kernel", right?

**Comment by smortaz** [comment]
Hi - sorry about that.  I just cloned your library and ran some notebooks and they worked ok.

Note that a dead kernel can happen for many many reasons, without even involving Azure Notebooks (google "dead jupyter kernel").   If you can repro this reliably (eg, sign in, start the library, run a notebook (or cell) that triggers the dead kernel), we can diagnose it much more quickly.   

Meanwhile pls sign out/back in and see if it happens again.  Your windows version is unrelated and browser choice is generally not a factor either).  If it does, pls follow up here so we can dig deeper!  

Thanks again!

**Comment by jsilverm** [comment]
It seems to still be happening.  This is pretty important to me, let's do whatever we can to debug this.

**Comment by jsilverm** [comment]
I found out what was going on by pushing in the settings...I had "experimental" selected, but didn't remember whether I had consciously chosen that, passively, or when the choice was made.

**Comment by smortaz** [comment]
Ah yes. Experimental still has a few hiccups, hence the name. We are
definitely working on it. Thanks again!

**Comment by jsilverm** [comment]
Thanks for the relatively quick response, if anything else goes funny I will reach out right here on github.
I actually quite like the Jupyter notebooks format for educational materials.

**Comment by smortaz** [comment]
Thank you for your patience!

**Comment by akalyaraj7** [comment]
> Originally logging out and back in did not solve my problem. However, changing that setting, saving, logging out and back in seems to have solved it, even when I turn experimental mode back on.



> I found out what was going on by pushing in the settings...I had "experimental" selected, but didn't remember whether I had consciously chosen that, passively, or when the choice was made.

Where should i find the "experimental" settings ?

**Comment by kkampf** [comment]
Hi @akalyaraj7 the UI has changed a bit since October, but you can find a couple toggleable settings in under your Profile

![image](https://user-images.githubusercontent.com/16325997/59284685-87b36080-8c21-11e9-8d3c-044f0c917257.png)

Edit Profile Informartion
![image](https://user-images.githubusercontent.com/16325997/59284771-b03b5a80-8c21-11e9-9f30-da62e569d403.png)

Scroll down to bottom "Enable Site Features"
![image](https://user-images.githubusercontent.com/16325997/59284855-d82abe00-8c21-11e9-8de9-3036cb52c45e.png)
