### ISSUE TITLE
"Show me some samples link" broken when open in new tab!

### ISSUE THREAD

**Issue by noahmacca** [Microsoft/AzureNotebooks#50]
### Description
Go to homepage (https://notebooks.azure.com/), ctrl+click "Show me some samples" button to open link in new tab, and it goes to 404 page. It works when you open it in the same tab.

### Repro Steps
See above

### Usage Scenario (e.g. teaching a computing course at university foo)
Exploring the homepage!

**Comment by gilbertw** [comment]
This workflow has changed.  Thanks for the feedback
