### ISSUE TITLE
Jupyter Notebook Kernal Error

### ISSUE THREAD

**Issue by SpencerUrban** [Microsoft/AzureNotebooks#500]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
   

#### Describe the issue you are encountering
I keep receiving this error with the Jupyter Notebooks for the course:

Kernal Error, Failed to Start the Kernal: XSRF cookie does not match POST argument.

I have re-cloned the Notebook from https://notebooks.azure.com/eric/libraries/Dev330x - but this did not work.

-->  Furthermore:  Now I cannot even launch Jupyter Notebooks from my Library!
https://notebooks.azure.com/SpencerUrban/libraries

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/SpencerUrban/libraries/Dev330x

Library is:  https://notebooks.azure.com/SpencerUrban/libraries

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.5
    [] Python 3.6 
  Not sure, but it is one of the Python 3 languages.

#### What time (please include time zone) did this occur?
6:00pm, October 2nd, 2018

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Other (Please Specify)  Chrome or Android:  Whatever a Chromebook would use

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/SpencerUrban/libraries/Dev330x

**Comment by andneilmsft** [comment]
We're still looking into this one. Clearing cookies is the work around for now. Sorry for the inconvenience. Please follow #448 for updates on resolution.

**Comment by SaurabhG-20** [comment]
Hi , I am using azurenotebook for python and machine learning development activity. I am facing weird issue that my kernel is not getting connected and keep ticking for connecting for every 120 second. I am not able to declare single value variable in jupyter note book.
Please help
