### ISSUE TITLE
Downloading notebooks as ipynb generates a utf-8'' prefix to the filename 

### ISSUE THREAD

**Issue by sharatsc** [Microsoft/AzureNotebooks#503]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Downloading notebooks as ipynb generates a utf-8'' prefix to the filename  utf-8''
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
* Open an existing notebook and select downloads as ipynb
* The filename has a utf-8" prefix attached to it after download. 
* This is on a windows chrome client

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Thanks for reporting this bug. This is a known issue that is tracked in our engineering backlog. Thanks for using Azure Notebooks and letting us know about it!
