### ISSUE TITLE
Create txt file... 

### ISSUE THREAD

**Issue by ahmetanildindar** [Microsoft/AzureNotebooks#51]
For some reason, I need to create txt file which is easy in Jupiter's default page; new >> text. But this is removed in Azure's notebook. 

Any suggestion?

**Comment by smortaz** [comment]
As a workaround you can do:

New / Terminal

And that will give you a shell prompt.

Thanks.

**Comment by ahmetanildindar** [comment]
@smortaz,
That is OK but anything else?

**Comment by smortaz** [comment]
Sorry @chris will have to comment.  I recall we had some issues with it &
had to remove it.  That may no longer be true.

You can always escape to shell too:

[image: Inline image 1]

**Comment by crwilcox** [comment]
We support adding text files and the like from our library UI. Under the '+' you can add a blank file, directory, or a notebook. Closing.
