### ISSUE TITLE
Failure to upload 150Mb csv file from computer

### ISSUE THREAD

**Issue by Ittyza** [microsoft/AzureNotebooks#510]
Hi

After creating a new library I attemped, multiple times to upload a 150Mb csv file without success. Within the same library, I was able to upload a smaller csv file.

I would like to know what steps I can take to:
1. Track the upload process of the file
2. Gauge whether the file is in fact uploading or not
3.  Understand the limitations of file uploads

Though I attempted from my PC, I also uploaded the file to google drive:
https://drive.google.com/open?id=19lz615iEZXgZ83bw6LfVqqosCIl3F3dk

Regards

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by poojasaxena** [comment]
Hallo, 
I am having the same problem, did you manage to find a way around to upload the file? I tried uploading from dropbox, but no success :( 

Regards,

**Comment by smortaz** [comment]
It’s probably over the limit.  It’s better to use python to read a file
placed elsewhere like blob storage. There’s a section in help that shows
how to do that.

**Comment by aferdoash** [comment]
Yes, upload of files > 100 MB fails

**Comment by tylerxty** [comment]
Still can't upload files > 100MB
Error message: `Error: {"data":"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-st`
