### ISSUE TITLE
Not able to upload local file in Microsoft Azure Notebook

### ISSUE THREAD

**Issue by poojasaxena** [microsoft/AzureNotebooks#511]
Please describe your issue as completely as possible.

#### Which site did you access us from?
     https://notebooks.azure.com

#### Describe the issue you are encountering
I tried uploading the local dataset file in Microsoft Azure Notebook, but after trying for a while I received an error message saying 'file not found'. I tried this yesterday as well as today couple of times and failed all the times..

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1. Open a new notebook and try uploading a file
2. My notebook used for this case is here: https://notebooks.azure.com/poojasaxena/libraries/klimaviberation

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.5

#### What time (please include time zone) did this occur?
Yesterday as well as today, CET 

#### Which Web Browser(s) did you see the error in?
    [] Chrome
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Ubuntu

**Comment by poojasaxena** [comment]
![image](https://user-images.githubusercontent.com/36233154/47019204-c8241280-d156-11e8-9385-531573a10787.png)

**Comment by AlverezYari** [comment]
We are getting the same error.

**Comment by KieranBrantnerMagee** [comment]
Hey folks,

Sorry for the slow reply.  We unfortunately have a limit on the size of files that can be local uploaded; currently at approximately 100mb.  

While I don't want to make any promises, this number sounds instinctively low to me, and I'm going to raise internally the possibility of lifting this limit. (and regardless making the error more clear.) Will loop back here if any news; in the interim, pulling from GitHub or via wget may serve as admittedly hacky workarounds.

Thanks for your patience, sorry for the issue,
-Kieran
