### ISSUE TITLE
The size of the request headers is too long.

### ISSUE THREAD

**Issue by Alex-H97** [Microsoft/AzureNotebooks#516]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Obtain the error below when accessing ".ipynb" files on the server (but not other files such as ".txt" and ".py").  I have tried changing the names of files to one letter long, but still no use.
The error is:
    "Bad Request - Request Too Long
     HTTP Error 400. The size of the request headers is too long."

![image](https://user-images.githubusercontent.com/41477761/47242780-c7ee7600-d3e7-11e8-81e9-325b1f7c54e0.png)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Don't Work:
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/LinearAlgebra.ipynb
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/Probability.ipynb
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/Statistics.ipynb
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/H.ipynb
Do Work:
 - https://notebooks.azure.com/anon-efenjq/libraries/data-science-from-scratch/html/Statistics.py
 - https://notebooks.azure.com/anon-efenjq/libraries/data-science-from-scratch/html/LinearAlgebra.py
 - https://notebooks.azure.com/anon-efenjq/libraries/data-science-from-scratch/html/Probability.py

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
21:31 BST

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows [10]
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/LinearAlgebra.ipynb
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/Probability.ipynb
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/Statistics.ipynb
 - https://datasciencefromscratch-anonefenjq.notebooks.azure.com/j/notebooks/H.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
Can't access notebooks to find this information, sorry.

**Comment by smortaz** [comment]
Clear your cookies pls and lmk if the issues goes away thx

**Comment by krishnaPerivilli** [comment]
I have same issue , I have undergone. I deleted that Library and created a duplicate library and uploaded the files. Its works for me.

**Comment by smortaz** [comment]
Just clear cookies. No need to delete library. Thx.

**Comment by andneilmsft** [comment]
work around provided. We continue to work with auth team to address this.

**Comment by eric-wieser** [comment]
Clearing cookies results in #530 for me
