### ISSUE TITLE
The IP Address returned by the Python **requests** module shows a private address

### ISSUE THREAD

**Issue by p7th0n** [Microsoft/AzureNotebooks#518]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/davekurman/libraries/check-response

The IP Address returned by the Python **requests** module shows a private address.  When this Jupyter notebook is run elsewhere it returns the IP Address returned by DNS.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
5:30 EDT

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/davekurman/libraries/check-response/html/CheckResponse.ipynb

**Comment by andneilmsft** [comment]
Import socket
 
addr1 = socket.gethostbyname('google.com')
addr2 = socket.gethostbyname('microsoft.com')
 
print(addr1, addr2)

Please debug the user code and let me know if you can get it working.

**Comment by p7th0n** [comment]
The socket module works for the code.

The Jupyter notebook lets users run checks on self-hosted services for debugging.

Thanks.

**Comment by andneilmsft** [comment]
great. have fun!
