### ISSUE TITLE
conda: command not found

### ISSUE THREAD

**Issue by bradcavanagh-ffs** [Microsoft/AzureNotebooks#519]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

At the top of my notebook, I have `!conda install osmnx -y` to install OSMnx. I ran this for the first time today (it ran fine yesterday) and it gave some errors near the end of the installation process (sorry, I didn't copy them out). I re-ran the code, and now I get: `/bin/sh: conda: command not found`

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://osmnxexamples-bradcavanagh.notebooks.azure.com/j/notebooks/notebooks/17-street-network-orientations.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

20:30 US/Pacific

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS 10.13.6
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://osmnxexamples-bradcavanagh.notebooks.azure.com/j/notebooks/notebooks/17-street-network-orientations.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

This returns `cat: .nb.log: No such file or directory`

**Comment by smortaz** [comment]
Does fully shutting down and restarting your 1) kernel and if not 2)
container resolve it?

**Comment by bradcavanagh-ffs** [comment]
Restarting the kernel didn't do it, but it looks like restarting the container did.
