### ISSUE TITLE
Provide a more natural way to link to & share notebooks directly

### ISSUE THREAD

**Issue by smortaz** [Microsoft/AzureNotebooks#52]
Please consider the template below to file your issue. 

### Description

Currently we can share a library which is a collection of notebooks.  but in many cases, users need to link to notebooks directly.  for example a user has a book w many chapters and they need to refer to one another.  

Today you can right click on the notebook in the library view and copy a link which has an odd format and not guessable, eg:

https://notebooks.azure.com/run/smortaz/myLIGO?dest=/notebooks/First_start_here.ipynb

with the introduction of the new libraries and userid's, a more natural form would be something along these lines:

notebooks.azure.com/UserName/Libraries/LibName/Notebook1.ipynb

### Usage Scenario (e.g. teaching a computing course at university foo)

* Cross linking from notebook to notebook, eg in a markdown section.
* sharing notebooks directly

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by mizzao** [comment]
Possibly related: #6

**Comment by crwilcox** [comment]
We have implemented this. You can find files at https://notebooks.azure.com/<USER>/libraries/<LIBRARY>/tree/somefolder/file
