### ISSUE TITLE
I uploaded a file in my Azure Notebook library, but when I am trying to open that file I am getting as Bad Request - Request Too Long HTTP Error 400. The size of the request headers is too long. Please anyone let me know how can I fix it?

### ISSUE THREAD

**Issue by krishnaPerivilli** [Microsoft/AzureNotebooks#521]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Clear cookies & sign back in.  thx.
