### ISSUE TITLE
cannot upload directory structure

### ISSUE THREAD

**Issue by leonbrag** [Microsoft/AzureNotebooks#522]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering

I want upload directory structure that contain nested folders. I am not able to do so. First folder just opens up and I have to selected individual files.

I want to upload entire directory structure

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
help provided over nbhelp email regarding using git hub. Please reactivate or work with us on that email thread for additional help.
