### ISSUE TITLE
Cookie bug

### ISSUE THREAD

**Issue by fsx950223** [Microsoft/AzureNotebooks#527]
Please describe your issue as completely as possible.
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
If I open  AzureNotebooks a long time and I sign up again.I will meet a http 400 error.Because old cookie is not deleted and the new one is added after it
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Thu Nov 01 2018 10:26:46 GMT+0800 (中国标准时间)
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
this is a known issue that we are working through with our authentication partner team. please clear cookies while we continue to identify the right fix.
