### ISSUE TITLE
Data > Choose from Dropbox fails to upload

### ISSUE THREAD

**Issue by kevinr** [microsoft/AzureNotebooks#53]
### Description

When importing a dataset into a running notebook from Dropbox, the files fail to upload to the notebook.

### Repro Steps

In a running notebook, select Data > Choose from Dropbox.  After linking a Dropbox account, select files to upload and confirm.  (Possibly relevant: I am using a business Dropbox account.)

### Result

<img width="713" alt="notebooks-azure-dropbox" src="https://cloud.githubusercontent.com/assets/52371/23392375/22c024ba-fd49-11e6-8e68-6a387623ec30.png">

### Usage Scenario (e.g. teaching a computing course at university foo)

Importing data into a notebook to work with.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python2
Occurrence Time: 2017-02-28T00:00:00-0500
Web Browser: Chrome 56
LibraryID and Notebook Name (if applicable): House prices/Boston housing analysis.ipynb
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

~~~
[I 03:59:07.239 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[I 03:59:07.247 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 03:59:07.271 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 03:59:07.271 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 03:59:07.310 LabApp] Using MathJax: /content/mathjax/MathJax.js
[I 03:59:07.311 NotebookApp] JupyterLab alpha preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 03:59:07.372 NotebookApp] "Notebook Storage implemented by ipnb.azure"
[I 03:59:07.373 NotebookApp] 0 active kernels 
[I 03:59:07.373 NotebookApp] The Jupyter Notebook is running at: http://[all ip addresses on your system]:19044/n/EkuEdfsMpBo/
[I 03:59:07.373 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 04:58:47.024 NotebookApp] Could not open static file ''
[W 04:58:47.026 NotebookApp] 404 GET / (172.17.0.1) 50.47ms referer=None
[I 04:58:48.682 NotebookApp] Writing notebook-signing key to /home/nbuser/.local/share/jupyter/notebook_secret
[W 04:58:48.685 NotebookApp] Notebook Boston housing analysis.ipynb is not trusted
[I 04:58:49.514 NotebookApp] Kernel started: c29c69b0-fc98-4ec8-8d13-c721b5303596
~~~

**Comment by smortaz** [comment]
interesting.  I just tried w a couple of small csv and .xlx files and it seems to work:

![image](https://cloud.githubusercontent.com/assets/742484/23392738/a21b80ea-fd32-11e6-91d2-6f271f2aaf01.png)


ok... i think i figured it out - you can't have an '&' in the file name.  try changing that see if that helps please.  i took the above file that downloaded ok & renamed it, and now it fails:

![image](https://cloud.githubusercontent.com/assets/742484/23392777/e27830f2-fd32-11e6-9b5e-2f19eb81cb8f.png)

**Comment by kevinr** [comment]
Sure enough, removing the & did it.
