### ISSUE TITLE
Feature request: adding other mathematical and scientific languages 

### ISSUE THREAD

**Issue by Foadsf** [microsoft/AzureNotebooks#532]
Hello everyone. I just discovered that our university Microsoft services also offers Azure NoteBooks. This awesome. I love it. It would even be be even better if you guys could also add other mathematical languages out there. I'm gonna list some of them here:

- Julia
- GNU Octave
- SciLab/ScicosLab
- FreeMat
- CERN ROOT-cling plus the new xtensor libraries
- Perl Data Language (PDL)
- GnuPlot
- GNU Data Language (GDL)
- or others: [Cadabra](https://cadabra.science/), [Singular](http://www.singular.uni-kl.de/index.php), [Giac/Xcas](http://www-fourier.ujf-grenoble.fr/~parisse/giac.html), [CoCoA](http://cocoa.dima.unige.it/), [GAP](http://www.gap-system.org/), [Erable/ALGB](https://en.wikipedia.org/wiki/Erable), [Aldor](http://www.aldor.org/), [ASCEND](http://ascend4.org/Main_Page), [bc](https://en.wikipedia.org/wiki/Bc_(programming_language)), [EngLab ](https://sourceforge.net/projects/englab/), [MathPiper ](http://www.mathpiper.org/home), [GSL Shell](http://www.nongnu.org/gsl-shell/), [PARI/GP](http://pari.math.u-bordeaux.fr/), [Calc](http://isthe.com/chongo/tech/comp/calc/), [GEL](https://www.jirka.org/genius.html)

as well as symbolic languages:

- Maxima
- Sage
- Yacas
- PanAxiom ( [Axiom](http://axiom-developer.org/), FriCAS, OpenAxiom )
- or others I have listed [here](https://www.reddit.com/r/coolguides/comments/9irkqd/the_best_completely_free_software_alternatives/e6nu8jg)

There are way many more options out there which I can add here. Adding all into AzureNotebooks can make it way more interesting for scientists and attract many more users. Many if them already have [Jupyter kernels](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) and not much needs to be done. 

#### Which site did you access us from?
    [ x ] https://notebooks.azure.com
    [] https://studio.azureml.net

**Comment by ViralBShah** [comment]
Julia support is being discussed in #4

**Comment by Foadsf** [comment]
@ViralBShah great news, I tweeted it [here](https://twitter.com/fsfarimani/status/1158995376348782592?s=20). It would be awesome to consider other kernels like Octave and Scilab as well.

**Comment by ViralBShah** [comment]
I just meant to say that this issue is a dup and it would be a good idea to discuss it in one place. I do not know of any plans for Julia support in Azure Notebooks - although the Data Science VM does include JuliaPro. 

Apologies for the ambiguity in my message.
