### ISSUE TITLE
Cannot insert image in Jupyter notebook using relative location

### ISSUE THREAD

**Issue by gsimchoni** [Microsoft/AzureNotebooks#534]
Please describe your issue as completely as possible.
This is identical to issue #509 which was for some reason closed by the issuer.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Jupyter notebook, kernel python 3.6, images aren't located and inserted in notebook if location is relative, not even if the image is in the same folder:
Not with markdown (`![](images/data_science_venn.png`)
Not with html tags (`<img src="images/data_science_venn.png">`)

The only insertion which works is by a complete link to somewhere else, e.g. the raw image in a Github repository:
`![](https://github.com/gsimchoni/Intro2DS/blob/master/image.png?raw=true)`

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://intro2ds-gsimchoni.notebooks.azure.com/j/notebooks/class/introduction/test.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
10:30 GMT+2
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://intro2ds-gsimchoni.notebooks.azure.com/j/notebooks/class/introduction/test.ipynb

**Comment by gglanzani** [comment]
Seeing this as well, external URL is the only solution (up to now)

**Comment by gglanzani** [comment]
@gsimchoni Sure, but I can't mix it with markdown :)

**Comment by psychemedia** [comment]
I'm seeing this issue too... Images render using `display(Image())` but not as markdown included images.

**Comment by kayapperson** [comment]
+1 Images render using display(Image()) but not as markdown included images. Failed on both Python 3.0 and 3.6 kernels.

**Comment by rachelgshaffer** [comment]
We are tracking this bug through the issue here: https://github.com/Microsoft/AzureNotebooks/issues/433
Apologies that we do not have support for this right now and I will try to provide an update on the ETA soon. Thank you for using Azure Notebooks!
