### ISSUE TITLE
Notebook won't open the second time

### ISSUE THREAD

**Issue by omri374** [microsoft/AzureNotebooks#537]
Please describe your issue as completely as possible.

---EDIT:
This behavior happens on all browsers, when a notebook is started for the second time (e.g. a day after it was initially opened).

When opening an existing notebook (which was previously accessible), I get an error message saying "Uh-oh, something went wrong..." with this error ID: 89a2337d-e7c0-48b0-af94-3b0fc19b9fa6 
This behavior happens on Firefox and Chrome.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Going from https://notebooks.azure.com/omri-m/libraries/dev288x to:

https://notebooks.azure.com/omri-m/libraries/dev288x/run/notebooks/Lab02%20-%20CNTK_204_Sequence_To_Sequence.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [X] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
09:10 am GMT+2 (Israel Standard Time)

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/omri-m/libraries/dev288x/run/notebooks/Lab02%20-%20CNTK_204_Sequence_To_Sequence.ipynb

**Comment by smortaz** [comment]
Very interesting. Does it  Display or if you completely shut down restart
FF and clear cookies?  Thx

**Comment by omri374** [comment]
It works on a private FF window. Probably a cookie problem

**Comment by omri374** [comment]
Please see updated description. It's a recurring problem across browsers. Starting a private window solves the problem

**Comment by smortaz** [comment]
Thanks for the updated description & repro steps.  We'll take a look!

**Comment by andneilmsft** [comment]
We have a trace on this issue and are prepping the solution, glad that you have a work around for now, we're sorry for the inconvenience.
