### ISSUE TITLE
ipyleaflet Error Displaying Widget

### ISSUE THREAD

**Issue by slipstreamJumper** [microsoft/AzureNotebooks#538]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
When trying to use ipyleaflet anytime a widget is called to display there is an error: "Error Displaying Widget.'

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/amill136/libraries/leaflets/run/lab/tree/10-E-ipyleaflet.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 

#### What time (please include time zone) did this occur?
1710EST 13 November 2018
#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [x] Other - Using Azure notebooks preview which runs on a linux environment.

 
![image](https://user-images.githubusercontent.com/7519228/48378511-df471900-e69e-11e8-9bd7-6cc4bf0e2db5.png)

**Comment by smortaz** [comment]
Does it work if you turn off unified FE?  in Settings:

![image](https://user-images.githubusercontent.com/742484/48378993-7ef8ad00-e687-11e8-9917-e351ef5c881a.png)

**Comment by slipstreamJumper** [comment]
Slight change. The zoom bar shows up (didn't before), but the Map is still not showing.

![image](https://user-images.githubusercontent.com/7519228/48390279-1b926d80-e6cf-11e8-8f66-e492183a4161.png)
