### ISSUE TITLE
Different rendering of markdown in preview vs. rendered markdown in notebook

### ISSUE THREAD

**Issue by nathaniel** [microsoft/AzureNotebooks#539]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
In markdown within my Jupyter notebook, I am trying to write a code snippet that includes LaTeX math mode markup -- single dollar signs at beginning and end -- as part of a tutorial. The code snippet is set off from regular markdown text with single backticks.
Whether I include plain dollar signs or backslash-escaped dollar signs in my code snippet, the snippet renders differently if I:
- view the markdown block as rendered markdown within the (editable) Notbeook
vs.
- view the entire notebook as an outsider sees it, as an un-editable rendered preview.

If I type my code snippet as follows, no backslash to escape the dollar signs:
![clip0](https://user-images.githubusercontent.com/68211/48447045-8cce3100-e760-11e8-901e-fc78167a7c51.PNG)
Then this renders within my (editable) notebook as
![clip0rnb](https://user-images.githubusercontent.com/68211/48447064-99528980-e760-11e8-8b7a-65eeb7cc8a01.PNG)
but appears to an outsider viewing my notebook (as uneditable preview) as
![clip0rpv](https://user-images.githubusercontent.com/68211/48447112-a66f7880-e760-11e8-98c2-8cf94c7f0870.PNG)

If instead I add a backslash to escape each dollar sign, my typed code looks like
![clip1](https://user-images.githubusercontent.com/68211/48447170-c7d06480-e760-11e8-9a3b-3a52ae414800.PNG)
Then this renders within my (editable) notebook as
![clip1rnb](https://user-images.githubusercontent.com/68211/48447173-cbfc8200-e760-11e8-839d-fad2201317db.PNG)
but appears to an outsider viewing my notebook (as uneditable preview) as
![clip1rpv](https://user-images.githubusercontent.com/68211/48447181-cef77280-e760-11e8-872e-e3073c558ba5.PNG)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

All this occurs in my notebook https://notebooks.azure.com/ncunning/libraries/tutorials/html/Intro%20to%20Python%20plotting%20in%20Jupyter%20notebooks.ipynb

#### What time (please include time zone) did this occur?
11/13/2018 at 4pm

#### Which Web Browser(s) did you see the error in?
    [x] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 7

**Comment by rachelgshaffer** [comment]
Thanks for your feedback and for using Azure Notebooks. We are aware of this limitation and when we have an ETA for this feature, we'll let you know.
