### ISSUE TITLE
Ability to select Python Version

### ISSUE THREAD

**Issue by abbazs** [Microsoft/AzureNotebooks#54]
### Description
I need to use Python 3.4. So I use the command !conda install -y python=3.4 and it does install. And it does works. However after a short while or after closing the session and reopening the session python version is reverted back to 3.5, how can I get a session with Python 3.4?

### Repro Steps
Install Python 3.4 by "!conda install -y python=3.4

### Usage Scenario (e.g. teaching a computing course at university foo)
I'm learning to use zipline library and it needs ta-lib which is available in python version 3.4 or below.

**Comment by smortaz** [comment]
Hi, please see the FAQ on the main page.  The notebook environment comes
preinstalled w a few kernels.  but beyond that, whatever you install
(code/data) will be gone after the container is reclaimed.  the only things
that persists are your notebooks currently.  everything else is transient.
