### ISSUE TITLE
require firefox / phantomjs

### ISSUE THREAD

**Issue by Enforcer007** [Microsoft/AzureNotebooks#540]
Please describe your issue as completely as possible.
Unable to run selenium with firefox. I'm interested in running headless browser
Using: https://notebooks.azure.com

#### Describe the issue you are encountering
I'm unable to install firefox or phantomjs as it requires root permissions.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
npm install phantomjs-prebuilt

#### What time (please include time zone) did this occur?
Asia - +5:30

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://marathonphototagging-robotekakhil.notebooks.azure.com/j/notebooks/marathon-photo-tagging/explore.ipynb

**Comment by andneilmsft** [comment]
we not not currently allow root access to our notebook containers. Firefox and phantomjs are usual requirement too. What is your end goal?

**Comment by Enforcer007** [comment]
End goal is to render js based web pages and then extract urls out of the rendered page.

**Comment by andneilmsft** [comment]
While we're considering opening up root for other scenarios, this is not a scenario that we would encourage on the azure notebooks platform. If you want to crawl, please implement a service in azure that can crawl. That service can then save the data you need in azure and you can import that into your notebook execution environment for processing.
