### ISSUE TITLE
Jupyter Never Starts

### ISSUE THREAD

**Issue by LaZeR30** [Microsoft/AzureNotebooks#542]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com

#### Describe the issue you are encountering
Hello, 1) I have Settings turned ON for Run in JupyterLab by default.  If enabled, notebooks will be always opened in JupyterLab.

2) Whenever I'm in my Library > Collections > and click on a Jupyter Notebooks file - example TEMP.ipynb - Jupyter Notebooks never starts.  The same page -  Library > Collections - always opens in a new tab.

3) Do you know how to resolve #2 so JupyterLab auto starts with the Notebook?

4) Is there a way to MANUALLY START Jupyter Notebooks or JupyterLab with the Notebook file (example TEMP.ipynb)?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
See above.  

#### Which language/kernel were you using when you experienced this issue?
    [X] Python 3.6 

#### What time (please include time zone) did this occur?
ALWAYS

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    
#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows 10 PRO
    
#### What is the path to the notebook file (if relevant) that reproduces the issue? 
https://notebooks.azure.com/LaZeR/libraries/Collections

**Comment by smortaz** [comment]
Hi there - I just cloned your library and it seems to work ok for me.  In settings I have:

![image](https://user-images.githubusercontent.com/742484/48588959-1a8b5700-e8ee-11e8-9c8a-93530173ba91.png)

when I click on TEMP it opens in jupyterlab as expected:


![image](https://user-images.githubusercontent.com/742484/48588943-08a9b400-e8ee-11e8-8dfc-7727125fa56b.png)

**Comment by LaZeR30** [comment]
Thanks @ smortaz - I will try - but why do you have the first Setting turned OFF?  Thanks Again!!

**Comment by smortaz** [comment]
NP.  I'm not sure if it's related (I didnt test).  It was left off as I was debugging something else...   LMK if turning in off affects things & we'll open a bug on that.  Cheers.

**Comment by LaZeR30** [comment]
Do you know what's wrong with my Notebook Tuples1.ipynb?  Does this open for you?

**Comment by smortaz** [comment]
Something seems to be corrupted in that file.  How was it created?  Did jupyter crash while editing it?

![image](https://user-images.githubusercontent.com/742484/48589299-cbdebc80-e8ef-11e8-92a0-d6e0af955f82.png)

**Comment by LaZeR30** [comment]
I think it was encapsulated/embedded in HTML - I replaced it.  Thanks Again!!

**Comment by LaZeR30** [comment]
@ smortaz - how do you paste your screenshots in here?

**Comment by smortaz** [comment]
Aha.  I was wondering why it looked odd. 

Cheers.

**Comment by smortaz** [comment]
re screenshot - just ctrl-c / ctrl-v ?

either hit PrtSc for a full screen, or hit alt-PrtSc for a sub window.  or use snipping tool.  then ctrl-v in the github "Write" window.  You can then click the Preview tab to see what it looks like.
