### ISSUE TITLE
Azure is freezing

### ISSUE THREAD

**Issue by Nada-Alameddine** [microsoft/AzureNotebooks#543]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I worked on Azure Notebooks around 15 hrs ago and all was fine. 3 hrs later, I was able to open my notebook but a minute later, the cursor started flickering, Azure and Google Chrome froze.
I restarted my laptop and still had the same issue.
I tried with FireFox, no change.
I went incognito, I cleared the cookies and cache, tried another laptop and still the issue is still persistent. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I will send it in an e-mail

#### Which language/kernel were you using when you experienced this issue?
  
    *[] Python 3.6 
    
#### Which Web Browser(s) did you see the error in?
   * [] Chrome
   * [] Firefox
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
Thanks for getting in touch.  Which page are you viewing when the flickering starts? Please try shutting down the container using the shutdown command bar button at the top of your notebook library list and re running the notebook. This will mitigate if the issue is caused by the Jupyter environment behind the notebook.

**Comment by Nada-Alameddine** [comment]
Thanks for getting back to me so promptly.
I am actually in my Notebook. Everything freezes and I have to close the browser from the task manager.
Here is the link to the Library I was working on:
https://notebooks.azure.com/Nada-Alameddine/libraries/Azure-issue
Regards,
Nada


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by Nada-Alameddine** [comment]
I just tried now to work on my Notebook and it looks to be working again.
Thanks a million

**Comment by Nada-Alameddine** [comment]
Sorry, got the same thing again :-(

**Comment by andneilmsft** [comment]
Can you try from another machine? 

We will need to get a performance trace from developer tools feature in chrome. If you are able to do this, please save the profile and share with nbhelp@microsoft.com. Please review the contents of the file to ensure you are happy sharing the content of it with us. 

![image](https://user-images.githubusercontent.com/42391274/48657528-db8cfc80-e9e6-11e8-940c-7df110075322.png)

**Comment by Nada-Alameddine** [comment]
Yesterday, I did.
I will try again now.


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by Nada-Alameddine** [comment]
How do I get the performance trace ?


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by Nada-Alameddine** [comment]
I tried from another machine. It still freezes.
I asked a colleague to check his account, he had no issues at all.




Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by Nada-Alameddine** [comment]
Dear Andrew,
Here are the comments on your e-mail:

  *   This happens when viewing the content of the notebook . it actually crashes after I start working on it for a minute or two.
  *   The issue only happens for notebooks in your library. Exactly, I had 25 students today in class who worked on their account with no issues. I did not share with them the library. They opened their own. I also asked another teacher to work on his account and he had no issues.
  *   The issue can be reproduced on at least two machines when you sign in there. On another machine and on any browser.
  *   The issue cannot be reproduced by your college using clones of your libraries. I did not try it. I can ask a colleague to try it out and let you know.
I have the library set as private as it was part of a test I was preparing for students. I will set it as public at the end of the day here. Can you please let me know when you clone it so that I set it as private after that.
What do you mean shutting by shutting down the containers?
Regards,
Nada


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by Nada-Alameddine** [comment]
Dear Andrew,
I just made the library public. I will have to set it back to private the soonest possible.
Please let me know once you clone it.
Thanks and regards,
Nada



Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.


From: Nada Alameddine(Adw)
Sent: Monday, November 19, 2018 11:31 AM
To: 'Microsoft/AzureNotebooks' <reply@reply.github.com>
Cc: Nada Alameddine(Adw) <nalameddine1@hct.ac.ae>; Nafeth Hamdi Al Hashlamoun <nhamdi@hct.ac.ae>
Subject: RE: [Microsoft/AzureNotebooks] Azure is freezing (#543)

Dear Andrew,
Here are the comments on your e-mail:

  *   This happens when viewing the content of the notebook . it actually crashes after I start working on it for a minute or two.
  *   The issue only happens for notebooks in your library. Exactly, I had 25 students today in class who worked on their account with no issues. I did not share with them the library. They opened their own. I also asked another teacher to work on his account and he had no issues.
  *   The issue can be reproduced on at least two machines when you sign in there. On another machine and on any browser.
  *   The issue cannot be reproduced by your college using clones of your libraries. I did not try it. I can ask a colleague to try it out and let you know.
I have the library set as private as it was part of a test I was preparing for students. I will set it as public at the end of the day here. Can you please let me know when you clone it so that I set it as private after that.
What do you mean shutting by shutting down the containers?
Regards,
Nada


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by andneilmsft** [comment]
looks like you took the library down again before i could access it. if it's just one notebook, please email it to nbhelp@microsoft.com

**Comment by Nada-Alameddine** [comment]
I will put it back now


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by Nada-Alameddine** [comment]
Done


Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-Tolerence.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.

**Comment by andneilmsft** [comment]
We were able to reproduce this problem. We are now investigating a fix. The problem happens when you click on the line ending character ¶. While we work on a fix, please avoid clicking on that character.

**Comment by Nada-Alameddine** [comment]
Thanks Andrew



Nada Alameddine(Adw)
Instructor - GARD(Foundations)
Foundations - System Wide

ندى علم الدين

مدرس - المتطلبات الأكاديمية العامة ( البرنامج التأسيسي)

كلية أبو ظبي للطالبات



[Main logo]

Direct.: +9712 206 2392
Email: nalameddine1@hct.ac.ae<mailto:nalameddine1@hct.ac.ae>
P.O.Box: 41012, Abu Dhabi, United Arab Emirates

[Ribbon]



www.hct.ac.ae<http://www.hct.ac.ae>

[Facebook]<https://www.facebook.com/hctuae>

[Twitter]<https://twitter.com/HCT_UAE>

[Instagram]<https://www.instagram.com/HCT_UAE/>

[YouTube]<https://www.youtube.com/user/hctuae>




[https://cdn.hct.ac.ae/Images/Signature/Email-Banner-30thAnniversary.png]

[Enviromental] Please consider the environment before printing this email

This Email and any attachments may contain HCT confidential and privileged information.If you are not the intended recipient, please notify the sender immediately by return email, delete this email and destroy any copies. Any dissemination or use of this information by a person other than the intended recipient is unauthorized and may be illegal. Unless otherwise stated, opinions expressed in this email are those of the author and are not endorsed by the author's employer.
