### ISSUE TITLE
Some nbextensions don't load

### ISSUE THREAD

**Issue by jfbercher** [microsoft/AzureNotebooks#544]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Jupyter\_contrib\_nbextensions are installed by default. That is fine. One can enable extensions using Edit/nbextensions config menu entry or File/open and the nbextensions tab. However, some extensions do not work at all or incompletely. For example, the `LaTeX environments for Jupyter` or `Variable inspector`. I am a heavy user of these extensions (I am the author of both these nbextensions and one of the maintainers at [Jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) )

- For the  `LaTeX environments for Jupyter`, the extension is not loaded at all. The console complains about loading the `nbextensions/latex_envs/latex_envs.js` file with a 404 error (file not found); though the file is still present in `/usr/local/share/jupyter/nbextensions/latex_envs` as it should. I can also mention that the `README.md` that shoud be displayed in the nbextension config tab for is also reported as missing. 
- For the `variable inspector` nbextension, it loads when enabled, the icon in the toolbar appear, but fails to work because a support file `var_list.py` (or `var_list.r`) are reported as missing (though they are in the directory). 
- It is possible to display the content of files in nbextensions via the server url, like eg `https://testy-jfbercher.notebooks.azure.com/j/nbextensions/varInspector/main.js` which appear, however `https://testy-jfbercher.notebooks.azure.com/j/nbextensions/varInspector/var_list.py` is reported as missing. Any file related to the `latex_envs` extension do not load.
    - A first idea is that for some reason, filenames with an underscore are/cannot be loaded, but some other extensions with underscores in filenames seems to work properly

**Workaround** Disabling the "Unified Frontend for Notebooks" in the profile leads to working extensions, with the drawback that settings are not persisted between sessions (and notebooks are shutdown in case of inactivity). In such case, the content of files is accessible eg in `https://testy-jfbercher.notebooks.azure.com/nb/nbextensions/latex_envs/latex_envs.js` and they are correctly loaded. 

Hence, it seems that the issue is related to the construction of URL or to the mounting of the nbextensions directory when the "unified frontend" is checked. 

As an aside, installing nbextensions in user mode (`jupyter contrib nbextension install`) also seems to not work: nbextensions located in the user directory `.local/share/jupyter/nbextensions` are not mounted in the server. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Described in the issue. Just enable the extension, look at the log in the js console; for the varInspector, press the button in the toolbar and look in js console. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [x] Other (Please Specify) debian

**Comment by Bregor-Mar-Rian** [comment]
The workaroud with disabling "Unified Frontend for Notebooks" is rather painful.
It would be great to have this issue fixed!
