### ISSUE TITLE
Customizing Azure Notebooks for my class

### ISSUE THREAD

**Issue by vanand74** [Microsoft/AzureNotebooks#547]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
This is a feature request. I will teach an introductory data science course in Fall 2019 and would like to use Azure Notebooks in my course.  It would help if I could customize the service as follows:
* I would like to be able to dedicate more resources (CPU, RAM, and storage) to each student's library. I am willing to pay for this. 
 * I would like to set up course libraries that are visible to my students but not to the public. 
 * Finally, I would like to have a set of predefined libraries created in my students' accounts (i.e. one for each unit of the course), and would like permission to view students' libraries. That way I can easily help them with their assignments.

FYI, faculty and students from my university are currently able to log in to Azure Notebooks with our university Net ID. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
N/A

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
2008-11-19 21:57:00 CDT

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by smortaz** [comment]
Hi there!  These features are quite reasonable & have been on the backlog for a while.  The good news is that they are getting closer to release.  Please stay tuned.  If all goes well, it should be ready well before your classes start.  Shoot an email to nbhelp@microsoft.com if you'd like to kick the tires early!

**Comment by vanand74** [comment]
Thanks for the speedy reply. I will email nbhelp@microsoft.com<mailto:nbhelp@microsoft.com> and see if I can participate in a preview or insider release.

Vic

**Comment by andneilmsft** [comment]
Thanks for sending us mail. I'll close this issue and we'll reply to your email soon.

**Comment by vanand74** [comment]
Sounds good. Currently, another instructor runs a Jupyter server for his course on AWS. His infrastructure setup seems unnecessarily complicated to me. Azure Notebooks is appealing because it’s simpler, with a better interface, and it’s something the students can continue to use after they graduate.

Vic
