### ISSUE TITLE
Ability to download files stored from python notebook

### ISSUE THREAD

**Issue by soboleva-daria** [Microsoft/AzureNotebooks#55]
Please consider the template below to file your issue. 

### Description
Hi everyone. I have a problem downloading from Azure Storage to my local machine files stored inside a  python notebook. Could you tell me the right way i should do it?

**Comment by smortaz** [comment]
Not quite sure I understood the question...

If you want to download a notebook:

File / Save As

If you want to download data from your session, try curl and transfer.sh

!curl --upload-file ./MyPlot.pdf https://transfer.sh/MyPlot.pdf

Better support is coming.

If you've written data to Azure storage you can use the Python Azure sdk or
one of the various utilities.

**Comment by soboleva-daria** [comment]
Thanks, it works:)
