### ISSUE TITLE
Unable to open any notebook. Is the Server down?

### ISSUE THREAD

**Issue by Dreambubble** [Microsoft/AzureNotebooks#552]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by Dreambubble** [comment]
https://notebooks.azure.com

Unable to open any notebook.

**Comment by smortaz** [comment]
Works fine for me.  Make sure your library hasnt gotten into a funky state.  Shut it down & restart:

![image](https://user-images.githubusercontent.com/742484/48916375-ec9a9b00-ee36-11e8-9471-4e4982820ede.png)

Find your library (ie container), click the Shutdown button in the command list.  Then click on a notebook again to get a fresh container.

**Comment by smortaz** [comment]
Ok, sorry about that.  If you can repro the issue, pls open another bug on that as it shouldnt happen.  thx.

**Comment by Dreambubble** [comment]
Will do. Thanks.
