### ISSUE TITLE
F# table format for FsLab Deedle frame output

### ISSUE THREAD

**Issue by roguetrainer** [microsoft/AzureNotebooks#553]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Perhaps this is expected behaviour, or else an issue with IfSharp, not Azure Notebooks, but we are unable to get  Deedle (/FsLab) data-frame output cells to "pretty print" into table format. Should that feature be available currently? If not, are there any work-arounds to get it? Thanks for any advice :).

Relevant links for others reading this are:
https://github.com/fsprojects/IfSharp
http://bluemountaincapital.github.io/Deedle/
https://fslab.org/
https://gist.github.com/mndrake/11223650
https://github.com/fsprojects/IfSharp/issues/10

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/ian-buckley/libraries/introduction-to-fsharp/html/Fs-Deedle-output-format.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [X] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/ian-buckley/libraries/introduction-to-fsharp/html/Fs-Deedle-output-format.ipynb

**Comment by cgravill** [comment]
Deedle needs a bit more effort to map onto the required output in Jupyter Notebooks. To make it look good you'll likely want to map to HTML tables. Did you try the approach on here https://github.com/fsprojects/IfSharp/issues/146#issuecomment-428968205 ?

If enough people find it useful, then adding Deedle/FSLab formatting as a helper script on the IfSharp project itself would make sense.

**Comment by roguetrainer** [comment]
@cgravill - thanks for the valuable advice. I confess that I had forgotten about https://github.com/fsprojects/IfSharp/issues/146#issuecomment-428968205. I will try that now. Thanks for reminding me.
