### ISSUE TITLE
F# Chrome hangs when URL has sub-heading suffix

### ISSUE THREAD

**Issue by roguetrainer** [microsoft/AzureNotebooks#555]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
We are using F# Azure Notebooks. Often, when we click on a heading, the heading name is appended to the notebook URL (see screenshot), & Chrome hangs. We have to kill chrome from the Task Manager, & restart it.

I am using the Collapsible Headings nbextension, which may be relevant?

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
All notebooks. 

![image](https://user-images.githubusercontent.com/5108342/48958783-6910a500-ef2f-11e8-98a3-5ac034d0ef16.png)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [X] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Thanks for reporting this, we can reproduce it and we will work to address this in a upcoming deployment.

**Comment by antkmsft** [comment]
We have deployed the fix for this issue a while ago. Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!
