### ISSUE TITLE
Cell numbers are duplicated when rerunning cell.

### ISSUE THREAD

**Issue by rcanand** [Microsoft/AzureNotebooks#557]
Please describe your issue as completely as possible.

#### Which site did you access us from?
https://notebooks.azure.com

#### Describe the issue you are encountering
Rerunning a cell reassigns existing cell number to new cell. A duplicate cell number is created.
 
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1. Open a notebook in Azure notebooks with two valid cells, second one should take a longish time to run.
2. Execute first cell. Note that the cell gets assigned number 1.
3. Execute second cell. Stop execution in the middle.
4. Rerun second cell to completion. Second cell gets number 1 assigned again.

Expected: second cell should have number 2 assigned.

#### Which language/kernel were you using when you experienced this issue?
Python 3.6 

#### What time (please include time zone) did this occur?
(Roughly) 8:30 am PST Nov 26 2018

#### Which Web Browser(s) did you see the error in?
Chrome

#### Which Operating System are you using? Please specify version as well if possible:
MacOS

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
Unable to find log files (the listing under the library folder shows that some files are hidden. Don't know how to access them, if the logs are there).

**Comment by andneilmsft** [comment]
Thanks for reporting. I just tried this in a notebook with two cells and the execution count incremented correctly. Can you still reproduce this? Could your kernel have died between the two cell executions? Finally, under your profile do you have unified front end enabled, or disabled?

**Comment by andneilmsft** [comment]
closing this as i am unable to repro, if you can reliably reproduce this issue please reactivate.

**Comment by rcanand** [comment]
I got this issue intermittently before, twice. Could not repro it since.
Will post here if it happens again.

**Comment by andneilmsft** [comment]
Please do!
