### ISSUE TITLE
problem when trying to run a notebook

### ISSUE THREAD

**Issue by sbassi** [microsoft/AzureNotebooks#559]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

When in a notebook (like https://notebooks.azure.com/py4bio/libraries/py3.us/html/Chapter%205%20-%20Handling%20Files.ipynb), I press the play button to run the notebook and I get redirected to a non existent URL:
https://notebooks.azure.com/nb/notebooks/Chapter%205%20-%20Handling%20Files.ipynb

But when I do it again, in the second try, it works.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/py4bio/libraries/py3.us/html/Chapter%205%20-%20Handling%20Files.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

About 8:30 PST.

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [X] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

This happends in all notebook here https://notebooks.azure.com/py4bio/libraries/py3.us

**Comment by andneilmsft** [comment]
Thanks for reporting this. I've been unable to reproduce this issue with the notebook that you shared.  We will need more specific steps to isolate this problem. Please try shutting down your container and restarting the notebook, and let us know if it happens again, along with any additional context. Thank you.

**Comment by smortaz** [comment]
Same here.  I cloned the library, did a Run All on that notebook and it worked fine - see below.

Are you sure that youre not referring to the normal startup process of a notebook?  basically after you click on a notebook in a library for the first time, you will get redirected from the HTML version to an actual running instance with a similar looking URL.

![image](https://user-images.githubusercontent.com/742484/49059724-0fbea500-f1bf-11e8-9dd1-ab1b8ba877c5.png)

**Comment by smortaz** [comment]
Something that might help is to do a screen capture of the issue & post the video link.
