### ISSUE TITLE
Import notebooks in same library as modules

### ISSUE THREAD

**Issue by SpencerPark** [Microsoft/AzureNotebooks#56]
### Description
[nbimporter](https://github.com/grst/nbimporter) is a python module that allows for importing other notebooks as modules. This can be really nice for breaking up a program into multiple files and works well when running Jupyter locally as all of the notebooks are physically in the directory that the notebook is running in.

On Azure the notebooks are not files but rather loaded from Azure storage. To work around this the following was executed to download other notebooks in the library and put them into files that can then be imported as modules with `nbimporter`.

```javascript
%%javascript
function importNotebook(notebook) {
    var nb = IPython.notebook;
    var kernel = IPython.notebook.kernel;
    
    var notebookURL = 'https://notebooks.azure.com' + nb.base_url + 'api/contents/' + notebook + '.ipynb';

    var getReq = new XMLHttpRequest();
    getReq.open("GET",  notebookURL, false);
    getReq.send();
    
    if (getReq.status !== 200) {
        console.log("Error downloading notebook " + notebook + ". ErrorCode: " + getReq.status + ". Error: " + getReq.statusText);
        return;
    }
    
    var notebookContents;
    try {
        notebookContents = JSON.parse(getReq.response);
    } catch (e) {
        console.log("Cannot find notebook " + notebook);
        return;
    }
    var b64Notebook = window.btoa(unescape(encodeURIComponent(JSON.stringify(notebookContents.content))));
    kernel.execute(`
import base64
NOTEBOOK_CONTENTS="""${b64Notebook}"""
NOTEBOOK_CONTENTS=base64.urlsafe_b64decode(NOTEBOOK_CONTENTS)
f = open("${notebook}.ipynb", "wb")
f.write(NOTEBOOK_CONTENTS)
f.close()`);
    console.log('Downloaded notebook ' + notebook);
}

['Module1', 'Module2'].forEach(function (nb) { importNotebook(nb); });
```

which would download the 'Module1.ipynb' and 'Module2.ipynb' from the library that the running notebook is in, into the working directory.

After running that cell the modules can then be imported with the following
```python
!pip install nbimporter
import nbimporter
from Module1 import *
from Module2 import *
```

### Possible Solutions

The above functionality could be built into the notebook like the `Data > Choose from Dropbox` that would list the other files in the library for download.

Another option could be a different nbimporter that can import notebooks from Azure storage.

**Comment by crwilcox** [comment]
I am not quite sure what the ask is from the Azure Notebooks project. 

The API you are calling in notebookURL is not azure notebooks specific, but an API provided by Jupyter. 
The way in which Azure Notebooks stores things not on disk is using a ContentsManager implementation as defined by Jupyter Interfaces. So, any Jupyter Instance running non-default storage would implement this interface.

It seems to me the code nbimporter is not a complete implementation as is. Improving upon this to support using the running notebook server's api/contents endpoint and gathering the file that would provide additional functionality. I can see not replacing it though as the current implementation allows you to import notebooks and not assume you are in a running notebook server. I could see having this have the ability to check though, or have an additional method to handle that.

**Comment by SpencerPark** [comment]
I thought the off disk storage was an Azure modification but I'm really happy to hear that it isn't and there is a standard storage API for the notebooks. The way to go about this would definitely be extending the importer to make use of the ContentsManager so that's what I'll look into next. Hopefully this ends up even cleaner than having to download notebooks. Thanks!

**Comment by SpencerPark** [comment]
I'm note sure when it was updated but all of the files in the library are also available in the same directory as the running notebook and so this is no longer an issue!
