### ISSUE TITLE
Error running in notebook, then loading error

### ISSUE THREAD

**Issue by SunixLiu** [microsoft/AzureNotebooks#562]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [*] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

The error is tracked by id: 962da4ee-ea90-4740-8a2c-8e0a144f6b8b
I was running CIFAR10 training, but there was error promoted by Jupyter and then training stopped, when I tried to reload the notebook file, it shows msg as below:
~~~~~~~~~
We're sorry, an error has occured while processing your request.

Please try again or report the issue on GitHub or via e-mail. 

The error is tracked by id: 962da4ee-ea90-4740-8a2c-8e0a144f6b8b
~~~~~~~~~~~
Then even I created a new notebook, I continuously got error info and am not able to load the new one

This issue happened since yesterday, a couple of times.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Don't know how to reproduce, but pls. check the link:
https://notebooks.azure.com/sunixliu/libraries/mycifar-1/run/notebooks/MyCifar10-1.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [*] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [*] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Thanks for reporting. Is your notebook public? I can't access it at the link you provided, 
Please check:
https://notebooks.azure.com/sunixliu/libraries/mycifar-1/run/notebooks/MyCifar10-1.ipynb

**Comment by SunixLiu** [comment]
Apologies, I just changed it to public, pls. re-check again. Thank you.
