### ISSUE TITLE
AzureNotebooks error

### ISSUE THREAD

**Issue by monikasimeria** [Microsoft/AzureNotebooks#563]
Please describe your issue as completely as possible.
Since yesterday I can't download any files from my computer to AzureNotebooks, and I see this message:
![azurenotebook error](https://user-images.githubusercontent.com/44191756/49141758-a7271380-f2f7-11e8-866c-ee77a0394dab.GIF)

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net
 https://notebooks.azure.com
#### Describe the issue you are encountering
I cant download anything into the AzureNotebooks from my computer.
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/Microsoft/libraries/samples/html/Azure%20Notebooks%20-%20Welcome.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal
R
#### What time (please include time zone) did this occur?
since yesterday, Nov.27th, after 8 PM ( UTC+1) Netherlands
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)
Chrome
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)
Windows
#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/Microsoft/libraries/samples/html/Azure%20Notebooks%20-%20Welcome.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
-----------------------------
Jupyter debug log
The .nb.log file stores the output from Jupyter

Typically when you're running Jupyter locally you may have started it from a terminal window. The terminal window will have output such as kernels being started, restarted, and other random information.

On Azure Notebooks we've redirected this output into a file in your home directory called .nb.log. From within a Python notebook you can enter into a cell: 
!cat .nb.log

Other languages such as R and F# don't support the magic cells. In these cases you can first click on the Jupyter logo in the upper left hand corner. This will take you to the Jupyter tree view. You can then click New->Terminal. From here you can enter: 
cat .nb.log
----------------------------
-- there is no tree view when I click on Jupyter logo.... :(

**Comment by andneilmsft** [comment]
The link you shared is: 

https://notebooks.azure.com/Microsoft/libraries/samples/ 

This links to libraries that are owned by Microsoft, you are not able to upload your files to Microsoft's library.  As of this week we now call libraries projects. If you click the link at the top of the page to go to "my projects" you can upload your files there.
