### ISSUE TITLE
downloading files in R from azure

### ISSUE THREAD

**Issue by sta017** [microsoft/AzureNotebooks#564]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [*] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I am unable to download CSV file using R directly from the terminal. I am using the command below: download.file("https://notebooks.azure.com/anon-alaa/libraries/A001/html/Module4/German_Credit_Preped.csv","German_Credit_Preped.csv")

It does not download the actual data file, so I have manually do it. Could you tell why would that be happening? 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/anon-alaa/libraries/A001/tree/Module4

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [*] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
1137 CST
#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [*] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/anon-alaa/libraries/A001/tree/Module4

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update that could potentially resolve this problem. I was able to run 
`download.file(`...`)` snippet, and it did download `German_Credit_Preped.csv` into my project folder.
Please reactivate this issue if you still see the problem. Thank you for using Azure Notebooks!
