### ISSUE TITLE
Carriage Return Not Working

### ISSUE THREAD

**Issue by Nole9399** [Microsoft/AzureNotebooks#565]
I have a problem with my carriage return cancelling out after hitting the spacebar, the new line jumps back up to the old line above.  The screen shot explains and shows exactly what is happening to my code.  I have to manually reset each line of code.  I'm on notebooks.azure.com with Python 3 using Chrome on an Android Tablet  @ https://dev236x-nole93.notebooks.azure.com/j/lab
Tablet Please help, Wayne

![screenshot_20181128-180226](https://user-images.githubusercontent.com/35415693/49189080-fd697600-f33a-11e8-84ff-851ba83f5f9f.jpg)

**Comment by andneilmsft** [comment]
Thanks for reporting this. We can't reproduce this on a laptop. We will attempt a repro on an Android device. Can you repro this on any other android browser? Does it happen on non andriod device for you? Do you have any Jupyter extensions installed?

**Comment by smortaz** [comment]
In general Jupyter UI doesnt work well in mobile browsers.  Your best bet is to use the ">" (Play or Run) button in the UI.  Even then, mobile browsers lose track of the cursor/input fields eventually.  Ie, it's a Jupyter limitation not Azure Notebooks.

**Comment by Nole9399** [comment]
Ok, Thanks for the info. I guess I will just have to do my programming on
my laptop instead of my tablet.
Thanks Wayne
