### ISSUE TITLE
Azure won't open my noteboks

### ISSUE THREAD

**Issue by chinmaykrishnan** [Microsoft/AzureNotebooks#566]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
#### Describe the issue you are encountering
So I created a few notebooks for my college class in a library. But, when I click on the notebook, it just redirects back to the library page, the same one where I clicked the notebook, instead of taking me to Jupyterlab. I have this issue only on my laptop and the college lab PC does the job well. Also, there are no error messages displayed.
#### Which language/kernel were you using when you experienced this issue?
     
    [] Python 3.5
#### What time (please include time zone) did this occur?
Indian Standard Time (GMT+5:30)
#### Which Web Browser(s) did you see the error in?
    [] Chrome
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
Sorry to hear you are having this problem. Please shutdown all active projects and clear browser cookies, this should get you into a good state again. let us know if that doesn't work.

**Comment by rachelgshaffer** [comment]
Closing this issue as we haven't heard back. Please reopen if you're still experiencing trouble.
