### ISSUE TITLE
Status in Azure notebook is showing 'Stopped'

### ISSUE THREAD

**Issue by amitsharma23** [Microsoft/AzureNotebooks#569]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I used to learn python in Azure Notebooks, but from today the dashboard status is showing 'Stopped' and I am not being able to open any of my previous work which I did on Jupyter. I don't know much about the technical aspects as I do not have any programming background. 
Please assist the steps to resolve this issue.
![c1](https://user-images.githubusercontent.com/40753294/49338239-dfef2180-f644-11e8-87fd-fb39c9fd11f1.JPG)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
#### Which Web Browser(s) did you see the error in?
    []Chrome
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows 10

**Comment by smortaz** [comment]
After a period of inactivity, your container is shut down. Simply click on
one of the notebooks and it should get you a fresh container to run your
code.

**Comment by andneilmsft** [comment]
if you are still having problems, please reactivate this issue.

**Comment by Angelynnetje** [comment]
I have to same problem. Is there a solution?

**Comment by tomgcoleman** [comment]
I also had the same problem.  After trying many things I found a work around:
In the Azure web page, log out, then log in again.
Maybe logging out causes all my containers to be closed out.

**Comment by Hamza5** [comment]
@tomgcoleman thanks a lot for the idea! The problem is still happening until now, and your suggestion is the solution.

**Comment by aashutosh0012** [comment]
Thanks @tomgcoleman , Logging out and Logging in back, works

**Comment by cgrodrig** [comment]
Logging out & back in, unfortunately, did not work for me.
