### ISSUE TITLE
Icon on the AzureNotebook tab

### ISSUE THREAD

**Issue by DanyWind** [Microsoft/AzureNotebooks#570]
Hello !

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering

I have a minor issue, there is no icon telling us whether the computation is over when we use Azure Notebooks, contrary to using Jupyter Notebooks.

Could you add this feature so we can know when the computation is done ? Thank you !

#### Which Web Browser(s) did you see the error in?

    [] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [] Ubuntu

**Comment by andneilmsft** [comment]
Thank you for making this feature request, we have added it to our backlog for future consideration.
