### ISSUE TITLE
Cannot open files from within a notebook

### ISSUE THREAD

**Issue by taupalosaurus** [microsoft/AzureNotebooks#571]
Hi,

One of our students is running into a strange bug. When she clones my library `https://notebooks.azure.com/nbarral/projects/introprog-lect6` and runs the notebook, python cells run, but any call to `open` fails with a File not found error. I have checked, the files appear in the GUI frontend, but I cannot see the library at all from the terminal.  
If I clone the library myself, it just works.
The username of the student can be provided in private.

Thanks,

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Which language/kernel were you using when you experienced this issue?
    [x] Python 3
    [x] Terminal

#### What time (please include time zone) did this occur?
~13:15 GMT

#### Which Web Browser(s) did you see the error in?
    [x] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows

**Comment by smortaz** [comment]
Hi pls send mail to nbhelp@microsoft with the username and library path.
Thx!

**Comment by taupalosaurus** [comment]
Thanks @smortaz, done.

I should add we're planning to have an exam next Thursday using azure notebooks. If we could make sure that doesn't happen again during the exam it would be really great !

**Comment by andneilmsft** [comment]
Email received, we'll take a look.

**Comment by andneilmsft** [comment]
we can repro this. For now, please have students who are impacted turn of unified front end. it's a toggle button in their user profile.  We'll have a fix out in the next week or so. Let us know if you can't find that toggle button.

**Comment by taupalosaurus** [comment]
Great ! I'm seeing the students Thursday I'll tell them and let you know if we still have a problem.

Thanks !

**Comment by rachelgshaffer** [comment]
We have looked into this further and switching off the 'Unified Front End' may not be sufficient. However use of absolute paths will always work. The working directory at the base of your project is `/home/nbuser/library` so the `data/data1.txt` file can be referenced: `/home/nbuser/library/data/data1.txt`. We are still investigating and will update with any further progress. Thanks!

**Comment by taupalosaurus** [comment]
Thanks for the update !

This solution is less than ideal, it makes things complicated for freshers that are Python beginners, especially for an exam...
Also, it results in the aznbsetup.sh file not being run, and in our auto-testing framework not working...

What would be a satisfying workaround ?

**Comment by taupalosaurus** [comment]
(To clarify: the tests frameworks need a tool pip installed in the setup file, and then rely on tests files in the library read by this tool, which also seemed to fail...)

**Comment by taupalosaurus** [comment]
Good evening,

Is there any update on this issue ? We've had a couple of practicals since, and every time there are about 10% of our students that have problems with opening files. So far, restarting the kernel has worked. But is it always going to work ? And is there another workaround ? 

Our exam is in two days and I am worried our students will be disturbed...

Thanks a lot for your help !

(cc'ing @ggorman)

**Comment by andneilmsft** [comment]
We are working through a candidate fix at the moment and hope to deploy it within the week. The workarounds remain using absolute paths and/or restarting the kernel.

**Comment by rachelgshaffer** [comment]
Apologies that we don't have a fix yet for this issue. We are still investigating. The workarounds remain:
1. Use absolute path
2. Restart kernel
