### ISSUE TITLE
Jupyter not loading images

### ISSUE THREAD

**Issue by luizbalestreri** [Microsoft/AzureNotebooks#572]
Please describe your issue as completely as possible.

#### Which site did you access us from?
https://notebooks.azure.com/Microsoft-Learning/projects/dev290x

#### Describe the issue you are encountering

The notebook is not displaying images, a broken source icon is being displayed

#### Which language/kernel were you using when you experienced this issue?

    [] Python 3.6 

#### What time (please include time zone) did this occur?
14:45 UTC-3
#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? 
All the notebooks are having this issue

    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

[I 10:19:01.027 NotebookApp] Using MathJax: /content/mathjax/MathJax.js
[I 10:19:01.049 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 10:19:01.594 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 10:19:01.594 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 10:19:01.715 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 10:19:01.805 NotebookApp] JupyterLab beta preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 10:19:01.806 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 10:19:01.853 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 10:19:01.854 NotebookApp] 0 active kernels
[I 10:19:01.856 NotebookApp] The Jupyter Notebook is running at:
[I 10:19:01.857 NotebookApp] http://nbserver:25198/nb/
[I 10:19:01.859 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 13:59:21.120 NotebookApp] Could not open static file ''
[W 13:59:21.123 NotebookApp] 404 GET / (10.36.41.1) 81.02ms referer=None
[I 13:59:21.466 NotebookApp] Kernel started: cb34c136-16bc-45b6-82ee-7dff96659c89
[I 13:59:24.313 NotebookApp] Adapting to protocol v5.1 for kernel cb34c136-16bc-45b6-82ee-7dff96659c89
[I 16:43:13.301 NotebookApp] Starting buffering for cb34c136-16bc-45b6-82ee-7dff96659c89:db9939492a094777b5226932c04c603d
[I 16:43:32.451 NotebookApp] Adapting to protocol v5.1 for kernel cb34c136-16bc-45b6-82ee-7dff96659c89
TermSocket.open: 1
[I 16:47:26.692 NotebookApp] New terminal with specified name: 1
TermSocket.open: Opened 1

**Comment by vasiljevic** [comment]
I even can't open an image from Jupyter's file browser. After I click on an image name (first screenshot) I got an error (second screenshot):

![image](https://user-images.githubusercontent.com/10418572/49577591-fd273700-f947-11e8-9c5f-28256b365c22.png)


![image](https://user-images.githubusercontent.com/10418572/49577448-b20d2400-f947-11e8-99a3-77fc42508487.png)

**Comment by rachelgshaffer** [comment]
A fix for this will be coming in a deployment soon (will reply back when that's pushed out). Thanks for reporting and thanks for using Azure Notebooks!

**Comment by luizbalestreri** [comment]
I solved it using Jupyterlabs, just click with the right button the azure and choose it.

**Comment by rachelgshaffer** [comment]
The fix for this is actually deployed since 12/13. Apologies for not replying back sooner. Please let me know if you are still experiencing any issue!

**Comment by luizbalestreri** [comment]
Hi, Rachel. I'm still with this problem, it seems that other people are experiencing it too, on the EDx help page.

**Comment by rachelgshaffer** [comment]
@luizbalestreri I cloned the notebook mentioned above (https://notebooks.azure.com/Microsoft-Learning/projects/dev290x) and am having no trouble viewing the .png files through Jupyter. If you're using a different project, please provide a link (make sure it's public).

**Comment by luizbalestreri** [comment]
![captura de tela 35](https://user-images.githubusercontent.com/39319424/50175638-7af22780-02e4-11e9-86bb-a6f1bb122530.png)

I've just cloned it again, and had the same issue

**Comment by rachelgshaffer** [comment]
Oh I see. You and @vasiljevic were actually referring to two separate issues. The issue you report, where images are not shown within the notebook in markdown cells, is tracked here: https://github.com/Microsoft/AzureNotebooks/issues/433

So please refer to that page for updates. Apologies that we don't have a fix for that issue yet.

**Comment by vasiljevic** [comment]
Now I can open an image from Jupyter's file browser, but images in markdown cells are still broken like @luizbalestreri also commented. 

Here is scenario: You have an inserted image in a markdown cell like `![alt text](image_name.png)`
and `image_name.png` is in your project in the same folder with the notebook.

Looks like images from a project are not properly exposed through  HTTPS.

**Comment by rachelgshaffer** [comment]
yes, that issue will be tracked via https://github.com/Microsoft/AzureNotebooks/issues/433
