### ISSUE TITLE
Can't open file, then kernel doesn't start after shutdown

### ISSUE THREAD

**Issue by taupalosaurus** [Microsoft/AzureNotebooks#574]
Hi,

This may be related to #571 or not, so I'm creating a different issue. 

Thanks !

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

It started with a TA complaining they couldn't open a file on the filesystem. 
I made them shutdown the library, and then relaunch the notebook, but then we tried running a cell (containing an `import numpy`, a `!ls` and an `open` lines) that froze (star next to the cell for a while, nothing happening). 
I asked them to interrupt the kernel, nothing happened. The restart the kernel seemed to do something (the star disappeared), but then they weren't able to run any cell at all (running the cell would do nothing).
Then I asked them to sign out and in again, and relaunch the notebook, but running cells would do nothing again. 
Then I asked them to shut down the library and relaunch the notebook, and it eventually worked all fine, both running cells and opening files.

Are we doing something wrong in this case ? Is it expected behavior

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://notebooks.azure.com/anon-xqazxq/projects/introprog-exam2017

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6
    [x] Python 3 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

15:45 GMT

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [x] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/anon-xqazxq/projects/introprog-exam2017

**Comment by andneilmsft** [comment]
Thanks for reporting, we'll continue to track our investigation and resolution of this under #571
