### ISSUE TITLE
Syntax highlighting enabled only when editing

### ISSUE THREAD

**Issue by fruboes** [Microsoft/AzureNotebooks#577]
#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
I'm going through one of the MS courses on edx. There is one minor annoyment when viewing the sources - in order to get syntax highlighting, I need to edit given file, then save it to exit. Would it be possible to have the highlighter enabled also in the preview mode? The example file is the following:

https://notebooks.azure.com/tmffmt/projects/DAT257x/html/LabFiles/lib/plotting.py

, currently rendered (in the preview mode) as a simple text file, i.e. without any color or font variation. 

#### Which Web Browser(s) did you see the error in?
    [x] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Ubuntu

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
https://notebooks.azure.com/tmffmt/projects/DAT257x/html/LabFiles/lib/plotting.py

**Comment by andneilmsft** [comment]
thanks for reporting, we currently only do preview mode colorization for code in cells in notebooks files, for example: 

https://notebooks.azure.com/tmffmt/projects/DAT257x/html/LabFiles/Module%201/Ex1.3%20Random.ipynb

I've added this to our feature request backlog for internal tracking. Thanks for using azure notebooks and for providing feedback.
