### ISSUE TITLE
data uploading option for large collection of files

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/AzureNotebooks#578]
data uploading is limited to few files at a time. also the menu moved, but docs still point to old menu:

https://notebooks.azure.com/help/jupyter-notebooks/data/uploading

**Comment by andneilmsft** [comment]
new docs are here https://docs.microsoft.com/en-us/azure/notebooks/ We'll have our help system integrated with the new docs in the next week or so. Even the new docs mention the old menu. We'll hae that updated soon too - moving these menu items was a decision we made  late in our release. 

You can also upload files into your project outside of jupyter, import from git hub or CURL them down.  here are the new pages to read: 

https://docs.microsoft.com/en-us/azure/notebooks/access-data-resources-jupyter-notebooks
https://docs.microsoft.com/en-us/azure/notebooks/work-with-project-data-files

**Comment by denfromufa** [comment]
Today I found that downloading (with wget) and unzipping (with unzip) cats
and dogs dataset ~800MB is 10x slower in Azure Notebooks than in Colab
Notebooks:

http://files.fast.ai/data/dogscats.zip
