### ISSUE TITLE
Upgrade version of azure.storage library

### ISSUE THREAD

**Issue by MattPitlyk** [Microsoft/AzureNotebooks#58]
### Description
Current version of the azure.storage library available on notebooks.azure.com is 0.20.3 and it incompatible with more recent versions, such as 0.33.0. This makes it hard to use the same code locally and on Azure notebooks. Trying to upgrade the library manually results in an error.

### Repro Steps
In a cell run:
`!pip install --upgrade azure.storage`

Output shows failure while trying to upgrade:

> Collecting azure.storage
>   Downloading azure_storage-0.34.0-py2-none-any.whl (187kB)
>     100% |################################| 194kB 2.9MB/s ta 0:00:01
> Collecting requests (from azure.storage)
>   Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
>     100% |################################| 593kB 1.6MB/s ta 0:00:01
> Requirement already up-to-date: azure-common in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from azure.storage)
> Requirement already up-to-date: azure-nspkg in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from azure.storage)
> Requirement already up-to-date: futures in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from azure.storage)
> Collecting cryptography (from azure.storage)
>   Downloading cryptography-1.7.2.tar.gz (420kB)
>     100% |################################| 430kB 2.2MB/s ta 0:00:011
> Collecting python-dateutil (from azure.storage)
>   Downloading python_dateutil-2.6.0-py2.py3-none-any.whl (194kB)
>     100% |################################| 194kB 3.9MB/s eta 0:00:01
> Collecting idna>=2.0 (from cryptography->azure.storage)
>   Downloading idna-2.5-py2.py3-none-any.whl (55kB)
>     100% |################################| 61kB 7.5MB/s eta 0:00:01
> Collecting pyasn1>=0.1.8 (from cryptography->azure.storage)
>   Downloading pyasn1-0.2.3-py2.py3-none-any.whl (53kB)
>     100% |################################| 61kB 5.3MB/s ta 0:00:011
> Requirement already up-to-date: six>=1.4.1 in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from cryptography->azure.storage)
> Collecting setuptools>=11.3 (from cryptography->azure.storage)
>   Downloading setuptools-34.3.1-py2.py3-none-any.whl (389kB)
>     100% |################################| 399kB 2.5MB/s eta 0:00:01
> Requirement already up-to-date: enum34 in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from cryptography->azure.storage)
> Collecting ipaddress (from cryptography->azure.storage)
>   Downloading ipaddress-1.0.18-py2-none-any.whl
> Collecting cffi>=1.4.1 (from cryptography->azure.storage)
>   Downloading cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl (387kB)
>     100% |################################| 389kB 2.3MB/s eta 0:00:01
> Collecting appdirs>=1.4.0 (from setuptools>=11.3->cryptography->azure.storage)
>   Downloading appdirs-1.4.3-py2.py3-none-any.whl
> Collecting packaging>=16.8 (from setuptools>=11.3->cryptography->azure.storage)
>   Downloading packaging-16.8-py2.py3-none-any.whl
> Collecting pycparser (from cffi>=1.4.1->cryptography->azure.storage)
>   Downloading pycparser-2.17.tar.gz (231kB)
>     100% |################################| 235kB 3.6MB/s eta 0:00:01
> Collecting pyparsing (from packaging>=16.8->setuptools>=11.3->cryptography->azure.storage)
>   Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
>     100% |################################| 61kB 8.9MB/s eta 0:00:01
> Building wheels for collected packages: cryptography, pycparser
>   Running setup.py bdist_wheel for cryptography ... - \ | / - done
>   Stored in directory: /home/nbuser/.cache/pip/wheels/3e/09/be/ca344cd1e68fd4d4d8872a25287e884a6f73557710efa51019
>   Running setup.py bdist_wheel for pycparser ... - \ | done
>   Stored in directory: /home/nbuser/.cache/pip/wheels/a8/0b/41/dc95621f9d3a0da7bc191b8a71f0e8182ffd3cc5f33ac55005
> Successfully built cryptography pycparser
> Installing collected packages: requests, idna, pyasn1, appdirs, pyparsing, packaging, setuptools, ipaddress, pycparser, cffi, cryptography, python-dateutil, azure.storage
>   Found existing installation: requests 2.12.4
>     Uninstalling requests-2.12.4:
>       Successfully uninstalled requests-2.12.4
>   Found existing installation: idna 2.1
>     Uninstalling idna-2.1:
>       Successfully uninstalled idna-2.1
>   Found existing installation: pyasn1 0.1.9
>     DEPRECATION: Uninstalling a distutils installed project (pyasn1) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
>     Uninstalling pyasn1-0.1.9:
>       Successfully uninstalled pyasn1-0.1.9
>   Found existing installation: pyparsing 2.1.4
>     Uninstalling pyparsing-2.1.4:
>       Successfully uninstalled pyparsing-2.1.4
>   Found existing installation: setuptools 23.0.0
> Cannot remove entries from nonexistent file /home/nbcommon/anaconda2_410/lib/python2.7/site-packages/easy-install.pth

### Recommended Metadata
The Jupyter Kernel Python 2
Occurrence Time: ~10:30am CST, March 8, 2017
Web Browser: Chrome
Logs: No relevant info.

**Comment by lmazuel** [comment]
As part of the Azure SDK team, I agree that the default container should be installed with 0.34.0 by default. This means not the one by default in the `azure` metapackage, but in the meantime waiting for an update on `azure`, it's the best thing to do.

**Comment by crwilcox** [comment]
Hi @MattPitlyk , https://notebooks.azure.com has version 0.33.0 of azure-storage along with updated versions of other azure components. I have also updated the sample to reference that version of the library.

Thanks!
Chris
