### ISSUE TITLE
Add C# support and .NET to Azure Notebooks environments

### ISSUE THREAD

**Issue by hkusulja** [microsoft/AzureNotebooks#580]
This is feature request regarding the great service - https://notebooks.azure.com
I hope it will soon support C# language with with .NET https://dotnet.microsoft.com and NuGet packages.

This is needed as soon as possible so existing c# developers can reuse existing core, such as data import (for example from Microsoft Dynamics 365 CRM services others), so there is no need to rewrite them in Python.

**Comment by lwives** [comment]
I agree. It would be very interesting to have C# on notebooks to show code (maybe console only).

**Comment by jflam** [comment]
We would love to get C# in, and are actively investigating this (and by "we", I mean the C# folks not my team). Now is a great time for you to chime in on what you think C# *the language* needs to become a viable interactive programming language. Are there things that you would like to see in the language itself (vs., say hacks like what we do in Mono C# REPL)? Thx!

**Comment by ebbypeter** [comment]
Jupyter notebooks now support .Net (https://www.hanselman.com/blog/AnnouncingNETJupyterNotebooks.aspx) 
Hopefully this will come to Azure Notebooks soon
