### ISSUE TITLE
ExpiredAuthenticationToken

### ISSUE THREAD

**Issue by dem108** [microsoft/AzureNotebooks#586]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [*] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I was running a sample notebook imported from Azure Machine Learning Notebooks (https://github.com/Azure/MachineLearningNotebooks)
With no changes, the code that normally runs well fails with the following error:
```
CloudError: Azure Error: ExpiredAuthenticationToken
Message: The access token expiry UTC time '12/13/2018 7:25:27 AM' is earlier than current UTC time '12/13/2018 7:34:47 AM'.
```
I restart the Free compute, and tried again several times. Sometimes it succeeded, sometimes it failed. I happened to other people in the same room.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Couldn't find a way to reproduce yet. Can this be caused by network issue? Want to know if this is already reported. Instead, I'm attaching the notebook file with the detailed error message.
[a notebook - auth expired error.zip](https://github.com/Microsoft/AzureNotebooks/files/2675737/a.notebook.-.auth.expired.error.zip)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [*] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Sometime between 15:00-17:00, Dec 13th, 2018, KST

#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [*] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)
Tried both Chrome and Edge

#### Which Operating System are you using? Please specify version as well if possible:
    [*] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
I've attached a copy.
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
Couldn't capture the log.

**Comment by dweissenborn** [comment]
Same issue here.
