### ISSUE TITLE
Promblem with running my program with an input python

### ISSUE THREAD

**Issue by ririzu** [microsoft/AzureNotebooks#589]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

when running my code with an inout, I don't get an input box.
![skjermbilde 2018-12-17 kl 19 20 39](https://user-images.githubusercontent.com/37240527/50106717-e4b0f980-0230-11e9-9f36-c97d8de6d5d0.png)
![skjermbilde 2018-12-17 kl 19 20 23](https://user-images.githubusercontent.com/37240527/50106722-e8dd1700-0230-11e9-92cf-191b3ad7e1ae.png)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify): Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by adigeak** [comment]
What you want to say?
