### ISSUE TITLE
Custom Jupyter Kernel

### ISSUE THREAD

**Issue by maveme** [microsoft/AzureNotebooks#59]
### Description
I have developed my own Jupyter Kernel and I would like to know if its possible to use it with Azure Notebooks? If the answer is positive, how can I install it?
Thank you

**Comment by DinoV** [comment]
It should be possible today but it's not super straight forward...  First you need to get the kernel on the system - which you should be able to curl it down from some place where you're hosting it.  You'll need to install it into /home/nbuser as you can't write to the system files.

Then you need to register it with Jupyter.  So you can make:
mkdir -p ~/.local/share/jupyter/kernels/mykernel

And then copy your kernel.json and any other associated kernel registration info in there. 

From there you should be able to refresh your notebook server and see the new kernel.

Unfortunately you'll need to repeat that each time you start your notebook server so you might want to drop that into a getting started notebook.

Over time we should probably consider implementing support for automating this.

**Comment by marbetschar** [comment]
Would be awesome to improve the dependency installation process after a Notebook was shut down. Despite the fact that I was able to install the Calysto Hy Kernel, I'm experiencing some rough edges every time the Notebook is freshly started.

Documented here as "Known Issues":
https://notebooks.azure.com/marbetschar/libraries/calysto-hy-kernel
