### ISSUE TITLE
img-classification-part1-training.ipynb does not run out of the box

### ISSUE THREAD

**Issue by ryotatomioka** [Microsoft/AzureNotebooks#592]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
It seems that the kernel spec of examples in `Getting Started/tutorials` are not consistent. Some use Python 3.5 and some use Python 3.6. The problem is in the Python 3.5 environment (`/home/nbuser/anaconda3_420/`), `azureml-core` which is required to run these tutorials are not installed. So users need to manually switch to using the Python 3.6 kernel (see this [issue](https://github.com/MicrosoftDocs/azure-docs/issues/20891))

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Clone and run this example
https://notebooks.azure.com/azureml/projects/azureml-getting-started/html/tutorials/img-classification-part1-training.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.5

#### What time (please include time zone) did this occur?
Wednesday Dec 19 UTC

#### Which Web Browser(s) did you see the error in?
    [] Chrome
 
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
https://azuremlgettingstarted1-ryotat.notebooks.azure.com/j/notebooks/tutorials/img-classification-part1-training.ipynb

**Comment by ryotatomioka** [comment]
Issue resolved.

**Comment by BKJackson** [comment]
What was the solution? I'm having this problem.

**Comment by anand-007** [comment]
@ryotatomioka I still see the issue. Should we setup a kernel which supports python 3.6. When i used python3 still i face the same issue. Please let me know how to fix this issue ?
