### ISSUE TITLE
Can't access project notebook - Notebook Server won't restart

### ISSUE THREAD

**Issue by ubjones** [Microsoft/AzureNotebooks#594]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
When I try to open a notebook in my Azure Notebooks project it says "The notebook server associated with this project has been shutdown". I click the "Restart Notebook Server" button, and then I keep getting the message saying my "Your notebook server appears to be unresponsive". I cloned my project and that allowed me to continue, but the same thing is happening with the clone now. 

![notebooks-error](https://user-images.githubusercontent.com/10351720/50523752-d3bd7f00-0a9f-11e9-95c9-22b978060d29.JPG)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

When I log in now, my project has status "Stopped". I select it and choose "Run". I get Jupyter page with no files. I refresh the page and I get the "The notebook server associated with this project has been shutdown" message.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://aicourse-brianj.notebooks.azure.com/j/notebooks/Vision.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

Cannot access the log

**Comment by rachelgshaffer** [comment]
Under your settings, can you try turning Unified Front End on? And out of curiosity, had you turned this feature off previously? If so, why?

**Comment by ubjones** [comment]
Unified Front End is on and has always been on. I believe the sire was having some resource problems.
It seems to be working fine now.

**Comment by o-utofbounds** [comment]
i had the same issue, logging off and on again solved it

**Comment by linshine** [comment]
Same issue here. The log off and log on didn't work for me.
![0](https://user-images.githubusercontent.com/24490917/52178487-26f6c000-280a-11e9-8db4-697f324a4121.PNG)

**Comment by bianwenbo** [comment]
> i had the same issue, logging off and on again solved it

I ran into the same problem and solved it with your method. Thanks for sharing.

**Comment by Jurcikas** [comment]
Solved it. Cheers mate

**Comment by filiphosko** [comment]
Same problem, logging out and back in "resolved" the issue.

**Comment by akmohtashami** [comment]
Same issue. Same solution worked.

**Comment by alextotal** [comment]
> i had the same issue, logging off and on again solved it

Thank you, logging off and again solved it for me too.

**Comment by laurapichardo** [comment]
> i had the same issue, logging off and on again solved it

Also signed out and in again and it solved the issue. Thank you.
