### ISSUE TITLE
Markdown document shows as raw instead of html

### ISSUE THREAD

**Issue by rcanand** [Microsoft/AzureNotebooks#595]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com

#### Describe the issue you are encountering
When I view [this markdown document](https://notebooks.azure.com/anand-ramanathan/projects/Azure-MachineLearningNotebooks/html/NBSETUP.md), I see raw markdown instead of an HTML converted preview.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
[Link](https://notebooks.azure.com/anand-ramanathan/projects/Azure-MachineLearningNotebooks/html/NBSETUP.md)

Update: I tried selecting the md file and clicking Preview - but I still get the raw markdown, instead of html.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Dec 29 2018, 1:40 pm PST

#### Which Web Browser(s) did you see the error in?
    [x] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows

**Comment by rachelgshaffer** [comment]
This issue is already tracked here, please follow this post for updates: https://github.com/Microsoft/AzureNotebooks/issues/539
