### ISSUE TITLE
Install fbprophet on Azure Notebooks

### ISSUE THREAD

**Issue by andreaskopp** [microsoft/AzureNotebooks#597]
Please describe your issue as completely as possible.

I struggle installing Facebook's fbprophet on Azure Notebooks. Did anyone geht this to work? 
Any best practices for a reliable experience?

In my notebook I tried installing fbprophet using pip and conda with no success.

#### Which site did you access us from?
    [] https://notebooks.azure.com
   

#### Describe the issue you are encountering

see above

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

12/31 all day

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by antkmsft** [comment]
I was able to install fbprophet by running `!conda install fbprophet --yes`. It took some time, but did install the package.
