### ISSUE TITLE
Suddenly "File not found error" in various projects/notebooks 

### ISSUE THREAD

**Issue by andreaskopp** [Microsoft/AzureNotebooks#598]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Is there a general issue currently ongoing with Azure Notebooks? When I run various notebooks from several projects I get "File not found error" from all methods which try to open "local" data files.
This also includes sample notebooks provided by Microsoft.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Since 1/1/2019 (Germany)

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by rachelgshaffer** [comment]
This issue is already tracked, please follow the post here for guidance and updates: https://github.com/Microsoft/AzureNotebooks/issues/571

Thanks for using Azure Notebooks!
