### ISSUE TITLE
Cannot connect to Azure from the Azure notebooks

### ISSUE THREAD

**Issue by shikharv10** [microsoft/AzureNotebooks#599]
Please describe your issue as completely as possible.
I was trying to work with the Jupyter Notebooks in the Azure ML portal. When I try to connect to Azure using the “Azure” Menu option next to “Kernel”, it gives me the error as shown in the attached picture “Azure2”.
I want to connect to azure to import data and that’s the most straightforward way I could find. I am already logged in to the portal but it prompts me to grant access and then there is no option to manually sign in as well.
I tried other ways to import data but there were either some issues or it was too round about and tedious a process to be efficient.
user email in use is sverma@advantageiq.com
I contacted our internal Azure guy to check for access, he asked me to check if connecting to Microsoft Azure Notebooks directly work using some kind of configuration notebook but again nothing happens when I sign in using one of the IDs as shown in the picture “Azure3”.

Azure2
![azure2](https://user-images.githubusercontent.com/31326950/50703711-037e0100-1023-11e9-8762-d8f13519e3b3.PNG)

Azure3
![azure3](https://user-images.githubusercontent.com/31326950/50703725-109af000-1023-11e9-9906-130d699b4011.PNG)

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [X] https://studio.azureml.net

#### Describe the issue you are encountering
see above

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
see description

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Multiple times throughout the day.
#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by shibbas** [comment]
Thank you for contacting us. As a workaround, you can try using [AzureCLI's device login](https://docs.microsoft.com/en-us/cli/azure/authenticate-azure-cli?view=azure-cli-latest#sign-in-interactively) (!az login) to login into Azure directly.

Can you provide more information on your repro steps? Are you logged into the AzureNotebooks with the same account as azure portal?

**Comment by shikharv10** [comment]
Thanks for the quick response!

So for repro:
1. Initiated a blank python3 notebook from https://studio.azureml.net/ portal. I have logged in to the portal and other azure services like blob storage, Web Apps, using my credentials so I am already in the portal.
2. Clicked on the 'Azure' menu option next to the 'Kernel' menu option. The drop down has a single option of 'Connect to Azure'.
3. Clicked on that to get the error boxes shown in the Azure2 pic in the description in the original issue posted above.
4. Tried going through https://notebooks.azure.com/ and followed the same steps but got similar errors but this time it gives me an option to sign in as shown in the Azure3 pic above. Once I do that, the pop-up boxes close and nothing happens.

**Comment by shibbas** [comment]
Thanks for the repro information. In step 4, you didn't get the same error as you did in Step 3? If the authentication window disappeared then it means you should be signed in to your azure account. You can confirm that by using [Azure Cli Account List](https://docs.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-list) to check the subscriptions in your account (!az account list)

**Comment by shibbas** [comment]
Yes, in step 4, Connect to Azure is an explicit action so it will bring up the Authentication windows again. We will review this behavior to see if it needs to be changed to avoid confusion. Looks like you were connected however, so that's great.

I'll investigate the issue with studioml.azure.net and get back to you as i find something.

**Comment by shikharv10** [comment]
So there is no option to upload data from local computer or Dropbox or something as shown in multiple tutorials online?

**Comment by shibbas** [comment]
You can upload to Azure Notebooks from the local computer by using File->Upload... . Note that there might be a delay after you select the file to upload and getting a modal dialog to select where to save the file in azureml. The file should then be accessible at the location you selected.

**Comment by shikharv10** [comment]
Yes, that part I am aware. However, I will still need to import the data separately that I need to run in that notebook right?

**Comment by shibbas** [comment]
Apologies on the delay with the response. I'm trying to understand your scenario better. From your local computer, you should be able to do File->Upload to import the data to the notebook as mentioned above. Are you asking how to use it in AzureML?
