### ISSUE TITLE
Allow users to collaborate in a library 

### ISSUE THREAD

**Issue by eclectir** [microsoft/AzureNotebooks#6]
Users should be able to invite other users to have access to a library so they can modify content, and also share forward.

**Comment by mizzao** [comment]
Yeah, this is a sorely needed feature. Right now it's impossible for more than one user to contribute code to a notebook - the "clone" option doesn't make it easy to merge code.

**Comment by garth-wells** [comment]
As part of this, more namespacing in the form of team would be helpful.

**Comment by smortaz** [comment]
hi garth - it's on the to do list.  collaboration, and finer grain access
control.

**Comment by shuffle2** [comment]
As it stands, the raison d'être of "Azure Notebooks" is very unclear. It seems less capable across the board than just hosting jupyter locally. Hopefully I'm missing something? But really, the whole use case for putting "jupyter in the cloud" would be shared notebook access and/or accelerated processing. Currently you just get a notebook that's a pain to interface with and is slower to process data than a typical end-user machine.

**Comment by smortaz** [comment]
Hi Shuffle2 - You're quite right, collaboration and finer grained access control & sharing is a must have & it's coming.  The main scenario for Azure Notebooks today is mostly for folks who want to test drive a notebook / github repo, or a professor that wants to teach 300 students & doesn't want to worry about machine setup, python/pkg updates, security, etc.

**Comment by ldfreight** [comment]
any idea when it is coming? so far this is preventing us to use it.

**Comment by kkampf** [comment]
Hi @ldfreight, we don't yet have a timeline to share for this, but we appreciate the feedback and will update you once we are able to share one!

**Comment by paalge** [comment]
Looking to use this in a university setting, but the lack of being able to share this with students removes the possible usefulness of it. I'm surprised this has taken more than three years to implement. A start would be the possibility to share a unique link to it without having to publish it

**Comment by ldfreight** [comment]
@kkampf @smortaz appreciate your answers.
If we dont have a timeline, does that mean we should not expect anything in the next 12months?
It is important we know so that we manage expectations of users and eventually switch in the mean time to other solutions such as Google Colab which seems to have excellent collaboration features.

**Comment by burstingninja** [comment]
@kkampf @smortaz  any news/updates regarding the collab feature?, is it on the roadmap for this year?
Thanks in advance

**Comment by chipmuenk** [comment]
I am interested in this issue as well - I'd like to use Azure Notebooks in a course setting starting in March where the students should work on shared notebooks.

**Comment by rraczae** [comment]
+1

**Comment by ldfreight** [comment]
that doesnt seem to be in Microsoft roadmap.... They have databricks for that
