### ISSUE TITLE
bug in twitter sample notebook

### ISSUE THREAD

**Issue by dbgannon** [Microsoft/AzureNotebooks#60]
Please consider the template below to file your issue. 

### Description
I tried running the twitter sample notebook.   works fine until it tried to build the word clouds.  
it crashed on fit_words(). i suspect there is a new version of the wordcloud library.  the fit_words method now calls generate_from_frequencies which expect a dictionary and not a list of tuples. see 
https://github.com/amueller/word_cloud/blob/master/wordcloud/wordcloud.py

By inserting this little function

<pre>
def conv_to_dict(tuplelist):
    newdic = {}
    for item in tuplelist:
        newdic[item[0]]= item[1]
    return newdic
</pre>
and changing this line in function wdc:
wordcloud.fit_words(item)
to
wordcloud.fit_words(conv_to_dict(item))

everything worked fine.  clouds appeared. 

### Recommended Metadata
The Jupyter Kernel :Python 2
Occurrence Time: 4:00pm 3/14/17 pdt
Web Browser: FireFox
LibraryID and Notebook Name (if applicable): sample notebooks -Discover Sentiments in Tweets.ipynb

**Comment by smortaz** [comment]
Thank you Dennis!

**Comment by brettcannon** [comment]
Another solution would pin the version of wordcloud, e.g. `pip install wordcloud~=1.2.1` to make sure we get the version we expect. The best solution may be to update the notebook **and** pin the version to `~=1.3.0` so we start off with the newest version.

And for @dbgannon 's own knowledge, the constructor for `dict()` will take a sequence of `key, value` pairs and do what you're suggesting:
```python
>>> pairs = [(1, 'A'), (2, 'B')]
>>> dict(pairs)
{1: 'A', 2: 'B'}
```

**Comment by crwilcox** [comment]
This was fixed a bit back. Closing.
