### ISSUE TITLE
Markdown cells can no longer access local files (e.g. for displaying images) in run mode

### ISSUE THREAD

**Issue by rgerkin** [Microsoft/AzureNotebooks#603]
#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Markdown links to local files no long work.  

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

In this notebook, for example:
https://notebooks.azure.com/rgerkin/projects/neuro-data-analysis-course/html/delete.ipynb

You can see two copies of an image display using Markdown cells, the first of which uses a local path to a file in that Azure notbooks project, and the second of which uses an external URL to the same file on GitHub.  However, if you (or at least if I) *run* the same notebook, the first image disappears and displays the alt-text, suggesting that local paths in Markdown cells are not working in the run-time.  They previously worked (at least last year when I presented the same material to my class).  

This makes it difficult to put external image content in notebooks, for example for interactive presentations or documentation, since the images have to be hosted somewhere else (or I have to memorize some internal URL that I don't know).  Is there some reason relative path access to the project directory was removed?  Is there a way to get it back?  

#### Which Web Browser(s) did you see the error in?
    [X] Chrome

**Comment by jflam** [comment]
Thanks for reporting this.

The image is definitely there on the notebook server. Here's a capture of a terminal session:

![image](https://user-images.githubusercontent.com/8877/50910570-ee1e2380-13e2-11e9-996b-f84749e5127f.png)

Here's the relevant piece of markdown:

```
EXAMPLE OF FAILED ACCESS TO IMAGE VIA LOCAL PATH (file exists at the specified path in this project)

![alt text](images/odor-receptors.jpg)
```

We will investigate.

**Comment by rachelgshaffer** [comment]
We are tracking this with the issue here: https://github.com/Microsoft/AzureNotebooks/issues/433.
We expect to have a fix deployed soon, at which point I will update the linked thread. Thanks for using Azure Notebooks!
