### ISSUE TITLE
Shutdown of a project - Notification Window

### ISSUE THREAD

**Issue by bvbpefi** [Microsoft/AzureNotebooks#607]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When I want to shutdown a specific project in the project overview view, a window appears asking if i am sure that I want to shut down the project. ("Shutdown "toii@SP"?  All the running instances of your notebook servers will be shutdown. Any unsaved state will be lost. Do you want to continue?")

But clicking on "OK" does not close the window.
Please find a screenshot of the issue [here.](https://imgur.com/a/OwvVIdP)
 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
- N/A - 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal
- N/A -

#### What time (please include time zone) did this occur?
2018-01-11, 11am, CET

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
- N/A -
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
- N/A -

**Comment by bvbpefi** [comment]
It is way better now. (Sinde 2 or more days).

**Comment by rachelgshaffer** [comment]
Great, thanks. Closing the issue for now.
