### ISSUE TITLE
Unable to open Notebook.

### ISSUE THREAD

**Issue by PerformanceGenetics** [Microsoft/AzureNotebooks#609]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Something went wrong...

We're sorry, an error has occured while processing your request.

Please try again or report the issue on GitHub or via e-mail.

The error is tracked by id: e03e1cea-5420-4942-953b-323f236ecc85

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Just tried to open an untitled.py file in the project.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

5:08PM EST

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/byron-rogers-1973/projects/precocity/html/Untitled.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

The error is tracked by id: e03e1cea-5420-4942-953b-323f236ecc85

**Comment by andneilmsft** [comment]
Hi byron, thanks for getting in touch. When i look under you projects list i don't see the precocity project. Is it missing (deleted) or is it just private? 

https://notebooks.azure.com/byron-rogers-1973/projects

**Comment by PerformanceGenetics** [comment]
Yes. It’s private. I’ll make it public. 

Byron

**Comment by rachelgshaffer** [comment]
I was able to clone and open your notebook. Are you still experiencing this error? If so, may I ask if you have "Unified Front End" turned on in your settings?

**Comment by PerformanceGenetics** [comment]
Solved. Thanks
