### ISSUE TITLE
Can't load projects on profile page

### ISSUE THREAD

**Issue by jflam** [Microsoft/AzureNotebooks#610]
When a user logs in, the first page they are redirected to is their profile page. The list of the user's projects never completes rendering on the profile page. This is different from #601 where it simply takes a long time to load. I've left my profile page up for _hours_ and it never completes. 

![image](https://user-images.githubusercontent.com/8877/51123751-89dbd500-17d1-11e9-92d5-1c177c429abf.png)

The My Projects page that is referenced in #601 renders instantly (I'm only including the first named project - there are others).

![image](https://user-images.githubusercontent.com/8877/51123807-ac6dee00-17d1-11e9-9424-39d2f38c40d5.png)

**Comment by dem108** [comment]
I have the same issue. Note that it happens only when I'm logged in. Without login, it finished showing public projects quickly. I can assume the issue is related to retrieve private projects.

I've tested with Edge, Chrome, IE. All the same.

**Comment by andneilmsft** [comment]
Performance issue addressed.
