### ISSUE TITLE
Broken numpy(v1.16.0) module in Python3.6 notebooks

### ISSUE THREAD

**Issue by vakarpus** [Microsoft/AzureNotebooks#612]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [v] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
    import tensorflow

Leads to numpy error in Python3.6 notebooks:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-3-66528752bad7> in <module>
      3 #--ignore-installed tensorflow==1.8.0
      4 
----> 5 import tensorflow as tf
      6 print(tf.__version__)

~/anaconda3_501/lib/python3.6/site-packages/tensorflow/__init__.py in <module>
     22 
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 # pylint: disable=wildcard-import
     26 from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin

~/anaconda3_501/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>
     45 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     46 
---> 47 import numpy as np
     48 
     49 from tensorflow.python import pywrap_tensorflow

~/anaconda3_501/lib/python3.6/site-packages/numpy/__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~/anaconda3_501/lib/python3.6/site-packages/numpy/core/__init__.py in <module>
     55 from . import umath
     56 from . import _internal  # for freeze programs
---> 57 from . import numerictypes as nt
     58 multiarray.set_typeDict(nt.sctypeDict)
     59 from . import numeric

~/anaconda3_501/lib/python3.6/site-packages/numpy/core/numerictypes.py in <module>
    109 )
    110 
--> 111 from ._type_aliases import (
    112     sctypeDict,
    113     sctypeNA,

~/anaconda3_501/lib/python3.6/site-packages/numpy/core/_type_aliases.py in <module>
     61         _concrete_typeinfo[k] = v
     62 
---> 63 _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
     64 
     65 

~/anaconda3_501/lib/python3.6/site-packages/numpy/core/_type_aliases.py in <setcomp>(.0)
     61         _concrete_typeinfo[k] = v
     62 
---> 63 _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
     64 
     65 

AttributeError: 'tuple' object has no attribute 'type'

```
_Note: Downgrading to numpy v.1.15.4 fixes the issue._

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
1. Create new Python3.6 notebook
2. try to run "import numpy" or "import tensorflow"

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [v] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Wed Jan 16 15:30:15 PST 2019

#### Which Web Browser(s) did you see the error in?
    [v] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [v] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by elibarzilay** [comment]
Hi @vakarpus,

I've tried the same thing, and it worked fine:
![image](https://user-images.githubusercontent.com/185905/51300327-7f9c1f80-19f9-11e9-9688-82917b377f32.png)

But note that I *do* see numpy v1.15.4, so maybe you have made changes to the environment in previous interactions, or in other notebooks, or in the terminal?

**Comment by elibarzilay** [comment]
Replied -- see below.

--
                   ((x=>x(x))(x=>x(x)))                  Eli Barzilay:
                   http://barzilay.org/                  Maze is Life!


________________________________

**Comment by vakarpus** [comment]
I've reproduced your results, but I'm getting them with Python2 kernel. For Python3 and Python3.6 I'm getting different versions of the libraries. On the good note - for Python3.6 the default numpy version is 1.14.6 now, which works just fine.

Python3.6:
<img width="839" alt="screenshot 2019-01-17 10 39 47" src="https://user-images.githubusercontent.com/29550904/51340748-a2075a80-1a44-11e9-9e85-e9e60a010aa5.png">

Python2:
<img width="876" alt="screenshot 2019-01-17 10 40 56" src="https://user-images.githubusercontent.com/29550904/51340779-b51a2a80-1a44-11e9-92a8-3c78f77b1ba1.png">

Python3:
<img width="816" alt="screenshot 2019-01-17 10 39 20" src="https://user-images.githubusercontent.com/29550904/51340791-bb100b80-1a44-11e9-8e70-7b317600a687.png">

**Comment by vakarpus** [comment]
@elibarzilay See above.

**Comment by elibarzilay** [comment]
Good morning @vakarpus,

Apologies: I've use the `python2` kernel by mistake last night (I should have caught that given the ancient TF version).  FWIW, the `python2` and `python3` kernels are frozen as-is and only the `python36` kernel is the one that is maintained.

I now confirmed that I'm getting the same `1.14.6` version for numpy.

So it seems that this is resolved--?

**Comment by vakarpus** [comment]
👍

**Comment by elibarzilay** [comment]
Thanks!
