### ISSUE TITLE
DEV236x_Introduction_to_Python: 0dd8b804-0d7e-41c9-9f95-b01a6e79804e

### ISSUE THREAD

**Issue by m3joy85** [Microsoft/AzureNotebooks#613]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Error code: 0dd8b804-0d7e-41c9-9f95-b01a6e79804e
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/m3joy85/projects/DEV236x/html/MOD01_1-2.4_Intro_Python.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by rachelgshaffer** [comment]
Could you explain what the issue you're running into is, and provide a screenshot if possible? It looks like your project is private. If it's possible to make it public, it may make it easier for us to diagnose the issue. Thanks for using Azure Notebooks!

**Comment by rachelgshaffer** [comment]
Closing since we don't have any further information. Please reopen and provide additional information if you are still having trouble.
