### ISSUE TITLE
links to images in the notebook do not work from azure notebooks repository

### ISSUE THREAD

**Issue by denfromufa** [Microsoft/AzureNotebooks#614]
Python 3.6, Windows 10, Chrome browser

Here is example:

https://pdsc-denfromufa.notebooks.azure.com/j/notebooks/Lectures/Lecture_01_Intro/examples/Notebook/Notebook%20Basics.ipynb

<img src="images/dashboard_notebooks_tab_5_0.png" />

![image](https://user-images.githubusercontent.com/7870949/51432590-990eb880-1bff-11e9-9baf-929e0af93d6c.png)

**Comment by andneilmsft** [comment]
Thanks for reporting. We have a fix pending for this. It should be live in the next week or so.

**Comment by rachelgshaffer** [comment]
Yes, we are tracking this here: https://github.com/Microsoft/AzureNotebooks/issues/433
I'll post to that thread when the fix is deployed. Thanks!
