### ISSUE TITLE
Terminal is not working

### ISSUE THREAD

**Issue by sumendar** [Microsoft/AzureNotebooks#615]
Please describe your issue as completely as possible.
I am not able to communicate with my github repository for the below project, when i opened the terminal button its showing blank without any default input cursor command like `nbuser@nbserver:~$`  
**project link:** https://notebooks.azure.com/sumendar/projects/FoundationOfStatsDSAIML-Python
**screenshot**:  
![Imgur](https://i.imgur.com/Mstl5gJ.jpg)

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Which language/kernel were you using when you experienced this issue?
   
    [] Python 3.5
    [] Python 3.6 
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by sumendar** [comment]
working now

**Comment by rachelgshaffer** [comment]
Apologies for the delay in response. We have recently deployed a fix that should resolve this problem. Please reactivate this issue if you are still having issues . Thanks for using Azure Notebooks!
