### ISSUE TITLE
Run cell not working in notebooks

### ISSUE THREAD

**Issue by keiawatkins** [Microsoft/AzureNotebooks#616]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Code is not executing. I've tried ctrl + enter and selecting Run from the top of the page to no avail. I am getting an asterisk next to the input box  and am getting no output. I've tried running the example code and inputting my own code under Task 1. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://dev236x-prettybird33.notebooks.azure.com/j/notebooks/MOD03_1-5.1_Intro_Python.ipynb 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
8:54 am EST

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
I'm not sure if this link is the path to the notebook file or not...
https://dev236x-prettybird33.notebooks.azure.com/j/notebooks/MOD03_1-5.1_Intro_Python.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
I am unable to access the log files as I can't run the cell

**Comment by JucheMane** [comment]
I am running into the same exact issue and haven't been able to find any solutions across the internet, just a lot of patient and unanswered comrades. I'm new to github so not entirely sure if this is bad etiquette but I hope my post draws more attention to this and we can get help.

**Comment by jwhitwo** [comment]
I have found that when I have an '*' in the cell it is because the kernel is still starting or become hung. Often restarting the kernel will fix the issue, at least temporarily.

**Comment by rachelgshaffer** [comment]
We were experiencing an issue where kernels were getting in a stuck position. The fix has been deployed. I am going to close this issue now, but please reactivate if you are still having trouble running cells. Thanks for using Azure Notebooks!
