### ISSUE TITLE
Azure Notebooks API

### ISSUE THREAD

**Issue by navoshta** [microsoft/AzureNotebooks#619]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
This is a feature request rather than an issue: I think it would be great if Azure Notebooks had a **public API** to query and launch user's projects, and then retrieve the running Jupyter instance URL (perhaps using Azure SDK for authentication?). This would be incredibly useful for my app [Juno](https://juno.sh), a Jupyter client for iOS — although I'm sure others might find this useful as well.

#### Which Operating System are you using? Please specify version as well if possible:
    iOS

**Comment by vunvulear** [comment]
Do we have updates related to it?
