### ISSUE TITLE
Broken "Get Started Link"

### ISSUE THREAD

**Issue by ideaterminal** [Microsoft/AzureNotebooks#62]
Please consider the template below to file your issue. 

### Description
"Get Started Link" is broken.

### Repro Steps
Click on "get Started" Link on homepage.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time: Mar 21st, 10PM
Web Browser: chrome
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Thanks Si. We are aware and it will be fixed shortly. Thanks for reporting.
