### ISSUE TITLE
theano installation issue

### ISSUE THREAD

**Issue by michael-ziedalski** [microsoft/AzureNotebooks#620]
So, I signed up for the Data Science VM with Ubuntu on the azure.portal, to use with my azure notebook to run some machine learning models, but I cannot get theano to work on it.

I start up with the VM-provided Python 3.6 ML kernel, and proceed to use `!conda install theano -y`, which installs without a problem, but then, no matter what I do, theano refuses to `import`, with the most common error being, 
`module 'theano' has no attribute 'compile'`.

The notebook I am trying to use is on https://notebooks.azure.com/model-testing/projects/pymc3-housing

Site used:
    [X] https://notebooks.azure.com

**Comment by paulshealy1** [comment]
The _Python 3.5_ kernel already has Theano installed, and you can import it there:

```
import os
os.environ["MKL_THREADING_LAYER"] = "GNU"
import theano
```

If you need to use the _Python 3.6 - AzureML_ kernel, theano does install correctly with conda:

`!conda install theano -y`

then

```
import os
os.environ["MKL_THREADING_LAYER"] = "GNU"
import theano
```

the notebook you linked to is installing with pip, which I do not recommend.
