### ISSUE TITLE
Azure Notebooks not stable

### ISSUE THREAD

**Issue by marcelfranke** [Microsoft/AzureNotebooks#623]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [https://notebooks.azure.com

#### Describe the issue you are encountering
The Notebooks are not stable. The kernel always get stucked. This is a really instable bad experience. Sometimes it doesn't work at all.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Provide a stable notebook platform please.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
In the last weeks
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by edervishaj** [comment]
I can confirm. Same thing happens to me on a regular basis. Just upon opening one notebook the kernel is busy and I cannot even go forward with the imports.

**Comment by jwhitwo** [comment]
I have experienced similar behavior. I have been using Azure Notebooks during the lab portion of my course and the stability has been an issue. Primarily I see issues where the kernel becomes unresponsive and has to be restarted multiple times. The larger issue my students have complained about is not being able to easily tell if the container is ready or not. It will say started but they have to wait 3-5 minutes. A better indicator of the status would be helpful (started and ready indicator).

**Comment by rachelgshaffer** [comment]
We're very sorry for the instability but yesterday we deployed changes that should resolve this problem. Please reactivate this issue if you are still unable to reliably get into a notebook. Thanks for using Azure Notebooks!

**Comment by edervishaj** [comment]
> We're very sorry for the instability but yesterday we deployed changes that should resolve this problem. Please reactivate this issue if you are still unable to reliably get into a notebook. Thanks for using Azure Notebooks!

I am still experiencing the same instability. I opened an existing notebook and the kernel is busy from the start and never resumes. Also working alongside with a new notebook is not possible.

**Comment by edervishaj** [comment]
> Please describe your issue as completely as possible.
> 
> ### Required:
> #### Which site did you access us from?
> ```
> [https://notebooks.azure.com
> ```
> #### Describe the issue you are encountering
> The Notebooks are not stable. The kernel always get stucked. This is a really instable bad experience. Sometimes it doesn't work at all.
> 
> #### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
> Provide a stable notebook platform please.
> 
> ### Optional, but often helpful:
> #### Which language/kernel were you using when you experienced this issue?
> ```
> [] Python 2.7 
> [] Python 3.5
> [x] Python 3.6 
> [] R 
> [] F#
> [] Terminal
> ```
> #### What time (please include time zone) did this occur?
> In the last weeks
> 
> #### Which Web Browser(s) did you see the error in?
> ```
> [x] Chrome
> [] Firefox
> [x] Internet Explorer / Edge (Please note this is not supported)
> [] Other (Please Specify)
> ```
> #### Which Operating System are you using? Please specify version as well if possible:
> ```
> [x] Windows
> [] MacOS
> [] Ubuntu
> [] Other (Please Specify)
> ```
> #### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com//libraries//html/. If this is sensitive, you can email it to [nbhelp@microsoft.com](mailto:nbhelp@microsoft.com)
> #### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

Can you please reopen the issue? I am still experiencing this problem. Thanks!

**Comment by andneilmsft** [comment]
@edervishaj thanks for getting in touch. Please could you share some projects that exhibit the poor kernel behavior. 

In the report form above, you did not provide step by step actions that you take in azure notebooks before you hit the problem of kernel unreliability. These would be very useful to know in isolating the source of the problem. 

Additionally, Could you elaborate on the problem of "working alongside with a new notebooks".

**Comment by edervishaj** [comment]
@andneilmsft The steps to generate the problem:
- Select existing project
- Press Run on Free Compute button (at this points a new tab opens up taking me to the project Jupyter Notebook Home)
- Open an existing notebook (Python 3.6)

At this point the kernel is shown to be busy all the time. Cells do not execute and after trying to restart the kernel nothing happens.
By "working alongside with a new notebook" I meant that when I encounter this kernel unreliability I create another project and a new notebook inside it and the kernel in the new notebook behaves the same.

**Comment by rachelgshaffer** [comment]
Thanks for the further details. As @andneilmsft mentioned, could you please point us to a few projects where you have seen this occur? And ensure they are public so that we can access!

**Comment by rachelgshaffer** [comment]
@jwhitwo - are you still experiencing issues or have things been working better recently?

**Comment by jwhitwo** [comment]
I appears to be working. I'll keep testing with the entire class.

Jeff Whitworth, M.S.

Associate Vice Chancellor for Enterprise Infrastructure

Information Technology Services, UNCG

611 Forest St

Greensboro, NC 27412

336.334.9854

https://its.uncg.edu

**Comment by edervishaj** [comment]
> Thanks for the further details. As @andneilmsft mentioned, could you please point us to a few projects where you have seen this occur? And ensure they are public so that we can access!

@rachelgshaffer I just tested it again now with the same project I had problems with and it seems to be working. I will update here again if I encounter the same issue. Thank you!

**Comment by rachelgshaffer** [comment]
Thanks!
