### ISSUE TITLE
R kernel unstable

### ISSUE THREAD

**Issue by tbendsen** [microsoft/AzureNotebooks#624]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
The system often appears unstable, meaning that the code-cells in my notebooks doesn't execute. When I go to "help" - "about" it says "unable to contact kernel". When I try "Kernel" - "reconnect/restart" and other similar options, nothing happens.
I have had this experience quite often within the last couple of weeks. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I don't know. Maybe try to run some of the notebooks in this project:
https://notebooks.azure.com/tbendsen/projects/statepi-r

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
The latest incident:
2019-01-31 13.30-13:39 GMT+1
(At 13.41 GMT+1 it worked again)

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://statepir-tbendsen.notebooks.azure.com/j/notebooks/Kapitel%202/2.1-%20Grafer-histogram.ipynb

**Comment by antkmsft** [comment]
We have recently deployed an R kernel update that could potentially resolve this problem.
Please reactivate this issue if you still see the problem. Thanks for using Azure Notebooks!
