### ISSUE TITLE
A project with this ID already exists

### ISSUE THREAD

**Issue by dealmeidavf** [microsoft/AzureNotebooks#625]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When uploading a GitHub repository, I get this message: A project with this ID already exists.
However there is no project with this ID. It existed in the past but it was deleted and no longer exists on my account.

#### What time (please include time zone) did this occur?
16:30 EST 
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
could you share the repro so i can attempt a repro. thanks!

**Comment by dealmeidavf** [comment]
Log into your Azure account. Go to “my projects” and use GitHub upload. For
the ID use anything different than the last time you cloned the repo.
