### ISSUE TITLE
No File Accesss with Direct Compute

### ISSUE THREAD

**Issue by niematron** [Microsoft/AzureNotebooks#626]
Any time a notebook is running with direct-compute, file system access ceases to work.  For example, if loading data from 'data/myDataFile.csv' in Free compute, it works fine, but once I kick off Direct Compute, that same file becomes inaccessible and the following error is shown:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-5-c1b174eb0926> in <module>
      5 
      6 # Read the whole text.
----> 7 text = open('data/examples/wordcloud.txt', encoding="utf8").read()
      8 
      9 # Generate a word cloud image

FileNotFoundError: [Errno 2] No such file or directory: 'data/examples/wordcloud.txt' 

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
CST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

Any Direct Compute Notebook.

**Comment by andneilmsft** [comment]
This is a current limitation of the direct compute provision we are working on introducing project and file access for DSVM.

**Comment by dikokob** [comment]
Any update on this?
