### ISSUE TITLE
Upload a notebook with a url

### ISSUE THREAD

**Issue by phpdistiller** [Microsoft/AzureNotebooks#627]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
It's not really an issue.
Is there a way to upload a notebook thanks to a url like `https://notebooks.azure.com/?url=urltothenotebook` ?

**Comment by andneilmsft** [comment]
We do not have a API in the service exactly like your example, but here are ways you can do similar: https://docs.microsoft.com/en-us/azure/notebooks/access-data-resources-jupyter-notebooks

**Comment by rachelgshaffer** [comment]
Linking this here: https://github.com/Microsoft/AzureNotebooks/issues/630
Reactivate if this is a distinct issue from the other one.
