### ISSUE TITLE
Cells not running code

### ISSUE THREAD

**Issue by ens-emily** [Microsoft/AzureNotebooks#628]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I have some notebooks that I use for teaching – the participants clone the notebooks and work through them. While I was teaching over the past couple of weeks, I found that sometimes the code in the cells did not run. No * appeared in the [] beside the cell when I clicked run. This sorted itself out later in the day, but later happened both to me while logged in but accessing a clone of my own notebook, and to a participant who had cloned a notebook.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
The error occurred with the code in both of these two notebooks:
https://notebooks.azure.com/ensembl-training/projects/rest-api-python
https://notebooks.azure.com/ensembl-training/projects/rest-api-r

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Friday 1st Feb, morning in Turkey and Wednesday 4th Feb, morning and afternoon in Turkey.

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)
On the first occasion I was able to fix the problem by switching to IE then back to Chrome. On the second occasion the problem occurred in both Chrome and Firefox and I had not other browsers installed to try.

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [x] Ubuntu
    [] Other (Please Specify)
Using Windows on the first occasion, Linux on the second.

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
Any of the code in the two notebooks listed above.

**Comment by rachelgshaffer** [comment]
We apologize for the issue you are experienced. We deployed changes yesterday and the issue should be resolved now. Please reactivate if you are still having trouble.
