### ISSUE TITLE
Notebook Requires Re-Installing ALL Pre-Installed Packages

### ISSUE THREAD

**Issue by uslu16** [Microsoft/AzureNotebooks#629]
When i create a new project, i can not  import previous installed packages. 
I am installing all packages again and again. Is it normal or am i missing some thing.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

When i create a new project, i can not  import previous installed packages. 
I am installing all packages again and again. Is it normal or am i missing some thing.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

GMT+3

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Any packages installed by pip etc will be cleaned from the container when you close your session or shutdown the container hosting your session.  the following documentation shows how to automate this installation. 

https://docs.microsoft.com/en-us/azure/notebooks/install-packages-jupyter-notebook 

https://docs.microsoft.com/en-us/azure/notebooks/quickstart-create-jupyter-notebook-project-environment

An alternative is to provision your own DSVM in azure with just the packages you require. As you own this machine the packages you install on it will live for however long you keep the machine around. 

https://blogs.msdn.microsoft.com/uk_faculty_connection/2018/12/10/microsoft-azure-notebooks-and-additional-compute-capacity-via-connecting-to-data-science-vms/
