### ISSUE TITLE
Ability to include requirements.txt or .yml file to specify environment?

### ISSUE THREAD

**Issue by rjleveque** [Microsoft/AzureNotebooks#63]
It would be nice if it were possible to provide a [requirement.txt](http://docs.mybinder.org/example-requirements) or [environment.yml](http://docs.mybinder.org/example-conda-environment) file to specify packages that should be installed on the notebook server.  This is allowed for example on mybinder.org, see the links in the previous sentence.

This would be nice when providing a collection of notebooks that all require the same set of software, rather than explicitly having to install it from a notebook.

A work-around is to have a separate notebook to install the software, as I did for example in the `Install-packages.ipynb` notebook in this library: https://notebooks.azure.com/library/M49KECGcvS0
for a class I recently taught.

We are now working on a book where we want people to be able to work with many notebooks and it would be nice if the required packages were automatically installed when launching a server.  In this case we have a [.travis.yml](https://github.com/clawpack/riemann_book/blob/master/.travis.yml) file that specifies the environment so it would be nice if this could be used directly.

**Comment by brettcannon** [comment]
I take it you are specifically looking for a solution that works for all notebooks in a library? Otherwise you can curl a requirements.txt file and then try running `!pip install -r requirements.txt` in an individual notebook (as well as listing a specific `pip` command that lists all of your requirements).

**Comment by rjleveque** [comment]
Yes, we are hoping for a solution that works for all notebooks in the library. Thanks!

**Comment by smortaz** [comment]
I am not sure whether it is visible on the public Bugtracker or not, but
that functionality is definitely on the to do.

**Comment by crwilcox** [comment]
We now have functionality for executing startup scripts for notebook libraries. https://notebooks.azure.com/help/libraries/library-settings/environment
