### ISSUE TITLE
Import Notebook with a link

### ISSUE THREAD

**Issue by phpdistiller** [Microsoft/AzureNotebooks#630]
Hi

It's possible to import a repo with a link like : https://notebooks.azure.com/import/gh/:owner/:repo/

This link import all notebooks.

But, is it possible to import only one notebook with a link like : https://notebooks.azure.com/import/gh/:owner/:repo/:notebook

I would like to create a badge for one notebook only.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

**Comment by rachelgshaffer** [comment]
Yes, you can upload a specific notebook. Follow the directions here: https://docs.microsoft.com/en-us/azure/notebooks/work-with-project-data-files#import-data
