### ISSUE TITLE
can't use link: https://notebooks.azure.com/help/libraries/creating/import-from-github, in this page: https://courses.edx.org/courses/course-v1:Microsoft+DAT274x+1T2019/courseware/9a27d5b6-48c4-1194-3afa-cf0232935159/e19cb5ef-410b-8332-4fcf-b704d408d9a7/?child=first

### ISSUE THREAD

**Issue by MieHjordt** [Microsoft/AzureNotebooks#633]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [#] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [#] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [#] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
Please provide more information on what went wrong. 

I was able to locate DAT274 at this URL https://github.com/MicrosoftLearning/Research-Methods-for-Data-Science-with-R

I was then able to import it from git hub into my project collection:

https://notebooks.azure.com/andneil/projects/research-methods-for-data-scie

Please clone from my project above, or attempt the git hub import again.
