### ISSUE TITLE
Terminal doesn't appear to work in Jupyterlab

### ISSUE THREAD

**Issue by argoneus** [microsoft/AzureNotebooks#634]
Please describe your issue as completely as possible.
When I start a Terminal in Jupyterlab, there's no prompt and the cursor just blinks.  It doesn't appear that I'm able to start a functional Terminal.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
The Terminal within Jupyterlab is non-functional.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Open any notebook by right-clicking and selecting 'Run in Jupyterlab'.  Once Jupyterlab loads, open Terminal via File->New->Terminal

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
1:32PM CST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
Any notebook can be used to repro the issue; this appears to be a bug in the Jupyterlab environment.

**Comment by rachelgshaffer** [comment]
Sorry to hear about this problem and for the delayed response. Are you still experiencing this issue? Does it also happen in regular Jupyter?

**Comment by davidefiocco** [comment]
I experience a similar issue on Firefox from time to time too.
The cursor is there, but the entire screen is blank. I can actually fire commands by e.g using arrows and I can even see a character under the position of the cursor once a command is "underneath it". 
I will add more here next time it happens.

**Comment by whtowbin** [comment]
I'am having the same problem using Safari. No prompt just a blinking cursor.

**Comment by imoisharma** [comment]
In my case when I am running I am receiving Internal 500 error? Does anyone know regarding that error?

**Comment by NorthDecoder** [comment]
@rachelgshaffer it still appears to be a problem as reported on 14-Feb 2019.
