### ISSUE TITLE
Output cells in Jupyterlab Dark theme can't be read

### ISSUE THREAD

**Issue by argoneus** [Microsoft/AzureNotebooks#636]
Please describe your issue as completely as possible.
When running any notebook in Jupyterlab and selecting the Dark Theme, the output cells are rendered as white text with a white background.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When running any notebook in Jupyterlab and selecting the Dark Theme, the output cells are rendered as white text with a white background.  This can't be easily read, and the default Dark Theme for Jupyterlab uses white text on a black or dark background.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Open any notebook in Jupyterlab, run a cell and view the output.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
2:47PM CST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by VanFPGA** [comment]
Same for me
![output light in dark theme](https://user-images.githubusercontent.com/19557525/56311984-131de300-6104-11e9-8c39-19e79f271b40.png)

**Comment by VanFPGA** [comment]
Same here
![output light in dark theme ](https://user-images.githubusercontent.com/19557525/56312176-790a6a80-6104-11e9-89ba-0efede97ea64.png)

**Comment by VanFPGA** [comment]
same here
![output light in dark theme ](https://user-images.githubusercontent.com/19557525/56312289-aeaf5380-6104-11e9-9c2c-192eb58e67c5.png)

**Comment by andneilmsft** [comment]
this appears to be a local Jupyter instance not notebooks.azure.com. Please reactivate if this is azure notebooks. Please raise the issue over here if it's Jupyter Lab locally: https://github.com/jupyterlab/jupyterlab
