### ISSUE TITLE
Bug in Azure Notebooks

### ISSUE THREAD

**Issue by atulgiri** [Microsoft/AzureNotebooks#639]
Whenever I make a new notebook with has the keyword "advert" the notebook never opens Eg. when the name of the file is "Keras_advert.ipynb", "advert_Practice.ipynb" or whenever it has the word "advert", it never opens and always shows error. So, I tried changing the name to say "kerasads.ipynb" (As I was using "advertisement.csv" dataset). It works now. It does seems that Microsoft Azure Notebooks have some bug against the keyword "advert". Please look into it.

**Comment by nathansegers** [comment]
Are you sure this is not an issue with an ad blocker? I've had that before on a website ...

**Comment by atulgiri** [comment]
OMG yes..you're right. It's working when ad blocker is disabled. Silly of
me. Thank you for getting back btw.

**Comment by nathansegers** [comment]
You're welcome. Care to check out my bug? Maybe it's something you've encountered as well :)

https://github.com/Microsoft/AzureNotebooks/issues/643

**Comment by atulgiri** [comment]
Hmm.. your issue seems to be quite complex to my understanding, considering
I'm just a beginner in all this. Sorry man..hope you get yours fixed soon.

**Comment by nathansegers** [comment]
i'm also somewhat of a beginner with Azure Notebooks, it's like I can't get a tutorial to work...


________________________________

**Comment by andneilmsft** [comment]
@nathansegers  we'll take a look at your direct compute problem shortly. I'll close this issue as it relates to a problem with an ad blocker which is resolved.

**Comment by atulgiri** [comment]
Sorry dude, I've no idea how Direct Compute works.
