### ISSUE TITLE
Renaming to invalid title creates undeletable duplicate

### ISSUE THREAD

**Issue by singul4r1ty** [Microsoft/AzureNotebooks#64]
### Description
I attempted to rename a file from "Question 6" to "Question 6 & 7". There was a pop-up saying this is an invalid filename (due to the &) and so I renamed it to "Question 6 and 7" instead. However I now have a notebook in my library called "Question 6 & 7" which cannot be opened, renamed or deleted.

Reproduction - fairly evident from description

### Usage Scenario (e.g. teaching a computing course at university foo)
Creating solutions to example problems set in my computing course at university
### Recommended Metadata
The Jupyter Kernel: Python 3
Occurrence Time: ~3PM GMT 22/3/17
Web Browser: Google Chrome
https://notebooks.azure.com/home/libraries/zk254lent

Not bothered about getting this fixed personally but it's a bug I thought should be brought to your attention.

**Comment by smortaz** [comment]
thanks for filing singul4r1ty!  we'll let you know when it's fixed.

cheers.

**Comment by crwilcox** [comment]
I believe this is fixed. I am closing this issue but feel free to reopen if the issue reoccurs.
Thanks!
Chris
