### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Liam-Jaedick** [Microsoft/AzureNotebooks#641]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [+] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When i try to open a terminal, it says "page not found"
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/Liam-Jaedick/projects/pythontrial/run/terminals/1

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
8:33 am SGT
#### Which Web Browser(s) did you see the error in?
    [+] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [+] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/Liam-Jaedick/projects/pythontrial/run/terminals/1

**Comment by atulgiri** [comment]
I am using  https://notebooks.azure.com <https://notebooks.azure.com>
It says "Error Loading notebook"

The error persists every time use the keyword "advert" the name for eg.
"advert.ipynb" or any other form like "open_advert.ipynb" or
"keras_advert.ipynb"
https://1234-atulgiri.notebooks.azure.com/j/notebooks/Open%20Lab/advert.ipynb
https://1234-atulgiri.notebooks.azure.com/j/notebooks/Open%20Lab/open_advert.ipynb
(I don't know if the link would work for you)
Kernel Used : Python 3.6
Time  : All the time (or from 6:00 am to 6:00 pm IST which I tried, I
didn't try opening outside of this time frame)
Browser Used : Mozilla Firefox (Latest Version)
OS : Windows 10

When I tried opening my link in private window, it's not showing any error.
It's just blank. So I suggest you to create a python 3.6 notebook of name
like "advert.ipynb" from your azure notebook account.

Below are the images with the error when "advert" is used and the other is
the image when "advert" is not used and working properly.

**Comment by andneilmsft** [comment]
Thanks for reporting this. Can you provide steps that you took to launch the terminal and if public, the project that you were in when launching the terminal

**Comment by rachelgshaffer** [comment]
Are you still having any issues here? Please provide the information andneilmsft asked for so that we can try to help.

**Comment by Liam-Jaedick** [comment]
Hi Rachel!

No more issue here. Sorry for the trouble and thanks!
