### ISSUE TITLE
Recover Deleted Notebook

### ISSUE THREAD

**Issue by slipstreamJumper** [Microsoft/AzureNotebooks#642]
I accidentally deleted a notebook. Is there any way to recover it?

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
I accidentally deleted a notebook. Is there any way to recover it?

**Comment by andneilmsft** [comment]
Thanks for reaching out. I'm sorry to hear that you've deleted your content. Unfortunately there is no way for us to recover your data.
