### ISSUE TITLE
Internal Server Error when adding Direct Compute

### ISSUE THREAD

**Issue by nathansegers** [microsoft/AzureNotebooks#643]
Please describe your issue as completely as possible.

When I am trying to add a Direct Compute in Azure Notebooks, I keep on getting "Internal Server Error" and I can never check the logs of it.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I am trying to add a Direct Compute with a DSVM on Azure that I have set up with JupyterHub, which is completely functioning.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

- I logged into Azure Notebooks
- I started a DSVM which works, as I can access it through the Public IP address and port 8000 and see JupyterHub running. 
- I tried to run on Direct Compute, which gives me problems.
![image](https://user-images.githubusercontent.com/29042774/53346760-fa6d2a00-3917-11e9-9bc6-2062324f964f.png)

The IP Address is correct, the username and password is working as well.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

**None yet**

#### What time (please include time zone) did this occur?
Always

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

Doesn't occur in Notebooks, but on the platform itself.

**Comment by ramkd12** [comment]
Hi,

Sorry you have to face this issue. We are looking into. However we wanted to know if you are not able to connect to any DSVM or just that? Is this machine is behind any special network security like a VNet etc?

Please let us know.

Thanks

**Comment by nathansegers** [comment]
@ramkd12 thank you for looking into it.
As far as I know, there is nothing "special" with the VNet it's currently in. I can access the port 8000 from my local network, so I assume it should be OK for Azure Notebooks to connect to it as well.

I did try it before with another DSVM, a clean install and it also didn't work.

I could try again with a fresh spun up VM and come back to you.

**Comment by nathansegers** [comment]
I noticed some 417 "Unknown AAD Errors" in the Browser Console, is this related?

**Comment by aman-moula** [comment]
Same is happening with my notebook. I have tried two clean DSVMs but it did not work on any of them :(

**Comment by srikiran7** [comment]
I am also facing the same issue when connecting to my Azure VM (Windows Server) through IP, its giving me 'Internal Server Error' and i see Port 8000 is enabled.

**Comment by andneilmsft** [comment]
Windows DSVMs require jupyterhub to be manually configured. Linux DSVMs come pre-configured for jupyter "out of the box"

**Comment by nathansegers** [comment]
@andneilmsft but it also doesn't work for Azure Notebooks with the out-of-the-box Jupyter on Linux DSVM

**Comment by D-i-l-r-u-k-s-h-i** [comment]
hi, 
Can I know whether there is a fix for this. I'm also facing a similar problem.

**Comment by cipang** [comment]
Use a lowercase username when creating the DSVM.
