### ISSUE TITLE
417 Unknown AAD Error

### ISSUE THREAD

**Issue by nathansegers** [microsoft/AzureNotebooks#645]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I keep on getting an error in the Browser Console, and I don't know if it's something important or not.
![image](https://user-images.githubusercontent.com/29042774/53402768-a2373600-39b2-11e9-968d-5a98cb66b880.png)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

- Open a notebook instance.
- Check browser console

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [X] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by ramkd12** [comment]
Thanks for reporting this issue.  If you are working on multiple browsers, and if you got logged out or 8hr idle time out from another session, every other session has seen this error log in console.

Can you try logging out and login back to Azure Notebooks portal and try this again?

**Comment by nathansegers** [comment]
This doesn't solve, it happens all the time

**Comment by ramkd12** [comment]
Does your account (or email), which signed in Azure Notebooks, have an associated Azure account? If not, then please ignore these errors in console as it is expected currently to see such errors.

**Comment by nathansegers** [comment]
Yes, i use it daily to power on the DSVM which I want to connect to. It has full Azure access with active subscriptions.
