### ISSUE TITLE
Cannot login to website

### ISSUE THREAD

**Issue by aaarima** [Microsoft/AzureNotebooks#646]
Please describe your issue as completely as possible.
This is maybe a personal issue but after I sign in and click `My Projects` from the [home page](https://notebooks.azure.com/), the page asks me to sign in again. I get stuck in a continuous loop of signing in, clicking `My Projects` and then being asked to sign in again. 

My Microsoft account is under aaron.arima@percolata.com. 

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
NA
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
NA

**Comment by KieranBrantnerMagee** [comment]
Hey aaarima;

Sorry you're having this issue!  

I'd be curious if you could try some naïve client side fixes for us.
- If you have not already, would you kindly try on another browser (or in an incognito window)
- If this works successfully, I would try clearing cookies+cache in F12 tools.

If you've tried these and/or they were ineffective, please let us know and we'll dig in further.

Thanks again for your patience and for using Notebooks.

**Comment by andneilmsft** [comment]
We've not heard back from you in a month. Closing this thread. Please reactivate if this is still a problem.
