### ISSUE TITLE
Update to pre-installed kernel packages with a suit for spatial data analysis

### ISSUE THREAD

**Issue by tomkom** [microsoft/AzureNotebooks#649]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
We have to manually install each time a large number of packages that take time and bandwidth (including when used with requirements). We are using notebooks for teaching at a large University which is an MS partner (The University of Melbourne).

The packages used are a standard suite of "spatial data manipulation" packages

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

You can try:

`
!conda install shapely -y
!conda install fiona -y
!conda install geopandas -y
!conda install osmnx -c conda-forge
!conda install folium -y
`
These are the minimal set of requirements ( that will download GEOS, libspatialindex and rtree as a minimum. 

The full list of required packages is:

`
  
  geos:    3.7.1-h0a44026_0    
  shapely: 1.6.4-py37he8793f5_0
  cairo              pkgs/main/osx-64::cairo-1.14.12-hc4e6be7_4
  click-plugins      pkgs/main/osx-64::click-plugins-1.0.4-py37_0
  cligj              pkgs/main/osx-64::cligj-0.5.0-py37_0
  fiona              pkgs/main/osx-64::fiona-1.8.4-py37h9a122fd_0
  fontconfig         pkgs/main/osx-64::fontconfig-2.13.0-h5d5b041_1
  freexl             pkgs/main/osx-64::freexl-1.0.5-h1de35cc_0
  gdal               pkgs/main/osx-64::gdal-2.3.3-py37hbe65578_0
  giflib             pkgs/main/osx-64::giflib-5.1.4-h1de35cc_1
  hdf4               pkgs/main/osx-64::hdf4-4.2.13-h39711bb_2
  json-c             pkgs/main/osx-64::json-c-0.13.1-h3efe00b_0
  kealib             pkgs/main/osx-64::kealib-1.4.7-hf5ed860_6
  libboost           pkgs/main/osx-64::libboost-1.67.0-hebc422b_4
  libdap4            pkgs/main/osx-64::libdap4-3.19.1-h3d3e54a_0
  libgdal            pkgs/main/osx-64::libgdal-2.3.3-h0950a36_0
  libkml             pkgs/main/osx-64::libkml-1.3.0-hbe12b63_4
  libnetcdf          pkgs/main/osx-64::libnetcdf-4.6.1-hd5207e6_2
  libpq              pkgs/main/osx-64::libpq-11.1-h051b688_0
  libspatialite      pkgs/main/osx-64::libspatialite-4.3.0a-h644ec7d_19
  munch              pkgs/main/osx-64::munch-2.3.2-py37_0
  openjpeg           pkgs/main/osx-64::openjpeg-2.3.0-hb95cd4c_1
  pixman             pkgs/main/osx-64::pixman-0.36.0-h1de35cc_0
  poppler            pkgs/main/osx-64::poppler-0.65.0-ha097c24_1
  poppler-data       pkgs/main/osx-64::poppler-data-0.4.9-0
  proj4              pkgs/main/osx-64::proj4-5.2.0-h0a44026_1
  xerces-c           pkgs/main/osx-64::xerces-c-3.2.2-h44e365a_0
  descartes          pkgs/main/osx-64::descartes-1.1.0-py37_0
  geopandas          pkgs/main/osx-64::geopandas-0.4.0-py37_1
  libspatialindex    pkgs/main/osx-64::libspatialindex-1.8.5-h2c08c6b_2
  psycopg2           pkgs/main/osx-64::psycopg2-2.7.6.1-py37ha12b0ac_0
  pyproj             pkgs/main/osx-64::pyproj-1.9.6-py37h9c430a6_0
  pysal              pkgs/main/osx-64::pysal-1.14.4.post1-py37_1
  rtree              pkgs/main/osx-64::rtree-0.8.3-py37_0
  altair             conda-forge/osx-64::altair-2.4.1-py37_0
  branca             conda-forge/noarch::branca-0.3.1-py_0
  folium             conda-forge/noarch::folium-0.8.0-py_0
  geographiclib      conda-forge/noarch::geographiclib-1.49-py_0
  geopy              conda-forge/noarch::geopy-1.18.1-py_0
  osmnx              conda-forge/noarch::osmnx-0.9-py_0
  vincent            conda-forge/noarch::vincent-0.4.4-py_1
`

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

will communicate by email if this is picked up

**Comment by elibarzilay** [comment]
Good morning,

Quick question: did you try to install all of these packages with a single `conda install`?  Doing that should be much faster since you avoid doing dependency resolution five times, and in addition, separate installs might download different versions of the same package a few times as more version constraints are added.
