### ISSUE TITLE
Error: "The installed widget Javascript is the wrong version" - using ipywidgets for slider & drop-down controls

### ISSUE THREAD

**Issue by roguetrainer** [Microsoft/AzureNotebooks#65]
Please consider the template below to file your issue. 

### Description
Unable to get plotly's widget app to work on Azure:
https://plot.ly/python/widget-app/ 

### Repro Steps
Export the notebook from https://plot.ly/python/widget-app/ 
Upload the notebook to Azure. E.g.: 
https://notebooks.azure.com/n/bwo5DyyZbTw/notebooks/widget_app.ipynb 
Try to run.
Scroll to "Time to try the app out!!"
Error message:
"The installed widget Javascript is the wrong version. It must satisfy the semver range ~2.1.4. The widget Javascript is version 2.0.20."
Controls appear, but no chart.

### Usage Scenario (e.g. teaching a computing course at university foo)
Experimenting with ipwidgets, to evaluate using them for creating mini-apps.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):  Python 3.
Occurrence Time: 23 March 2017  2:50 pm
Web Browser: Chrome
LibraryID and Notebook Name (if applicable): 
https://notebooks.azure.com/.../libraries/plotly01
https://notebooks.azure.com/n/bwo5DyyZbTw/notebooks/widget_app.ipynb.ipynb# 
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Thanks for report - we just upgraded them to 6.0.0 today.  can you try in a
/new/ library and let us know?  thx!

**Comment by roguetrainer** [comment]
Thanks all for doing the upgrade. Sorry for the delay in testing this. 
I recreated the notebook in a new library (plotly002).
The error message is gone. The widgets appear correctly, but not the dynamically updated chart.  
(l do not need this feature but am sharing this result in case it is useful. So low priority.) Thanks.
https://notebooks.azure.com/library/plotly002/dashboard
https://notebooks.azure.com/n/MVYhdixmdAQ/notebooks/widget_app.ipynb

**Comment by roguetrainer** [comment]
This example works fine: ipywidgets/docs/source/examples/Lorenz Differential Equations.ipynb
(Also in https://notebooks.azure.com/library/plotly002/)
