### ISSUE TITLE
Cannot load notebook in chrome (but in Firefox does)

### ISSUE THREAD

**Issue by jochensteinmetz** [Microsoft/AzureNotebooks#650]
Please describe your issue as completely as possible.
Cannot load notebook

It looks like machine is shutting down right after start or not starting at all.

#### Which site did you access us from?
  ==>   [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
see above
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Just try to start the resource and open the above notebook

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
current 20190304 CET
#### Which Web Browser(s) did you see the error in?
    [] Chrome  ==> here I have the issue
    [] Firefox ==> here it works
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
   ==>[] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/jochensteinmetz/projects/principles-of-machine-learning/html/Final%20Exam/Challenge_classification_real.ipynb

**Comment by rachelgshaffer** [comment]
Apologies that you're having trouble. To clarify, are you referring to running the notebook or looking at the preview?

**Comment by jochensteinmetz** [comment]
I cannot run the notebook

Gesendet mit der WEB.DE Mail App

Am 05.03.19 um 00:22 schrieb rachelgshaffer

**Comment by rachelgshaffer** [comment]
When you say "It looks like machine is shutting down right after start or not starting at all.", what are you seeing that makes you think that? If applicable, could you provide a screenshot?

**Comment by jochensteinmetz** [comment]
When I start the kernel, i get a status saying kernel started, the notebook tries to open in a new tab and fails there. When goung back the status of the kernel is shur down. Can try to create a screenshot tomorrow

Gesendet mit der WEB.DE Mail App

Am 05.03.19 um 00:24 schrieb rachelgshaffer

**Comment by rachelgshaffer** [comment]
OK, a few more clarifying questions..
1. By starting the kernel, do you mean clicking on the run button? Where are you seeing the status that the kernel has started if you aren't already looking at the notebook?
2. When it opens the new tab for the notebook, what do you see? Can you see the notebook but are unable to run cells or are you not even seeing the notebook?

**Comment by jochensteinmetz** [comment]
Hi, just to let you know. The problem is magically gone. Thanks for your support

Gesendet mit der WEB.DE Mail App

Am 05.03.19 um 00:22 schrieb rachelgshaffer

**Comment by rachelgshaffer** [comment]
Thanks for using Azure Notebooks!
