### ISSUE TITLE
FileNotFoundErro

### ISSUE THREAD

**Issue by nosotrosf** [Microsoft/AzureNotebooks#651]
Please describe your issue as completely as possible.

I ran the script some days ago and work fine. 

Not I'm getting **FileNotFoundError** when try to open the file
Features = np.array(pd.read_csv('Credit_Features.csv'))

But the file always has been in this place.

Thanks in advance
Luis E. Fernandez

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [x] Python 3
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
03/5/2019 11:11 AM

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
My Projects/DAT275x Principles of Machine Learning - Python Edition/ Module 5/CrossValidation.ipynb

    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them ---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-9413b841d1ff> in <module>()
----> 1 Features = np.array(pd.read_csv('Credit_Features.csv'))
      2 Labels = np.array(pd.read_csv('Credit_Labels.csv'))
      3 print(Features.shape)
      4 print(Labels.shape)

~/anaconda3_420/lib/python3.5/site-packages/pandas/io/parsers.py in parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, escapechar, comment, encoding, dialect, tupleize_cols, error_bad_lines, warn_bad_lines, skipfooter, skip_footer, doublequote, delim_whitespace, as_recarray, compact_ints, use_unsigned, low_memory, buffer_lines, memory_map, float_precision)
    644                     skip_blank_lines=skip_blank_lines)
    645 
--> 646         return _read(filepath_or_buffer, kwds)
    647 
    648     parser_f.__name__ = name

~/anaconda3_420/lib/python3.5/site-packages/pandas/io/parsers.py in _read(filepath_or_buffer, kwds)
    387 
    388     # Create the parser.
--> 389     parser = TextFileReader(filepath_or_buffer, **kwds)
    390 
    391     if (nrows is not None) and (chunksize is not None):

~/anaconda3_420/lib/python3.5/site-packages/pandas/io/parsers.py in __init__(self, f, engine, **kwds)
    728             self.options['has_index_names'] = kwds['has_index_names']
    729 
--> 730         self._make_engine(self.engine)
    731 
    732     def close(self):

~/anaconda3_420/lib/python3.5/site-packages/pandas/io/parsers.py in _make_engine(self, engine)
    921     def _make_engine(self, engine='c'):
    922         if engine == 'c':
--> 923             self._engine = CParserWrapper(self.f, **self.options)
    924         else:
    925             if engine == 'python':

~/anaconda3_420/lib/python3.5/site-packages/pandas/io/parsers.py in __init__(self, src, **kwds)
   1388         kwds['allow_leading_cols'] = self.index_col is not False
   1389 
-> 1390         self._reader = _parser.TextReader(src, **kwds)
   1391 
   1392         # XXX

pandas/parser.pyx in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)()

pandas/parser.pyx in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)()

**Comment by rachelgshaffer** [comment]
Sorry to hear you're experiencing an issue. Can you provide a link to the notebook (if it's public)? One possible workaround would be to restart the kernel:
![image](https://user-images.githubusercontent.com/10291901/53825532-5ee94400-3f2b-11e9-967b-42f2baebdafd.png)

**Comment by nosotrosf** [comment]
Thank you
This is my link:
Microsoft Azure Notebooks - Online Jupyter Notebooks


| 
| 
|  | 
Microsoft Azure Notebooks - Online Jupyter Notebooks

Provides free online access to Jupyter notebooks running in the cloud on Microsoft Azure.
 |

 |

 |


I don't know if it is public. The script that I'm try to run is related with:


    On Tuesday, March 5, 2019, 12:45:17 PM EST, rachelgshaffer <notifications@github.com> wrote:  
 
 
Sorry to hear you're experiencing an issue. Can you provide a link to the notebook (if it's public)? One possible workaround would be to restart the kernel:

**Comment by nosotrosf** [comment]
Hi, 

My script is at:
Microsoft Azure Notebooks - Online Jupyter Notebooks


| 
| 
|  | 
Microsoft Azure Notebooks - Online Jupyter Notebooks

Provides free online access to Jupyter notebooks running in the cloud on Microsoft Azure.
 |

 |

 |


This script is related with this course:DAT275x Principles of Machine Learning - Python Edition
Module 5, CrossValidation.ipynb
Any help will be appreciated!Thank++Luis

    On Tuesday, March 5, 2019, 12:45:17 PM EST, rachelgshaffer <notifications@github.com> wrote:  
 
 
Sorry to hear you're experiencing an issue. Can you provide a link to the notebook (if it's public)? One possible workaround would be to restart the kernel:

**Comment by rachelgshaffer** [comment]
It seems like you may be responding through email and unfortunately the response looks quite garbled and I don't see a link. I am looking for something like: https://notebooks.azure.com/rashaf/projects/introprog-lect6

**Comment by nosotrosf** [comment]
Hi,Please, check it
https://dat275x-nosotrosf.notebooks.azure.com/j/notebooks/Module%205/CrossValidation.ipynb

Thanks++Luis   
 On Tuesday, March 5, 2019, 1:53:02 PM EST, rachelgshaffer <notifications@github.com> wrote:  
 
 
It seems like you may be responding through email and unfortunately the response looks quite garbled and I don't see a link. I am looking for something like: https://notebooks.azure.com/rashaf/projects/introprog-lect6

**Comment by nosotrosf** [comment]
Hi,
Could you let me know the status of my issue?
https://dat275x-nosotrosf.notebooks.azure.com/j/notebooks/Module%205/CrossValidation.ipynb

   FileNotFoundError
This script belong to "DAT275x Principles of Machine Learning - Python Edition" chapter 5, Cross Validation.ipynb.

Thanks in advanceLuis E Fernandez
On Tuesday, March 5, 2019, 1:53:02 PM EST, rachelgshaffer <notifications@github.com> wrote:  
 
 
It seems like you may be responding through email and unfortunately the response looks quite garbled and I don't see a link. I am looking for something like: https://notebooks.azure.com/rashaf/projects/introprog-lect6

—
You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or mute the thread.

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
FileNotFoundErro · Issue #651 · Microsoft/AzureNotebooks

Please describe your issue as completely as possible. I ran the script some days ago and work fine. Not I'm gett...
 |

 |

 |





| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Build software better, together

GitHub is where people build software. More than 31 million people use GitHub to discover, fork, and contribute ...
 |

 |

 |

**Comment by rachelgshaffer** [comment]
I was just able to clone your project and read from the cells without any problem. You may be running into an intermittent issue. As mentioned, restarting the kernel should help. Can you try that?

**Comment by nosotrosf** [comment]
Hi,
Yes, I did Kernel->Restart & Clear Output. I did Kernel->Restart.
But I got the same error. 
I tried with Edge also, and I got the same error.
May I do some else?
Thanks in advance
    On Wednesday, March 6, 2019, 3:37:23 PM EST, Rachel Shaffer <notifications@github.com> wrote:  
 
 
I was just able to clone your project and read from the cells without any problem. You may be running into an intermittent issue. As mentioned, restarting the kernel should help. Can you try that?

**Comment by nosotrosf** [comment]
Hi,
I attaching my trace, may be it help you.
Thanks in advanceLuis E. Fernandez


    On Wednesday, March 6, 2019, 3:37:23 PM EST, Rachel Shaffer <notifications@github.com> wrote:  
 
 
I was just able to clone your project and read from the cells without any problem. You may be running into an intermittent issue. As mentioned, restarting the kernel should help. Can you try that?

**Comment by rachelgshaffer** [comment]
Hmm, changing the kernel should mitigate the issue. Can you also try changing the kernel to a different language and then changing it back? Another workaround that should work is using an absolute file path - prefix the file name with `/home/nbuser/library`. So for the file `Credit_Features.csv`, use `/home/nbuser/library/Credit_Features.csv` instead.

**Comment by andneilmsft** [comment]
As we have not heard back from you in a month we are closing this thread. Please reactivate it if this is still a problem
