### ISSUE TITLE
Kernel Dies Every Time I ran the Code

### ISSUE THREAD

**Issue by Pabla007** [Microsoft/AzureNotebooks#652]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com

#### Which language/kernel were you using when you experienced this issue?
     Python 2.7 

#### What time (please include time zone) did this occur?
9:23:29 AM 
Sunday, March 10, 2019 
India Standard Time (IST) +0530 UTC

#### Which Web Browser(s) did you see the error in?
     Chrome (In Windows)
     Firefox (In Linux)

#### Which Operating System are you using? Please specify version as well if possible:
     Windows 10 
and 
    Ubuntu 18.0.1 (both)

#### https://testinggui-pabla007.notebooks.azure.com/j/notebooks/PyQT(1).ipynb
    
My Code :
import ipywidgets as widgets
from IPython.display import display

get_ipython().enable_gui('qt')
get_ipython().enable_matplotlib('inline')

from PyQt5.QtWidgets import QFileDialog

def gui_fname(dir=None):
    """Select a file via a dialog and return the file name."""
    if dir is None: dir ='./'
    fname = QFileDialog.getOpenFileName(None, "Select data file...", 
                dir, filter="All files (*);; SM Files (*.sm)")
    return fname[0]
button = widgets.Button(description="Choose File  !!")
button.style.button_color = 'yellow'
display(button)

def on_button_clicked(b):
    print("Button clicked.")
    %matplotlib qt
    f=gui_fname()
    %matplotlib inline
    #print "file selected successfully"
    #import fileplot
    #fileplot.load_file(f)
    

button.on_click(on_button_clicked)

Problem :
Kernel dies every time when i run the program but it works if i run it locally in my pc 
![kernel](https://user-images.githubusercontent.com/35897183/54080545-507a9e00-4318-11e9-94a1-ee727a9de892.PNG)

Like this I want to take file from user When I implement it remotely can you help me this issue .

What i want is i am making a file dialog box that takes file from user directly from his Local pc rather than upload it to azure storage and can compute it directly. I have achieved it locally but when i implement it azure the kernel dies every time and i am not able to get the output.
![22](https://user-images.githubusercontent.com/35897183/54080524-c16d8600-4317-11e9-9362-a219b0d5e8f7.PNG)
I want like this to happen from azure notebook also.

**Comment by rachelgshaffer** [comment]
Sorry to hear about this. Could you possibly make the project public (via "Project Settings") so that I can attempt to reproduce the issue?

![image](https://user-images.githubusercontent.com/10291901/54149516-95273780-43f3-11e9-845d-25b28c7d611b.png)

**Comment by Pabla007** [comment]
I have done it public now you can check it.

**Comment by elibarzilay** [comment]
@Pabla007, I tried your code, and it seems like if you'll run on the more recent 3.6 kernel, things work a bit better.  But "better" is only in giving some errors about working in headless mode.

The thing is that you're trying to do something via QT which normally uses the local GUI for things like a file dialog.  I think that there are some parts of QT that get redirected through the web interface, but not all of them.  So if you're getting such errors involving "headless mode" it means that it's trying to do something that can only run on a local machine via X.

Another sidenote: when the kernel dies, you can start a terminal from the same project, and look at the `.nb.log` file in your home directory: that file has the output of the jupyter process, and you can see there if there is any more useful information.  At least for me, when I tried your code and variations of it, that log had an error saying `QWidget: Must construct a QApplication before a QWidget`.  I'm just mentioning this as another resource you can use when you're trying to debug your code.

**Comment by govirginia** [comment]
what do you mean "home" directory.  I see no .nb.log file on failures to connect

**Comment by Sumeshks29** [comment]
I am also facing the same issue. the code runs once after attempting 20 times or so. Every time the Kernel dies and restarts. The memory isn't over shooting, nor am I running multi-thread process.
