### ISSUE TITLE
MICROSOFT AZURE NOTEBOOK NOT WORKING

### ISSUE THREAD

**Issue by Ani0812** [microsoft/AzureNotebooks#654]
Hey

I've been using Microsoft Azure Notebook for learning python. It was working quite fine around three or four days back, however, since the last three days its taking too long for the page to load. My notebooks aren't opening and my machine hangs up. When they do something like as shown in the picture happens.
Please help.
![ss](https://user-images.githubusercontent.com/48709775/54588708-b74f3400-4a49-11e9-8573-4d770370c49b.png)

**Comment by davidefiocco** [comment]
Hi! Can you share a link to an example (e.g. a public project of yours)? Have you tried running on a different web browser?
