### ISSUE TITLE
Add PowerShell support

### ISSUE THREAD

**Issue by TravisEz13** [microsoft/AzureNotebooks#655]
Please describe your issue as completely as possible.

#### Which site did you access us from?

- [x] https://notebooks.azure.com
- [ ] https://studio.azureml.net

#### Describe the issue you are encountering

Cannot run PowerShell

This can be run using:
~~https://github.com/Jaykul/Jupyter-PowerShell~~
Update: https://github.com/dotnet/interactive is a better implementation

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

create a `test.ps1` with `write-host 'test'` and try to run it

#### Which language/kernel were you using when you experienced this issue?
- [ ] Python 2.7 
- [ ] Python 3.5
- [ ] Python 3.6 
- [ ] R 
- [ ] F#
- [ ] Terminal
- [x] PowerShell Core

#### Which Web Browser(s) did you see the error in?
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer / Edge (Please note this is not supported)
- [ ] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
- [ ] Windows
- [x] MacOS
- [ ] Ubuntu
- [ ] Other (Please Specify)

**Comment by kilasuit** [comment]
I just tagged another issue where recent support in https://github.com/dotnet/interactive may help in  providing this functionality within Azure NoteBooks

**Comment by TravisEz13** [comment]
@kilasuit is right, definitely should use dotnet/interactive.  I updated the original issue description.
