### ISSUE TITLE
Your notebook server appears to be unresponsive

### ISSUE THREAD

**Issue by quadfather85** [Microsoft/AzureNotebooks#656]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
notebook server is unresponsive tried restarting the notebook server refreshing the page still can't access my notebook
![Annotation 2019-03-20 143820](https://user-images.githubusercontent.com/31605846/54714010-f9e24080-4b1d-11e9-84ab-a0e4dd2cfdae.png)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [x] Terminal

#### What time (please include time zone) did this occur?
1:30pm CST
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/quadfather/projects/essential-math-for-machine-lea/restart

**Comment by rachelgshaffer** [comment]
Sorry to hear you're having trouble. Can you visit your project page - the same URL you provided WITHOUT /restart at the end and tell me what the status says now?

**Comment by quadfather85** [comment]
it goes straight to
![image](https://user-images.githubusercontent.com/31605846/54717892-38302d80-4b27-11e9-88b0-be9011d7305a.png)

**Comment by rachelgshaffer** [comment]
are you looking at the project page? as in the page that shows the files? something like this:
https://notebooks.azure.com/rashaf/projects/imagetest
![image](https://user-images.githubusercontent.com/10291901/54718020-d071e680-4b16-11e9-8fb7-2bd4bee1dd80.png)

**Comment by rachelgshaffer** [comment]
May seem like a silly question but are you logged into your account? Could you try logging out and logging back in?

**Comment by quadfather85** [comment]
Well, something as small as logging out and back in worked thank!
