### ISSUE TITLE
Error "Unexpected polling state invalid_grant" when logging in to Azure

### ISSUE THREAD

**Issue by sjohner** [microsoft/AzureNotebooks#658]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Unable to sign in to Azure. Getting error "Unexpected polling state invalid_grant" when trying to sign in. Tried either Azure CLI `!az login` or `azureml.core` library. I am redirected to the device login page, can enter the code and it tells me that I have signed in to the Microsoft Azure Cross-platform Command Line Interface application on my device.

However when switching back to the Azure Notebook, the above mentioned error appears.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://azuremlgettingstarted-stefanjohner.notebooks.azure.com/j/notebooks/01.run-experiment.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

1700 UTC+1

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://azuremlgettingstarted-stefanjohner.notebooks.azure.com/j/notebooks/01.run-experiment.ipynb

**Comment by arkosark** [comment]
I am getting the same error. 
@sjohner Did you hear anything from Microsoft or solve the problem?
https://azuremlgettingstarted-arka.notebooks.azure.com/j/notebooks/01.run-experiment.ipynb

Appreciate your help!!

**Comment by sjohner** [comment]
No, i did not hear anything from Microsoft. I suspect it to be an issue with conditional access rules configured in our environment

**Comment by shibbas** [comment]
Hi, since you are using Azure CLI login, you might be hitting the issue described here: https://github.com/Azure/azure-cli/issues/6095.
