### ISSUE TITLE
Cannot run Python code 

### ISSUE THREAD

**Issue by hidelensman** [microsoft/AzureNotebooks#659]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Am learning the "DAT257x: Reinforcement Learning Explained" course and using Azure Notebook (Jupyter) to do the lab. Previously it worked well but I haven't been able to run the Python Codes since Mar 22, 2019. I tried to restart the Kernel and re-run the notebook, but no response from the notebook.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Open the notebooks and press the button of "run" or "restart the Kernel and re-run...". No responses.
https://dat257x-anons3xwqw.notebooks.azure.com/j/notebooks/LabFiles/Module%204/Ex4.1%20Policy%20Evaluation%202%20Arrays-Practice.ipynb
https://dat257x-anons3xwqw.notebooks.azure.com/j/notebooks/LabFiles/Ex%205.2%20SARSA%20Agent_P.ipynb

#### Which language/kernel were you using when you experienced this issue?

    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 

Have tried Python 2.7, 3.5, and 3.6 - all trials were in vain.

#### What time (please include time zone) did this occur?
Since Mar 22, 2019 (Taipei Time)

#### Which Web Browser(s) did you see the error in?
    [] Firefox
    [] Internet Explorer / Edge

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

Windows 10 64bit

**Comment by rachelgshaffer** [comment]
I'm sorry to hear you're running into issues. Could you try logging out of the site, and then logging back in?
