### ISSUE TITLE
Share link not working

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/AzureNotebooks#66]
### Metadata
Python3
~2:45 PM 3/23/17
Web Browser: IE/Edge
STUDENT_3-23 library
Share Link: https://notebooks.azure.com/home/libraries/DnFhT4OU0Ig

**Comment by atifield** [comment]
I think the notebook has to be public before sharing is allowed.

**Comment by crwilcox** [comment]
Also, /home/ means you don't have a user id. I think that may be the issue. Can you try creating a user id here: https://notebooks.azure.com/account/settings? 

I think you found an issue trying to share without one.

**Comment by crwilcox** [comment]
Closing as we have rolled out a change that makes sure everyone has user ids.
