### ISSUE TITLE
Nbextensions gets reset after the NotebookServer restart

### ISSUE THREAD

**Issue by SriramAvatar** [microsoft/AzureNotebooks#660]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I have a set a few nbextensions like freeze, RunTools etc on my notebook. After a warning from the notebook about the cache/cookies, I cleared the browser cache and cookies. Then I got a red warning on the Azure Notebooks Project page stating that the notebook server has to be restarted. After restarting, I notice that the nbextensions are reset on my notebook.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
I think this will not be accessible, but incase you need the account under which this ran(sriram.narayanan@codit.eu)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
    
#### What time (please include time zone) did this occur?
around 11 AM CEST(2/April/2019)

#### Which Web Browser(s) did you see the error in?
    [] Chrome
   
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by gilbertw** [comment]
Can you clarify "I have a set a few nbextensions like freeze, RunTools etc on my notebook."  Are you merely enabling them from the jupyter extensions tab or are you doing something special to configure them in the  container?

**Comment by SriramAvatar** [comment]
I added them from the Jupyter notebook menu : Edit>>nbextensions config.
![image](https://user-images.githubusercontent.com/16073195/55435165-959d9300-5599-11e9-9f43-b03506f198f7.png)
