### ISSUE TITLE
Location and Azure data center

### ISSUE THREAD

**Issue by plillevold** [Microsoft/AzureNotebooks#661]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
This is a request for information: is there any documentation on which data center a notebook will be executed in? And if possible, is there any way to configure preferred locations?

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by KieranBrantnerMagee** [comment]
Hey Plillevold,
For the time being, yes.  Your notebook will execute within the South Central US region if you're launching from notebooks.azure.com.  

This may change in the future if additional georeplication is enabled, we will attempt to notify users and update our documentation on docs.microsoft.com if this comes to pass.

For future reference and completeness, users coming in via studio.azureml.net's non US regions will be provided notebooks running within that same region.

Don't hesitate to shout/reopen this if you have any further questions/if any clarification is needed.
Thanks for using Notebooks!
