### ISSUE TITLE
geom_rect() shows empty plot

### ISSUE THREAD

**Issue by tmandzak** [microsoft/AzureNotebooks#662]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

`geom_rect()` shows empty plot when using continuous variable for `fill` parameter in `aes()`:

```
ggplot(DF_all, aes(ymin = ymin,
                 ymax = ymax,
                 xmin = xmin,
                 xmax = xmax,
                 fill = residual)) +
  geom_rect()
```
The code above works in DataCamp environment. The code above also works for `fill = FILL` being `chr`.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Bug chapter at the end of https://dcggplot2-tarasmandzak.notebooks.azure.com/j/notebooks/California%20Health%20Information%20Survey.ipynb#Bug

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify)  Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by antkmsft** [comment]
Unfortunately, the notebook with the repro steps is no longer available.
But we have recently deployed an R kernel update that could potentially resolve this problem.
Please reactivate this issue if you still see the problem. Thanks for using Azure Notebooks!
