### ISSUE TITLE
stringr package needs installation

### ISSUE THREAD

**Issue by tmandzak** [microsoft/AzureNotebooks#663]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

`library("tidyverse")` produces error:
```
Error: package or namespace load failed for ‘tidyverse’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringr’
```
so that `install.packages("stringr")` needs to be executed each time.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Just type `library("tidyverse")`

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [x] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [x] Other (Please Specify) Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by antkmsft** [comment]
We have recently deployed a fix that should resolve this problem.
Please reactivate this issue if you still see the issue. Thank you for using Azure Notebooks!
