### ISSUE TITLE
Error trying to open Terminal

### ISSUE THREAD

**Issue by mikenewman1** [Microsoft/AzureNotebooks#664]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I click on the button to open a terminal. I get an error message
``` We're sorry, an error has occured while processing your request.
Please try again or report the issue on GitHub or via e-mail.
The error is tracked by id: 9e125cf8-3b52-4162-a68b-fb1394a783a6 ```

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/mike-newman/projects/my-copy-of-enwiki8/run/terminals/1

### Optional, but often helpful:
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
9:28AM EST

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
I tried the `!cat .nb.log` command to get the logs, but that just gave me an error (and now I think my kernel might be in a bad state)

**Comment by mikenewman1** [comment]
I think the problem was that I was not signed in (I'm running on free compute, and it had timed out) but it did not give me any useful troubleshooting.
I actually seem to be running into this a lot. I get `kernel error` messages, rather than `you need to sign in`

**Comment by KieranBrantnerMagee** [comment]
Hey Mike,
Thanks for pinging us on this.  We've recently taken some fixes internally to address some aspects of this class of problem (The lack of clues that you were signed-out on a timer) and have added your scenario to the list.  Can't give promises to when we'll work through that queue but better feedback should start occurring around the site as these changes begin to role out in the near term.


Thanks for your patience and for using notebooks!
