### ISSUE TITLE
Cannot open ipynb

### ISSUE THREAD

**Issue by jellyfishrui** [Microsoft/AzureNotebooks#666]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Cannot open ipynb. The error is tracked by id: 0936ffe8-f003-4ddf-ae7f-2bc5b035e759 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/zhan305/projects/tap-analysis/run/notebooks/DataProcessing.ipynb

#### Which language/kernel were you using when you experienced this issue?

    [Python 3.6 

#### What time (please include time zone) did this occur?
8:10 PM PST

#### Which Web Browser(s) did you see the error in?

    [] Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by andneilmsft** [comment]
Is zhan305 your account? If not the notebook you are trying to run is either private or has been deleted. here is a list of projects that are publicly shared by zhan305:

https://notebooks.azure.com/zhan305/projects

**Comment by andneilmsft** [comment]
Please reactivate when you have more information.
