### ISSUE TITLE
!curl command not working in notebook or on server

### ISSUE THREAD

**Issue by shanamatthews** [Microsoft/AzureNotebooks#668]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

running "! curl https://www.transtats.bts.gov/Download_Lookup.asp\?Lookup\=L_AIRPORT -o 'airports.csv'" in an Azure Notebook cell results in error - curl: (56) Received HTTP code 503 from proxy after CONNECT

Running the same command on the server throught the terminal results in the same.

However, running the command in Jupyter locally or on my local terminal downloads the file with no issues.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://learn2-shanamatthews.notebooks.azure.com/j/lab

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

Has occurred for weeks.

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/shanamatthews/projects/learn2/html/learnpython.ipynb
  
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

---
[I 17:27:37.860 NotebookApp] Using MathJax: /OpenSource/mathjax_2-7-5/MathJax.js
[I 17:27:37.910 NotebookApp] Writing notebook server cookie secret to /home/nbuser/.local/share/jupyter/runtime/notebook_cookie_secret
[W 17:27:38.810 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 17:27:38.810 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 17:27:39.261 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
[I 17:27:39.437 NotebookApp] JupyterLab beta preview extension loaded from /usr/local/lib/python2.7/dist-packages/jupyterlab
[I 17:27:39.438 NotebookApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 17:27:39.502 NotebookApp] Serving notebooks from local directory: /home/nbuser/library
[I 17:27:39.503 NotebookApp] 0 active kernels
[I 17:27:39.503 NotebookApp] The Jupyter Notebook is running at:
[I 17:27:39.503 NotebookApp] http://nbserver:25198/nb/
[I 17:27:39.504 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 19:45:46.580 NotebookApp] Could not open static file ''
[W 19:45:46.582 NotebookApp] 404 GET / (10.36.5.1) 94.72ms referer=None
[W 19:45:46.589 NotebookApp] 404 GET / (10.36.5.1) 1.50ms referer=None
[W 19:45:46.597 NotebookApp] 404 GET / (10.36.5.1) 7.18ms referer=None
[W 19:45:46.599 NotebookApp] 404 GET / (10.36.5.1) 1.19ms referer=None
[W 19:45:48.119 NotebookApp] 404 GET / (10.36.5.1) 1.86ms referer=None
[I 19:45:49.112 NotebookApp] Kernel started: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[I 19:45:56.516 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[I 19:45:56.517 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[I 19:45:56.517 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 19:55:48.099 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:9358873db7237dcae1e7ad460d3808c9
[I 19:55:53.101 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 19:55:58.100 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:7058ee1e84ab0cac78a50b29ce37e28f
[I 19:56:03.103 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 20:05:38.039 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:9358873db7237dcae1e7ad460d3808c9
[I 20:05:43.043 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 20:05:58.045 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:7058ee1e84ab0cac78a50b29ce37e28f
[I 20:06:03.048 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
TermSocket.open: 1
[I 20:13:43.774 NotebookApp] New terminal with specified name: 1
TermSocket.open: Opened 1
[W 20:15:27.308 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:9358873db7237dcae1e7ad460d3808c9
[I 20:15:32.312 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 20:15:47.109 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:7058ee1e84ab0cac78a50b29ce37e28f
[I 20:15:52.114 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 20:25:13.774 NotebookApp] WebSocket ping timeout after 119994 ms.
Websocket closed
[I 20:28:15.026 NotebookApp] Starting buffering for 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:9358873db7237dcae1e7ad460d3808c9
[I 21:20:33.854 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[I 21:20:37.286 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 21:30:31.188 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:7058ee1e84ab0cac78a50b29ce37e28f
[E 21:30:33.856 NotebookApp] Exception in callback <bound method ZMQChannelsHandler.send_ping of ZMQChannelsHandler(25ec18f5-71e3-4aa2-8eae-7157e1aa55fe)>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 1041, in _run
        return self.callback()
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/zmqhandlers.py", line 189, in send_ping
        self.ping(b'')
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 260, in ping
        raise WebSocketClosedError()
    WebSocketClosedError
[W 21:30:36.127 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:9358873db7237dcae1e7ad460d3808c9
[I 21:30:36.189 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[E 21:30:36.200 NotebookApp] Uncaught exception GET /nb/api/kernels/25ec18f5-71e3-4aa2-8eae-7157e1aa55fe/channels?session_id=9358873db7237dcae1e7ad460d3808c9 (10.36.5.1)
    HTTPServerRequest(protocol='http', host='40.74.244.87:6999', method='GET', uri='/nb/api/kernels/25ec18f5-71e3-4aa2-8eae-7157e1aa55fe/channels?session_id=9358873db7237dcae1e7ad460d3808c9', version='HTTP/1.1', remote_ip='10.36.5.1', headers={})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 196, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/usr/local/lib/python2.7/dist-packages/notebook/services/kernels/handlers.py", line 418, in _on_zmq_reply
        super(ZMQChannelsHandler, self)._on_zmq_reply(stream, msg)
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/zmqhandlers.py", line 250, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 210, in write_message
        raise WebSocketClosedError()
    WebSocketClosedError
[W 21:30:36.206 NotebookApp] Got events for closed stream None
[I 21:30:36.211 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
TermSocket.open: 1
TermSocket.open: Opened 1
[W 21:40:20.374 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:7058ee1e84ab0cac78a50b29ce37e28f
[I 21:40:25.376 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe
[W 21:40:30.309 NotebookApp] Replacing stale connection: 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe:9358873db7237dcae1e7ad460d3808c9
[I 21:40:35.312 NotebookApp] Adapting to protocol v5.1 for kernel 25ec18f5-71e3-4aa2-8eae-7157e1aa55fe

**Comment by andneilmsft** [comment]
I was not able to get your command line to work, but i was able to curl this one time, the API appears very slow and sometimes it fails. 

!curl www.transtats.bts.gov/Download_Lookup.asp?Lookup=L_AIRCRAFT_GROUP -o 'aircraft.csv'

Code,Description
"0","Piston, 1-Engine/Combined Single Engine (Piston/Turbine)"
"1","Piston, 2-Engine"
"2","Piston, 3-Engine/4-Engine"
"3","Helicopter/Stol"
"4","Turbo-Prop, 1-Engine/2-Engine"
"5","Turbo-Prop, 4-Engine"
"6","Jet, 2-Engine"
"7","Jet, 3-Engine"
"8","Jet, 4-Engine/6-Engine"
"9","Used for capturing expenses not attributed to specific aircraft types"

**Comment by shanamatthews** [comment]
Interesting. I can't get that call to work in the notebook either but consistently works fine locally. Are you seeing similar? Why would the behavior be different on the notebook server?

**Comment by andneilmsft** [comment]
I wasn't able to get your url to CURL locally or from azure notebooks. i got 404.  the url i shared i got to work from time to time locally and from time to time in azure notebooks. If it works for you locally, as a work around you could pull the csv down and upload it into your notebook. I know that this is only a snapshot, but it seems to me like there are issues with the APIs rather than the notebook service.

**Comment by shanamatthews** [comment]
Yeah, I just tried on powershell and also got a 404. Works fine on WSL. Will just host the needed file elsewhere for my purposes. Thanks for looking into it!

**Comment by andneilmsft** [comment]
thanks for using azure notebooks and for getting in touch.
