### ISSUE TITLE
Online demo of Anomaly Detector API is broken

### ISSUE THREAD

**Issue by sharontf** [Microsoft/AzureNotebooks#669]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Link to online demo of Anomaly Detector API is broken

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://github.com/Azure-Samples/anomalydetector
Scroll down to Demo and click on the link to online demo -> it leads to this link: https://notebooks.azure.com/AzureAnomalyDetection/projects/anomalyfinder
which is broken

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
4:20pm Pacific Time

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/AzureAnomalyDetection/projects/anomalyfinder

**Comment by andneilmsft** [comment]
looks like a typo in the documentation, try this link: 

https://notebooks.azure.com/AzureAnomalyDetection/projects/anomalydetector
