### ISSUE TITLE
Whitelist VSTS REST API

### ISSUE THREAD

**Issue by atifield** [Microsoft/AzureNotebooks#67]
### Description

https://microsoft.visualstudio.com used to be whitelisted but now it is not

### Repro Steps

Access to VSTS REST API returns 

URLError: <urlopen error Tunnel connection failed: 403 Forbidden>

### Usage Scenario (e.g. teaching a computing course at university foo)

Triggering a VSTS build or getting build information from Azure Notebook

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python3
Occurrence Time: 3/23/2017
Web Browser: Chrome

**Comment by DinoV** [comment]
Thanks for the feedback, I've added this to the white list
