### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by omnekkanti** [microsoft/AzureNotebooks#670]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-e3a17b6d23fe> in <module>
      7 import logging
      8 import os
----> 9 from azureml.train.automl import AutoMLConfig
     10 
     11 # print to check azure sdk installation

~/anaconda3_501/lib/python3.6/site-packages/azureml/train/automl/__init__.py in <module>
     15 sys.path.append(vendor_folder)
     16 
---> 17 from automl.client.core.common.utilities import extract_user_data, get_sdk_dependencies
     18 
     19 from .automl import fit_pipeline

~/library/automl.py in <module>
      7 import logging
      8 import os
----> 9 from azureml.train.automl import AutoMLConfig
     10 # print to check azure sdk installation
     11 print(azureml.core.VERSION)

ImportError: cannot import name 'AutoMLConfig'

#### Which site did you access us from?
    [yes] https://notebooks.azure.com

#### Describe the issue you are encountering
import statement not working for AutoMLConfig
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://automatedml-omprakashnekkanti.notebooks.azure.com/j/notebooks/MLSERVICE.ipynb

#### Which language/kernel were you using when you experienced this issue?

    [yes] Python 3.6 
   
#### Which Web Browser(s) did you see the error in?
    [yes] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [yes] Windows
   

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/omprakash-nekkanti/projects/automatedml/MLSERVICE.ipynb

**Comment by davidefiocco** [comment]
That import statement works fine for me.

If that fails, maybe restart your notebook kernel and in a Jupyter cell run

`!pip install --upgrade azureml-sdk azureml-contrib-run`

And also

```
import azureml.core
# display the core SDK version number
print("Azure ML SDK Version: ", azureml.core.VERSION)
```

For any relatively recent version (you should be on 1.0.30 as of today), your import statement should work fine.
