### ISSUE TITLE
Can I embed Azure Notebook in iframe ?

### ISSUE THREAD

**Issue by chavalit** [Microsoft/AzureNotebooks#671]
Hi,

I would like to make some tutorial pages and wonder if I can embed public Azure Notebook in an iframe on my website ?

Thanks.

**Comment by andneilmsft** [comment]
Thanks for reaching out. The use-case you are describing is great, unfortunately we do not support it today.

**Comment by chavalit** [comment]
Hi @andneilmsft 
Thanks a lot for your confirmation.
Have a nice day.
