### ISSUE TITLE
py 3.7 support

### ISSUE THREAD

**Issue by jwlockhart** [Microsoft/AzureNotebooks#673]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Please add a python 3.7 kernel option, with associated newer package versions.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
n/a

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [X] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
n/a

**Comment by andneilmsft** [comment]
Thanks for getting in touch. Python 3.7 is in the roadmap for later this year.
