### ISSUE TITLE
After cloning https://notebooks.azure.com/azureml/projects/azureml-getting-started opening the notebook resolves in opening jupyter with an error that just says error loading notebook. 

### ISSUE THREAD

**Issue by gingerchris86** [Microsoft/AzureNotebooks#674]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
After cloning https://notebooks.azure.com/azureml/projects/azureml-getting-started
opening the notebook resolves in opening jupyter with an error that just says error loading notebook. 
 
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://azuremlgettingstarted-djdimsim.notebooks.azure.com/j/notebooks/01.run-experiment.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
10:56AM AEST 
#### Which Web Browser(s) did you see the error in?
    [] Chrome
   
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
  

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
I Can't get to that as it wont let me near it

**Comment by andneilmsft** [comment]
Thanks for reaching out. I am not able to reproduce this. Please sign out of azure notebooks and try again.  if this problem still occurs reactivate this issue.
