### ISSUE TITLE
Cannot sign in 

### ISSUE THREAD

**Issue by lleellaa** [microsoft/AzureNotebooks#678]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I would like to create a notebook on Azure Notebooks to test Machine Learning Features of the Microsoft Azure Cloud. I tried to follow the instructions in the tutorial how to create and run a jupyter notebook (https://docs.microsoft.com/de-de/azure/notebooks/tutorial-create-run-jupyter-notebook). Unfortunately, it seems that I cannot sign in to https://notebooks.azure.com/. When I want to sign in, I'm redirected to the company's log in site and afterwards, I end up at the start page of notebooks.azure.com and I'm not signed in. On the top right corner, there is still the 'sign in' buttom. This happens whatever I try to do (e.g. cloning the getting started notebook run-experiment.ipynb, I'm forced to log in and redirected to the start page again). I already tried to sign in in inkognito mode and with different browsers (Edge and Chrome), but still can't sign in. Is there an issue with my account? I use the same company account to sign in that I use in the Azure Cloud (works perfectly in the Azure Cloud and on https://studio.azureml.net).

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
It has never worked so far.

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by pjmattingly** [comment]
I have the same problem.

Which site did you access us from?
[x] https://notebooks.azure.com
[] https://studio.azureml.net

What time (please include time zone) did this occur?
It has never worked so far.

Which Web Browser(s) did you see the error in?
[x] Chrome
[] Firefox
[] Internet Explorer / Edge (Please note this is not supported)
[] Other (Please Specify)

Which Operating System are you using? Please specify version as well if possible:
[x] Windows 10
[] MacOS
[] Ubuntu
[] Other (Please Specify)
