### ISSUE TITLE
R Notebooks: devtools R Package Not Working Due to Outdated Dependencies

### ISSUE THREAD

**Issue by cannin** [microsoft/AzureNotebooks#679]
#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

The devtools R package is described as the way to install in-development packages: 

https://notebooks.azure.com/help/jupyter-notebooks

but the devtools package for R notebooks is not usable

Error: package or namespace load failed for ‘devtools’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘callr’ 1.0.0 is being loaded, but >= 2.0.0 is required

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

In an R kernel notebook run: 

library(devtools)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [X] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

April 29, 2019 9AM, Eastern US time zone

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://devtoolserror-cannin.notebooks.azure.com/j/notebooks/tmp.ipynb

**Comment by antkmsft** [comment]
We have recently deployed a fix that should resolve this problem.
Please reactivate this issue if you still see the issue. Thank you for using Azure Notebooks!
