### ISSUE TITLE
Page Not Found on Homepage 

### ISSUE THREAD

**Issue by johnzens** [Microsoft/AzureNotebooks#68]
I was browsing through the homepage(notebooks.azure.com) and clicked the "Show me some samples" link, but i got a page not found error instead. 

Occurrence Time:
2017-03-26 1:45 pm (WAT) 

Web Browser:
Opera Mini

**Comment by smortaz** [comment]
thanks johnzens - i tried to repro the bug but i can't.  tried all the links on the front page and they seem to go to the right place.  the 'show me sample' links simply scrolls down the page to the various samples.
