### ISSUE TITLE
Some  Azure Notebooks users currently cannot Load projects

### ISSUE THREAD

**Issue by briglx** [Microsoft/AzureNotebooks#681]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Get error when loading project 
The error is tracked by id: 39068446-bf89-4071-9fef-745d1b8863eb

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Go to my projects.
Click on project to open.
Get error message

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
2:05 US Arizona

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://notebooks.azure.com/anon-3yc3bw/projects/learn-neural-networks

**Comment by andneilmsft** [comment]
Apologies for the downtime. Azure networking is currently experiencing a global DNS outage. This means that the azure notebooks site is not at this moment able to find a route to your project storage. You can follow the updates on the issue here: https://azure.microsoft.com/en-us/status/

Azure notebooks is tweeting on the impact of this to our service and we’re looking at mitigations for our site.

**Comment by andneilmsft** [comment]
DNS is coming back online. Some users will now be able to access their data.

**Comment by andneilmsft** [comment]
All users should now have access to their data.
