### ISSUE TITLE
Can't Install rstan

### ISSUE THREAD

**Issue by zacharyhimmelsbach** [microsoft/AzureNotebooks#683]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
I'm not able to install rstan. Is it not supported?

![image](https://user-images.githubusercontent.com/15902447/57157297-56d44600-6dae-11e9-8c13-7c8e7973c11a.png)

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

https://rtestnotebook-zacharyhimmelsbach.notebooks.azure.com/j/notebooks/Untitled.ipynb

#### Which language/kernel were you using when you experienced this issue?
    R

#### What time (please include time zone) did this occur?
2pm EST

#### Which Web Browser(s) did you see the error in?
    Firefox

#### Which Operating System are you using? Please specify version as well if possible:
    Windows

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://rtestnotebook-zacharyhimmelsbach.notebooks.azure.com/j/notebooks/Untitled.ipynb
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

I wasn't able to get to the tree page to launch the terminal (clicking on the jupyter symbol wasn't getting me to a different page, though the address appeared in my address bar).

**Comment by ellenwterry** [comment]
What's the status of rstan on azure notebooks?

**Comment by ellenwterry** [comment]
I'm able to install pystan, but not rstan.
