### ISSUE TITLE
Feature Request: GitHub Continuous Integration

### ISSUE THREAD

**Issue by t-eckert** [microsoft/AzureNotebooks#685]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I would like to set up an Azure Pipeline to continuously update a notebook project from GitHub.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

I have created a [GitHub repo](https://github.com/t-eckert/detecting-emotion-with-azure-cognitive-services-en) to help teachers use Azure Cognitive Services in the classroom. I cloned the repo to [notebooks](https://notebooks.azure.com/t-eckert/projects/acs-emotion). There is an existing deployment story where I manually update the notebook project by deleting and re-cloning the project for every update to the GitHub repo. I think a better solution could be developed using Azure Pipelines to deploy to Notebooks continuously.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [x] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Hi Thomas! Thanks for the input, we will factor this feedback into our future plans

**Comment by t-eckert** [comment]
Thanks @kkampf! Great to meet you at PyCon! Let me know if I can help in any way!
