### ISSUE TITLE
Accessing raspberry Pi cameras from an azure notebook

### ISSUE THREAD

**Issue by FrancescoCiriello** [microsoft/AzureNotebooks#687]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I would like to install the picamera module on a microsoft azure notebook to run a Pi Camera v2 on a raspberry pi.

I am trying to install in the notebook with:

!pip install picamera

Collecting picamera
  Using cached https://files.pythonhosted.org/packages/79/c4/80afe871d82ab1d5c9d8f0c0258228a8a0ed96db07a78ef17e7fba12fda8/picamera-1.13.tar.gz
Building wheels for collected packages: picamera
  Building wheel for picamera (setup.py) ... error
  ERROR: Complete output from command /home/nbuser/anaconda3_420/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-tec07ich/picamera/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7ktsjatj --python-tag cp35:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/picamera
  copying picamera/renderers.py -> build/lib/picamera
  copying picamera/mmal.py -> build/lib/picamera
  copying picamera/mmalobj.py -> build/lib/picamera
  copying picamera/array.py -> build/lib/picamera
  copying picamera/color.py -> build/lib/picamera
  copying picamera/exc.py -> build/lib/picamera
  copying picamera/streams.py -> build/lib/picamera
  copying picamera/bcm_host.py -> build/lib/picamera
  copying picamera/display.py -> build/lib/picamera
  copying picamera/encoders.py -> build/lib/picamera
  copying picamera/camera.py -> build/lib/picamera
  copying picamera/frames.py -> build/lib/picamera
  copying picamera/__init__.py -> build/lib/picamera
  running egg_info
  writing top-level names to picamera.egg-info/top_level.txt
  writing picamera.egg-info/PKG-INFO
  writing dependency_links to picamera.egg-info/dependency_links.txt
  writing requirements to picamera.egg-info/requires.txt
  reading manifest file 'picamera.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching 'debian'
  no previously-included directories found matching 'docs'
  writing manifest file 'picamera.egg-info/SOURCES.txt'
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-tec07ich/picamera/setup.py", line 145, in <module>
      main()
    File "/tmp/pip-install-tec07ich/picamera/setup.py", line 140, in main
      cmdclass             = {'install': CustomInstallCommand},
    File "/home/nbuser/anaconda3_420/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/nbuser/anaconda3_420/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 215, in run
      self.run_command('install')
    File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-tec07ich/picamera/setup.py", line 111, in run
      raise ValueError('Unable to determine if this system is a Raspberry Pi')
  ValueError: Unable to determine if this system is a Raspberry Pi
  ----------------------------------------
  ERROR: Failed building wheel for picamera
  Running setup.py clean for picamera
Failed to build picamera
Installing collected packages: picamera
  Running setup.py install for picamera ... error
    ERROR: Complete output from command /home/nbuser/anaconda3_420/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-tec07ich/picamera/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-39lr03wt/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tec07ich/picamera/setup.py", line 145, in <module>
        main()
      File "/tmp/pip-install-tec07ich/picamera/setup.py", line 140, in main
        cmdclass             = {'install': CustomInstallCommand},
      File "/home/nbuser/anaconda3_420/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/nbuser/anaconda3_420/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-tec07ich/picamera/setup.py", line 111, in run
        raise ValueError('Unable to determine if this system is a Raspberry Pi')
    ValueError: Unable to determine if this system is a Raspberry Pi
    ----------------------------------------
ERROR: Command "/home/nbuser/anaconda3_420/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-tec07ich/picamera/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-39lr03wt/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-tec07ich/picamera/

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [X] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

12 May 2019 at 19:00 GMT

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [X] Other (Please Specify)
Chromium
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [X] Other (Please Specify)
Raspbian

**Comment by christian-vorhemus** [comment]
What you're trying to achieve can't work because the picamera module requires direct access to the Raspberry Pi CSI interface while your Azure Notebook is running on VMs in the cloud and not directly on your Raspberry Pi.

If you want to work with notebooks and use native Raspberry Pi modules, [install Jupyter Notebooks](https://www.instructables.com/id/Jupyter-Notebook-on-Raspberry-Pi/) directly on your Raspberry Pi
