### ISSUE TITLE
caret package not installing in R notebook

### ISSUE THREAD

**Issue by LaurentPetit2019** [microsoft/AzureNotebooks#688]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
1) I've created a project from https://github.com/MicrosoftLearning/Principles-of-Machine-Learning-R
2) Trying to run the script Setup.ipynb as it is required for installing caret
<<
system("mkdir -p ~/.R", intern = TRUE)
system("cp ~/library/Makevars ~/.R/Makevars", intern = TRUE)
install.packages("caret", verbose = TRUE)
>>
3) It continuously generates the following error:
<<
Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
system (cmd0): /opt/microsoft/ropen/3.4.1/lib64/R/bin/R CMD INSTALL
also installing the dependencies ‘generics’, ‘recipes’

foundpkgs: generics, recipes, caret, /tmp/Rtmp1ZPxi6/downloaded_packages/generics_0.0.2.tar.gz, /tmp/Rtmp1ZPxi6/downloaded_packages/recipes_0.1.5.tar.gz, /tmp/Rtmp1ZPxi6/downloaded_packages/caret_6.0-84.tar.gz
files: /tmp/Rtmp1ZPxi6/downloaded_packages/generics_0.0.2.tar.gz, 
	/tmp/Rtmp1ZPxi6/downloaded_packages/recipes_0.1.5.tar.gz, 
	/tmp/Rtmp1ZPxi6/downloaded_packages/caret_6.0-84.tar.gz
1): succeeded '/opt/microsoft/ropen/3.4.1/lib64/R/bin/R CMD INSTALL -l '/home/nbuser/R' /tmp/Rtmp1ZPxi6/downloaded_packages/generics_0.0.2.tar.gz'
Warning message in install.packages("caret", verbose = TRUE):
“installation of package ‘recipes’ had non-zero exit status”Warning message in install.packages("caret", verbose = TRUE):
“installation of package ‘caret’ had non-zero exit status”
>>
4) Obviously caret does not install as I'm not able to run all further scripts that rely on caret package

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [X] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)
(also running it under OSX Safari... same error)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by antkmsft** [comment]
We have recently deployed a fix that should resolve this problem.
Please reactivate this issue if you still see the issue. Thank you for using Azure Notebooks!
