### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by bryanhpchiang** [microsoft/AzureNotebooks#689]
Just a few of my initial thoughts on Azure Notebooks. 

1. Love how it's structured like GitHub repositories - this is where Azure NB 10x better than Google Colab (difficult to share notebooks). The ability to clone notebooks + have projects that contain data/notebooks (that can access data directly without downloading each time) is incredible. 

2. Needs GPU support. I know there's the option to do this under DS/DL VMs but there needs to be a one-click, zero-configuration switch for *free* GPU acceleration. Super important since Colab already has this. 

3. Azure/GitHub NB integration. This is the holy grail - open a GitHub repository, click on a IPython notebook, and have an option to start playing around directly in an Azure Notebook. Sounds doable considering MSFT acquisition of GH - obviously people will complain about choice, but this would be so convenient.  Right now GH is static viewing only, too many steps involved in getting notebooks/GitHub repositories into Colab/NBviewer. Would be so nice if there's a continuous, all in one solution.

**Comment by kkampf** [comment]
Thanks for the feedback and for using Azure Notebooks! 

Glad to hear you're enjoying the experience and we appreciate your suggestions. We are working towards your ask in 2, and I encourage you to stay tuned for this and other enhancements in the future.
