### ISSUE TITLE
Writing Data Back to Datasets 

### ISSUE THREAD

**Issue by SG-Gank** [microsoft/AzureNotebooks#690]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    **[] https://studio.azureml.net**

#### Describe the issue you are encountering

After making  manipulation or running a model, how do I write the result/new data frame back to the "Dataset" folder in ML Studio? See example below: suppose I got this piece of data from another source and I made some changes to it. How would I then save it back to the "Dataset" folder for future modeling purposes? 

![image](https://user-images.githubusercontent.com/50460251/57889031-95272780-77e8-11e9-870e-cd2a87bf18bc.png)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by christian-vorhemus** [comment]
How about using ```add_from_dataframe()```?

```python
from azureml import Workspace, DataTypeIds
import pandas as pd
ws = Workspace()
frame = pd.DataFrame([[1,2,3],[4,5,6]], columns=list('ABC'))
ws.datasets.add_from_dataframe(frame, 
                               data_type_id=DataTypeIds.GenericCSV,
                               name="sample.csv",
                               description="Dataset description")
```
This will create a new dataset called sample.csv in your workspace.

**Comment by SG-Gank** [comment]
Awesome help @christian-vorhemus , 

Two other related questions: 
1. Is there a way to write/read data files directly from Sharepoint Site from my AzureML Notebook? 
2. Is there a way to connect PowerBI desktop directly to Azure ML WorkSpace's dataset?  (Say I did some manipulation and got results from my ML model, now I want to present this result in Power BI) 

Thanks bro!
