### ISSUE TITLE
There seems to be an issue connecting to the DSVM selected. Please check if you are able to connect to JupyterHub port at https://13.69.123.134:8000/ and retry.

### ISSUE THREAD

**Issue by JanderHungrige** [microsoft/AzureNotebooks#692]
Hi,

I started two differnt dsvm and tried to connect via azure notebooks: direct connect to it.
I get this error: 
There seems to be an issue connecting to the DSVM selected. Please check if you are able to connect to JupyterHub port at https://13.69.123.134:8000/ and retry.

- I tried to change the rules in the connection setting of the dsvm for ports 8000-8888.
- I added rules to my firewall to allow firefox to use those port
- I tried to ssh putty to the server without succsess.

I use a windows platform and the dsvm are also winservers

p.s. how can I check that jupyterhub is connected? Where do I find it?

Thank you for your help.
Best regards, 
Jan

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Differnt times during the week
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by JanderHungrige** [comment]
Security group needed to be added. 

Done

**Comment by JanderHungrige** [comment]
P.s. Sometime the security group needs to be renewed. Meaning, you have to unelect and select your security group in the azure portal for your VM and press save again. That renews the group for a certain amount of time. 
Hope that helped

**Comment by Fulltimegrinder** [comment]
@JanderHungrige: Hi Jan, I have the same problem. Where can I add a security group? Thanks!

**Comment by saiyan86** [comment]
hi @JanderHungrige what's the Azure Notebook IP we need to whitelist? I don't want to expose my VM to the internet. Thanks!

**Comment by JanderHungrige** [comment]
> @JanderHungrige: Hi Jan, I have the same problem. Where can I add a security group? Thanks!

Hi Fulltimegrinder, 
at the time I had the solution, you have to go to your VM. There under Network you will find "application security groups". There either create a new one or reselect an existing one. IT helped at the time. Lately I had ther problem again but this time the siolution did not helpß. 

Good luck to you. Maybe if you find another solution you can post a reply here.
Cheers

**Comment by vpekar** [comment]
You need to paste the VM's address in a new window in your browser, enter your credentials there. If you are logged in successfully, go back to the MS Azure notebooks and hit "Validate" again.

**Comment by dineshdaultani** [comment]
@vpekar Thanks! This worked for me. I think the reason being if it's a new VM, you need to login once to start the notebook server.
