### ISSUE TITLE
Different UI?

### ISSUE THREAD

**Issue by Anhduyvu04** [microsoft/AzureNotebooks#693]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [ ] https://studio.azureml.net

#### Describe the issue you are encountering

I'm new to Azure Notebook. I took an online Python course and the first lesson was to open Azure Notebook and create a library. But my Azure Notebook UI is different from theirs. It lacks not only the Libraries section but also the ability to create a library. Manually enter <notebooks.azure.com/[username]/libraries> doesn't work either. Also when open any notebook in Jupyter Notebook, I always need to manually go to "Help > Launch Classic Notebook" to view the notebook in Classic view. Is there any way to make it always launch in Classic view? Thank you very much.

**_My Azure Notebook UI:_**
![image](https://user-images.githubusercontent.com/51105522/58450269-60946380-8138-11e9-9ae0-2e28a5da7687.png)

**_Their Azure Notebook UI:_**
![image](https://user-images.githubusercontent.com/51105522/58450278-71dd7000-8138-11e9-9a0b-1d056cb8d452.png)

**_Jupyter Notebook non-Classic mode:_**
![image](https://user-images.githubusercontent.com/51105522/58452407-74909300-8141-11e9-8ef8-899d8f839bfd.png)

**_Classic mode:_**
![image](https://user-images.githubusercontent.com/51105522/58452553-f41e6200-8141-11e9-8ed4-4183238a1249.png)

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [x] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Hi,

Apologies for the confusion! The Azure Notebooks UI was updated in December which included the changes you are noting above. "Libraries" are now called "Projects." You can read more on these updates at: https://github.com/Microsoft/AzureNotebooks/wiki/Azure-Notebooks-at-Microsoft-Connect()-2018 

Additionally, there is a setting in your profile to always launch in the Classic Jupyter UI.
To access this setting, go to your name in the top right -> My Account
![image](https://user-images.githubusercontent.com/16325997/58489911-0e941380-8121-11e9-86ca-635d14712ecc.png)

Then click "Edit Profile Information"
![image](https://user-images.githubusercontent.com/16325997/58490011-371c0d80-8121-11e9-86cd-2fa4e5095ffc.png)

Then scroll down to "Enable Site Features" and turn off the option to run in JupyterLab by default
![image](https://user-images.githubusercontent.com/16325997/58490057-4dc26480-8121-11e9-9b0c-32add3bde686.png)

**Comment by Anhduyvu04** [comment]
> Hi,
> 
> Apologies for the confusion! The Azure Notebooks UI was updated in December which included the changes you are noting above. "Libraries" are now called "Projects." You can read more on these updates at: https://github.com/Microsoft/AzureNotebooks/wiki/Azure-Notebooks-at-Microsoft-Connect()-2018
> 
> Additionally, there is a setting in your profile to always launch in the Classic Jupyter UI.
> To access this setting, go to your name in the top right -> My Account
> ![image](https://user-images.githubusercontent.com/16325997/58489911-0e941380-8121-11e9-86ca-635d14712ecc.png)
> 
> Then click "Edit Profile Information"
> ![image](https://user-images.githubusercontent.com/16325997/58490011-371c0d80-8121-11e9-86cd-2fa4e5095ffc.png)
> 
> Then scroll down to "Enable Site Features" and turn off the option to run in JupyterLab by default
> ![image](https://user-images.githubusercontent.com/16325997/58490057-4dc26480-8121-11e9-9b0c-32add3bde686.png)

@kkampf Hi. Thank you so much for replying. So it's just a change of name. Technically it's the same thing, right? Is there any way to opt out to the old design? It's OK if there's no way. I just feel kinda weird  to practice new stuffs with outdated examples.

**Comment by kkampf** [comment]
@Anhduyvu04 No problem! Yes, it is the same thing, just with a new name :) There is not a way to go back to the old UI, but I hope you'll find the examples etc. will still run as expected
