### ISSUE TITLE
Azure DevOps repository

### ISSUE THREAD

**Issue by franperezlopez** [microsoft/AzureNotebooks#694]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I know is possible to import notebooks from GitHub. Is it possible to do the same from Azure DevOps repository? How??

**Comment by atimesastudios** [comment]
I'd like to add my support for this request. We have DevOps-based git repos for our internal development and we'd really like to leverage collaborative, version-controlled development with the consistent compute environment that Azure Notebooks provides.

**Comment by sasauz** [comment]
+1

**Comment by orion1900** [comment]
I'm extremely late to the party, but I would love this feature very much.
