### ISSUE TITLE
Add support for Xvfb

### ISSUE THREAD

**Issue by wmvanvliet** [microsoft/AzureNotebooks#695]
On `https://notebooks.azure.com`, it would be great to have `Xvfb` available.

### The problem
As far as I know, `Xvfb` cannot be installed through anaconda or pip, so I see no way to install it into the virtual machine. Many X11 libs and things are already installed there, but `Xvfb` is missing.

### Background
I'm preparing a hands-on workshop on neuroimaging. To not have any installation hassle, I'd love to drop the students into an Azure notebook. However, one big thing for a neuroimaging workshop is to plot a brain and visualize brain activity on this brain:

![plot](https://user-images.githubusercontent.com/428273/58542804-e5e64980-8206-11e9-8bd8-6b3d8b04e03c.png)

 This requires some 3D rendering. Python 3D plotting libs (for example [mayavi](https://docs.enthought.com/mayavi/mayavi/)) require a screen to render to, even when in the end only a PNG image is embedded in the notebook itself. In other hosted notebook environments such as [binder](https://mybinder.org/v2/gh/wmvanvliet/SNL_workshop_2019/master?filepath=pysurfer_demo.ipynb) and CI environments, this can be done by launching an `Xvfb` in the background that supplies a virtual framebuffer.

**Comment by thoth291** [comment]
@wmvanvliet  try this:
```bash
conda search xvfb
#select the one you like (with server in it)
conda install xorg-x11-server-xvfb-cos7-x86_64
XVFBPATH=$(dirname $(find ${CONDA_PREFIX} -name "Xvfb" -type f | head -1))
echo ${XVFBPATH}
```
Then in your .bashrc append this path to PATH env variable (or modify activate.d/deactivate.d scripts).
Then restart your kernel and it should be available for your experiments.
