### ISSUE TITLE
Accessing keyvault / azure user credentials login from notebook/project

### ISSUE THREAD

**Issue by alonisser** [microsoft/AzureNotebooks#698]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com

#### Describe the issue you are encountering

I need to use azure keyvault from notebook (or any other way to load common secrets without putting an unncrypted vars file in the notebook code) - Is there a built in way to do it?
Alternatively I can hack a bash script to use az cli tool at startup to populate envs But for some reason az cli tools demands interactive login - although the user already is authenticated to the notebooks with an azure user and the interactive login in the bash script fails to start the container, and besides doing this every time, is really bad exprience. I'm Sure we're not the only one with this use case. I can login with a service principle but then again, I would need an secure environment variable for that
 Please advice

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [X] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Hi, thanks for sharing your scenario. We're exploring this in our backlog, but don't have a timeline to share just yet. I'll be sure to update when we have a timeline
