### ISSUE TITLE
Notebook server unresponsive

### ISSUE THREAD

**Issue by mladeroute** [microsoft/AzureNotebooks#699]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
On the free tier of the notebooks, my project is displayed as running. However, when I try to open individual notebooks I get an error: "You're notebook appears to be unresponsive." and I'm given the option to restart the notebook serve --however the restart is not correcting this issue. 

Also, the link "connecting to it again" has a leading "." before notebook, so it's ref is "https://.notebooks.azure.com/nb/tree" not sure if that's intended. 

Note: I'm running Chrome and the service was working perfectly yesterday on chrome. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
You can test the free tier service notebook instances to see if they are responding, otherwise I'm not sure how to reproduce it. Create a new project, add a notebook and see if they uploaded notebook is accessible. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
3:19PM EST
#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

![azurenotebookissue](https://user-images.githubusercontent.com/48420645/58828817-4d8c0280-8614-11e9-8e62-c024e1700d86.png)

**Comment by mladeroute** [comment]
Issue is now resolved.

**Comment by philipbel** [comment]
Still seeing this.
