### ISSUE TITLE
Enable "Private" libraries and secure sharing of those libraries

### ISSUE THREAD

**Issue by eclectir** [Microsoft/AzureNotebooks#7]
User should be able to mark a library private and share it with a select group of users via their email ids.

**Comment by garth-wells** [comment]
This would be really helpful.

Would it include shared write access to a library? This would help a lot in teaching classes with multiple teachers.

**Comment by eclectir** [comment]
Yes, but that is covered by https://github.com/Microsoft/AzureNotebooks/issues/6
 
Great to see your support for it!

**Comment by garth-wells** [comment]
Now that private libraries are supported, maybe this issue could be closed and a new one opened specifically on sharing of private libraries? 'Teams' may be an important part of sharing private libraries.

**Comment by crwilcox** [comment]
@garth-wells. 

Sure. I will close this. Feel free to open up a new issue for tracking shared access to private libraries. We have no schedule for that work but I can certainly see the value of such a feature.

Hopefully being able to have libraries private to you is of use.

Thanks!
Chris
