### ISSUE TITLE
Brunel doesn't display in notebooks

### ISSUE THREAD

**Issue by AronT-TLV** [microsoft/AzureNotebooks#70]
### Description
After pip install, Brunel doesn't display output in notebooks

# Steps to replicate
1. Ran following commands to get brunel on board:

> !pip install brunel --user
> !pip install jupyter_contrib_nbextensions --user
> !jupyter nbextension enable --py --sys-prefix widgetsnbextension

N.B. First tried it with only the first line.

2. Imported data file and brunel

> import pandas as pd
> import brunel
> 
> cars = pd.read_csv('cars.csv')

3. run a brunel command

> %brunel data('cars') x(mpg) y(horsepower) color(origin) filter(horsepower)  :: width=800, height=300

Output is blank - don't see any visualization. On other platforms get the appropriate visualization.
### Recommended Metadata
The Jupyter Kernel: Python2
Occurrence Time:
Web Browser: Chrome
LibraryID and Notebook Name (if applicable):
https://notebooks.azure.com/aront/libraries/brunel-test
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable
Nothing at all in log

**Comment by crwilcox** [comment]
In the output of installing brunel the wheel fails to install. I am guessing that is the issue with the output is it isn't correctly installed. I am going to consider this a request to install brunel.

**Comment by AronT-Emelai** [comment]
Did you install w/ --user flag? Because I did have errors w/o that flag, but it did appear to install fw/o error w/ the flag.

**Comment by crwilcox** [comment]
I just ran your library with the exact args above.
```
error: [Errno 13] Permission denied: '/home/nbuser/.local/share/jupyter/nbextensions/brunel_ext/'
  
  ----------------------------------------
  Failed building wheel for brunel
```

**Comment by AronT-Emelai** [comment]
Hmm, yes, I tested it in a clean account and got same error message. As I mentioned, I tried the --user only after getting the permissions error the first time. Apparently If you run it a second time (with or without --user) you don't get any error - but don't know if that's just a quirk of pip. Here's the output when I re-run
!pip install brunel


Requirement already satisfied (use --upgrade to upgrade): brunel in ./.local/lib/python2.7/site-packages

Requirement already satisfied (use --upgrade to upgrade): pandas in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from brunel)

Requirement already satisfied (use --upgrade to upgrade): jinja2 in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from brunel)

Requirement already satisfied (use --upgrade to upgrade): ipython in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from brunel)

Requirement already satisfied (use --upgrade to upgrade): jupyter-pip in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from brunel)

Requirement already satisfied (use --upgrade to upgrade): JPype1 in ./.local/lib/python2.7/site-packages (from brunel)

Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from pandas->brunel)

Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from pandas->brunel)

Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.0 in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from pandas->brunel)

Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from jinja2->brunel)

Requirement already satisfied (use --upgrade to upgrade): six>=1.5 in /home/nbcommon/anaconda2_410/lib/python2.7/site-packages (from python-dateutil->pandas->brunel)

You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

It makes it seem as if Brunel is in fact installed!

Aron Trauring, CIO
http://emelai.io
+972-54-992-7866

________________________________
