### ISSUE TITLE
cant pip install h2o library

### ISSUE THREAD

**Issue by Andrei079** [microsoft/AzureNotebooks#701]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [X] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, 
https://
[screenshot.docx](https://github.com/microsoft/AzureNotebooks/files/3263457/screenshot.docx)
[screenshot.docx](https://github.com/microsoft/AzureNotebooks/files/3263458/screenshot.docx)

heart-andreiv.notebooks.azure.com/j/lab/tree/Heart%20M-Copy.ipynb

**Comment by kkampf** [comment]
Hi @Andrei079 I tried to repro your issue and H2O installed successfully for me with the same kernel. Based on the attached screenshot you attached  I'm a bit unsure on if the project was stopped during install (in which case the notebook would stop running)

Can you provide some more information on this if you are still seeing the issue?

**Comment by Andrei079** [comment]
Sorry, a can't install. I create new project, but installation stops in the process, not react. New screenshot
[screen.docx](https://github.com/microsoft/AzureNotebooks/files/3291478/screen.docx)

**Comment by kkampf** [comment]
Thanks for the additional info! It looks like this may be an issue with the JupyterLab view. Could you switch to the classic view and let me know if that fixes it for you? Instructions for this below

Click on my account
![image](https://user-images.githubusercontent.com/16325997/59525957-92256280-8e8c-11e9-88b4-2db6a427e9db.png)

Click on edit profile settings
![image](https://user-images.githubusercontent.com/16325997/59525943-89cd2780-8e8c-11e9-9f40-31c193419d38.png)

Scroll to the bottom and turn off run in JupyterLab
![image](https://user-images.githubusercontent.com/16325997/59526004-b1bc8b00-8e8c-11e9-8c74-ce085f63fbf3.png)

**Comment by Andrei079** [comment]
Thanks for your help! H2O installed successfully.  
Additional info:  a similar problem was previously observed for the installation  XGBoost, Hyperopt python library (JupyterLab view). But there are no problems installing on the local computer.
