### ISSUE TITLE
Connecting To SharePoint 

### ISSUE THREAD

**Issue by SG-Gank** [microsoft/AzureNotebooks#702]
Please describe your issue as completely as possible.

#### Which site did you access us from?

    [] https://studio.azureml.net

#### Describe the issue you are encountering
1. Is there a way to write/read data files directly from Sharepoint Site from my AzureML Notebook?
2. Is there a way to connect PowerBI desktop directly to Azure ML WorkSpace's dataset? (Say I did some manipulation and got results from my ML model, now I want to present this result in Power BI)
#### Which language/kernel were you using when you experienced this issue?

    [] Python 3.6 

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by kkampf** [comment]
Hi @SG-Gank for Azure Notebooks there is not yet a way to connect to Sharepoint, it's being considered in our backlog and we'll be sure to update if we have a timeline to share. #2 is best directed to the Azure Machine Learning team

**Comment by SG-Gank** [comment]
Thanks bunch Katherine!

**Comment by stpeteparadox** [comment]
Azure Notebooks is great to see, especially as we already use Azure DevOps.

All of our SFTP datafeeds come in using Microsoft Flow to a Sharepoint library, though.

Sign us up when a Sharepoint/Onedrive data connector is available :)
