### ISSUE TITLE
Julia kernel for notebooks?

### ISSUE THREAD

**Issue by tonyhur** [microsoft/AzureNotebooks#703]
I uploaded a Notebook to my repository using Python kernel. Open it works fine.

see. https://notebooks.azure.com/tony-huerlimann/projects/lpls

However, it seems that the Julia Kernel is still missing. When will it be available?
Thanks
Tony Hürlimann

**Comment by kkampf** [comment]
Hi @tonyhur, thanks for sending this along. We are considering adding a Julia kernel in the future, but do not have timelines to share just yet.

**Comment by lewisl** [comment]
I would like to see this reopened. It has to be less work to support Julia than either version of Python if Azure runs LLVM. Julia's package manager is cleaner and more consistent than Python pip. Seriously, no one uses F# for data science or machine learning outside of Microsoft Research. Julia is growing. Jupyter already supports Julia quite well: seems like AzureNotebooks should support whatever Jupyter supports.
