### ISSUE TITLE
AAD/RBAC: How does we add new user?

### ISSUE THREAD

**Issue by hirtanak** [microsoft/AzureNotebooks#705]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I'm a Microsoft employee. But I would like to find the info based on the customer request. If I have a better way to ask/improve instead of issuing it on here, please let me know.

My customer would like to allow to use Azure Notebook for some limited users of their Azure AD tenant. We have a good site, https://notebooks.azure.com/account/adminConsent. 
But unfortunately, this site allows to ALL tenant users. So it cannot meet their security compliance. On the other hands, I can not find a way to allow to add an individual user.
In addition, the end-users don't have AAD App user privileges. The customer would like to avoid asking AAD admin multiple times when they have a new user.  

[Q1]: How does my AAD customer's administrator add new users?
[Q2]: If the customer wants to add a new user randomly, the customer AAD administrator creates a group user group one time, and then add a new user by themselves. If possible, please let me know.
[Q3]: Please let me proper RBAC role in AAD.
 
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by andneilmsft** [comment]
the site is a public SaaS, it's not an RP stamped into a subscription. Please contact the team using the nbhelp address for more details.
