### ISSUE TITLE
 Module2_Lab4_Edges_and_Corners 

### ISSUE THREAD

**Issue by wintsuman** [microsoft/AzureNotebooks#706]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net
https://dev290x-agweeg***.notebooks.azure.com/j/notebooks/Module2/Lab4/Module2_Lab4_Edges_and_Corners.ipynb

#### Describe the issue you are encountering
# Find the contours - just external contours to keep post-processing simple
_, contours, _ = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# Sort the candidates by size, keep the largest one
contours = sorted(contours, key=cv2.contourArea, reverse=True)[:1]

# Create two related images - one contains the shape of the martini
# glass with black (0's) in the remainder, the other contains
# black where the martini glass is and a colour everywhere else
h, w, num_c = img.shape
segmask = np.zeros((h, w, num_c), np.uint8)
stencil = np.zeros((h, w, num_c), np.uint8)

for c in contours:
    cv2.drawContours(segmask, [c], 0, (255, 0, 0), -1)
    cv2.drawContours(stencil, [c], 0, (255, 0, 0), -1)

# Rearrange the colors in the stencil.  Anything that's black
# replace with green.
stencil[np.where((stencil==[0,0,0]).all(axis=2))] = [0, 255, 0]
# Now its safe to convert the blue to black
stencil[np.where((stencil==[255,0,0]).all(axis=2))] = [0, 0, 0]

# Add the two images (or or them if you prefer)
mask = cv2.bitwise_or(stencil, segmask)
plt.imshow(cv2.cvtColor(mask, cv2.COLOR_BGR2RGB))

output = cv2.bitwise_or(mask, img)
# plt.imshow(output)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-403ca93eaf13> in <module>()
      1 # Find the contours - just external contours to keep post-processing simple
----> 2 _, contours, _ = cv2.findContours(dilation, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
      3 
      4 # Sort the candidates by size, keep the largest one
      5 contours = sorted(contours, key=cv2.contourArea, reverse=True)[:1]

NameError: name 'dilation' is not defined

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal
???
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    x[] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
https://dev290x-agweeg***.notebooks.azure.com/j/notebooks/Module2/Lab4/Module2_Lab4_Edges_and_Corners.ipynb

**Comment by kkampf** [comment]
Hi @wintsuman, thanks for reaching out. This looks like it is a code bug rather than an Azure Notebooks service issue. I'm not having luck accessing the notebook you linked so perhaps it's private, but based on the sample notebook it looks like there may be some missing code to define the dilation
