### ISSUE TITLE
"Tenant Null Not Found" - Connect to Azure Auth 

### ISSUE THREAD

**Issue by SG-Gank** [microsoft/AzureNotebooks#707]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://studio.azureml.net

#### Describe the issue you are encountering
While I am trying to connect to Azure in my notebook, I am encountering the following issue:

"AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator."

I am the owner of the notebook.

Here's some more details:

Request Id: 8ad904b2-0fc7-4a7d-b697-26acceb40e00
Correlation Id: b55370f1-224a-4413-82e8-a31502fff332
Timestamp: 2019-06-13T22:45:07Z
Message: AADSTS90002: Tenant 'null' not found. This may happen if there are no active subscriptions for the tenant. Check with your subscription administrator.
Advanced diagnostics: Enable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 

#### What time (please include time zone) did this occur?
6/18/2019
#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by shibbas** [comment]
Hi! Thanks for reporting! Can you help us understand how you are connecting to Azure? Is this happening via Azure->Connect to Azure?  

You should be able to login directly using [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login) by doing `!az login` in the notebook cells. Have you tried this already?

**Comment by SG-Gank** [comment]
Hi Shibbas, 

Thanks for replying. Yes, I am trying to connect Azure ML to Azure. Specifically, trying to use Azure MLNotebook to read Azure Blob Storage. Is there a way for me to send you my note book URL so that you can take a look directly?

**Comment by shibbas** [comment]
Sorry, to clarify, are you using the Azure Menu in the notebook to connect or using a command? If using the Azure menu, then this is not supported in studio.azureml.net. Only for notebooks.azure.com. 

Sure, you can send the notebook to nbhelp@microsoft.com. However, I recommend using !az login from the notebook directly which should allow you to connect to azure using Azure Command Line Interface (Azure CLI).

**Comment by SG-Gank** [comment]
Thanks for your help Shibbas, 

I sent a detailed email outlining my issue to the email above. Looking forward to your reply. Also, I will post the solutions here once this issue is resolved.

**Comment by kkampf** [comment]
Hi @SG-Gank, are you still seeing this issue? If not, can I resolve this issue?

**Comment by SG-Gank** [comment]
Found a work-around. This is issue is resolved. 

Thanks!
