### ISSUE TITLE
Documentation: 4.1

### ISSUE THREAD

**Issue by ShalokShalom** [microsoft/AzureNotebooks#709]
I know, this is probably the incorrect repo to report - while I am not quite sure what the issue is and the team here might feel responsible. 

The current [documentation](https://docs.microsoft.com/en-us/azure/notebooks/azure-notebooks-overview) says the supported F# version on the Azure instance is 4.1:

a) This instance is outdated. 
b) The documentation is outdated.

**Comment by kkampf** [comment]
Hi @ShalokShalom thanks for reaching out! Can you elaborate on the documentation issue you're seeing? We do include version 4.1

**Comment by ShalokShalom** [comment]
Yeah, the current version is 4.6, so do you support the current version of F# and the documentation is outdated, or is the documentation up to date and the F# support is outdated?

**Comment by kkampf** [comment]
The documentation is up-to-date, we support 4.1
