### ISSUE TITLE
I've been using Azure notebooks, but recently I get a message that says "DSVM Configuration required Your current DSVM requires credentials to be used as a compute target on Azure Notebooks. Please go to Project page and click Run to configure your DSVM."  I have been using Azure notebook as part of an edx course and I am almost done but need to finish by the 30th. I need the Azure notebook to finish. Please help.

### ISSUE THREAD

**Issue by Steve35897** [microsoft/AzureNotebooks#711]
Please describe your issue as completely as possible.

#### Which site did you access us from?
https://notebooks.azure.com/eric/libraries/DEV236x
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I've been using Azure notebooks, but recently I get a message that says "DSVM Configuration required Your current DSVM requires credentials to be used as a compute target on Azure Notebooks. Please go to Project page and click Run to configure your DSVM."  I have been using Azure notebook as part of an Edx course.
#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
For the last few days in the morning between 9am and noon. I am in Mountain time

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com
My Projects
 DEV236x_Introduction_to_Python_Unit_1_Clone

**Comment by getroyer** [comment]
Sorry for the inconvenience.

If you get this message while trying to use free compute, give this a try: 
1) click 'Shutdown' on the project page
2) run your notebook on free compute again
