### ISSUE TITLE
Unable to connect Kernel in Jupyter notebook. Getting msg that no connection to kernel. 

### ISSUE THREAD

**Issue by SaurabhG-20** [microsoft/AzureNotebooks#712]
Please describe your issue as completely as possible.
Hi , I'm using for python and machine learning development activity. I am not able to execute any line of code in jupyter notebook. I am getting error that " no connection to kernel" and also keep getting blinker of connect to kernel which automatically get shut off.

### Required:
Azurenotebook
Jupyter launcher
Python 3.6
#### Which site did you access us from?
    [✓] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Unable to execute python in jupyter note book as" no connection to kernel "error

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Launch azurenotebook. Check kernel

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [✓] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Since 25th June 2019 8:00 pm
#### Which Web Browser(s) did you see the error in?
    [✓] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [✓] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by johnsonjmaliakal** [comment]
It would be REALLY useful for the people working on your issue if you also provided a link to the project on which this issue occurred. They can check the logs to see the details of the issue at hand. Also, include a time zone, as just saying "8:00", is very vague.

**Comment by nscozzaro** [comment]
Hi, I'm getting this same error on this link:
https://mltutorialen-nscozzaro.notebooks.azure.com/j/notebooks/unit1_python_overview.ipynb at 
~12:30 EST

**Comment by johnsonjmaliakal** [comment]
> Hi, I'm getting this same error on this link:
> https://mltutorialen-nscozzaro.notebooks.azure.com/j/notebooks/unit1_python_overview.ipynb at
> ~12:30 EST.
> Could not connect to the kernel at all.

Hey, uh, is that project public?
Make sure that it _**is**_ set to public and resend the link.
One way to fix your issue would be to close your browser and start it all over again.

**Comment by nscozzaro** [comment]
I changed the project setting to public. 
![image](https://user-images.githubusercontent.com/15185105/73566494-00c22b00-4432-11ea-85c3-10935ad0ef2e.png)

**Comment by johnsonjmaliakal** [comment]
Wait a moment Nicolas! I'm not the one responsible for fixing stuff around here!
Just create a new issue of your own, don't just leave it in a comment waaayyy down here.

**Comment by johnsonjmaliakal** [comment]
You can create it on the top-right corner button from here that says "New Issue".
