### ISSUE TITLE
Cannot access my Notebook

### ISSUE THREAD

**Issue by paulvv1** [microsoft/AzureNotebooks#713]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
 
#### Describe the issue you are encountering
When trying to open my notebook, which I created and saved yesterday, I am getting the following message: 

---
The notebook server associated with this project has been shutdown.

Your notebook server is automatically shutdown after a 1 hour period of inactivity. Any files in your 'project' folder will be persisted after the lifetime of the notebook. All other files and state will be discarded.

You can restart your notebook server by clicking on the button below.

(Button says 'Restart notebook server'

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
    (but this issue happens before the notebook is opened).

#### What time (please include time zone) did this occur?
8.15AM, GMT+1 (Amsterdam)

#### Which Web Browser(s) did you see the error in?
       [] Firefox
   
#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/paulvanveen/projects/capstone-project-2-poverty
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

This has to be done from within my Notebook, which I cannot access at this time.

**Comment by KieranBrantnerMagee** [comment]
Hey Paul,
First, sorry for taking so long to get back to you, and thanks for your patience!
Second, I took a peek at your situation, and I'm wondering two things.  One, that project you linked is private, correct?  And Two, did you try in an incognito window/logging out and back into notebooks again?

My going hypothesis is that your access token expired behind the scenes and in trying to launch a private project, it gave a very unhelpful error.

Let me know if the issue still repros and if so if an incognito session helps.

Thanks again for your time and for using Notebooks!

**Comment by paulvv1** [comment]
Hi Kieran, 

This was indeed solved by logging out of the Notebooks app, and then logging back in. So I think your hypothesis is correct. 

This happens from time to time, and the error is indeed unhelphul. It just says 'error'. So may be that's something you can change. 

Thanks for your response!
Rgds, 
Paul

    On Monday, July 15, 2019, 10:57:32 PM GMT+2, KieranBrantnerMagee <notifications@github.com> wrote:  
 
 
Hey Paul,
First, sorry for taking so long to get back to you, and thanks for your patience!
Second, I took a peek at your situation, and I'm wondering two things. One, that project you linked is private, correct? And Two, did you try in an incognito window/logging out and back into notebooks again?

My going hypothesis is that your access token expired behind the scenes and in trying to launch a private project, it gave a very unhelpful error.

Let me know if the issue still repros and if so if an incognito session helps.

Thanks again for your time and for using Notebooks!

**Comment by KieranBrantnerMagee** [comment]
Totally in agreement Paul, I've surfaced this UX issue to the powers that be, we'll have to see what we can do to improve this flow.

Thanks again, glad to be of assistance!
