### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by SQLScott** [microsoft/AzureNotebooks#716]
Please describe your issue as completely as possible.

#### Which site did you access us from?
https://courses.edx.org/courses/course-v1:Microsoft+DAT274x+2T2019/courseware/9a27d5b6-48c4-1194-3afa-cf0232935159/e19cb5ef-410b-8332-4fcf-b704d408d9a7/1?activate_block_id=block-v1%3AMicrosoft%2BDAT274x%2B2T2019%2Btype%40vertical%2Bblock%40c9b1c21a-2cb0-d9a0-73d9-8f1cf00c4870

In the Preparing for the Labs section, there is a link to Azure notebooks which does not work. The full link is below.

#### Describe the issue you are encountering
On this page, there is a link to: 
https://notebooks.azure.com/help/libraries/creating/import-from-github

I get "the page you're looking for was not found".

#### What steps can we take to reproduce this issue? 
You may need an edX account, but click on the edx.org link above, then click on the link for Azure notbooks in the Preparing for the Labs section.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
1:00PM PST

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue?

https://notebooks.azure.com/help/libraries/creating/import-from-github

**Comment by kkampf** [comment]
Thanks for letting us know about this! The information you're looking for can be found at https://notebooks.azure.com/help/projects/creating and https://docs.microsoft.com/en-us/azure/notebooks/quickstart-clone-jupyter-notebook 

We'll work on contacting the right folks to have the course link updated for the future as well
