### ISSUE TITLE
My Project wasn't and isn't Private

### ISSUE THREAD

**Issue by johnsonjmaliakal** [microsoft/AzureNotebooks#718]
I will link the project again here, as it isn't actually private, it is Public.
The issue seems to have mostly disappeared, but occasionally, it recurs. I will comment the timings of the occurrences here.

Hey Johnson,
apologies for taking so long to follow up, thanks for pinging again.

We've seen similar symptoms recently reported by other users, wherein you are signed out behind the scenes, and because the project in question is private, you'll see errors when trying to run it; this has largely started occurring since we defaulted to private-projects-on-creation for security reasons.

In the interim a workaround would likely be hitting sign out -> re-signing in. (If a bigger hammer is needed, a new browser session/incognito session would certainly do the trick)  Feel free to reopen if this recurs and the workaround is not helpful.

We've taken the feedback to try and improve the UX presented to avoid future confusion.

Thanks so much for your patience and for using Notebooks.
Best,
-Kieran

_Originally posted by @KieranBrantnerMagee in https://github.com/microsoft/AzureNotebooks/issues/715#issuecomment-511915277_

**Comment by KieranBrantnerMagee** [comment]
Closing to continue discussion in original thread #715
