### ISSUE TITLE
How to unzip and open pickle file in Azure Jupyter Notebook?

### ISSUE THREAD

**Issue by nrcjea001** [Microsoft/AzureNotebooks#72]
I have a saved dataset (zip file) in Azure ML studio. Inside the zip file is a .pickle file. I am now using (Python 3.5) Jupyter in Azure's notebook service. I would like to open and load the .pickle file in my Jupyter notebook from the saved zip file in the Azure ML Studio. Any ideas on how to do that? My code is as follows (with error):

```
from azureml import Workspace
from six.moves import cPickle as pick
from six.moves import range

ws = Workspace(workspace_id = '...', authorization_token='...')

with ws.datasets['xxx.zip'].open() as zf:
    with open(zf, 'rb') as p:
        pload = pick.load(p)
        train_dataset = pload['train_dataset']
        del pload
print(train_dataset.shape)

```
---> 14 with open(zf, 'rb') as p:
TypeError: invalid file: requests.packages.urllib3.response.HTTPResponse object at 0x7fe739589ef0

**Comment by crwilcox** [comment]
My guess is something has went wrong retrieving that dataset though. It didn't throw an exception/error but it does appear to have returned something unusual. I am fairly certain the code that will be called from the first open is: https://github.com/Azure/Azure-MachineLearning-ClientLibrary-Python/blob/4204e2b2f1540e6d9f936b19457048c5afdca860/azureml/http.py#L120

I would suggest just running `zf = ws.datasets['xxx.zip'].open()` and then looking into what `zf` is. 
These methods should all be available https://docs.python.org/3.5/library/http.client.html#httpresponse-objects

**Comment by nrcjea001** [comment]
To give you more context, I am loading a pickle file, which contains several datasets, from a zipfile. As suggested, I took a look at what zf is and made some adjustments to the code. Now the Jupyter Kernel is dying:

```
from six.moves import cPickle as pick
from six.moves import range
from zipfile import ZipFile
from io import BytesIO

h = ws.datasets['xxx.zip'].read_as_binary()
pfile = 'xxx.pickle'
with ZipFile(BytesIO(h), "r").open(pfile, 'r') as zf:
    pload = pick.load(zf)
    del h
    train_dataset = pload['train_dataset']
    train_labels = pload['train_labels']
    valid_dataset = pload['valid_dataset']
    valid_labels = pload['valid_labels']
    test_dataset = pload['test_dataset']
    del pload
    zf.close()
    
print(train_dataset.shape) 

```

Any ideas?

**Comment by nrcjea001** [comment]
"The kernel appears to have died. It will restart automatically".

**Comment by smortaz** [comment]
hi, does this work locally in jupyter?  i would try that 1st to see if it's
a jupyter or azure notebooks issue.

**Comment by crwilcox** [comment]
@nrcjea001, if the kernel is dying (the notebook) it can be for a number of reasons. One common one though is exhausting a resource, typically memory. Is this a large amount of data? There is a log at ~/.nb.log but often when the kernel crashes out of memory the logging is less than useful.

Each notebook server instance is limited in resources. For more information on these limits you can read the following: https://notebooks.azure.com/faq#service_restrictions

@smortaz  suggestion of trying on a local jupyter instance is a reasonable thought as locally you may have more than 4GB of memory to work with.

I would, to debug this if I was encountering the same issue, simplify the code. Try loading just one dataset, then two, then 3. Try to figure out where it fails.
