### ISSUE TITLE
Session ends after 8 hours

### ISSUE THREAD

**Issue by kmbl-md** [microsoft/AzureNotebooks#727]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    https://notebooks.azure.com

#### Describe the issue you are encountering
I'm connecting to a DSVM from Azure notebooks. After 8 hours the session expires and I have to log back into notebooks.azure.com and re-enter the DSVM connection. It would be nice if the session would last 9 or 10 hours to make it through a full work day.

On the whole Azure notebooks has been a pleasant experience, thank you for providing this service.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.5

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows 10

**Comment by kkampf** [comment]
Hi @kmbl-md thanks for the feedback! Sorry this has been an inconvenience for you, we'll consider this if we rework our session timings in the future
