### ISSUE TITLE
Uploaded Notebooks with Python >3.6 should default to Python 3.6 kernel, not 3.5

### ISSUE THREAD

**Issue by jruales** [microsoft/AzureNotebooks#728]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
On my machine, I have a Jupyter notebook that uses Python 3.7. When I upload the notebook to Azure Notebooks, it's treated as a Python 3.5 Notebook. The expected behavior would be for it to be treated as a Python 3.6 Notebook, since that is the latest version available in Azure Notebooks.

This is causing issues for me because I use a library that requires Python >=3.6, and every time I upload my 3.7 notebook, it breaks the notebook and I need to change the kernel version to 3.6.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Upload to Azure Notebooks a notebook that has the following metadata:
```
"metadata": {
  "celltoolbar": "Tags",
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.1"
  }
 },
```

Notice that the Python version says "3.7.1"

Then, immediately download the notebook and take a look at the metadata. The version will have changed to `"version": "3.5.4"`. The expected behavior would have been for it to change to 3.6.X

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
2019-08-08 18:20:00 UTC

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by gilbertw** [comment]
Thanks for using the service.  Jupyter only allows one default for a language.  Our python 3 currently defaults to 3.5 for compatibility reasons.  We are exploring moving that to be a more recent python.  For now you can workaround this by uploading your notebooks with the Kernel set to 3.6
"kernelspec": {"display_name": "Python 3.6", "name": "python36", "language": "python"}

**Comment by jruales** [comment]
Got it. Thanks for the reply and the alternative!
