### ISSUE TITLE
Upgrade CNTK to latest

### ISSUE THREAD

**Issue by usuyama** [Microsoft/AzureNotebooks#73]
### Description
The latest version of CNTK/Python is 2.0.beta15.0, but the version on Azure Notebook is still 2.0. From version 2.0, there're lots of bug fixes, so without the upgrade, it's hard to use Azure Notebook.

**Comment by crwilcox** [comment]
Hi @usuyama . You are correct that we are running an older version. Though we aren't as out of date as it would seem. We are actually on 2.0.beta9 but CNTK doesn't update their version string to show which beta version you are on. 

We will work to update CNTK and report back once it is up to date.

**Comment by crwilcox** [comment]
CNTK RC1 is installed on Python 2 and Python 3. 

Thanks!
Chris
