### ISSUE TITLE
Feature Request: Export to Github repo

### ISSUE THREAD

**Issue by andreas-wilm** [microsoft/AzureNotebooks#733]
Hi there,

just like you can import Github repos into Azure Notebooks, it would be nice to export to Github repos as well. The workaround described [here](https://medium.com/@dadbrains/integrating-azure-notebooks-jupyter-notebooks-with-github-fd847e941e4) is rather cumbersome.

Thanks,
Andreas

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

None. This is a feature request

**Comment by tcox04-su** [comment]
I'm actually having the opposite issue. I can't upload my github repository to Azure notebook and my repository doesn't seem to work when I try to download it in the terminal using 'git clone'. It would show the files being downloaded completely but some git commands like 'git status' and 'git config credential.helper store' wouldn't work. Any solutions?
