### ISSUE TITLE
upload gi

### ISSUE THREAD

**Issue by tcox04-su** [microsoft/AzureNotebooks#734]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
When I try to upload a github repository (https://github.com/IST256-classroom/fall2018-learn-python-tcox04-su.git) to azure notebook, the window tells me that it can't access the repository through the URL. I even tried removing the .git extension like another thread suggested.
#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Try to upload a github repository for a new project in azure notebook with this URL: https://github.com/IST256-classroom/fall2018-learn-python-tcox04-su.git

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [
![Screenshot 2019-08-22 at 10 54 24 PM](https://user-images.githubusercontent.com/35647748/63563917-d722e080-c530-11e9-9008-8edd29df110b.png)
] Terminal

#### What time (please include time zone) did this occur?
EST
#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [x] Other (Please Specify)
ChromeOS

**Comment by tcox04-su** [comment]
Also, when in terminal after creating a new project, i try to download the repository through 'git clone' followed by the URL and the repository would download all the file, but then git commands such as 'git status' and 'git config' wouldn't work, as seen below.
![Screenshot 2019-08-22 at 11 16 06 PM](https://user-images.githubusercontent.com/35647748/63564370-d68b4980-c532-11e9-84b7-97225be30cad.png)

**Comment by elibarzilay** [comment]
The repository looks like it's private.

Re your manual use of `git` -- after the `clone` is done, you need to `cd` into the new directory to use `git` commands (`cd fall2018-learn-python-tcox04-su` in your case).

**Comment by tcox04-su** [comment]
Thanks. This helped a lot.

**Comment by tcox04-su** [comment]
I'm also having an issue opening jupyter notebook in my terminal. My class instructions tell me to type 'jupyter-notebook' in the terminal window and a new tab should open up with the new notebook open. However, I don't get a new window wit Jupyter open, just the terminal saying the notebook is running. I screenshotted it below.
![Screenshot 2019-08-23 at 1 04 16 PM](https://user-images.githubusercontent.com/35647748/63610352-4dfac080-c5a7-11e9-99ac-c92e9202dd73.png)
