### ISSUE TITLE
CNTK not found with Python2 Kernel

### ISSUE THREAD

**Issue by usuyama** [Microsoft/AzureNotebooks#74]
### Description
With Python2 kernel,
```
import cntk

ImportErrorTraceback (most recent call last)
<ipython-input-1-6b467b8c6865> in <module>()
----> 1 import cntk

ImportError: No module named cntk
```

Python3 kernel has cntk module.

**Comment by crwilcox** [comment]
When we had installed CNTK, we were given a custom wheel (they weren't yet distributing wheels) for Python 3. Now that they provide a Python 2 wheel we can work to get CNTK on Python 2.

Thanks for letting us know!
Chris

**Comment by crwilcox** [comment]
CNTK RC1 is installed on Python 2 and Python 3. 

Thanks!
Chris
