### ISSUE TITLE
Constant Internal Server Error on every Notebook

### ISSUE THREAD

**Issue by nateginger** [microsoft/AzureNotebooks#745]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
I get an internal server error for literally any notebook.
I want to make a copy of one but it just says internal server error

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://dev236x1-natetitans5.notebooks.azure.com/j/notebooks/1%20Week%20Coursera.ipynb
https://dev236x1-goose555.notebooks.azure.com/j/notebooks/2018%20World%20Cup-Copy.ipynb

These are just two examples

#### Which language/kernel were you using when you experienced this issue?
    
    [] Python 3.6 
    
#### What time (please include time zone) did this occur?
Eastern Standard
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
   

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
   

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

It is any notebook
for example: https://dev236x1-natetitans5.notebooks.azure.com/j/notebooks/1%20Week%20Coursera.ipynb

**Comment by nateginger** [comment]
I've tried erasing cookies, and history. I've also tried sharing the project and opening it on another account

**Comment by KieranBrantnerMagee** [comment]
Hey Nate, thanks for reaching out, sorry you've run into this issue!

What's got me scratching my head is that you report opening the project on another account reproduced the issue. (Correct me if I misunderstood.)  Is this the goose555 account you also logged into?

My confusion is that, from the logs, I'm seeing errors in the time span you reported this that have to do with your login session having expired.  Typically the advice here is "click the log out button, log back in again" but your statement about erasing cookies also makes me question that.  I'd ask if you can try explicitly logging out and in, trying a new browser, and if those fail, kindly send me the name of the second account you're trying and we'll dig in further.

Thanks in advance for your patience, and for using Notebooks
Best,
-Kieran
