### ISSUE TITLE
Notebook cannot be loaded, with error loading notebook

### ISSUE THREAD

**Issue by pm0107** [microsoft/AzureNotebooks#746]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [/] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
For the past 12 hours my notebooks are unable to load. It has an error loading notebook window with error message

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [/] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [/] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [/
<img width="863" alt="Annotation 2019-09-09 091437" src="https://user-images.githubusercontent.com/55069143/64497644-59a5f100-d2e2-11e9-9f7f-d25a7f36ea4d.png">
] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by stvincentwower** [comment]
I've had this error most of the day too. Close to 12 hours. 

<img width="1077" alt="Unresponsive" src="https://user-images.githubusercontent.com/42941883/64498131-ef506a80-d267-11e9-8343-5c362556d8bc.png">

**Comment by pm0107** [comment]
It seems that it is working now. I logged out and logged back in and it worked. Not too sure if that was the solution though
