### ISSUE TITLE
State of JupyterLab? 

### ISSUE THREAD

**Issue by bgue** [microsoft/AzureNotebooks#747]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
5:00 PM MDT
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

Hi - can you comment on the state of Jupyterlab support in late 2019? #294 indicates that it's not ready to be 'front and centre' yet. Has that changed in the last year and a half? 

Thanks for your efforts... JL is a big part of the puzzle for me.

**Comment by dpalbrecht** [comment]
I'm wondering the same, thanks in advance!

**Comment by mgraauw** [comment]
Same question here. Jupyterlab 1.0 has been out some time now and should be considered the default.
