### ISSUE TITLE
Unable to load any project. Status is showing stopped. 

### ISSUE THREAD

**Issue by lenorajan** [microsoft/AzureNotebooks#748]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [*] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Unable to open Jupyter lab

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
Login to Azure Notebook
select a buitin project and click clone
It opens a new project and there I get an error message.
Screenshot of that error attached

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [*] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
20th September 2019, 8.30 pm onwards (Singapore Local time)
#### Which Web Browser(s) did you see the error in?
    [*] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [*] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/lenorajan/projects/DEV236x
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log
<img width="1187" alt="Screenshot 2019-09-20 at 11 06 00 PM" src="https://user-images.githubusercontent.com/24367551/65337774-69cfa180-dbfb-11e9-9cbc-c3710154dca5.png">
)

**Comment by hpahkala** [comment]
I have same issue; I can not launch any of my notebooks and status is stopped. I also tried to allocate my own Azure VM to the Notebooks, but got errors.

**Comment by ScottHutchinson** [comment]
I repeatedly have the same problem on Windows using Chrome, Edge, and Vivaldi. After my session times out, it says "stopped" and will not restart, no matter what I try (signing out/in, opening a different browser, opening a new incognito window, restarting Windows).

https://notebooks.azure.com/ScottHutchFP/projects/complete-python-3-bootcamp
