### ISSUE TITLE
Cannot load SQL Azure data

### ISSUE THREAD

**Issue by computermacgyver** [Microsoft/AzureNotebooks#75]
### Description

The [FAQ](https://notebooks.azure.com/faq#upload_data) states it is possible to load data from a Azure SQL instance:

```
How can I upload my data and access it in a notebook? 
...
Access data stored in SQL Azure
* !pip install pyodbc from within a Python notebook
* See the documentation and sample code for how to [Connect to a SQL Database using Python](https://azure.microsoft.com/en-us/documentation/articles/sql-database-develop-python-simple/)

```
The "[Getting to your Data in Azure Notebooks](https://notebooks.azure.com/run/Microsoft/samples?dest=/notebooks/Getting%20to%20your%20Data%20in%20Azure%20Notebooks.ipynb#usingsql)" sample notebook also has a section showing the same code linked from the FAQ. 

However, the example notebook (and code I wrote) both fail with the message, "Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)". The same code works successfully on a local machine; so, it appears to be a problem with notebooks.azure.com itself / the security restrictions. The failing code is part of a samples notebook provided by Microsoft, however, which seems strange.

```
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-2-4b3ea9e0271d> in <module>()
      7 
      8 driver= '{ODBC Driver 13 for SQL Server}'
----> 9 cnxn = pyodbc.connect('DRIVER='+driver+';PORT=1433;SERVER='+server+';PORT=1443;DATABASE='+database+';UID='+username+';PWD='+ password)
     10 cursor = cnxn.cursor()
     11 cursor.execute("select @@VERSION")

Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")

```

### Repro Steps
1. Open the [Getting to your Data in Azure Notebooks](https://notebooks.azure.com/run/Microsoft/samples?dest=/notebooks/Getting%20to%20your%20Data%20in%20Azure%20Notebooks.ipynb#usingsql) sample notebook provided by Microsoft
2. Run the cell under the heading "Using SQL"
3. Observe error message that the driver cannot be loaded.

### Usage Scenario (e.g. teaching a computing course at university foo)
Loading data for research / teaching from SQL Azure

### Recommended Metadata
I have tried this on both Python2 and Python3 Jupyter Kernels with the same results
Occurrence Time: 2017-04-07-1500 GMT
Web Browser: Firefox
LibraryID and Notebook Name (if applicable): [Getting to your Data in Azure Notebooks.ipynb in the sample notebooks](https://notebooks.azure.com/run/Microsoft/samples?dest=/notebooks/Getting%20to%20your%20Data%20in%20Azure%20Notebooks.ipynb#usingsql).
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by computermacgyver** [comment]
It appears this issue has been half addressed. Today the error message is

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-1-4b3ea9e0271d> in <module>()
      7 
      8 driver= '{ODBC Driver 13 for SQL Server}'
----> 9 cnxn = pyodbc.connect('DRIVER='+driver+';PORT=1433;SERVER='+server+';PORT=1443;DATABASE='+database+';UID='+username+';PWD='+ password)
     10 cursor = cnxn.cursor()
     11 cursor.execute("select @@VERSION")

OperationalError: ('HYT00', '[HYT00] [unixODBC][Microsoft][ODBC Driver 13 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
```

This suggests the driver is now located, but perhaps does not have any network access.

**Comment by jeancroy** [comment]
I do have similar problem connecting to SQL server.
pyodbc example tell me the kernel has died.
pymssql go further telling me it could not connect to server.

Now I know that SQL azure won't accept connection from anything not on firewall whitelist.
Would it be possible to know which ip to whitelist to accept azure notebook ?

**Comment by computermacgyver** [comment]
The symptoms of this issue have evolved. 2 weeks ago the error message change to a timeout and this past week I started getting the same symptom as @jeancroy, namely a message that the kernel has died. This occurs with both Python2 and Python3 kernels.

@jeancroy You can get the IP address of your notebook server by executing:
```
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
s.connect(("8.8.8.8", 80))
print(s.getsockname()[0])
s.close()
```
I have whitelisted the IP, but still not been able to connect. Really, you shouldn't have to whitelist the IP and should only have to enable 'allow access from azure services', but this also didn't work for me. I would be interested to know the outcomes for you and also what zone your SQL database is in. My SQL database is in uk-south, and I wonder if a differ zone would produce different behavior.

**Comment by crwilcox** [comment]
@computermacgyver, do you know the ip of your sql server? Since you have already stated you opened up to azure ips it seems this may be something more unique. Feel free to send it to my github username at microsoft dot com if you don't want to share it to the world :) I think perhaps there is something particular about certain sql servers.

**Comment by computermacgyver** [comment]
@crwilcox Thank you for investigating this, and my apologies for the delay. My Azure SQL is hosted on  uksouth1-a.control.database.windows.net (51.140.184.11). Do you hosting the database in another region would solve the issue?

It seems more as though the current issue is global to my account. I get the same issue of the kernel dying even if I don't populate the connection information and use the code in the sample notebook as provided.

![screenshot from 2017-05-20 16-02-43](https://cloud.githubusercontent.com/assets/1648212/26276783/21bb4b68-3d76-11e7-9608-7579f47790bf.png)

**Comment by computermacgyver** [comment]
@crwilcox Quick update. pymssql is now working for me. The error in my previous message occurs with pyodbc. So, for now, I would recommend everyone use pymssql.

**Comment by rishi8313** [comment]
@computermacgyver  - Hi.. I am also trying to connect to MSSQL database from Azure notebook preview. How have you whitelisted your IP. If you don't mind, could you please share the connection string used in pymssql connect() method.

**Comment by computermacgyver** [comment]
@rishi8313 You shouldn't have to whitelist the individual IP. In the [firewall settings for your Azure SQL Database](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-firewall-configure), just make sure that 'Allow access to Azure services' is set to 'On'

Example code for pymssql is:

```
import pymssql
conn = pymssql.connect("yourserver.database.windows.net", "yourusername@yourserver", "yourpassword", "yourdatabase")
cursor2 = conn.cursor()
cursor2.execute("select @@VERSION")
row = cursor2.fetchone()
if row:
    print( row)
```

I'm using Pandas; so, the actual code I am using is closer to:
```
import pymssql
import pandas as pd

conn = pymssql.connect("yourserver.database.windows.net", "yourusername@yourserver", "yourpassword", "yourdatabase")

sql="SELECT * FROM table1"
data=pd.read_sql_query(sql, conn)
```

**Comment by rishi8313** [comment]
@computermacgyver  - Hi.. I am getting the below error when tried with the given code.

(20002, 'DB-Lib error message 20002, severity 9:\nAdaptive Server connection failed\n')

**Comment by alyoshkin** [comment]
Anyone knows how to do the same in R ? It seem to have driver problems. Also where is .jar file for JDBC connection ? 

> install.libraries("RODBC")
> library(RODBC)
> cn <- odbcDriverConnect(connection="Driver={ODBC Driver 13 for SQL Server};server=servername.database.windows.net;database=first_db;Uid=admin;Pwd=pwd;Encrypt=yes")
> 
> _Warning message:
> In odbcDriverConnect(connection = "Driver={ODBC Driver 13 for SQL Server};server=servername.database.windows.net;\ndatabase=first_db;Uid=admin;Pwd=pwd;Encrypt=yes"): [RODBC] ERROR: state IM002, code 0, message [unixODBC][Driver Manager]Data source name not found, and no default driver specifiedWarning message:
> In odbcDriverConnect(connection = "Driver={ODBC Driver 13 for SQL Server};server=servername.database.windows.net;\ndatabase=first_db;Uid=admin;Pwd=pwd;Encrypt=yes"): ODBC connection failed_
> 


For python the example with pymssql worked just fine !

**Comment by JWMB** [comment]
In R, using {ODBC Driver 11 for SQL}, I get "Can't open lib 'ODBC Driver 11 for SQL Server'". Substituting 11 with 13 I get "The kernel appears to have died" instead.
In Python (3.6) I also get a kernel crash when using pyodbc, but with pymssql it works fine.

How can I connect to my Azure SQL server from R?

**Comment by jflam** [comment]
How are you authenticating with your SQL Server? Is it SQL Server auth (i.e., you're embedding user id and password in the connection string)?

**Comment by alyoshkin** [comment]
For local R works fine, bc I installed ODBC 13 driver from MS web page. For Azure notebook crushes bc there is no proper driver, or at least it is not in global variables

> library(RODBC)
> cn <- odbcDriverConnect(connection="Driver={ODBC Driver 13 for SQL Server};server=servername.database.windows.net;database=first_db;Uid=user;Pwd=pwd;Encrypt=yes")
> tables = sqlQuery(cn,"select * from sys.tables;")

**Comment by jflam** [comment]
Thanks. Feels like we have a work item to update the ODBC driver in the kernel. @gilbertw can you look at this?

**Comment by JWMB** [comment]
@jflam Yes, embedded in the connection string

**Comment by JWMB** [comment]
Is it possible to get an ETA for this? Not knowing anything about the internals of the system, it seems like a fairly quick fix, however I see @gilbertw isn't very active in this project.

**Comment by shaibee** [comment]
Hi @jflam and @gilbertw 

Any update on this issue? ETA?

**Comment by kenorb** [comment]
> Can't open lib 'ODBC Driver 13 for SQL Server' : file not found

Is usually related to missing `odbcinst.ini` file (`~/.odbcinst.ini` on Linux/macOS).

On macOS, create by:

    printf "[ODBC Driver 13 for SQL Server]\nDescription=Microsoft ODBC Driver 13 for SQL Server\nDriver=/usr/local/lib/libmsodbcsql.13.dylib\n" >> ~/.odbcinst.ini

Related: Microsoft/homebrew-mssql-release/issues/3

**Comment by bcafferky** [comment]
Any update on this? Not being able to load SQL Server data is critical for me.

**Comment by crwilcox** [comment]
ODBC Driver 13 is now present on our machines.

```
import pyodbc
server = 'SERVER.database.windows.net'
database = 'DATABASENAME'
username = 'USERNAME'
password = 'PASSWORD;'
driver= '{ODBC Driver 13 for SQL Server}'
connection_string = 'DRIVER='+driver+';PORT=1433;SERVER='+server+';PORT=1443;DATABASE='+database+';UID='+username+';PWD='+ password
cnxn = pyodbc.connect(connection_string)
```

**Comment by alyoshkin** [comment]
I guess pyodbc uses ODBC 11, but R needs exactly 13. pyodbc worked already months ago. The problem with R still remains.
And you still have 11: 

> nbuser@nbserver:~$ ls /opt/microsoft/msodbcsql/lib64/
> libmsodbcsql-11.0.so.2270.0

**Comment by crwilcox** [comment]
@alyoshkin, it seems we haven't finished rotating all of the old instances out yet. Let me reach out to you again once we are 100% transitioned.
Thanks!
Chris

**Comment by crwilcox** [comment]
I verified this as fixed. I am closing this.

**Comment by fior-di-latte-byte** [comment]
I still get the same error message:
`Error: ('01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 13 for SQL Server' : file not found (0) (SQLDriverConnect)")` , using the default Python 3.6 AzureML kernel.
