### ISSUE TITLE
Unable to use pandas read_csv

### ISSUE THREAD

**Issue by james9226** [microsoft/AzureNotebooks#750]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I have a 997MB data file uploaded to '/data/home/USERNAME/azure_notebooks' but calling pd.read_csv does nothing (or is taking so long that it is unusable). I can load the data locally (or upload it to cloud storage) in a matter or minutes. 

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Upload data to azure notebooks. Try to call pd.read_csv on it. 

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
17:35:00 BST
#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows 10
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Hi @james9226 it looks like you may be running out of memory on our free compute offering, could you try conencting to a data science virtual machine [(docs)](https://docs.microsoft.com/en-us/azure/notebooks/use-data-science-virtual-machine) and see if that helps?

**Comment by james9226** [comment]
I thought I had already upgraded to the full compute account but maybe it had something to do with the legacy of switching over? 

I've now created a Machine Learning service workspace which seems to be exactly what I was looking for to start with and have successfully (and easily) loaded the data. 

Thanks for the replying!

**Comment by kkampf** [comment]
Glad to hear AML is working for you! Free feel to check out the doc I linked for connecting to VM if you end up needing it
