### ISSUE TITLE
Azure Notebook is not able to load

### ISSUE THREAD

**Issue by Diwakargit** [microsoft/AzureNotebooks#756]
We have created one Azure Notebook VM and able to access the jupyter notebook but after providing login credentials over login page. it is now taking time and after some time giving us error "this page is not working"
Kindly help.

**Comment by kkampf** [comment]
Hi @Diwakargit, thanks for reaching out on this! It looks like this may be an issue with an [Azure Machine Learning Notebook VM](https://docs.microsoft.com/en-us/azure/machine-learning/service/how-to-configure-environment#notebookvm), not the Azure Notebooks service. You can file feedback on this from the Azure Portal or via their [GitHub](https://github.com/Azure/MachineLearningNotebooks/issues). I will also forward this along to their team.
