### ISSUE TITLE
Not able to view output of my results, even simplest statement of Python such as 2+2.

### ISSUE THREAD

**Issue by rohitsinha001** [microsoft/AzureNotebooks#757]
Which site did you access us from?
https://notebooks.azure.com

Describe the issue you are encountering
Not able to view output of my results, even simplest statement of Python such as 2+2.
Optional, but often helpful:
Which language/kernel were you using when you experienced this issue?
Python 3.6

What time (please include time zone) did this occur?
Every time

Which Web Browser(s) did you see the error in?
Chrome

Which Operating System are you using? Please specify version as well if possible:
Windows 10 Pro

What is the path to the notebook file (if relevant) that reproduces the issue?
https://firstpython-rohitsinha001.notebooks.azure.com/j/lab

**Comment by christian-vorhemus** [comment]
What do you do to run the cell? Did you wait until the Kernel has started? What happens when you select the cell and click "Run"?

![ezgif-6-6fce6ec6b428](https://user-images.githubusercontent.com/3229424/67408785-d56dab80-f5b9-11e9-85b2-9f865d7184a7.gif)
