### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by DragonflyStats** [microsoft/AzureNotebooks#76]
### Description

Following a suggestion by the person who runs the azure notebook twitter account.

1. Is it possible to get libraries with libraries (sub-libraries, so to speak)?
2. Is it possible to have some way of quickly moving a notebook from one library to another?
3. is it possible to get Julia notebooks too?

I am a big fan of these notebooks, and plan to start using them in teaching from now on.

**Comment by ViralBShah** [comment]
Julia support is in #4.
