### ISSUE TITLE
Notebook is unresponsive. Reconnecting, restarting, stopping and running does not help.

### ISSUE THREAD

**Issue by brunorijsman** [microsoft/AzureNotebooks#764]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [X] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

Error message "Your notebook server appears to be unresponsive. This could be an intermittent connectivity issue so you can try connecting to it again . If your notebook doesn't respond or returns you back here then click the button to restart the notebook server."

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

Tried:
- Clicking the reconnect link 
- Clicking the restart button
- Shutting down and clicking the run button

Nothing helps

UPDATE 1: After 3 hours, the same issue still occurs. Reconnecting, restarting, stopping and restarting - nothing works. 

UPDATE 2: I just noticed that the link in "you can try restarting it again" is linked to a URL that looks weird: "https://.notebooks.azure.com/nb/tree" (note that it starts with a dot and doesn't appear to have any kind of notebook instance ID embedded in it)

UPDATE 3: Logging out and logging back in fixed it. The exact sequence of steps was (1) log out (2) connect VPN to USA instead of Europe (3) log back in, problem is fixed (4) log out again (5) disconnect VPN, back to Europe (6) log back in, problem is still fixes

UPDATE 4: Still no response from Microsoft 14 days after having opened the issue. Looks like AzureNotebooks is a product without any support.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [X] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?

9am, Netherlands time zone

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [X] Other (Please Specify)  Safari

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [X] MacOS
    [] Ubuntu
    [] Other (Please Specify)

#### What is the path to the notebook file (if relevant) that reproduces the issue? For example, https://notebooks.azure.com/<USER-NAME>/libraries/<LIBRARY-NAME>/html/<PATH-TO-FILE>. If this is sensitive, you can email it to nbhelp@microsoft.com

https://notebooks.azure.com/brunorijsman/projects/time-slot-quantum-scheduling
    
#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)

**Comment by andrea-villanca** [comment]
Same problem in 2020

**Comment by brunorijsman** [comment]
Yup.  I have not had any response from Microsoft in the 5 months since I filed the issue.

I stopped using the product; I cannot afford depending on a product that just stops working and offers zero support.

**Comment by mimijanny** [comment]
I'm having the same problem now. What should I do?

**Comment by brunorijsman** [comment]
> I'm having the same problem now. What should I do?

I never ever got any response from Microsoft.  Don't use Microsoft is your only option.

**Comment by ace108** [comment]
I am getting this issue today. I tried to stop and restart the notebook server a few times and keep getting this error after restart. 

![image](https://user-images.githubusercontent.com/10270432/81254967-0c3f7680-905f-11ea-932d-a903b91a5f86.png)

When I clicked on link 'connecting to it again', it opens this:
https://.notebooks.azure.com/nb/tree

See the "." in front? Anyway, I tried with https://notebooks.azure.com/nb/tree and https://notebooks.azure.com/nb which loads nothing. Then went https://notebooks.azure.com and drill to the project and notebook. Still getting the same problem.

**Comment by ace108** [comment]
### I tried something something else that works in case anyone is interested. 
I was using Edge (the Chromium based version one) when I had this issue. 
After trying restart the server a few times, I decided to open Edge In Private mode and signon to https://notebooks.azure.com/ which asked to create a username. I created a different one from what I had before. Amazingly, the project I created before with the notebook appeared but I still cannot get to work on my Edge even after sign out and it but I'm not about to go and clear cache and try.

**Comment by kkampf** [comment]
Hi folks, sorry to hear you're running into issues with Azure Notebooks! I would suggest clearing your cookies and retrying in case you reached an odd wedge state. The site is in Preview, but we also have a [notebook experience in VS Code ](https://code.visualstudio.com/docs/python/jupyter-support) if interested. Hope this helps :)

**Comment by nhanhardt** [comment]
Had this exact same issue, clearing cache and cookies worked for me.  Using Edge (Chromium) v83.0.478.33.
