### ISSUE TITLE
Kernel Not Connected

### ISSUE THREAD

**Issue by govirginia** [microsoft/AzureNotebooks#766]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
Kernel Not Connected

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://helloworldinpython-kevin-hankins.notebooks.azure.com/nb/notebooks/HelloWorldInPython.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 3.6 
Running on Free Compute

#### What time (please include time zone) did this occur?
11/26/2019 noon to 2pm EDT

#### Which Web Browser(s) did you see the error in?
    [] Chrome
also IE11

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows 10 64 bit

#### Each notebook instance has log files. It may be helpful for us to have them. You can retrieve them by following this [help article](https://notebooks.azure.com/help/jupyter-notebooks/troubleshooting/jupyter-debug-log)
cant find

**Comment by hamlett-neil-ur** [comment]
Experience same problem.  Created brand new DSVM, brand new test project. All using default configurations.

Am able to SSH into DSVM and perform basic operations using iPython. So the server is operational.

I follow the steps to start the project on DirectCompute instance.
<img width="895" alt="image" src="https://user-images.githubusercontent.com/58610536/70378113-cc773600-18ea-11ea-865a-c7f24ab68839.png">

Created new project "Untitled.ipynb" When I launch, it gives me "Kernel error" state. 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/58610536/70378086-7d310580-18ea-11ea-94bc-cde471ed215a.png">


<img width="888" alt="image" src="https://user-images.githubusercontent.com/58610536/70378143-1fe98400-18eb-11ea-9b95-dccb7935eb79.png">
