### ISSUE TITLE
Can Not Upload jpeg files...where do they go after hitting upload button so I can reference in my code???

### ISSUE THREAD

**Issue by calcqu** [Microsoft/AzureNotebooks#77]
Please consider the template below to file your issue. 

### Description
Can Not Upload jpeg files...where do they go after hitting upload button so I can reference in my code???

### Repro Steps
I am trying to open a jpeg in a azure nb.  I tried from my local computer directory, and it failed.  I tried to upload it using the tab labeled data and dropdown that says upload but where does it go?  I figured it would be in current azure directory now so I could just do open('file.ext') but that fails...then I tried my azure library path but that fails...

Most frustrating...I can open it fine on my local jupyter notebook - what am i missing using azure?? 

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
hi, i just tried it and it seems to work.  i dont get a confirmation that
it was uploaded, but all the .jpg files i multi-selected are available in
my home dir.  downloaded as well to double check & they work for me.

**Comment by calcqu** [comment]
But what is the home directory??? 😂 like can you write that out so I can try it in my code please - thanks!

**Comment by smortaz** [comment]
ah!  it's the standard linux home dir, ie "~".  so in your notebooks you
can:

[image: Inline image 1]


btw the upload/download menu will be improving in the next couple of weeks.

**Comment by smortaz** [comment]
additionally, you can open a shell prompt by:

Juypter / New / Terminal

and that it'll give you a standard shell that you can use to check out your
local files.

**Comment by calcqu** [comment]
Thanks but may I ask for more explicit clarity - so can you send me a screenshot of where you identify the directory where your jpeg file was uploaded to - for example my file name is image.jpg so when I do my image.open('path/image.jpeg')...what will the path be???

Will it be ~/image.jpeg?

Sorry but it's always best to be super clear - thanks so much!!!

**Comment by smortaz** [comment]
oops!  i replied from gmail and pasted in the picture and looks like it didnt make it. here its:

![rem nnnn](https://cloud.githubusercontent.com/assets/742484/25057076/c87661e8-2121-11e7-98ad-eafc1b7b829c.png)

so path is /home/nbuser/yourimage.jpg

**Comment by calcqu** [comment]
Hi - I have Keras on my local machine but can access in the azurenotebook - please advise.  i am using in conjunction with TensorFlow.

**Comment by smortaz** [comment]
On Sun, May 21, 2017 at 2:02 PM calcqu <notifications@github.com> wrote:

> Hi - I have Keras on my local machine



but can access in the azurenotebook -


Can or can't ?  I assume you mean can't.

Have you installed keras on azure notebooks?  If not then it won't be
there. Check their instructions for installation.

please advise. i am using in conjunction with TensorFlow.
>
> Sent from my iPhone
>
