### ISSUE TITLE
Error with Steps in 04 Polynomial Regression - Step 2

### ISSUE THREAD

**Issue by Signet13** [microsoft/AzureNotebooks#774]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
   https://mslearnmlcrashcoursepytho-cygnetxiv.notebooks.azure.com/j/notebooks/04.%20Polynomial%20Regression%20-%20Python.ipynb

#### Describe the issue you are encountering

*****Not a processing error.  This is a documentation error*****
Documentation error in notebook describing transpose command in 
Step 2 of Polynomial Regression in the ML notebook:
Transpose command seems to have magically added a sixth row of data.

Data pre transpose = 5 x 24
Data post-transpose = 24 x 6

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://mslearnmlcrashcoursepytho-cygnetxiv.notebooks.azure.com/j/notebooks/04.%20Polynomial%20Regression%20-%20Python.ipynb

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Thanks for the heads up! Adding @jasallen to help update the Learn module
