### ISSUE TITLE
New notebook doesn't open as a notebook but as a text file

### ISSUE THREAD

**Issue by HumaMilisic** [microsoft/AzureNotebooks#775]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

New notebook doesn't open as a notebook but as a text file.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.

1. Open the 'Create New Notebook' popup
1. Pick the language, Python 3.6 
1. Enter text into the "Notebook Name" field
1. Press the Enter key

Result:

1. A new file is created, without an extension. 
1. Because it is without extension, the notebook opens as a text file

'Enter' triggers the forms submit before the other necesary logic completes.

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [x] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Hi @HumaMilisic are you still seeing this issue? Just tried to reproduce this in Firefox and all worked as expected
