### ISSUE TITLE
Access to own Notebooks denied

### ISSUE THREAD

**Issue by ThePhoebius** [Microsoft/AzureNotebooks#78]
### Description
I tried to open a notebook from inside AzureML, which worked fine just a few days ago, but then get the "Access Denied" error message, telling me to check if I am signed in (I am, although with an ID i haven't seen before. Manual login with proper AzureML credentials produces the same ID) or to ask the person who gave me the link to share the notebook to the library instead of the server.

### Repro Steps
Sign in to studio.azureml.net
Open notebook from "Notebooks"-panel or from a dataset in experiments.

### Usage Scenario (e.g. teaching a computing course at university foo)
Working on edX-course on laptop in public network.
Issue did reproduce with smartphone on mobile data.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Any language
Occurrence Time: ~15:30 UTC+1, April 14, 2017
Web Browser: Vivaldi 1.8.770.56, Opera mobile 42.7.2246.114996

The AzureML Account is a free subscription.

edit:
Yesterday evening I tried it on my Desktop PC at home and could not reproduce the issue. Today I get the same error again.

**Comment by 8forty** [comment]
FWIW I've discovered that I also have this problem but only with Chrome, but not with Edge.

**Comment by crwilcox** [comment]
@8forty, I am going to try and keep the thread together as this issue is the same (I believe) as #79 which I have been posting to.

**Comment by ThePhoebius** [comment]
My personal problem was solved. The error occurred, because my browser blocked third party cookies. As discussed in #79 I solved it by adding an exception for azure.com to that setting. So I'm closing this thread.
