### ISSUE TITLE
Unable to load project after signing in.

### ISSUE THREAD

**Issue by Shrey-Viradiya** [microsoft/AzureNotebooks#783]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
after signing in, my projects are not being loaded. My request is timed out. I tried this in two browsers. Tried signing out and signing in again but nothing happened.

The error is tracked by id: 9ab404c0-033f-4af5-a047-a9da362e131e

#### What time (please include time zone) did this occur?
Time when this occured: 10:09 Indian Standard Time
#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [✔] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [✔] Other (Opera)

#### Which Operating System are you using? Please specify version as well if possible:
    [✔] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by johnsonjmaliakal** [comment]
Try closing the browser you are using and try again.
Also, it would be very useful for the guys in the backend if you also provided a link to your project.
Make sure that it is set to public.
