### ISSUE TITLE
Predictive Maintenance Modeling Guide Python 3 Notebook.ipynb ---Error 

### ISSUE THREAD

**Issue by kevinochieng** [microsoft/AzureNotebooks#785]
Hello am following your python notebook:Predictive Maintenance Modeling Guide Python 3 Notebook.ipynb 
am getting this error :
TypeError: ufunc subtract cannot use operands with types dtype('<M8[ns]') and dtype('float64')
on line 22. 
Kindly assist.

**Comment by Amalx9** [comment]
Hi, have you found a solution to this?
