### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by DevSecOps-Prod** [microsoft/AzureNotebooks#787]
ModuleNotFoundError: No module named 'azure'.

I tried install using pip install azure doesn't work.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003E33088>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003E27B88>: Failed to establish a new connection: [WinError 10051] A socket operation was attempted to an unreachable network')': /simple/azure/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003E3F508>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/azure/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000003E3F7C8>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/azure/

ERROR: Could not find a version that satisfies the requirement azure (from versions: none)
ERROR: No matching distribution found for azure

**Comment by MaheshDolas** [comment]
ERROR: Could not find a version that satisfies the requirement azure (from versions: none)
ERROR: No matching distribution found for azure
