### ISSUE TITLE
Notebook cannot connect to DSVM , validation fail

### ISSUE THREAD

**Issue by JanderHungrige** [microsoft/AzureNotebooks#788]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering

I have a DSVM running (Ubuntu, differnet sizes, different locations). 
I can connect via SSH to the DSVM. 
However, when trying to connect via the Azure Notebook, the validation fails with following error:

> There seems to be an issue connecting to the DSVM selected. Please check if you are able to connect to JupyterHub port at https://...IP...:8000/ and retry.

The manual checkup of the https does not work. No other information is given. 
My own solution I once found (applying a application security group) does not work.

The DSVM is not in my region, could that be the problem? (The quota for my region is up, so I cannot try)
What would be a  soultion?

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [x] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [x] Ubuntu
    [] Other (Please Specify)

**Comment by CrimyTheBold** [comment]
It does that to me all the time. I have to do it 3 or 4 times, then it works. I guess the jupyter server on the 8000 port takes some time to start.
Keep pushing the validate button :)
