### ISSUE TITLE
Admin consent does not apply to AD members of type "Guest"

### ISSUE THREAD

**Issue by mVaihinger** [microsoft/AzureNotebooks#789]
#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Describe the issue you are encountering
Users of type "Guest" of my AD-backed organization cannot use Azure Notebooks although I did an admin consent. They are still shown the following error message when trying to log in to Azure notebooks. 

> "You can't access this application. Azure Notebooks needs permission to access resources in your organization that only an admin can grant. Please ask an admin to grant permission to this app before you can use it."

Users of type "Member" can use Azure notebooks. Is this behavior intended? If so, please update the documentation. 

Please change admin consent to apply to "Guest" users, too.

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
As an admin, do an admin consent for your AD tenant at https://notebooks.azure.com/account/adminConsent. Then log in to Azure Notebooks as an AD "Guest" user.

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [x] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Thanks for reaching out and using Azure Notebooks! This looks like an error you may need to work with your AD admin on to get member permissions.
