### ISSUE TITLE
None of my notebooks are running. Help. Need for class.

### ISSUE THREAD

**Issue by lvwarren** [microsoft/AzureNotebooks#790]
Please describe your issue as completely as possible.

#### Which site did you access us from?

https://notebooks.azure.com/lvwarren/projects/IntroductionToR

#### Describe the issue you are encountering

Notebooks won't run, none of the eight python R Jupyter notebooks will execute
They ran fine yesterday

#### What steps can we take to reproduce this issue? If you have this in a notebook already, you can just share a link here.
https://notebooks.azure.com/lvwarren/projects/IntroductionToR

#### Which language/kernel were you using when you experienced this issue?

    [] R 

#### What time (please include time zone) did this occur?

Thu Feb 20, 4:28 PM
#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] MacOS

#### What is the path to the notebook file (if relevant) that reproduces the issue? 
See above, link not redirecting properly

**Comment by chasbecker** [comment]
I am now having the same problem with my Python notebooks.:
https://notebooks.azure.com/clbecker/projects/textanalysis
I was getting an error message, but now my screen just flashes and takes me back to the directory listing.

**Comment by lvwarren** [comment]
it started working after i logged out, wrote this message and logged back in. go figure.

________________________________

**Comment by chasbecker** [comment]
Thanks for the update.  I'll keep trying....

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
