### ISSUE TITLE
What can we do to increase the storage space of data for .csv, excel files for AzureNotebooks to use

### ISSUE THREAD

**Issue by dwynndrm** [microsoft/AzureNotebooks#795]
In case we have many .csv, Excel files how can we increase storage space or where to store those .csv, Excel files for AzureNotebooks to use to process those files.

#### Which site did you access us from?
    [x] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [x] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [x] Chrome
    [] Firefox
    [x] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [x] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by CrimyTheBold** [comment]
I'm doing Deep Learning so i save the weights from time to time during training. But after a while, the "account is full" and crash my training.
We need more space !!
