### ISSUE TITLE
intro to cntk

### ISSUE THREAD

**Issue by sojohan** [Microsoft/AzureNotebooks#80]
Please consider the template below to file your issue. 

### Description
The cntk tutorials doesn't work straight out of the box! 
Any ideas how one can get these to work?

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A):
Occurrence Time:
Web Browser:
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
@sojohan, Could you please elaborate? @sayanpa from the Microsoft/CNTK project.

**Comment by sayanpa** [comment]
Happy to help. What environment are you trying to run? All the tutorials are nightly tested for any regression. So we need to look into your environment. These notebooks are being used for teaching at universities so definitely a supported scenario.

**Comment by crwilcox** [comment]
Closing as stale.
