### ISSUE TITLE
Cell don't Run

### ISSUE THREAD

**Issue by KPIyer** [microsoft/AzureNotebooks#800]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by Tosin654** [comment]
Hello,
Please my jupyter notebook cell does not run. I accessed the site from notebook.azure.com. The cell will not run unless the kernel is restarted for every command. I am running python 3 on the notebook with chrome browser with windows 8. Thanks
