### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by severe90** [microsoft/AzureNotebooks#810]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### Which Web Browser(s) did you see the error in?
    [] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by kkampf** [comment]
Hi @severe90 I don't see which link you were trying to access when you saw the Page Not Found error in your issue above. In general, please make sure you logged in and that the project you are trying to access is public
