### ISSUE TITLE
Reinstall python modules every time notebook opened? 

### ISSUE THREAD

**Issue by SeaDude** [microsoft/AzureNotebooks#813]
I'm performing `!pip install <module-name>` to bring in some external modules. 
- Are Azure Notebooks reverted to an original state each time they are closed?
- Do I need to reinstall external modules **each time** I run the notebook or _do they persist_?

I can't tell. 

For some packages, the messages say `Requirement already satisfied...` for others, it re-downloads and installs the module.

![image](https://user-images.githubusercontent.com/8636973/80627794-48425e00-8a05-11ea-8f8c-e4ac56ee3cce.png)

Thank you

**Comment by kkampf** [comment]
Hi @SeaDude Azure Notebooks' free compute comes with some common packages preinstalled, which is likely those that you are seeing "requirement already satisfied" for. The free compute option puts you in a fresh compute environment each time you attach to it. So, you would need to reinstall these extra packages each time. You can do this by leaving the pip install cells in the notebook and rerunning those cells each time. Alternatively, you could use the [DSVM option](https://docs.microsoft.com/en-us/azure/notebooks/use-data-science-virtual-machine) to connect to the same virtual machine each time. Then, you could only install the packages once and always connect to that same VM

**Comment by SeaDude** [comment]
Thank you very much.
