### ISSUE TITLE
Uploading files from Url

### ISSUE THREAD

**Issue by sofianBen** [microsoft/AzureNotebooks#820]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com

#### Describe the issue you are encountering
I would like to upload two files of 245MB and 175MB. They are too big for uploads "from Computer". I'm trying to upload them "from Url" but it tells me that Azure Notebook doesn't have access rights while the files are in public on the different drives I've tried.
Here is the error message:
"Error while downloading notebook: Notebook does not exist at target URL, or target site has not given us permission to download it. If the file is accessible via other means, please try uploading from computer."
Can you tell me what platform I can put my files on so I can upload them to Azure Notebooks?

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 

#### What time (please include time zone) did this occur?
Not Applicable

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:
    [] Windows

**Comment by kkampf** [comment]
Sorry to hear you're running into this! I just tested the import from URL with a public raw file from GitHub without issue.

**Comment by sofianBen** [comment]
> Sorry to hear you're running into this! I just tested the import from URL with a public raw file from GitHub without issue.

On Github, you can't import files larger than 100MB. What did you do to upload big files to github?

**Comment by kkampf** [comment]
Apologies, missed your note on your file sizes! There are a few different approaches you can use for pulling in data if the from URL upload is not working for your case. We have info on this in our [docs](https://docs.microsoft.com/en-us/azure/notebooks/work-with-project-data-files) as well a [sample project](https://notebooks.azure.com/Microsoft/projects/2018-data-access). Hope that helps!
