### ISSUE TITLE
upgrading R version on Azure jupyter notebook 

### ISSUE THREAD

**Issue by minali19** [microsoft/AzureNotebooks#823]
#### Which site did you access us from?
    [] https://notebooks.azure.com
 
#### Describe the issue you are encountering
'Remotes' package is not available In 3.5.3 Version of R , and it is supported by 3.6.3 , so want to know how to upgrade the R version On Azure jupyter notebook
#### Which language/kernel were you using when you experienced this issue?

    [] R 

#### Which Web Browser(s) did you see the error in?
    [] Chrome

#### Which Operating System are you using? Please specify version as well if possible:

    [] Ubuntu

**Comment by DragonflyStats** [comment]
was this issue fixed?
