### ISSUE TITLE
Opening Notebook Reaches "Page not Found" error

### ISSUE THREAD

**Issue by Meaxers** [Microsoft/AzureNotebooks#83]
Please consider the template below to file your issue. 

### Recommended Metadata
The Jupyter Kernel: R
Occurrence Time: 2017.04.23 11:10
Web Browser: Chrome
LibraryID and Notebook Name (if applicable): Bickett DS450 Homework #1 - Wine Prediction.ipynb

**Comment by smortaz** [comment]
A guess: remove the "#" in the title

**Comment by Meaxers** [comment]
@smortaz - thank you - I hope this is the issue.  Any idea on how I can change the name without being able to open the file?  Unfortunately I did all of my work in this file.

**Comment by smortaz** [comment]
I think u can download the whole library, unzip, then reload that notebook
under a different name. Not 100 percent sure since on mobile. Look for
download on library page

**Comment by Meaxers** [comment]
@smortaz you're a goddamned champion. Thanks, you saved my bacon.
