### ISSUE TITLE
Feature Request: Notebooks with Visual Studio Code

### ISSUE THREAD

**Issue by DSgUY** [microsoft/AzureNotebooks#835]
It would be nice to have a way to connect VSC to azurenotebooks. 

I tried to setup a public key so I can access with VSC over ssh but ports seems to be disabled. I also fail to get the notebook url to do what is explained in [https://code.visualstudio.com/docs/python/jupyter-support]

Great work!

**Comment by ChayimFriedman2** [comment]
Agree. I love the VSCode interface and it has much more complete coding helpers (IntelliSense etc.). I think there **must** be a way to remotely connect to the notebook.

**Comment by kkampf** [comment]
Hi folks! You can connect to a [remote compute via SSH](https://code.visualstudio.com/docs/remote/ssh)or a [remote Jupyter server](https://code.visualstudio.com/docs/python/jupyter-support#_connect-to-a-remote-jupyter-server) with VS Code. However, we don't support connecting to Azure Notebooks compute. Hope that helps :)

**Comment by DSgUY** [comment]
Yes, amazing idea! Also pretty useful when working with a remote Raspberry Pi!!

**Comment by ChayimFriedman2** [comment]
We know it's possible to connect to a remote Jupyter server. If it would not be, we would fire this request on the VSCode repo 😸
