### ISSUE TITLE
End of the Azure Notebooks preview and retirement of the site

### ISSUE THREAD

**Issue by acrokat** [microsoft/AzureNotebooks#838]
The Azure Notebooks preview is ending on *October 9th* as we focus on building great Jupyter notebooks experiences across our products, including Visual Studio Code, Azure, GitHub, Codespaces. Please visit [our site](https://aka.ms/aznb-notebooks-at-msft) to find information on these experiences as well as instructions for downloading any content you currently have on the Azure Notebooks site.

We deeply value the Azure Notebooks community and all that was created over the past 4 years. This has our team all the more excited to share our latest notebooks experiences with you.

**Comment by corsilt** [comment]
I have some Jupyer Notebooks that lived on my Azure studio ML server. How can I access those? I am having trouble connecting to the server as I did before, and I would like to download them before this service is removed.

**Comment by xiaoharper** [comment]
Hi @corsilt , 

The AML Studio(classic) notebook feature has been shutdown in April 2020. There were email and in app notification for the shutdown in April. 

If you are using Studio(classic) standard workspace, you can still find the notebook files in workspace associated storage account following below steps:
1.	Go to the Workspace storage account. You can find the storage account in "Settings" tab in AML Studio(classic)
2.	Go to the storage account in Azure portal, then go to notebooks container
3.	All your notebook files are in this container, you can download there
 
If you are using free workspace,  I'm afraid it's not possible to restore the notebooks.

**Comment by whatevergeek** [comment]
dear azure notebooks team, 

thank you very much for providing such a great experience these past years
especially to @smortaz who has been supporting when i was creating a jupyter lab workshop for the community

azure notebooks has been the best free platform hosting jupyter lab
i bet the community will miss this gift

so sad to see it go.. i guess it's tough to sustain such product/service
i wonder where/how google colab gets it funding...

anyway, kudos to the team and i wish you all the best in your future endeavors!

**Comment by MsShannon** [comment]
Shutting this down now without an easy, free option for teachers during online learning is tragic!  I just started my class on Python and now have to figure out an easy way for them to learn without having to install any new software.

Please reconsider shutting this down until kids are back in school!

**Comment by whatevergeek** [comment]
hi @MsShannon ,
I empathize with your situation. 
Azure Notebooks was far the best free jupyter lab platform available online.
I was deeply saddened by the news too. But, I guess the team (as awesome as they are) would have their legitimate reasons.
That aside, I was also searching for other viable free platforms.

Here's what I got so far:

- https://mybinder.org/ - This can generate an instance of jupyter lab based on a github repo. It requires setup on github. No installation needed on my local computer.
-  https://www.kaggle.com/kernels - Free notebook platform in the cloud. works like jupyter notebook though doesn't look like one.
- https://colab.research.google.com/ -  Free notebook platform in the cloud. works like jupyter notebook though doesn't look like one. I still use this if a need free GPU. (and only if i need the free GPU :-P)
- https://datalore.jetbrains.com/ -  yet another free notebook platform in the cloud. works like jupyter notebook though doesn't look like one.
- https://cocalc.com/ - This is actually great if you're good with the initial setup. I used it for a few days.. then, I realized I need to pay if my notebook needs to access internet like cloning a github repo :-P
- https://www.katacoda.com/ - This last one is a hack. But, I was able to run a jupyter lab instance :-)
For creating jupyter lab instance:
	• Follow the tutorial but use lab instead of notebook
	• https://www.katacoda.com/openshift/courses/ai-machine-learning/jupyter-notebooks

**Comment by MsShannon** [comment]
Thank you for your response and assistance!


Stacey Shannon

Computer Science Teacher

2200 Wakefield Pines Dr.

Raleigh, NC  27614

________________________________

**Comment by bilalProgTech** [comment]
Hello,
I wanted to download the Azure Notebook Project in a zip file, but I'm not able to download it from the azure notebook portal, though, the sit pop-up was also allowed. Please let me know the process with which I can easily download my small project.

**Comment by andneilmsft** [comment]
Hey Bilal, based on your github profile. I guessed your profile URL as [https://notebooks.azure.com/bilalhungund/](https://notebooks.azure.com/bilalhungund/). I  was able to download CT_IDX_Model - your single publicly available project. I do see that the ZIP IS 250mb. It will take a few minutes to compress and become available to download.

**Comment by bilalProgTech** [comment]
Hey Andrew, 
I'm so sorry but will you please either edit or delete this comment, if possible because of some issue. 
Thanking you.

**Comment by andneilmsft** [comment]
done!

**Comment by bilalProgTech** [comment]
Thank you Andrew!

**Comment by bilalProgTech** [comment]
> done!

Hello Andrew, would you please help in downloading the zip file of the azure notebook project of my account, I don't know why but I'm facing some issue in downloading the file.

**Comment by andneilmsft** [comment]
We’ll look into getting these files to you.

**Comment by MsShannon** [comment]
I have downloaded them all.  Thank you.


Stacey Shannon

Computer Science Teacher

2200 Wakefield Pines Dr.

Raleigh, NC  27614

919-295-2537 (Google Voice)
________________________________

**Comment by yakosgit** [comment]
Such a disappointing and inconsiderate way of shutting down the platform. You did not even bother giving an option for the users to download all their project at once as a zip file or even select multiple projects to download. There is no way to select all the projects and it is taking for every to download each one individually. Cheap!

**Comment by marsantser** [comment]
Hello everybody!

I have donwloaded 2 of my projects in a zip file but I cannot do it with the third one.
I think that it is becasuse it is too big.

Could you help me please?
It is really important for me.

Thanks in advance!

**Comment by kkampf** [comment]
@marsantser hello! is this a public project? If so, could you provide a link to it?

**Comment by marsantser** [comment]
> @marsantser hello! is this a public project? If so, could you provide a link to it?

@kkampf thanks for your answer.
I am talking about projects into notebooks azure, ok?

I am not sure about if my projects are public. I think that they don't.
You can find attached an image about my projects.
![image](https://user-images.githubusercontent.com/74729520/99875809-abd6e780-2bf2-11eb-8053-4c6051199e08.png)

I have donwloaded "3DMountains" and "Udemy" but I cannot donwload "99.Labs".
Can you help me?

Thanks in advance!

Regards,
Mario

**Comment by msherv** [comment]
Hi - only seeing this message now and realizing I am 12 days too late! Thank you for the great service.

Also, were there any backups or migration done for people who missed the deadline to backup their own files?

Looking forward to the new platform!

Cheers

**Comment by kkampf** [comment]
@msherv Hello! You can contact me Katherine.Kampf@microsoft.com for direct help

**Comment by gachet** [comment]
How I can recover my notebooks ?
Thanks un advance

Diego Gachet
diegogachet@hotmail.com
