### ISSUE TITLE
Clone a shared library one step process missing

### ISSUE THREAD

**Issue by eric-camplin** [Microsoft/AzureNotebooks#84]
### Description: Clone a shared library one step process missing  
given a link to a shared library there is no Clone Library button  after link is opened

### Repro Steps  
- get a link like https://notebooks.azure.com/eric/libraries/Unit1Demo and open
- look for a way to clone entire library (none found)  
(workaround to open an individual file, open in jupyter, clone dialog opens - after clone of nb can find the library of nb in your libraries)

### Usage Scenario  
share a library with students or colleague

### Recommended Metadata
The Jupyter Kernel : python 3
Occurrence Time: 12:45 PM PST 4/25/17
Web Browser: edge or chrome
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/eric/libraries/Unit1Demo

**Comment by smortaz** [comment]
It's coming!

**Comment by eric-camplin** [comment]
is it possible to get an ETA?

**Comment by crwilcox** [comment]
Hi Eric. I would expect an update to this to go live in 1-2 weeks. We are working to improve the experience in this area. Hopefully our solution resolves your concerns.

Thanks!
Chris

**Comment by crwilcox** [comment]
Update was released last Thursday. Closing this.
