### ISSUE TITLE
No Kernel Connected - Kernel Operations greyed out

### ISSUE THREAD

**Issue by orngeatom** [microsoft/AzureNotebooks#840]
Please describe your issue as completely as possible.

#### Which site did you access us from?
    [] https://notebooks.azure.com
    [] https://studio.azureml.net
    [X] https://ml.azureml.com

#### Describe the issue you are encountering
no kernel connected cannot execute notebook

#### Which language/kernel were you using when you experienced this issue?
    [] Python 2.7 
    [] Python 3.5
    [] Python 3.6 
    [] R 
    [] F#
    [] Terminal

#### What time (please include time zone) did this occur?
Eastern 

#### Which Web Browser(s) did you see the error in?
    [X] Chrome
    [] Firefox
    [] Internet Explorer / Edge (Please note this is not supported)
    [] Other (Please Specify)

#### Which Operating System are you using? Please specify version as well if possible:
    [X] Windows
    [] MacOS
    [] Ubuntu
    [] Other (Please Specify)

**Comment by kimhelmer** [comment]
I face the same issue. I have tried multiple computes. deleted ressource group, still kernel is gryed out. I can work with them in jupyter but not in Azure ML.

Starting and stopping the compute doesnt help either.

![kernel error](https://user-images.githubusercontent.com/73886523/105482966-7198cd80-5ca9-11eb-996c-73ed6be6a2d8.png)

**Comment by kkampf** [comment]
@kimhelmer can you reach out to me at katherine.kampf@microsoft.com? It looks like this issue is with Azure ML but if you contact me there I can connect you with the right folks. Thanks!
