### ISSUE TITLE
Azure Notebook "Forgets" Postgres Connections and Will not reconnect to Postgres DB

### ISSUE THREAD

**Issue by carydavis-sd** [microsoft/AzureNotebooks#843]
Attached Azure Studio to a Postgres SQL database on AWS.
Was able to successfully run sql queries from cell.  
Save and closed notebook.
Once notebook is reopened and I'm reconnected to the Postgres server and attempt to re-run the query from the cell dialog box pops up asking for a connection but no longer offers postgres sql as an option.  SQL server is the only option available.  

![image](https://user-images.githubusercontent.com/71886927/95539628-dbbc8980-09bc-11eb-848d-31c84158532f.png)

![image](https://user-images.githubusercontent.com/71886927/95539757-3524b880-09bd-11eb-8704-d02b8240d4d2.png)

**Comment by kkampf** [comment]
Hi @carydavis-sd it looks like this issue is actually with Azure Data Studio, not notebooks.azure.com
I would suggest creating this issue in the Data Studio repo for the best help https://github.com/microsoft/azuredatastudio/issues
