### ISSUE TITLE
Installing Graphlab 

### ISSUE THREAD

**Issue by Walid-Ked** [Microsoft/AzureNotebooks#85]
### Description
I'm trying to install Graphlab using pip but i get the following error : 

`Collecting https://get.graphlab.com/GraphLab-Create/2.1/xxxxxx@gmail.com/4979-2629-7787-8767-049A-C0BB-5869-FBD6/GraphLab-Create-License.tar.gz
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by ProxyError('Cannot connect to proxy., OSError('Tunnel connection failed: 403 Forbidden',))': `/GraphLab-Create/2.1/xxxxxx@gmail.com/4979-2629-7787-8767-049A-C0BB-5869-FBD6/GraphLab-Create-License.tar.gz`
  

### Repro Steps
open a new notebook and try :
 
!pip install --upgrade --no-cache-dir https://get.graphlab.com/GraphLab-Create/2.1/your registered email address here/your product key here/GraphLab-Create-License.tar.gz

**Comment by crwilcox** [comment]
Fixed the issue as the problem was graphlab.com wasn't whitelisted. Handled on StackOverflow.
