### ISSUE TITLE
Error accessing Notebooks from Azure ML

### ISSUE THREAD

**Issue by ianovski** [Microsoft/AzureNotebooks#86]
When I attempt to create/edit a notebook from Azure ML using my Microsoft account, I receive the following error: 
"You do not have access to the specified notebook.
If someone shared this link with you please ask them to share the link to their library instead of sharing the link to their running notebook server.
Otherwise check if you are still signed in and please login again if you've been signed out."

I am logged into the same account in Notebooks so I do not understand why I'm not gaining access.

Occurrence Time: 11:26 4/28/2017
Web Browser: Chrome

**Comment by ianovski** [comment]
Update: Worked fine on the Edge browser. Seems like a bug that should be looked at.

**Comment by crwilcox** [comment]
It has been looked at and resolved. You need to enable third party cookies.
https://github.com/Microsoft/AzureNotebooks/issues/79

**Comment by laktak** [comment]
> You need to enable third party cookies.

That should be part of the FAQ.

**Comment by crwilcox** [comment]
@laktak , thanks for the suggestion. We have a work item planned to improve the messaging in this case so you receive better feedback.
