### ISSUE TITLE
YSOD if cancel auth dialog from mobile

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/AzureNotebooks#87]
Please consider the template below to file your issue. 

### Description
I got ASP.NET Yellow Screen of Death when first clicked Sign In, then selected work account, on dialog to confirm granting the permissions I clicked Cancel.

### Repro Steps
See above

### Usage Scenario (e.g. teaching a computing course at university foo)
n/a

### Recommended Metadata
Occurrence Time: April, 28 2017 ~22:18
Web Browser: Chrome for Android ver. 58.0, Android 7.1.2

**Comment by abatishchev** [comment]
I was able to reproduce this again

![screenshot_20170428-222315](https://cloud.githubusercontent.com/assets/351644/25553161/5f682858-2c61-11e7-8ab9-3f7eba2c568f.png)

**Comment by crwilcox** [comment]
Sorry for the delay getting back to you. Did this error happen around  when you posted it (2017-Apr-28 22:24 PDT)?

Or was it about 10-30 minutes before? I am going to look into our logs and see if I can't find the underlying error but if I can get a time when it occurred I can narrow in on a much smaller set of logs :)

Thanks!
Chris

**Comment by abatishchev** [comment]
Hi Chris, no worries, thanks for looking into this issue! It did happen not earlier than 20 minutes before I posted, and more likely in 5-7 minutes.

**Comment by crwilcox** [comment]
@abatishchev, we will look into a fix. It seems from my initial inspection it is an interaction with angular (the javascript framework we use), android, and auth. I was able to discover some logs that appear to be from your. Hopefully we can get to the bottom of this and get a fix out.

**Comment by crwilcox** [comment]
Closing this as we have done work to remove the ASP.NET Yellow Screen.
