### ISSUE TITLE
CondaVerificationError on attempt to install fenics

### ISSUE THREAD

**Issue by leonavery** [Microsoft/AzureNotebooks#88]
### Description

I'm using azure to explore FEniCS. I need to start by installing fenics every day, which I do using the following in a notebook:

    !conda config --add channels conda-forge
    !conda install -y fenics

This has worked fine the last few days. This morning, however, I'm getting a long string of messages like this (full log attached):

    CondaVerificationError: The package for gcc located at /home/nbcommon/anaconda3_410/pkgs/gcc-4.8.5-7
    appears to be corrupted. The path 'share/java/libgcj-tools-4.8.5.jar'
    specified in the package manifest cannot be found.

    CondaVerificationError: The package for gcc located at /home/nbcommon/anaconda3_410/pkgs/gcc-4.8.5-7
    appears to be corrupted. The path 'share/locale/be/LC_MESSAGES/cpplib.mo'
    specified in the package manifest cannot be found.

### Repro Steps

Just try to evaluate 

    !conda config --add channels conda-forge
    !conda install -y fenics

in a Python 3 Jupyter notebook. (Haven't yet tried Python2.)

### Usage Scenario (e.g. teaching a computing course at university foo)

Self-teaching.

### Recommended Metadata
The Jupyter Kernel: Python3
Occurrence Time: 7:00 AM (Japan time)
Web Browser: Firefox
LibraryID and Notebook Name (if applicable): lavery-waterloo/Libraries/starting/FENICS ft08_navier_stokes_channel.ipynb
(URL : https://notebooks.azure.com/run/lavery-waterloo/starting?dest=/notebooks/FENICS%20ft07_navier_stokes_channel.ipynb )
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable
[CondaVerificantionError.txt](https://github.com/Microsoft/AzureNotebooks/files/967048/CondaVerificantionError.txt)

**Comment by leonavery** [comment]
It seems that 

    conda clean --all

followed by responding y to everything resolves the problem. Still don't know why it occurs in the first place, though. Presumably an earlier install ended without completing successfully, leaving gcc in a corrupt state.

**Comment by leonavery** [comment]
It seems that 

    conda clean --all

followed by responding y to everything resolves the problem. Still don't know why it occurs in the first place, though. Presumably an earlier install ended without completing successfully, leaving gcc in a corrupt state.

**Comment by shandou** [comment]
@leonavery I ran into the same problem just now. Thanks for figuring this out!

**Comment by kuabhish** [comment]
Thanks It helped a lot

**Comment by amjltc295** [comment]
I think I ran into similar problem because I tried to create several conda environment at the same time in different tmux sessions, so they write in the same package file

**Comment by cpoptic** [comment]
> I think I ran into similar problem because I tried to create several conda environment at the same time in different tmux sessions, so they write in the same package file

Yeah likewise.  I was doing a cleanup session of all my conda environments with 3 cmd prompt sessions open and I suspect this caused the issue.  To prevent in future, use one terminal when updating conda environments.
