### ISSUE TITLE
Take signed in user directly to her library dashboard

### ISSUE THREAD

**Issue by eclectir** [Microsoft/AzureNotebooks#9]
Today if a signed in user goes to notebooks.azure.com, she lands on our homepage instead of the library dashboard. Returning, signed in users should be taken to their dashboards.

**Comment by DinoV** [comment]
Thanks for the suggestion...  When signing in from the main page we'll now take you to /<youruserid> or /home (if you don't have a user id configured).  That page displays your most recently used notebooks.
