### ISSUE TITLE
Filter out existing urlencoding for notebook filenames

### ISSUE THREAD

**Issue by booyaa** [microsoft/AzureNotebooks#90]
### Description

Sanitize notebook file names.

### Repro Steps

- Add a notebook from this [URL](https://raw.githubusercontent.com/atleypnorth/notebook_intro/master/Intro%20to%20notebooks.ipynb) or create a notebook called `Intro%20to%20notebooks.ipynb` 
- The notebook will be further urlencoded to `Intro%2520to%2520notebooks.ipynb`
- You will be unable to open or delete the notebook

### Recommended Metadata

The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python 3
Occurrence Time: 2017-05-05
Web Browser: IE 11 / Firefox 53.0
LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/run/codemonkey/hello-azure-notebooks?dest=/notebooks/Intro%2520to%2520notebooks.ipynb

p.s. I'd be grateful if someone could delete this notebook.

**Comment by crwilcox** [comment]
@booyaa, Thank you for reporting this. I have made sure we are tracking this issue and we will work to fix it. I have deleted the file in your link so it isn't in your library anymore.

Thanks!
Chris
