### ISSUE TITLE
Request to whitelist UCAR THREDDS data server URL

### ISSUE THREAD

**Issue by donovan1983** [Microsoft/AzureNotebooks#91]
### Description
Unable to access UCAR THREDDS data server (`http://thredds.ucar.edu/`) due to HTTP access to URL being blocked.

### Possible Resolution
Please whitelist URLs that begin with `http://thredds.ucar.edu/`

### Reproduction Steps
```
from siphon.catalog import TDSCatalog
best_gfs = TDSCatalog('http://thredds.ucar.edu/thredds/catalog/grib/NCEP/GFS/Global_0p5deg/catalog.xml')
print(list(best_gfs.datasets))
```

### Usage Scenario
Accessing, ultimately for viewing and plotting, meteorological forecast model output data.

### Recommended Metadata
The Jupyter Kernel: Python3
Occurrence Time: 2017-05-05

Thank you very much!

**Comment by crwilcox** [comment]
@donovan1983,

I have whitelisted thredds.ucar.edu for you.

Thanks!
Chris
