### ISSUE TITLE
Error when downloading notebook as pdf

### ISSUE THREAD

**Issue by khaledvic** [Microsoft/AzureNotebooks#92]
### Description
when trying to download the notebook as pdf, I get the following :

> The page cannot be displayed because an internal server error has occurred.
### Repro Steps
open notebook file->Download as->Pdf as latex
(html works for example)

### Recommended Metadata
Log
` nbconvert failed: xelatex not found on PATH, if you have not installed xelatex you may need to do so. Find further instructions at https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex.
[E 11:32:38.764 NotebookApp]`

**Comment by crwilcox** [comment]
@khaledvic , thanks for reporting this. And thank you for including the logs. We can add xelatex to the path and hopefully fix this issue for you.

**Comment by jsmorph** [comment]
ETA? Still seeing this exact problem.

**Comment by crwilcox** [comment]
@jsmorph probably a bit late for you but I suspect this is fixed. We have, over the past 3-6 months, done a decent amount of work around notebook conversion. If this is still broken let us know and we can dig in again. 

If you do have this still happening, please provide us with a library and a notebook to use that results in the error as notebook contents can greatly influence the result of the conversion.
