### ISSUE TITLE
Unable to install packages with R Kernel

### ISSUE THREAD

**Issue by szaydel** [Microsoft/AzureNotebooks#93]
### Description
When using R kernel with Jupyter NB, installing libraries appears to fail consistently with following output:

```
Installing package into '/home/nbcommon/R'
(as 'lib' is unspecified)
```

### Repro Steps
In the first box auto-generated at the time noteboook is launched, attempt to install package, like:
```
install.packages("PerformanceAnalytics")
```

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): 
```
               _                           
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          3.0                         
year           2016                        
month          05                          
day            03                          
svn rev        70573                       
language       R                           
version.string R version 3.3.0 (2016-05-03)
nickname       Supposedly Educational 
```

Occurrence Time: Does not appear to matter

Web Browser: Chrome

LibraryID and Notebook Name (if applicable): https://notebooks.azure.com/szaydel/libraries/dat203-1x

Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by smortaz** [comment]
Hmmm... not an R expert, but it seems to work ok for me:


![image](https://cloud.githubusercontent.com/assets/742484/25813940/69744a36-33d0-11e7-928e-603e0ea576ff.png)

**Comment by szaydel** [comment]
This is too funny, I did not even try to load the packages, because I immediately assumed that the message
```
Installing package into '/home/nbcommon/R'
(as 'lib' is unspecified)
```
basically meant it never had a chance to install. The one thing I am definitely missing here, and wish I had was shell access. I run Jupyter notbooks on my laptop and my servers and of course always have shell access. I am sure I have been spoiled by this fact.

Thanks, I guess we can call this resolved. Though I don't think that message is normal.

**Comment by smortaz** [comment]
no worries.

btw - you DO have shell access.  in a notebook, click the Jupyter icon (top left).  In the Jupyter tree view, do a "New / Terminal" and youve got a shell.

**Comment by szaydel** [comment]
Thanks. I did not realize, I just assumed it would not be allowed.

**Comment by smortaz** [comment]
nope, it's your very own container, party on!  there are some limitations...

**Comment by carloscrosetti** [comment]
Hi, I am still getting the error found above in this thread, environmeb is Azure ML.


Installing package into ‘/home/nbuser/R’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ddalpha’, ‘recipes’

Warning message in install.packages("caret", dependencies = TRUE):
“installation of package ‘ddalpha’ had non-zero exit status”Warning message in install.packages("caret", dependencies = TRUE):
“installation of package ‘recipes’ had non-zero exit status”Warning message in install.packages("caret", dependencies = TRUE):
“installation of package ‘caret’ had non-zero exit status”

**Comment by smortaz** [comment]
Hi, did you do the things outlined in the example notebook where it shows caret being successfully installed?  thx.

**Comment by carloscrosetti** [comment]
Thanks fior asking. I saw the recommendatuoln and appliei it into thr Mixrosoft Notebioks env amd found it unstsble. Worked intemitently. Would need to try into Azure ML. Nevertheless this workaround looks reaonable. From my viewpoubt dealing with this id not sustainable long term. Would be difficilt to you to provide a service request form to sllow comolex oscksge ibstslls by Microsoft?

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by carloscrosetti** [comment]
Please reopen the case, problem: cannotload caret package


This command does not work


system("mkdir -p ~/.R", intern = TRUE)
system("cp ~/library/Makevar.txt ~/.R/Makevars", intern = TRUE)


I see log output going to a R directory without dot prefix.

________________________________
