### ISSUE TITLE
Unable to log into AzureNotebooks using my Microsoft account

### ISSUE THREAD

**Issue by trallard** [Microsoft/AzureNotebooks#94]
I am unsure if this goes here, but it is worth trying 🙂 

I have a valid Microsoft account (I use this with other services regularly), however when trying to log in AzureNotebooks with that account I get the following error (every time):

<img width="1291" alt="screen shot 2017-05-11 at 09 32 17" src="https://cloud.githubusercontent.com/assets/23552331/25941530/c55b645c-3631-11e7-874b-3f0fd2cf44ca.png">

I tried multiple devices and it still fails.

Web Browser: Safari, Chrome

**Comment by crwilcox** [comment]
Hi @trallard. There was an outage during //Build of AAD after bringing another service online. Is this still impacting you? If so, let us know when you tried and I will dig into our logs and see if I can't get to the bottom of it.

Thanks!
Chris

**Comment by trallard** [comment]
Hi  @crwilcox and thanks for looking into this. I tried just a few minutes back again and I am still getting the same message.

Thanks 

Tania

**Comment by crwilcox** [comment]
@trallard, this should be fixed at this point. let us know though if it was never resolved.
Thanks!
Chris
