### ISSUE TITLE
feature request: provide url for specific notebook within a library

### ISSUE THREAD

**Issue by lheagy** [microsoft/AzureNotebooks#95]
### Description

Right now, sharing notebooks requires that one provide a link to an entire library. There are scenarios when it would be handy to be able to direct a user to a specific notebook within a library, for example if a notebook is a supplementary resource in a blog or textbook. Would it be possible to provide a url for sharing a single notebook within a library? If the user has not cloned the library they could then be prompted with the option to either clone the whole library or to clone the individual notebook and then the linked notebook launches. 

### Usage Scenario (e.g. teaching a computing course at university foo)

We are currently using azure to provide notebooks that are a supplementary resource to a web-based "textbook" (http://em.geosci.xyz). Some of the pages refer to a specific notebook that supports an explanation, and being able to link directly to it would simplify the learner's experience. 

Thank you! Azure notebooks has been an invaluable resource for a short course on geophysics that we are running.

**Comment by smortaz** [comment]
This is a great idea and is on the to do list.

 There is a way that you can do this currently:

-  in the library click on the row of the notebook you want to share
-  this will light up the printer icon which is meant for viewing the HTML
preview

-  you can now grab that URL and share that  directly for the notebook in
question

-  your user can then choose to clone and run it which requires logging in

-  and without logging in they can at least view the contents of the
notebook and the output of the cells

 Let us know if this works for you. Thanks!

**Comment by adamlamee** [comment]
I second this one. I'm on a project that serves individual notebooks hosted on Github via URL to up to 1000s of students in a school district. We're currently using Colab, which nicely supports this feature, but I'd love to offer Azure as an option, too.
