### ISSUE TITLE
Error when return Pandas dataframe as json from a Azure ML webservice

### ISSUE THREAD

**Issue by rishi8313** [Microsoft/AzureNotebooks#99]
Please consider the template below to file your issue. 

### I want to return a json from my webservice. This is how I created webservice. 
from azureml import services
@services.publish(workdspace_id, authorization_token)
@services.service_id(service_id)
@services.types(input=str)
@services.returns(str)
def function(input):
    frame = pd.DataFrame([[1,2,3],[2,3,4],["h","e","l"]],columns = ["number","value","string"])
    return frame.to_json(orient = 'records')

Error: 
{u'error': {u'message': u'Module execution encountered an error.', u'code': u'ModuleExecutionError', u'details': [{u'message': u'Error 0085: The following error occurred during script evaluation, please view the output log for more information:\r\n---------- Start of error message from Python interpreter ----------\r\nCaught exception while executing function: Traceback (most recent call last):\n  File "\\server\\InvokePy.py", line 120, in executeScript\n    outframe = mod.azureml_main(*inframes)\n  File "\\temp\\1731077335.py", line 1093, in azureml_main\n  File "\\temp\\1731077335.py", line 357, in _decode\n  File "C:\\pyhome\\lib\\json\\__init__.py", line 338, in loads\n    return _default_decoder.decode(s)\n  File "C:\\pyhome\\lib\\json\\decoder.py", line 366, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File "C:\\pyhome\\lib\\json\\decoder.py", line 384, in raw_decode\n    raise ValueError("No JSON object could be decoded")\nValueError: No JSON object could be decoded\n\r\n\r\n---------- End of error message from Python  interpreter  ----------', u'code': u'85', u'target': u'Execute Python Script RRS'}]}}

### Repro Steps
create a webservice a return pandas dataframe converted to json using to_json() function and using  @services.returns(str)

### Usage Scenario (e.g. teaching a computing course at university foo)
Working with Azure ML to create my final year project.

### Recommended Metadata
The Jupyter Kernel (Python2, Pyhton3, R, N/A): Python2
Occurrence Time: Everytime
Web Browser: Chrome
LibraryID and Notebook Name (if applicable):
Logs (!cat .nb.log Or: New/Terminal, $cat .nb.log) - attach files if applicable

**Comment by crwilcox** [comment]
Please file an issue on the repository for this library
https://github.com/Azure/Azure-MachineLearning-ClientLibrary-Python
